### ISSUE TITLE
target SQLiteCipher build  failed

### ISSUE THREAD

**Issue by todaylover** [stephencelis/SQLite.swift#100]
![image](https://cloud.githubusercontent.com/assets/2224551/7121354/955ee7d8-e246-11e4-9140-3c8f52830f3b.png)

I use xcode 6.3.    `sqlite3_key` declared in sqlite3.h file, I think missing `#import <sqlite3.h>` in SQLite-Bridging.h file  or `import sqlite3` in Cipher.swift file

**Comment by stephencelis** [comment]
Did you follow the instructions here? https://github.com/stephencelis/SQLite.swift#sqlcipher

**Comment by todaylover** [comment]
I use it not as subproject,.
I clone the project, git submodule init and update , then build SQLiteCipher target. it failed.
