### ISSUE TITLE
Explicit "IS" and "IS NOT" operator

### ISSUE THREAD

**Issue by jake-b** [stephencelis/SQLite.swift#1003]
Possibly quick/easy feature request:

Sometimes you are comparing an nullable Expression to an optional Value and you explicitly want the "IS" or "IS NOT" operator.

Currently SQLIte.swift will only give you the IS/IS NOT operator if your rhs Value is nil. 

I'm not sure the best way to implement this.  You could overload another operator such as "==="  and "!==" perhaps... But I'm sure there's a too-clever-by-half "swifty" way to do it better.

**Comment by jake-b** [comment]
I tried my hand at pull request #1019 to implement this request.

**Comment by NathanFallet** [comment]
Was fixed by your PR. Closing.
