### ISSUE TITLE
INSERT OR REPLACE

### ISSUE THREAD

**Issue by confile** [stephencelis/SQLite.swift#101]
Is there a way to express INSERT OR REPLACE instead of only insert?

**Comment by stephencelis** [comment]
Use `Query.replace`:

``` swift
users.replace(id <- 1, email <- "alice@example.com")!
```

Keeping this open as it's not documented yet.

**Comment by confile** [comment]
@stephencelis Thank you very much for your help. I would love to send pull requests for docu and code if I can. It might take some time for me to understand the code complete.

I read the docs carefully and found the following:
```
let stmt = db.prepare("INSERT INTO users (email) VALUES (?)")
for email in ["betty@icloud.com", "cathy@icloud.com"] {
    stmt.run(email)
}
```
I did not see how I can do the following:
```
let stmt = db.prepare("SELECT * from users where email in (?)")
stmt.run(["betty@icloud.com", "cathy@icloud.com"])
```
Could you please give me a hint and I will update the example in the docs? Thank you.

**Comment by briv** [comment]
Hi @confile, I think this section of the documentation might be what you're looking for: https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#filtering-rows
It lets you do:
```swift
let email = Expression<String>("email")
db["users"].filter(contains(["betty@icloud.com", "cathy@icloud.com"], email))
```

**Comment by stephencelis** [comment]
The title issue has been addressed in 14573e4.

**Comment by confile** [comment]
Could you please give me an example for insert or replace: 

I tried: 
```
if let someId = appDataTable.insert(or: .Replace, appVersion <- version_) {
        callback.onSuccess()
    }
```
but it failed.

**Comment by confile** [comment]
There is ``insert(<#query: Query#>)``

but no: ``insert(or: <#Query.OnConflict?#>, <#query: Query#>)``

**Comment by confile** [comment]
I see the request can't fail anymore right. Then it is just:

```
someId = appDataTable.insert(or: .Replace, appVersion <- version_)
```

**Comment by stephencelis** [comment]
@confile You figure things out? Yep. See https://github.com/stephencelis/SQLite.swift/commit/a5011f4a216fb9e60ee33aa17c84c5831d1db5fa

If you want to use `if`–`let` you'll need to call `.rowid` on the return value:

``` swift
if let someId = appDataTable.insert(or: .Replace, appVersion <- version_).rowid {
    callback.onSuccess()
}
```

**Comment by confile** [comment]
What does it mean if someId is nil? Does this mean insert or replace failed?

**Comment by stephencelis** [comment]
Yes. It generally means a `CHECK` or `UNIQUE`/etc. constraint failed.
