### ISSUE TITLE
How to create a derived query?

### ISSUE THREAD

**Issue by Mactacs** [stephencelis/SQLite.swift#1012]
Hi. I'm struggling in creating a query that needs a derivation. Here is my SQLite query : 

```sql
SELECT * FROM (SELECT * FROM messages AS a ORDER BY a.date_sent DESC,a.time_sent DESC) as c GROUP BY c.client_user_id, c.client_student_id
```

I converted this query using this dependency and it produces different result compare above query. I don't know what I was lacking. Please help thanks.

Here is my query : 
```swift
let query1 = (Messages.messagesTable.select(*).order(Messages.messagesTable[Messages.date_sent].desc).order(Messages.messagesTable[Messages.time_sent].desc)).select(*).group(Messages.messagesTable[Messages.client_user_id]).group(Messages.messagesTable[Messages.client_student_id])
```

**Comment by NathanFallet** [comment]
Please ask on StackOverflow for this kind of questions (we are tracking bugs on GitHub)
