### ISSUE TITLE
FailableIterator next() crash

### ISSUE THREAD

**Issue by enamor** [stephencelis/SQLite.swift#1028]
extension FailableIterator {
    public func next() -> Element? {
        return try! failableNext()
    }
}

Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: disk I/O error (code: 10)

**Comment by juanjoseluisgarcia** [comment]
This occurs when more than one thread is trying to access the DB. This library is not thread-friendly. My suggestion is that you create one global connection (in the AppDelegate for example) and use that connection all over your app.

**Comment by avnerbarr** [comment]
issue also occurs if the db is open in 2 processes

**Comment by NathanFallet** [comment]
Merged a fix to replace `try!` by `try?`.

**Comment by vitock** [comment]
> Merged a fix to replace `try!` by `try?`.

I saw you reverted  that change ?

**Comment by NathanFallet** [comment]
> > Merged a fix to replace `try!` by `try?`.
> 
> 
> 
> I saw you reverted  that change ?

Yes, because as explained in #1075, you should use `failableNext()` and handle the error by yourself using a `do`/`catch` block (as explained in the PR). We cannot provide a default behavior (e.g. return nil) when an error occurs, it's up to you to choose what you want to do.
