### ISSUE TITLE
I know delete one table data, but have any idea to clear sqlite all data?

### ISSUE THREAD

**Issue by Bruce9487** [stephencelis/SQLite.swift#1029]
I want to ask if I want to clear sqlite all data, only one way to call delete table data in each table?
like following code.

```
try db.run(users.delete())
try db.run(shops.delete())
try db.run(employees.delete())
try db.run(objects.delete())
try db.run(drinks.delete())
try db.run(food.delete())
.....
.....
.....
```

**Comment by Yigang0622** [comment]
Delete the db.sqlite3 file directly in the Document folder of your app and you will get everything erased.

**Comment by NathanFallet** [comment]
Deleting and recreating the database should do the job.
