### ISSUE TITLE
Unable to create database

### ISSUE THREAD

**Issue by adnanafzal565** [stephencelis/SQLite.swift#1032]
I am getting the following error from the master branch while creating a connection to the database:

`cannot open file at line
open(//my_db.sqlite3)
The operation couldn’t be completed. (SQLite.Result error 0.)`

I wanted to ask, do I have to give some permissions to create a database?

If yes, kindly let me know which ones and how to add them.

Thanks.

**Comment by NathanFallet** [comment]
@adnanafzal565 Can you show us your code please?

**Comment by NathanFallet** [comment]
Duplicate of #982
