### ISSUE TITLE
Check if filter value exists

### ISSUE THREAD

**Issue by adnanafzal565** [stephencelis/SQLite.swift#1033]
Hi.

I want to know is there any way I can check if the filter() function returns a record or not ?

**Comment by NathanFallet** [comment]
@adnanafzal565 Try to execute your query and check how many lines are returned:

```swift
let result = try db.prepare(table.filter(yourExpression))
if let _ = result.next() {
    // You have at least one record
}
```

**Comment by adnanafzal565** [comment]
Yes, it was fixed. Thank you.
