### ISSUE TITLE
Creating a DateFormatter for every Date?

### ISSUE THREAD

**Issue by JetForMe** [stephencelis/SQLite.swift#1038]
Just perusing the code, in `Foundation.swift`, `extension Date`, it seems a `DateFormatter` object is created for every `Date` created. Perhaps that should be `static`? I believe they're thread-safe once converted, if unmodified.

**Comment by dennis-alpine** [comment]
If you're referring to the global variable, `public var dateFormatter: DateFormatter = { /* return formatter */ }()`, it already acts like a static.  If it was written as a getter, `public var dataFormatter: DateFormatter { /* return formatter */ }`, then that wouldn't be good.

**Comment by JetForMe** [comment]
Oh, sorry, I thought it was part of `extension Date`, didn't realize it was outside the scope of that. Nevermind!
