### ISSUE TITLE
Security vulnerabilities with bundler 1.17.1

### ISSUE THREAD

**Issue by pratjai** [stephencelis/SQLite.swift#1044]
## Build Information
- SQLite.swift version: 0.12.2
- How do you integrate SQLite.swift in your project?: Carthage

## Details:
- Security vulnerabilities reported with bundler 1.17.1, the recommendation is to update it to "Upgrade to version v2.1.0.pre.3".

**Comment by NathanFallet** [comment]
Bundler was updated today, so will be fixed in the next release
