### ISSUE TITLE
Cannot find Database in scope

### ISSUE THREAD

**Issue by Akeuuh** [stephencelis/SQLite.swift#1046]
Hi!

I'm trying to connect a prepopulated database as shown in the documentation

`
import SQLite

class DB_Manager {
    let path = Bundle.main.path(forResource: "nameOfDatabase", ofType: "sqlite3")
    let db = Database(path, readonly: true)
    
}
`

But Xcode tells me :
Cannot find Database in scope

I've tried reinstall SQLite with Pods but it doesn't work. Do you know what's going on?

**Comment by NathanFallet** [comment]
We need more information to help you to resolve your issue. Do you have any git or source to allow us to check and reproduce the issue?

**Comment by NathanFallet** [comment]
Please ask on StackOverflow for this kind of questions (we are tracking bugs on GitHub)
