### ISSUE TITLE
Query should contain ErrorMessage if failed to execute 

### ISSUE THREAD

**Issue by confile** [stephencelis/SQLite.swift#105]
A ``Query`` object should contain a Bool failed and a String errorMessage to check if the query succeeded. 

Example: 

```
let query = userTable.filter(self.username == username)
if query.failed {
 println("Could not execute query: \(query.errorMessage)")
}
```

**Comment by stephencelis** [comment]
The example you give hasn't actually executed anything. For inserts, updates, and deletes, you can use the `Statement` object returned to test if it `failed` and the `Database` object for the `lastError`. Generally, you shouldn't need to do much error checking at all with the library, though. What kinds of failures are you anticipating?

**Comment by stephencelis** [comment]
Marking as a dupe of #103, regardless.
