### ISSUE TITLE
Move to GitHub Actions (instead of travis-ci.org)

### ISSUE THREAD

**Issue by NathanFallet** [stephencelis/SQLite.swift#1058]
The old travis.org service is [no longer available](https://blog.travis-ci.com/2021-05-07-orgshutdown).
You need to activate something in order to move the CI to travis-ci.com. PRs won't be able to get merged otherwise

**Comment by NathanFallet** [comment]
@stephencelis It's an important point, it takes about 5 minutes, and you are the only one having the permission to do it.

**Comment by NathanFallet** [comment]
@jberkel I talked with Stephen today, and we concluded we had to move to GitHub Actions. We still have an unresolved error with Swift Package Manager test command `swift test`. Any idea of where it could come from?

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/30439790/129949630-01e6f009-7ece-47ba-a35e-dbb5f1044605.png">

**Comment by jberkel** [comment]
@NathanFallet thanks, I'll take a look. I saw that you merged some PRs, wouldn't it be better to sort out the CI before merging more code?

**Comment by NathanFallet** [comment]
@jberkel I only merged PRs about documentation (no CI needed) and little additions like conforming types (e.g. UUID or Int64) to codable things. I checked, and all tests are passing (except the SPM one, but others driven by Cocoapods or Carthage did)

**Comment by NathanFallet** [comment]
Could the SPM build error be related to #1051?

**Comment by jberkel** [comment]
Yes, I found the problem will open a PR soon. Some of the last merged PRs broke the tests

**Comment by NathanFallet** [comment]
@jberkel Okay, waiting for the fix.
