### ISSUE TITLE
Expose new schema alteration operations

### ISSUE THREAD

**Issue by jberkel** [stephencelis/SQLite.swift#1073]
These have been added in more recent versions:

* `RENAME COLUMN` (3.25.0)
* `DROP COLUMN` (3.35.0)

(maybe more)

**Comment by tianzhuqiao** [comment]
Thanks for the great project. Do we have any plan for these features?

**Comment by jberkel** [comment]
@tianzhuqiao what do you mean?

**Comment by tianzhuqiao** [comment]
Thanks. I mean if we have plan to include such features in SQLite.swift

> Renaming Columns
>
> Added in SQLite 3.25.0, not exposed yet. #1073
> Dropping Columns
>
> Added in SQLite 3.35.0, not exposed yet. #1073

**Comment by jberkel** [comment]
> Thanks. I mean if we have plan to include such features in SQLite.swift

Yes, that's why I created this issue.

**Comment by tianzhuqiao** [comment]
> Yes, that's why I created this issue.
Great, roughly when will it be available?

**Comment by jberkel** [comment]
Sorry, no idea.

**Comment by underthestars-zhy** [comment]
When will these features be exposed?
