### ISSUE TITLE
Missing required module 'SQLiteObjc'

### ISSUE THREAD

**Issue by muzipiao** [stephencelis/SQLite.swift#1079]
**Error description:**

1. I integrated  SQLite.swift in the static library through Swift Package Manager, uncheck when `Choose package products and targets` is operated;
2. Click `+` in `Target -> Build Phases -> Dependencies` to add SQLite dependencies;
3. When `import SQLite` in Swift file, report this error `Missing required module'SQLiteObjc'`.

Since I need to reference SQLite.swift in multiple static libraries, I cannot add it to `Link Binary With Libraries`, otherwise it will cause `duplicate symbols` error.
I would like to ask how to use SQLite.swift in multiple static libraries, thank you very much!

**Comment by ismetanin** [comment]
I've just faced the same issue while installing SQLite.swift via SPM

<img width="520" alt="image" src="https://user-images.githubusercontent.com/11653316/146929607-86619fd1-159a-40ca-8703-a971e9a51f91.png">

**Comment by jostster** [comment]
Seems to still be an issue :( with carthage

**Comment by jberkel** [comment]
These sources should be removed, see  #1104

**Comment by jberkel** [comment]
Note that the integration happens via SPM, so I don't see why changes to `project.pbxproj` would fix the issue?

**Comment by justinmeiners** [comment]
@maciekish This fixed manual subproject inclusion for me.

**Comment by jberkel** [comment]
Could somebody using SPM try this change?
