### ISSUE TITLE
Module file's minimun deployment target is ios8.3

### ISSUE THREAD

**Issue by pong343** [stephencelis/SQLite.swift#108]
How to run lower than 8.3

**Comment by stephencelis** [comment]
This should be fixed now. SQLite.swift has moved its deployment target to 8.0.

**Comment by sqlwindspeaker** [comment]
so currently cannot work on 7.0 right?

**Comment by stephencelis** [comment]
@sqlwindspeaker No module/framework works with 7.0. You can, however, use SQLite.swift on 7.0 if you copy over the source files manually as instructed in the documentation.
