### ISSUE TITLE
Value of type 'Connection' has no member 'key'

### ISSUE THREAD

**Issue by Bruce9487** [stephencelis/SQLite.swift#1086]
As title, what's wrong with my code.

I use Carthage install
github "stephencelis/SQLite.swift"

xcode ver 12.5.1
sqlite ver 0.13.0

![截圖 2021-09-16 15 15 12](https://user-images.githubusercontent.com/19691907/133567540-d70a51c3-0e7b-4316-a2f6-985a834a3249.png)

I follow document usage
<img width="1038" alt="截圖 2021-09-16 15 35 48" src="https://user-images.githubusercontent.com/19691907/133570376-e6159b8f-55a2-4514-9db0-240ef35136ae.png">

**Comment by nitrag** [comment]
You did not install `SQLite.swift/SQLCipher` pod

**Comment by jberkel** [comment]
stale, closing.
