### ISSUE TITLE
How to install SQLite.swift into Xcode playgrounds?

### ISSUE THREAD

**Issue by leeyspaul** [stephencelis/SQLite.swift#1102]
In the docs it mentions that you can learn SQLite.swift in playgrounds. However, there are no details of how to get it installed so it's available in playgrounds.

How would one do that? 

ps., thanks for the awesome package :]

**Comment by jberkel** [comment]
The easiest way is  to clone the repository and open the included playground.

**Comment by leeyspaul** [comment]
got it. Thank you :D
