### ISSUE TITLE
How can I write the BUILD file in Bazel to successfully reference SQlite.swift?

### ISSUE THREAD

**Issue by zyvv** [stephencelis/SQLite.swift#1103]
I'm using Bazel to manage projects. How can I write the BUILD file in Bazel to successfully reference SQlite.swift?

**Comment by NathanFallet** [comment]
@zyvv Checkout this article, it can help you to integrate it with Bazel. Feel free to update the documentation in a PR if you find a working solution.
https://chuckgrindel.com/swift-packages-in-bazel/
