### ISSUE TITLE
Cast expression type in select

### ISSUE THREAD

**Issue by samritchie** [stephencelis/SQLite.swift#112]
I have a database where some of the values in a column are stored as integers and some as text. I’d like to access them all as text, but I can’t seem to work out how to perform the cast - if I use `select(cast(painful_column) as Expression<String?>)` it happily generates a `SELECT CAST(painful_column AS TEXT)` but doesn’t alias the expression and I can’t retrieve it from the row. 

Is there an easy solution?

**Comment by stephencelis** [comment]
It should alias just fine. Just re-use (or re-call) `cast`. I tested the following:

``` swift
users.insert(age <- 30)!
let stringAge = cast(age) as Expression<String?>
let user = users.select(stringAge).first!
XCTAssertEqual("30", user[stringAge]!)
```

**Comment by samritchie** [comment]
Ah, okay, thanks.
