### ISSUE TITLE
Error in CircleCI pipeline: Duplicate symbol error with another swift package dependency

### ISSUE THREAD

**Issue by BajwaRevelAmeer** [stephencelis/SQLite.swift#1123]
### Describe the problem

**No problem with actual library.**

Issue occurs when running through circleCI pipeline. Received a duplicate symbol error when compiling all the different libraries in the Xcode project on circleCI with another swift package dependency (SimpleKeyChain). Has anyone else seen experienced something like this?

### What was the expected behavior?

- Compiling of code coverage should run smoothly

### Screenshot of circleCI pipeline error that occurs

![Screen Shot 2022-04-12 at 8 02 26 AM](https://user-images.githubusercontent.com/90710345/163413012-f57f13b8-0b2d-4cfa-b92e-b100127eadad.png)

### Environment

> Please provide the following:

- **Version of `SQLite.swift` used: 0.13.2
- **Version of `SimpleKeychain` used: 0.12.5**
- **Version of iOS/macOS/tvOS/watchOS: iOS deployment 14.0**
- **Version of Xcode: 13.3**

Linked to https://github.com/auth0/SimpleKeychain/issues/123

**Comment by jberkel** [comment]
It doesn't look related to SQLite.swift, more like a configuration problem. How is the build executed? Can you post the full log instead of a screenshot?
