### ISSUE TITLE
Tokenizer: Unicode61 constructor uses incorrect spelling of 'remove_diacritics'

### ISSUE THREAD

**Issue by KennethFra** [stephencelis/SQLite.swift#1128]
SQLite.swift version: 0.13.3
Xcode: 13.3.1 
Swift Package manager
FTS4.swift: 106

`            arguments.append("removeDiacritics=\(removeDiacritics ? 1 : 0)".quote())
`

Should be:
`            arguments.append("remove_diacritics=\(removeDiacritics ? 1 : 0)".quote())
`

https://www.sqlite.org/fts3.html#tokenizer

**Comment by jberkel** [comment]
@KennethFra thanks, fixed!
