### ISSUE TITLE
Bitcode Dropped - iPhone Simulator build architecture X86-64

### ISSUE THREAD

**Issue by nikiizvorski** [stephencelis/SQLite.swift#1135]
Hello. I am having issues generating bitcode for the SQLite framework i am using cocoapods to add it as a dependency to my project. I can see that there is bitcode enabled and all flags are added to the pods project and my project. When archiving to create a framework i am having a problem with bitcode. It doesn't seem to make an issue for my iphone build but for simulator it does and for the arch type: x86_64. Would much appreciate any feedback on the subject. 

## Build Information

- Include the SQLite.swift version, commit or branch experiencing the issue.
Official version from cocoapods -> https://cocoapods.org/pods/SQLite.swift
- Mention Xcode and OS X versions affected:
Xcode 12.5 and iOS 13
- How do do you integrate SQLite.swift in your project?
CocoaPods -> pod 'SQLite.swift', '~> 0.13.3'
I am using Cocoapods latest version
- My Project and Pods project have bitcode enabled for all 
It fails only for x86_64 
- I have use_frameworks! in both my project and test project 
both are xcframeworks and the dummy is for testing

## Error Information
ld: warning: all bitcode will be dropped because 'x86_64/SQLite.swift/SQLite.framework/SQLite' was built without bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.

**Comment by jberkel** [comment]
The message you posted (ld: warning) looks like a warning message, are you sure this stops the build from completing? Maybe the error is somewhere else.

**Comment by nikiizvorski** [comment]
Hey @jberkel it doesn't stop processing the build but later it have an effect when I need to do some manipulation on top.

**Comment by jberkel** [comment]
Sorry, your bug report is not very helpful. What exactly doesn't work?

**Comment by jberkel** [comment]
I'm not sure if it even makes sense to have bitcode for simulator builds, or if it's possible. Bitcode is meant for AppStore submissions, and you can't submit simulator builds to Apple.

**Comment by nikiizvorski** [comment]
Yes. That's correct. Seems bitcode is available only for iOS and macOS there is a way to generate it for simulator but I don't believe it makes sense.
