### ISSUE TITLE
Command failed due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by bitcrumb** [stephencelis/SQLite.swift#115]
I am running into this segmentation fault when adding the NSDate extension to my project as documented in the documentation file. Note that I have to support iOS7, so I've followed the instructions on how to do that.

Everything compiled fine up until adding an extensions to NSDate (& some other custom enums I use) to implement the Value protocol.

Has anyone experienced anything similar?

**Comment by stephencelis** [comment]
Do you have more information? Can you go to the Report navigator and print out the build log here?

You may be hitting a Swift bug, but there are usually workarounds, and it would be good to capture for an Apple bug report.

**Comment by bitcrumb** [comment]
I've recreated the issue in a blank project. You can download it here:
http://www.bitcrumbs.be/SQLiteSwift.zip

Hope this is helpful. Thanks!

**Comment by stephencelis** [comment]
Moving your value extensions to Value.swift in SQLite fixes things. Can you open a bug report with Apple at https://bugreport.apple.com and post the bug number here?

**Comment by stephencelis** [comment]
This actually duplicates https://github.com/stephencelis/SQLite.swift/issues/98
