### ISSUE TITLE
path to sqlite3.h in modulemap file

### ISSUE THREAD

**Issue by krzyzanowskim** [stephencelis/SQLite.swift#116]
currently path is defined as absolute path for different platforms and SDK's
```swift
header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/sqlite3.h"
```

however, according to the latest revelations: https://twitter.com/jckarter/status/590928617770602496 it seems to be enough to specify it like this:
```swift
header "/usr/include/sqlite3.h"
```
for any platform.

**Comment by stephencelis** [comment]
I unfortunately had to revert this here: https://github.com/stephencelis/SQLite.swift/commit/036288a8dd64bd74e30105870cfaef449bddbffe

It appears that the absolute path is preserved and people without the Xcode command line tools installed couldn't build anything.
