### ISSUE TITLE
Value name conflict with Keychain.swift

### ISSUE THREAD

**Issue by banxi1988** [stephencelis/SQLite.swift#117]
> SQLite/Value.swift:126:28: Reference to generic type 'Value' requires arguments in <...>

conflict with Value<T> decl in https://github.com/kishikawakatsumi/KeychainAccess/blob/master/Lib/KeychainAccess/Keychain.swift

**Comment by stephencelis** [comment]
For frameworkless targets, it's up to you to rename conflicting classes, structures, etc.
