### ISSUE TITLE
fts3_tokenizer.h file not found

### ISSUE THREAD

**Issue by banxi1988** [stephencelis/SQLite.swift#118]
errors as follows:
> SQLite/SQLite-Bridging.m:28:9: fatal error: 'fts3_tokenizer.h' file not found
> #import "fts3_tokenizer.h"
>        ^
> 1 error generated.

**Comment by banxi1988** [comment]
finally i found the file in Vendor dir
while I think the doc should be updated for frameworkless target
in https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#frameworkless-targets

**Comment by stephencelis** [comment]
Updated the docs, thanks!
