### ISSUE TITLE
Any particular reason for iOS 8.3 as default target?

### ISSUE THREAD

**Issue by DannyGlover** [stephencelis/SQLite.swift#119]
Hello there. Thank you for this great framework.

Is there any particular reason for making iOS 8.3 the default target for the Xcode project? I feel setting it to 8.1/8.2 by default would be the better choice, due to the varying user demographic in regards to OS version installs.

Thank you

**Comment by stephencelis** [comment]
It should be. I cherry-picked https://github.com/stephencelis/SQLite.swift/commit/078a76b6b74bf62606ea5828ea1d6f42a55361a4 but that doesn't apply to as many targets as I'd assumed. Let me make sure it applies to everything and push the changes.
