### ISSUE TITLE
How do I convert data returned from sql query

### ISSUE THREAD

**Issue by duncangroenewald** [stephencelis/SQLite.swift#1195]
I can't find any documentation that explains how to convert the returned column data to Swift types.

The example provided is singularly unhelpful

    for row in try db.prepare("SELECT id, email FROM users") {
        print("id: \(row[0]), email: \(row[1])")
        // id: Optional(2), email: Optional("betty@icloud.com")
        // id: Optional(3), email: Optional("cathy@icloud.com")
    }

If I try and cast the row[0] as? Int or anything else for that matter is always fails.

How does one extract the original type value ?

**Comment by NathanFallet** [comment]
You should use expressions instead:

```swift
let users  = Table("users")
let id = Expression<Int>("id")
let email = Expression<String>("email")

for row in try db.prepare(users.select(id, email)) {
    let idAsInt = try row.get(id)
    let emailAsString = try row.get(email)
    // You can do whatever you want with `idAsInt` and `emailAsString` which are safe Int/String
}
```

This is explained in the documentation [here](https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#selecting-rows).
