### ISSUE TITLE
Returning array of Row's from query?

### ISSUE THREAD

**Issue by DannyGlover** [stephencelis/SQLite.swift#121]
Hello there.

I have read the documentation but am not particularly clear on how to achieve this.
Example: Retrieve all rows from a table where user id is equal to 6.

    let query = users.filter( userId == 6)

We can get the first or last row by doing:
    
    let row: Row = query.first // or query.last

How do we go from that query object to getting an array of rows? Or better, how do we iterate over the query object to grab each matching row?

Thanks in advance

Edit: Can't seem to figure out how to add labels to mark this as "help wanted"

**Comment by stephencelis** [comment]
The `help wanted` tag is actually when I'm looking for PRs for something that I'd gladly accept but haven't made time for yet.

Check out the second example under **Selecting Rows**:

https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#plucking-rows

**Comment by DannyGlover** [comment]
Your talking about:

    let all = Array(users)

Right?

So it would perhaps go something like this:

    let all = Array(users.filter( id == 6 ) )
    for user in all {
        var row = user.first
    }

On the right track there?

**Comment by stephencelis** [comment]
I edited my post with links to other sub-sections. It's all right there in the docs. As for your example:

1. If you're just iterating, do `for user in users.filter(id == 6) { … }` (though if `id` is a unique rowid, I'm not sure why you're not using `first`).
2. In your iteration, `user` is the `Row` object.

Continue to experiment! Option-click values to see what they are. Try playing around with the playground.

**Comment by DannyGlover** [comment]
That is excellent. Thank you for the additional explanation and the specific sections to check out.
Appreciate the help!
