### ISSUE TITLE
Problem with inserting: Could not find an overload for 'insert

### ISSUE THREAD

**Issue by mostworld77** [stephencelis/SQLite.swift#122]
I tried all variants but without results.

My code:
let sport = db["sport"]
let id = Expression<Int64>("id")
let begin = Expression<String?>("begin")
let weight = Expression<Double>("weight")

Variants:
let insert_withPlan = sport.insert(begin <- chosen_date, trainingplan <- selected_plan, weight <- theweight)?
// Error: Could not find an overload for 'insert

let insert_withPlan = sport.insert(begin <- chosen_date, trainingplan <- selected_plan, weight <- theweight)!
// Error: Could not find an overload for 'insert

if let trainingid = sport.insert(begin <- "chosen_date", trainingplan <- selected_plan, weight <- theweight)?{
            // success logic
        }
// Error: Could not find an overload for 'insert

let insert_withPlan = sport.insert(begin <- chosen_date, trainingplan <- selected_plan, weight <- theweight).id
// id not found

What can be the problem?
Thanks

**Comment by stephencelis** [comment]
Sorry for the trouble. The interface recently changed to deal with general confusion: https://github.com/stephencelis/SQLite.swift/commit/a5011f4a216fb9e60ee33aa17c84c5831d1db5fa

You no longer can (or need to) disambiguate:

``` swift
let insert_withPlan = sport.insert(begin <- chosen_date, trainingplan <- selected_plan, weight <- the weight).rowid // or if-let
```

And it's `rowid` now, not `id`.

**Comment by mostworld77** [comment]
thanks for reply.
But if i remove the disambiguate, then i get the error:
"Cannot invoke 'insert' with an argument list of type (setter,setter,setter)"

Im using the latest xcode, and the latest SQLite Framework (deleted today and linked again)

Not work:
let insert_withPlan = sport.insert(begin <- chosen_date, trainingplan <- selected_plan, weight <- theweight)

Also not work:
let insert_withPlan = sport.insert(
    begin <- chosen_date, trainingplan <- selected_plan, weight <- the weight
).rowid

Error: Cannot find member: rowid

**Comment by stephencelis** [comment]
@mostworld77 Hm. There are a lot of tests that are passing just fine and I have no trouble making the above work. Have you cleaned your build folder and/or deleted DerivedData? Do you have a sample project I can take a look at that exhibits the problem?

**Comment by tthbalazs** [comment]
I also had the same problem with the latest version, and this workaround seems to fix the issue:
```swift
let insert_withPlan = sport.insert(
    (begin <- chosen_date), (trainingplan <- selected_plan), (weight <- the weight)
).rowid
```

**Comment by stephencelis** [comment]
@tthbalazs That's strange, the `<-` operator should produce that all the same. Do either of you have a project that exhibits the problem I can troubleshoot?

**Comment by tthbalazs** [comment]
@stephencelis Sadly I have no small project that I could share, altough I think I found the source of the problem, which seems to be a type mismatch. Basically the error is no help in this case.

```swift
var tours = self.db["tours"]

let id = Expression<Int>("id")

// tour.id is Int64
if let row = toursDB.insert(id <- tour.id).rowid {
    // does not work, and the error is 'Could not find member 'rowid' '
}

// tour.id is Int
if let row = toursDB.insert(id <- tour.id).rowid {
    // no errors
}
```

**Comment by stephencelis** [comment]
@tthbalazs Hm. I just don't have much control over how errors are surfaced. I may have to change `Setter` to be an actual type and not a typealias.

**Comment by stephencelis** [comment]
@mostworld77 Per the update from @tthbalazs can you try breaking down the expression further to see the real error?

``` swift
let setter1 = begin <- chosen_date
let setter2 = trainingplan <- selected_plan
let setter3 = weight <- the_weight
let insert_withPlan = sport.insert(setter1, setter2, setter3)

```

**Comment by tthbalazs** [comment]
@stephencelis I understand that you don't have control over the errors, and really this is a fault on our side. I don't think that changing `Setter` to be an actual type would worth it over this... maybe a heads-up in the documentation? I'm not sure, this is completely a typo mistake on our side, so it shouldn't really occur that often.

**Comment by stephencelis** [comment]
@tthbalazs I'm going to add a section to the `CONTRIBUTING.md` file with common troubleshooting techniques. Thanks!
