### ISSUE TITLE
Just insert

### ISSUE THREAD

**Issue by Chiliec** [stephencelis/SQLite.swift#125]
Ubiquitously in docs 
`users.insert(email <- "alice@mac.com", name <- "Alice")`
but it doesn't work for me: ![](https://s3.amazonaws.com/uploads.hipchat.com/204140/1800415/z8ovK2b8RecThc3/Скриншот%202015-05-06%2015.04.30.png)

It works if I do
`if let user = users.insert(email <- "alice@mac.com", name <- "Alice")`
or 
`users.insert(email <- "alice@mac.com", name <- "Alice") as? Int64`
or 
`users.insert(email <- "alice@mac.com", name <- "Alice") as Optional`
or 
`users.insert(email <- "alice@mac.com", name <- "Alice").rowid`
but it doesn't work just 
`users.insert(email <- "alice@mac.com", name <- "Alice")`

It's a bug or feature?

**Comment by stephencelis** [comment]
@Chiliec You appear to have checked out an earlier version. The interface changed with a recent update: https://github.com/stephencelis/SQLite.swift/commit/a5011f4a216fb9e60ee33aa17c84c5831d1db5fa
