### ISSUE TITLE
Insert or Replace not working

### ISSUE THREAD

**Issue by Silve2611** [stephencelis/SQLite.swift#126]
I'm trying the following
```
if let insertID = table.insert(or: .replace, service <- serviceI, client <- clientI, client_type <- client_typeI, allowed <- allowedI).rowid
```
But I'm getting the error 'could not find memeber 'replace' '
Where is my error? 

Is it smarted to use the following?
```
let stmt = db.prepare("INSERT OR REPLACE INTO access (service, client, client_type, allowed, prompt_count) VALUES (?,?,?,?,?)")
stmt.run([serviceI, clientI, client_typeI, allowedI, prompt_countI])
```

**Comment by davelyon** [comment]
If that's an exact copy and paste, it looks like simply changing `.replace` to `.Replace` would fix the issue. Swift is telling you that the struct doesn't have a member named `replace`.

**Comment by Silve2611** [comment]
it is not solving the problem .Replace produces the same error

**Comment by stephencelis** [comment]
@Silve2611 Are you on the latest version of SQLite.swift?

**Comment by stephencelis** [comment]
@Silve2611 Going to close this due to inactivity. Please chime in if you're still having trouble and have a reproducible bug.
