### ISSUE TITLE
PrivacyInfo.xcprivacy

### ISSUE THREAD

**Issue by numb-cola** [stephencelis/SQLite.swift#1263]
- Include the SQLite.swift version, commit or branch experiencing the issue.
- 0.15.1

- Mention Xcode and OS X versions affected.
- 15.3

- How do do you integrate SQLite.swift in your project?
- CocoaPods

## General guidelines

Use cocoapods to import version 0.15.1, but it does not contain PrivacyInfo.xcprivacy. I saw that it exists on the remote repository. Did the podspec ignore it?

**Comment by SagarSDagdu** [comment]
@numb-cola I have opened a PR to fix this.

**Comment by numb-cola** [comment]
Thank you @SagarSDagdu  for your help!
