### ISSUE TITLE
Demo Project

### ISSUE THREAD

**Issue by lltu** [stephencelis/SQLite.swift#130]
Look at title!

**Comment by stephencelis** [comment]
This has been on the roadmap for awhile, but it all boils down to time and the patterns that emerge while using SQLite.swift. In the end it'll probably exist as a separate repo, but I'll track it here in the meantime.

**Comment by hoffmanjon** [comment]
Would you accept demo projects submitted by users?  I have this repository with a demo project that I created:  https://github.com/hoffmanjon/SQLiteDataAccessLayer  The readme has links that blog posts that explain how I created the data access layer.

**Comment by hoffmanjon** [comment]
I created another demo using sqlite.swift with Swift 2.  The github repository is here:  https://github.com/hoffmanjon/SQLiteDataAccessLayer2/tree/master  
I also have a blog post explaining how I created the data access layer.  The blog post is here:  http://masteringswift.blogspot.com/2015/09/create-data-access-layer-with.html

**Comment by andersonacs** [comment]
Great job @hoffmanjon, your blog post was really helpful to me. thanks.

**Comment by ponxu** [comment]
really good job! @hoffmanjon

**Comment by stephencelis** [comment]
@hoffmanjon Thanks! If you'd like to add a link to the README via pull request I'm sure it would be helpful for others!
