### ISSUE TITLE
SQLite.swift turned many frameworks red

### ISSUE THREAD

**Issue by sehgalsaheel** [stephencelis/SQLite.swift#131]
Hello
I installed SQLite.swift from cocoapods and it has turned the products under my project and SQLite.framework and Pods.framework red and it giving me 10 errors. I added the bridging file and added 
#import <sqlite3.h>
#import "SQLite-Bridging.h"
now it gives me only 7 errors. 

Undefined symbols for architecture x86_64:
  "_ACAccountTypeIdentifierTwitter", referenced from:
      -[PF_Twitter getLocalTwitterAccountAsync] in Parse(PF_Twitter.o)
  "_OBJC_CLASS_$_ACAccountStore", referenced from:
      objc-class-ref in Parse(PF_Twitter.o)
  "_OBJC_CLASS_$_FBSDKAccessToken", referenced from:
      objc-class-ref in ParseFacebookUtilsV4(PFFacebookUtils.o)
      objc-class-ref in ParseFacebookUtilsV4(PFFacebookAuthenticationProvider.o)
  "_OBJC_CLASS_$_FBSDKApplicationDelegate", referenced from:
      objc-class-ref in ParseFacebookUtilsV4(PFFacebookUtils.o)
  "_OBJC_CLASS_$_FBSDKLoginManager", referenced from:
      objc-class-ref in ParseFacebookUtilsV4(PFFacebookAuthenticationProvider.o)
  "_OBJC_CLASS_$_FBSDKSettings", referenced from:
      objc-class-ref in ParseFacebookUtilsV4(PFFacebookAuthenticationProvider.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by stephencelis** [comment]
@sehgalsaheel Did you read through the [Contributing Guidelines](https://github.com/stephencelis/SQLite.swift/blob/master/CONTRIBUTING.md)? Can you provide a Podfile/project with a reproducible case?

**Comment by sehgalsaheel** [comment]
Ya I checked the Contributing Guidelines and no mistake there. 
i boiled it down to 3 errors. 
Podfile
platform :ios, '8.3'
use_frameworks!
pod 'SQLite.swift', git: 'https://github.com/stephencelis/SQLite.swift.git'

**Comment by stephencelis** [comment]
@sehgalsaheel So you cleaned your build, etc.? The Podfile contents you pasted above works fine in a new project as it only references SQLite.swift. Your error above seems to at the very least also include FBSDK and PFFacebookUtils.

**Comment by sehgalsaheel** [comment]
I am new to iOS programming so this is my first time using cocoapods and I wanted to use this! 
I did added those and the error count went up to 17!

**Comment by sehgalsaheel** [comment]
is it ok for pods.framework to be red in the target->build phases-> link binary with libraries?

**Comment by sehgalsaheel** [comment]
I solved it thanks...

**Comment by stephencelis** [comment]
@sehgalsaheel Can you comment on your solution?
