### ISSUE TITLE
Values are ?

### ISSUE THREAD

**Issue by sehgalsaheel** [stephencelis/SQLite.swift#132]
I am trying to add data to database in memory 

        func createDatabase(){
        var data = db["formatedData1"]
        db.create(table: data, ifNotExists: true){ d in
            d.column(type, primaryKey: true)
            d.column(ada)
            d.column(code)
            d.column(name)
            d.column(proof)
            d.column(size)
            d.column(case_size)
            d.column(price)
        }
        
        for var i = 0; i < self.dataArrayMut.count; ++i{
            println(data.insert(type <- (self.dataArrayMut[i].valueForKey("Type") as! String), ada <- (self.dataArrayMut[i].valueForKey("ADA") as! String), code <- (self.dataArrayMut[i].valueForKey("Code") as! String), name <- (self.dataArrayMut[i].valueForKey("Name") as! String), proof <- (self.dataArrayMut[i].valueForKey("Proof") as! String), size <- (self.dataArrayMut[i].valueForKey("Size") as! String), case_size <- (self.dataArrayMut[i].valueForKey("CaseSize") as! String), price <- (self.dataArrayMut[i].valueForKey("Price") as! String)))
        }
and I am getting error 
(Optional(1), INSERT INTO "formatedData1" ("Typeeeee", "ADA", "Code", "Name", "Proof", "Size", "Case_Size", "Min") VALUES (?, ?, ?, ?, ?, ?, ?, ?))

**Comment by stephencelis** [comment]
Care to elaborate? Not sure the "issue"?

**Comment by sehgalsaheel** [comment]
Sorry! I just updated my question!

**Comment by stephencelis** [comment]
@sehgalsaheel That's not an error. That's the return value of a successful insert:

- `Optional(1)` is the rowid
- `INSERT INTO ...` is the statement object

**Comment by sehgalsaheel** [comment]
So why am I getting ? or values.
When i print them before the loop I get the actual data that needs to go in the database.
Any Idea?

**Comment by stephencelis** [comment]
If you want to log the _actual query_, you set up a trace:

``` swift
db.trace(println)
```

Otherwise if you print the statement you will log the unbound query. SQLite uses `?` as a placeholder for unescaped values, _e.g._, for raw statements:

``` swift
db.run("SELECT * FROM users WHERE name = ?", "stephen")
// SELECT * FROM users WHERE name = 'stephen'
```

**Comment by sehgalsaheel** [comment]
Ya, When I do that i get 

SELECT count(*) FROM "formatedData1"

I want to see if my table holds the correct data

**Comment by stephencelis** [comment]
That means you're running a `count` query somewhere. Your insert will get printed to the console when it happens.

**Comment by sehgalsaheel** [comment]
Yes, I was and now when I delete the count println. I see nothing for db.trace(prinln)

**Comment by stephencelis** [comment]
Please read the contributing guidelines and provide as much as possible to reproduce. I will say that depending on the version of SQLite, `trace` has bugs in what it prints out. If you really need to verify a row was inserted (by all evidence above, it was: you have a rowid), then query it and inspect the row.

**Comment by sehgalsaheel** [comment]
sorry i didn't understand the provide as much as possible to reproduce part!
I just installed the SQLite week ago!

**Comment by stephencelis** [comment]
There just doesn't seem to be any evidence of a problem. If you're unfamiliar with SQLite, please read the docs at sqlite.org. If you're having general problems, please open a StackOverflow ticket. There are many people there that can help you with SQLite in general, and for SQLite.swift-specific issues, I try to answer them there when I can.

I'm going to close this out for now. If you believe you've found an actual bug, we can reopen it, but I need a reproducible case.
