### ISSUE TITLE
Joining two joins returns a join which is missing fields

### ISSUE THREAD

**Issue by zzpaf** [stephencelis/SQLite.swift#134]
I am working on a project that has to do several joins and I found out the following issue:

I did a first join:

let ext_tasks = tasks.join(tasktypes, on: tasktypes[tty_id] == tasks[task_type])
        .join(preUsers, on: preUsers[Worker_ID] == task_ownerID)
        .order(task_dueDate)
        .filter(task_ownerID == iUserID)

And then a second join:

    let ext_equipment = equipment.join(equipment_type, on: equipment_type[eqt_id] == equipment[equ_type])
        .join(facilities, on: facilities[fac_id] == equipment[equ_facid])
        .join(eqowners, on: eqowners[Worker_ID] == equipment[equ_owner])
        .order(equ_make)
        .filter(equ_status >= 0)

These two joins work perfectly and I can see all the fields from all the joined tables as a result, no problem up to here, however when I try to join these two:

 let comp_tasks = ext_tasks.join(ext_equipment, on: ext_equipment[equ_id] == ext_tasks[task_eqID])
        .order(task_dueDate)

The resulting join is missing a lot of fields. Actually, the resulting "comp_tasks" includes all the fields from the first join (ext_tasks) but only the equipment table fields from the second join (ext_equipment).

========

A solution for this was doing a chained join, which makes the code much more complex but ends up giving the same result:

        let ext_tasks = tasks.join(tasktypes, on: tasktypes[tty_id] == tasks[task_type])
            .join(preUsers, on: preUsers[Worker_ID] == task_ownerID)
            .order(task_dueDate)
            .filter(task_ownerID == appDelegate.iUserID)

        let ext2_tasks = ext_tasks.join(equipment, on: equipment[equ_id] == ext_tasks[task_eqID])
            .order(task_dueDate)

        let ext3_tasks = ext2_tasks.join(facilities, on: facilities[fac_id] == equipment[equ_facid])
            .order(task_dueDate)

        let ext4_tasks = ext3_tasks.join(equipment_type, on: equipment_type[eqt_id] == equipment[equ_type])
            .order(task_dueDate)

        let comp_tasks = ext4_tasks.join(eqowners, on: eqowners[Worker_ID] == equipment[equ_owner])
            .order(task_dueDate)
            .filter(equipment[equ_status] >= 0)

At the end of this chain of joins, we get the same result as the expected result above.

I hope this helps understand and reproduce the problem.

**Comment by stephencelis** [comment]
Thanks for the report!

> I hope this helps understand and reproduce the problem.

Unfortunately, to reproduce the problem I'll need enough code to paste into a test case or project. This means:

 1. All of your column definitions, _e.g._:

    ``` swift
    let tty_id = Expression<Int64>("tty_id")
    // etc...
    ```

 2. All of your table creation calls (raw SQL or `db.create(table: tastTypes) { t in /* ... */ }`, etc.).

If you could provide a link to a sample project or a block of code that be easily pasted into a single test case, that would be incredibly helpful. Thanks!

**Comment by stephencelis** [comment]
@zzpaf Any update here?

**Comment by mikemee** [comment]
I'm doing a pass to close some old issues. Please re-open if you have more information or feel this should still be active. it is definitely an interesting scenario, so if you never resolved this and/or have more information, please let us know. Thanks!
