### ISSUE TITLE
No rule to process module.modulemap for architecture i386

### ISSUE THREAD

**Issue by cooliceman** [stephencelis/SQLite.swift#135]
I want my project to support iOS 7 and later, so I copy all source files from SQLite project.
But Xcode 6.3.2 gives the following warning.
Warning: no rule to process file 'myprojectPath/SQLite/module.modulemap' of type sourcecode.module-map for architecture i386.

Should I just remove module.modulemap from my project's build phases/compile sources?

**Comment by stephencelis** [comment]
Yep.
