### ISSUE TITLE
Correctly configured but still getting use of undeclared type error

### ISSUE THREAD

**Issue by jamorat** [stephencelis/SQLite.swift#138]
![screen shot 2015-06-14 at 11 28 43 am](https://cloud.githubusercontent.com/assets/5558998/8149179/96401c5e-1288-11e5-922b-a0869bbd8867.jpg)

![screen shot 2015-06-14 at 11 28 50 am](https://cloud.githubusercontent.com/assets/5558998/8149181/9b92aab4-1288-11e5-8580-9795089bc667.jpg)

![screen shot 2015-06-14 at 11 28 54 am](https://cloud.githubusercontent.com/assets/5558998/8149182/a035a68e-1288-11e5-8330-da6bd6a6062e.jpg)

**Comment by stephencelis** [comment]
Please read the documentation and contributing guidelines thoroughly. The problem you're having has to be at the least presented here in a fashion that can be reproduced. Closing this one in favor of #136.
