### ISSUE TITLE
IFNOTEXIST is not working

### ISSUE THREAD

**Issue by sehgalsaheel** [stephencelis/SQLite.swift#141]
I am trying to create database on view did load and only wanted to create table once. so I added the IF NOT EXIST as true but overtime view did load occurs it creates the database and inserts data again!

    func createDatabase(){
        println("C1")
        println(self.dataArrayMut.count)
        var data = db["PriceBook"]
        
        db.create(table: data, ifNotExists: true){ d in
            d.column(type, unique: false)
            d.column(ada)
            d.column(code, primaryKey: true)
            d.column(name)
            d.column(proof)
            d.column(size)
            d.column(case_size)
            d.column(price)
        }
        
        for var i = 0; i < self.dataArrayMut.count; ++i{
            let (id, statement) = data.insert(type <- (self.dataArrayMut[i].valueForKey("Type") as! String), ada <- (self.dataArrayMut[i].valueForKey("ADA") as! String), code <- (self.dataArrayMut[i].valueForKey("Code") as! String), name <- (self.dataArrayMut[i].valueForKey("Name") as! String), proof <- (self.dataArrayMut[i].valueForKey("Proof") as! String), size <- (self.dataArrayMut[i].valueForKey("Size") as! String), case_size <- (self.dataArrayMut[i].valueForKey("CaseSize") as! String), price <- (self.dataArrayMut[i].valueForKey("Price") as! String))
            
            if let dbRowID = id {
                println("New entry: \(dbRowID)")
            } else if statement.failed {
                println("Row insertion failed because \(statement.reason!)")
            }
            
        }

    }

**Comment by stephencelis** [comment]
Where are you initializing `db`? Can you show us that code?

**Comment by sehgalsaheel** [comment]
Its a global variable    

      var db = Database()

**Comment by stephencelis** [comment]
Please reread the documentation, especially: https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#connecting-to-a-database

The database you're opening is never persisted. It's in-memory and will only live as long as the `db` instance. So when you run it again it's working as it should.

Make sure you pass a valid file path.

**Comment by sehgalsaheel** [comment]
Yes, I know it is an in-memory database. I create this database on load of one tableview and once I leave that 2nd table view and come back to first table view it acts fine. But if I leave 1st tableview and go back to home page and come back to tableview it should not create the database again. But it is

**Comment by stephencelis** [comment]
@sehgalsaheel Can you breakpoint and see if your database ever hits `deinit`? Is your `db` truly global or is it a property on a view controller? Have you considered opening a file-backed database in a temporary directory, instead? If you think this is a bug in SQLite.swift and don't think it would be an issue in sqlite3 proper, would you please provide an example project that reproduces the issue?

**Comment by sehgalsaheel** [comment]
It is global because I create database in a custom class and call it from my tableviewcontroller. 
How can I open file-backed database in a temporary directory?

**Comment by sehgalsaheel** [comment]
Well if a table already exists then don't create a table and don't insert anything in there.
and I did create a database with 

        let path = NSSearchPathForDirectoriesInDomains(
        .DocumentDirectory, .UserDomainMask, true
        ).first as! String    
        var db = Database("\(path)/db.sqlite3")


and same problem. but this time it says row insertion failed because of UNIQUE constraint. I don't want it to try to insert since there already is a table

**Comment by stephencelis** [comment]
@sehgalsaheel That's not the same problem. The unique constraint failed because you already inserted those rose. You need to check for the rows or run `insert(or: .Replace, …)`.

**Comment by sehgalsaheel** [comment]
I fixed the issue myself. 
Thanks for your help!

**Comment by stephencelis** [comment]
Glad you got things working!

**Comment by Krrunal** [comment]
i m having same issue can you please help me out how to solve this issue
