### ISSUE TITLE
Support for sqlite date and time function

### ISSUE THREAD

**Issue by cooliceman** [stephencelis/SQLite.swift#142]
Can you add support for Date and time functions?
These function are very important and convenience to do with dates and times.

https://www.sqlite.org/lang_datefunc.html

**Comment by stephencelis** [comment]
In concert with [this extension](https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#date-time-values), you should be able to do the following:

``` swift
func date(timestring: String, modifiers: String...) -> Expression<NSDate?> {
    if !modifiers.isEmpty {
        let templates = ", ".join([String](count: count(modifiers), repeatedValue: "?"))
        return Expression("date(?, \(templates))", [timestring] + modifiers)
    }
    return Expression("date(?)", timestring)
}

// etc.
```

I'd still like to have first-class support for this in the future (which means lifting the public embargo on Foundation), so I'll leave this open.

**Comment by stephencelis** [comment]
For what it's worth, if you use the above extension you may find that your need to use the SQLite datetime functions goes away entirely. You can just use `NSDate` objects:

``` swift
publishedAt // Expression<NSDate?>("publishedAt")

let published = posts.filter(publishedAt <= NSDate())
// SELECT * FROM "posts" WHERE "publishedAt" <= '2015-06-19 07:52:00'
```

**Comment by cooliceman** [comment]
Thanks a lot for your reply. Your answers give me a lot of help. Waiting for the support for date and time functions.

**Comment by stephencelis** [comment]
@cooliceman There should be no reason to wait: you can use them now if you use the extension I pasted in above, or you can use NSDate directly as recommended after.

**Comment by cooliceman** [comment]
Thanks for your reply.I will use NSDate to do date and time compre and search as you say.

**Comment by C4Grey** [comment]
Sorry, but the proposed solution `1.week.ago..<NSDate() ~= publishedAt` causes a compiler error: Binary operator '~=' cannot be applied to operands of type 'HalfOpenInterval<NSDate>' and 'Expression<NSDate>'

**Comment by stephencelis** [comment]
@C4Grey `NSDate` must conform to both `SQLite.Value` and `Swift.Comparable`. The former requires the extension I linked to earlier. The latter requires Timepiece or similar. If you're still having trouble can you provide all the boilerplate code needed to reproduce?

**Comment by C4Grey** [comment]
@stephencelis Thank you for the reply. Yes, I am using both the extension that you provided(representing a date as a TEXT) and the Timepiece framework. It seems like Timepiece do not implements the pattern match operator(~=) for dates, so I am wondering if the example that you wrote above worked in your case. Anyway, here is the simple test:
```swift
import UIKit
import XCTest
import SQLite
import Timepiece

extension NSDate: Value {
    public class var declaredDatatype: String {
        return String.declaredDatatype
    }
    public class func fromDatatypeValue(stringValue: String) -> NSDate {
        return SQLDateFormatter.dateFromString(stringValue)!
    }
    public var datatypeValue: String {
        return SQLDateFormatter.stringFromDate(self)
    }
}

let SQLDateFormatter: NSDateFormatter = {
    let formatter = NSDateFormatter()
    formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSS"
    formatter.locale = NSLocale(localeIdentifier: "en_US_POSIX")
    formatter.timeZone = NSTimeZone(forSecondsFromGMT: 0)
    return formatter
    }()

class SQLiteDateExtensionTest: XCTestCase {
    private let database = Database()
    private var table:Query!
    private let columnTestDate = Expression<NSDate>("test_date")
    private let date = NSDate()
    
    override func setUp() {
        super.setUp()
        table = database["test"]
        database.create(table: table) { t in
            t.column(columnTestDate)
        }
        database.trace(println)
    }
    
    func testDate() {
        let insert = table.insert(
            columnTestDate <- date
        )
        XCTAssert(!insert.statement.failed, "Inserted")        
        let rows = Array(table.filter(date.beginningOfDay..<date.endOfDay ~= columnTestDate))
        XCTAssertNotNil(rows.first?.get(columnTestDate), "Should fetch the recently inserted date")
    }
    
    override func tearDown() {
        database.drop(table: table, ifExists: true)
        super.tearDown()
    }
}
```
P.S. Also I've figured out that the such request will work fine:
```swift
let rows = Array(table.filter(columnTestDate >= date.beginningOfDay && columnTestDate <= date.endOfDay))
```

**Comment by stephencelis** [comment]
@C4Grey SQLite.swift provides the pattern matcher here: https://github.com/stephencelis/SQLite.swift/blob/fde8c3391b265eb34b6407e3665160fb981b6857/SQLite/Expression.swift#L532-L537

I'll take a look tonight and try to figure out what condition isn't being met.

**Comment by cfilipov** [comment]
Looks like the code snippet from earlier in this conversation no longer compiles:

```
func date(timestring: String, modifiers: String...) -> Expression<NSDate?> {
    if !modifiers.isEmpty {
        let templates = ", ".join([String](count: count(modifiers), repeatedValue: "?"))
        return Expression("date(?, \(templates))", [timestring] + modifiers)
    }
    return Expression("date(?)", timestring)
}
```

Updated to modern swift:

```
func day(timestring: String, modifiers: String...) -> Expression<NSDate?> {
    if !modifiers.isEmpty {
        let templates = [String](count: modifiers.count, repeatedValue: "?").joinWithSeparator(", ")
        return Expression("date(?, \(templates))", [timestring] + modifiers)
    }
    return Expression("date(?)", timestring)
}
```

But it's still not compiling. Looks like the constructor for `Expression` expects a `Binding`.

> Binary operator '+' cannot be applied to operands of type '[Binding?]' and '[String]'

It looks like String was already extended to implement the protocol, so I don't understand why it's not working.

**Comment by huntwj** [comment]
At the risk of shamelessly bumping this, what is the status here? It seems "native support" for DATETIME columns should be something the library supports. I'm happy to help as I can, but Swift is not my first or second language, so my ability to contribute is less than I'd like.

Thanks in advance for the update.

**Comment by jberkel** [comment]
@huntwj seems like this ticket got buried, i re-added it to the next milestone. if it's not included in the core lib the provided snippet should at least compile ok.

**Comment by stephencelis** [comment]
This lib tried to be "native swift" early on and avoid importing Foundation (thus Blob instead of NSData), but now that Foundation has been much better integrated into Swift, I can see embracing the types!

**Comment by huntwj** [comment]
That's really exciting, thanks!

I'll spend some time tomorrow seeing if I can get the snippet above to work. This is a great library. Thank you for putting it out there. :)

**Comment by avinassh** [comment]
Any update on this?
