### ISSUE TITLE
How to check whether key for encrypted database is valid

### ISSUE THREAD

**Issue by AndyQ** [stephencelis/SQLite.swift#144]
We use an encrypted database that the user has to enter the key to access.  Is it possible to validate that the user has entered the key correctly?

If you try to query the database with an invalid key then we currently just get an assertion (debug mode) and the app halts.

**Comment by stephencelis** [comment]
That's not currently possible with the error model in the Swift 1.2 version. This will improve with the Swift 2 version, but that won't be ready for a little while.

One solution in the meantime would be to store the user's password in the keychain, and use that value for checking/keying the database.

**Comment by AndyQ** [comment]
Sadly thats not possible as the database is dynamically downloaded every so often with a different key.

Just for info, I've worked around it for the moment by added a new method to Cipher - can AccessDatabase which does a simple sqlite3_execute call without wrapping with the try and returns true if no error or false if any other error.

**Comment by TheNephilim88** [comment]
Any news on this?
