### ISSUE TITLE
I can't get the playground to work

### ISSUE THREAD

**Issue by violabg** [stephencelis/SQLite.swift#15]
I open the SQLite project, run the build command, than select the SQLite.playground file, but it doesn't print the results.
Am I missing some steps?

**Comment by bryan1anderson** [comment]
Playground execution failed: <module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/Users/Bryan Anderson/Library/Developer/Xcode/DerivedData/Chats-dwkoxdfwcycztagyqitrtxvrhiko/Build/Products/Debug-iphonesimulator/SQLite.framework/Headers/SQLite.h"
        ^
/Users/Bryan Anderson/Library/Developer/Xcode/DerivedData/Chats-dwkoxdfwcycztagyqitrtxvrhiko/Build/Products/Debug-iphonesimulator/SQLite.framework/Headers/SQLite.h:9:9: note: in file included from /Users/Bryan Anderson/Library/Developer/Xcode/DerivedData/Chats-dwkoxdfwcycztagyqitrtxvrhiko/Build/Products/Debug-iphonesimulator/SQLite.framework/Headers/SQLite.h:9:
#import <SQLite/SQLite-Bridging.h>
        ^
/Users/Bryan Anderson/Library/Developer/Xcode/DerivedData/Chats-dwkoxdfwcycztagyqitrtxvrhiko/Build/Products/Debug-iphonesimulator/SQLite.framework/Headers/SQLite-Bridging.h:28:9: error: include of non-modular header inside framework module 'SQLite.SQLite_Bridging'
#import "sqlite3.h"
        ^
could not build Objective-C module 'SQLite'

Is the error I'm getting every time I try to run the playground in my CocoaPods workspace. Xcode 7.1
