### ISSUE TITLE
Access is needed to columnNames private variable in Query object

### ISSUE THREAD

**Issue by Hexidecibel** [stephencelis/SQLite.swift#151]
When iterating through a result set obtained via a select * query, the exact number of columns is unknown. The columnNames variable is needed to properly iterate through this kind of result set and this commit provides access to it via the Query object.

    var aliasByColumnName = [String: String]
    var aliases = database("SELECT * FROM ALIASES")
    for alias in aliases {
      var columnNames:[String: Int] = alias.getColumnNames()
      for (key, value) in columnNames {
        aliasByColumnName[key] = alias.values[value]
      }
    }

I've created a pull request that implements this.

**Comment by stephencelis** [comment]
PR: #150.

**Comment by mikemee** [comment]
Closing this out.  Per PR #150, you can get a list of all columns returned from a query with something like:

```swift
let stmt = try db.prepare("select * from emails")

for row in stmt {
    for (index, name) in stmt.columnNames.enumerate() {
        print ("\(name)=\(row[index]!)")
    }
}
```
