### ISSUE TITLE
library not found for -lsqlite3

### ISSUE THREAD

**Issue by irshad9998** [stephencelis/SQLite.swift#159]
I have installed sqlite.swift library using cocopods when i run app in simulator its works perfect but in device got error library not found for -lsqlite3

**Comment by stephencelis** [comment]
Could you please provide more information per the [Contributing Guidelines](https://github.com/stephencelis/SQLite.swift/blob/master/CONTRIBUTING.md)? More details (Xcode version, iOS version, etc.). Zipping up a sample project that exhibits the problem would also be a big help.

**Comment by stephencelis** [comment]
Going to close this ticket due to inactivity. I'll happily reopen it if you're still having trouble and can provide more information per the Contributing Guidelines, linked above.
