### ISSUE TITLE
ld: malformed 32-bit x.y.z version number: 0.1.0.pre

### ISSUE THREAD

**Issue by culmek** [stephencelis/SQLite.swift#162]
while I use cocoapods to install SQLite.swift and rebuild ,
then show an error "ld: malformed 32-bit x.y.z version number: 0.1.0.pre"
version is 0.1.0 pre??

**Comment by culmek** [comment]
It was cause by cocoapods 0.38.1, in 0.38.2 is ok

**Comment by stephencelis** [comment]
Glad to hear it's fixed! :smile:
