### ISSUE TITLE
Add sqlite3.h to Xcode project

### ISSUE THREAD

**Issue by davedelong** [stephencelis/SQLite.swift#163]
Instead of manually defining the path to sqlite3.h in `module.modulemap`, you should instead add the file directly to the xcodeproj.

Add it by finding it within your current SDK (i.e., `Xcode.app/Contents/Developer/Platforms/{platform}.platform/Developer/SDKs/{SDK}.sdk/usr/include/sqlite3.h`). When you add it this way, Xcode notices that it's relative to your current SDK, and so it gets added to the .xcodeproj as a relative file, like this:

    55C030C21B691CB40051264D /* sqlite3.h */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.c.h; name = sqlite3.h; path = usr/include/sqlite3.h; sourceTree = SDKROOT; };

Since the "sourceTree" of the file is "SDKROOT", it will correctly resolve to either the Mac SDK or the iOS SDK, depending on what your build destination is. Then you can delete the manual path specification in `module.modulemap`, and it should all Just Work™.

**Comment by stephencelis** [comment]
@davedelong Hm, this was one of the first things I tried and compilation failed. I'll try again tonight and see if I can get it to work. Otherwise I'll file a radar.

**Comment by stephencelis** [comment]
Got it working! Must have bungled it the first time around. Just need to confirm/push `master` with my non-Capitan machine. Thanks!

**Comment by stephencelis** [comment]
This is "fixed" in the `swift-2` branch, though CocoaPods must still use a custom module map as it cannot currently generate project files with `SDKROOT`-relative files: https://github.com/CocoaPods/CocoaPods/issues/3942

**Comment by rickpasetto** [comment]
Greetings.  Looks like still having the ```module.modulemap``` files still hard-coding the location of ```sqlite3.h``` causes dependent projects to fail to build if they don't have ```Xcode.app``` installed in ```/Applications``` (for instance, if they have ```Xcode Beta.app``` or multiple versions of Xcode installed).  Commenting out the "header" lines in the ```module.modulemap```s works around the problem, but can you fix this for those of us who do not use CocoaPods (i.e. Carthage users)?
