### ISSUE TITLE
External Content FTS4 Table

### ISSUE THREAD

**Issue by go1t** [stephencelis/SQLite.swift#164]
Is there a way to do this in SQLite.swift? : 
```javascript
 CREATE VIRTUAL TABLE table USING fts4(content='some_other_table', id, name)
```
I'd like to pre-populate my fts4 virtual table, but inserting one by one is very slow since my table contains over 30,000 rows. Is there any recommended way for this in SQLite.swift?

**Comment by stephencelis** [comment]
Many of the options for `fts4` aren't exposed yet but should be. Making this function public will get you closer:

https://github.com/stephencelis/SQLite.swift/blob/89d16192bb73bf179c08c30227fbd9e52be6bf32/SQLite/FTS.swift#L36

Or you can execute the raw SQL instead.

**Comment by igodzp** [comment]
That's one quick reply, thanks! 

I have a bit of the trouble about executing raw SQL. I currently have one read-only database and the read-write database for creating virtual table. The read-only one contains the records I want to pre-populate the virtual table in another database. The location of that read-only database is in the Supporting Files folder inside the project. How could I possibly use the table from that database in raw SQL? I can open it with SQLite.swift database with these command just fine: 

```swift
var path = NSBundle.mainBundle().pathForResource("db", ofType: "sqlite3")!
let readonlydb = Database(path, readonly: true)
```
but I cant seem to be able to access the database and tables with raw SQL.  Thank you in advance!

**Comment by lukescott** [comment]
It would also be nice if there was a way to setup the triggers to keep the data in sync, as shown here: http://www.sqlite.org/fts3.html#section_6_2_2 .

**Comment by mikemee** [comment]
Added to [Feature Requests](https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Planning.md).
