### ISSUE TITLE
 umbrella header 'SQLite.h' not found  

### ISSUE THREAD

**Issue by LeeLux** [stephencelis/SQLite.swift#166]
I used cocoa pods to add it ,when i build the project ，it breaked at   umbrella header "SQLite.h"

**Comment by stephencelis** [comment]
Would you please provide more information? At the very least:

- Version of Xcode
- Version of Swift
- Version of CocoaPods
- Your Podfile
- Your Podfile.lock

And, additionally, steps to reproduce, screen shots of the issue, etc.

For more ideas, try the Contributing Guidelines: https://github.com/stephencelis/SQLite.swift/blob/89d16192bb73bf179c08c30227fbd9e52be6bf32/CONTRIBUTING.md

**Comment by LeeLux** [comment]
Xcode 6.4
  Swift 1.2   
CocoaPods 0.37.2  
 OS-X 10.10.4 
Podfile 

target 'Weather' do

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 1.3'

pod 'Kingfisher', '~> 1.4'

pod 'SnapKit', '~> 0.12.0'

pod 'SQLite.swift', git: 'https://github.com/stephencelis/SQLite.swift.git'

pod 'SwiftyJSON', '~> 2.2.1'


end

target 'WeatherTests' do

end


Podfile.lock

PODS:
  - Alamofire (1.3.0)
  - Kingfisher (1.4.2)
  - SnapKit (0.12.0)
  - SQLite.swift (0.1.0.pre):
    - SQLite.swift/Library (= 0.1.0.pre)
  - SQLite.swift/Core (0.1.0.pre)
  - SQLite.swift/Library (0.1.0.pre):
    - SQLite.swift/Core
  - SwiftyJSON (2.2.1)

DEPENDENCIES:
  - Alamofire (~> 1.3)
  - Kingfisher (~> 1.4)
  - SnapKit (~> 0.12.0)
  - SQLite.swift (from `https://github.com/stephencelis/SQLite.swift.git`)
  - SwiftyJSON (~> 2.2.1)

EXTERNAL SOURCES:
  SQLite.swift:
    :git: https://github.com/stephencelis/SQLite.swift.git

CHECKOUT OPTIONS:
  SQLite.swift:
    :commit: 89d16192bb73bf179c08c30227fbd9e52be6bf32
    :git: https://github.com/stephencelis/SQLite.swift.git

SPEC CHECKSUMS:
  Alamofire: 220403a8d5840e0b4c946a6fbaf209dbca124282
  Kingfisher: 4446782a827abbe2e6048a1fa741924a10e6ad7c
  SnapKit: 00c388aa3bf1944c1b55472f31e841f75bd83882
  SQLite.swift: 6e05cc2b8efb0e91911e9cfb93551dd682b25843
  SwiftyJSON: ae2d0a3d68025d136602a33c4ee215091ced3e33

COCOAPODS: 0.37.2

Anything ?

**Comment by stephencelis** [comment]
CocoaPods is currently at version 0.38.2. Would you please upgrade and try again?

**Comment by stephencelis** [comment]
@LeeLux Any update here?

**Comment by stephencelis** [comment]
Going to close this due to inactivity. Please let me know if you're still having problems!

**Comment by LeeLux** [comment]
solved Tks.
