### ISSUE TITLE
iOS 7 SqlCipher Support

### ISSUE THREAD

**Issue by tosbaha** [stephencelis/SQLite.swift#167]
I am trying to use with iOS 7 therefore I manually added source files as in the instructions. I added sqlciper with pod "SQLCipher" But Xcode complains ```Use of unresolved identifier 'sqlite3_key'```
I tried to import sqlite3 as you stated on issue #100  but this time it says ```no such module 'sqlite3'```

**Comment by stephencelis** [comment]
SQLCipher is not built into SQLite.swift, so it needs to be installed manually. Please use CocoaPods or [manually](https://www.zetetic.net/sqlcipher/ios-tutorial/).

**Comment by tosbaha** [comment]
I guess I am not clear in my issue. As I stated before 
***I added sqlcipher with pod "SQLCipher"***
It means I used Cocoapods and added SQLCipher. However it doesn't work.

**Comment by stephencelis** [comment]
Ah, sorry, my eyes glossed right over that. Did you `#import "sqlite3.h"` into your bridging header?

**Comment by tosbaha** [comment]
Yes I used #import "sqlite3.h" still doesn't work. I know that it can find the file because if I change file name to ```sqlite34.h``` lets say, it says cant find file name. I tried cleaning project, rebuilding multiple times it always fails. My bridging header is like below
```
#import <sqlite3.h>
#import "SQLite-Bridging.h"
```

**Comment by wildonr** [comment]
Sorry to be a pain, I'm now down to only this error since upgrading to Swift 2, any ideas ?
