### ISSUE TITLE
"Library not loaded" error when archiving

### ISSUE THREAD

**Issue by PhilippOtto89** [stephencelis/SQLite.swift#170]
Hello,

first, thanks a lot for writing this great framework!!!

Sadly, I am facing problems using SQLite.swift in my project. I followed all the steps from the installation guide and was optimistic first since all seemed to work well in the simulator and when I deployed the app to my device in debug mode. Now that I try to archive the app and deploy it to my device via iTunes I get the following error when opening the app:

Dyld Error Message:
  Library not loaded: @rpath/SQLite.framework/SQLite
  Referenced from: /private/var/mobile/Containers/Bundle/Application/A1420D05-4A5C-4BA7-B1A8-06586F571A81/TestApp.app/TestApp
  Reason: no suitable image found.  Did find:
	/private/var/mobile/Containers/Bundle/Application/A1420D05-4A5C-4BA7-B1A8-06586F571A81/TestApp.app/Frameworks/SQLite.framework/SQLite: mmap() error 1 at address=0x1001A4000, size=0x000CC000 segment=__TEXT in Segment::map() mapping /private/var/mobile/Containers/Bundle/Application/A1420D05-4A5C-4BA7-B1A8-06586F571A81/TestApp.app/Frameworks/SQLite.framework/SQLite
  Dyld Version: 353.12

Binary Images:
0x12002c000 - 0x120053fff dyld arm64  <75c68bbe28b13fcd91014f15139742dc> /usr/lib/dyld

I read the following links but had no success with the changes suggested there.

http://stackoverflow.com/questions/24333981/ios-app-with-framework-crashed-on-device-dyld-library-not-loaded-xcode-6-beta

Also from SQLite.swift help: https://github.com/stephencelis/SQLite.swift/issues/25

I tried to install SQLite.swift manually and with the help of a Podfile but get the same error for both cases. To repeat myself I only get the error when trying to archive my project as an ipa file so I guess there is something wrong with release configuration.

Do you have any idea what is going wrong? Any help appreciated. Thanks in advance!

My configuration:
XCode 6.4
Device iPhone 6 - iOS 8.3

(Sorry for the distracting red rectangles. I thought it would make it better but obviously I was wrong. ;-) )

<img width="258" alt="sqlite1" src="https://cloud.githubusercontent.com/assets/10837066/9086283/d11a80e8-3b83-11e5-874b-b8c6f63783cf.png">

<img width="822" alt="sqlite2" src="https://cloud.githubusercontent.com/assets/10837066/9086282/d119f074-3b83-11e5-86ff-9f50fa15cb41.png">

<img width="789" alt="sqlite3" src="https://cloud.githubusercontent.com/assets/10837066/9086285/d11c6912-3b83-11e5-8650-28277bcdd7a7.png">

<img width="867" alt="sqlite4" src="https://cloud.githubusercontent.com/assets/10837066/9086284/d11a83ea-3b83-11e5-9ab3-15b935dded38.png">

**Comment by stephencelis** [comment]
This is a model bug report :+1: Thanks for the very detailed information! I'll see if I can reproduce soon. You're installing the **.ipa** via iTunes and _not_ Xcode?

**Comment by PhilippOtto89** [comment]
Thanks for your fast answer. Yes I use iTunes to install the ipa. Should be the same like installing the app over the app store later. Correct me if I am wrong. I hope you can reproduce the issue and solve it. Looking forward hearing from you! :-)

**Comment by xaclincoln** [comment]
I got the same problem using Xcode 6.4 (not beta). and i tried the Pods, drag the Xcode project and the drag the source files, all failed with the same error message -- "Library not loaded: @rpath/SQLite.framework/SQLite..... reason: image not found"

**Comment by blkbam** [comment]
I'm getting it also. Same setup using Xcode 6.4 :(

**Comment by blkbam** [comment]
I got it to work.  I'm not sure what exactly was the issue but I removed all references to SQLite.framework in the project settings then readded it all back using the manual steps and it works now.

**Comment by PhilippOtto89** [comment]
Tried adding the framework again manually but could not get it to work. :-/ Stephen have you already found time to look at the problem?

**Comment by yarshure** [comment]
Xcode 7 GM
dyld: Library not loaded: @rpath/SQLite.framework/SQLite
  Referenced from: /var/mobile/Containers/Bundle/Application/52EA055B-8C62-41AB-B3F3-8CCD0B9A4B3A/qood.app/qood
  Reason: image not found

**Comment by stephencelis** [comment]
@PhilippOtto89 Did you try, as @blkbam did, to remove and re-add the framework? Any way you can zip up and send me a sample project exhibiting the issue?

**Comment by PhilippOtto89** [comment]
@The Others: Did you try to archive the app or did you just run it. Because I only get an error when archiving the app.

@stephencelis: I tried to remove and add  the framework again but with no access. I uploaded a sample project which references and uses the SQLite. 

You can find it here: https://onedrive.live.com/?cid=59a74647ae854517&id=59A74647AE854517!118

Try to run it and it will run. But when you try to archive it and install it on a device, it will crash with the error from my inital post.

Could you please have a look at my example project?

Thank you very much!

**Comment by mikemee** [comment]
I'm doing a pass to close some old issues and given the elapsed time, it seems this may have been resolved already, and/or be part of another set of pod build errors (like #196) which are still being investigated. Please re-open if you have more information or feel this should still be active. Thanks!

**Comment by PeterKaminski09** [comment]
This is still an issue, as I'm getting it with my archiving when using SQLite.

**Comment by PeterKaminski09** [comment]
http://stackoverflow.com/questions/34027882/ios-dyld-library-not-loaded-with-sqlite

This solved it.
