### ISSUE TITLE
table.insert throwing error .rowid not found

### ISSUE THREAD

**Issue by madskunker** [stephencelis/SQLite.swift#171]
I have just started with this and it looks great but the Insert does not operate the way the the docs state.

```
class Posts {
    var title :String?
    var description :String?
    var whereAt :String?
    var imageBlob :SQLite.Blob?
    var whenAt:String?
    var id :Int64?
    var likesCount : Int64?
    
    init(title: String, description: String, whereAt: String, imageBlob: SQLite.Blob) {
        self.title = title
        self.description = description
        self.whereAt = whereAt
        self.imageBlob = imageBlob
    }
    
}

protocol DataHelperProtocol {
    typealias T
    static func createTable() -> Void
    static func insert(item: T) -> Int64
}

class PostDataHelper: DataHelperProtocol {
    static let TABLE_NAME = "Posts"
    
    static let title = Expression<String>("Title")
    static let description = Expression<String>("Description")
    static let whereAt = Expression<String>("WhereAt")
    static let imageBlob = Expression<SQLite.Blob>("ImageBlob")
    static let whenAt = Expression<String>("WhenAt")
    static let id = Expression<Int64>("id")
    static let likesCount = Expression<Int64>("LikesCount")
    
    static let table = SQLiteDataStore.sharedInstance.db[TABLE_NAME]
    
    typealias P = Posts
    
    static func createTable() {
        let results = SQLiteDataStore.sharedInstance.db.create(table: table, ifNotExists: true) { t in
            t.column(id, primaryKey: true)
            t.column(title)
            t.column(description)
            t.column(whenAt)
            t.column(whereAt)
            t.column(likesCount)
            t.column(imageBlob)
        }
    }
    
    static func insert(item: P) -> Int64 {
            if let results = table.insert(title <- item.title, description <- item.description, whereAt <- item.whereAt, imageBlob <- item.imageBlob).rowid {
                return results
            }
        return -1
        
    }
    
}
```

the table.insert throws "Could not find member .rowid"

What am I missing

Jeff

**Comment by stephencelis** [comment]
Have you tried breaking it down into smaller chunks to troubleshoot?

``` swift
let a = title <- item.title
let b = description <- item.description
let c = whereAt <- item.whereAt
let d = imageBlob <- item.imageBlob
let insert = table.insert(a, b, c, d)
let rowid = insert.rowid
```

**Comment by madskunker** [comment]
End up doing it this way

        let results = table.insert()
        let query = table.filter(id == db.lastInsertRowid!)
        let updateResults = query.update(title <- item.title!, description <- item.description!, whereAt <- item.whereAt!, imagePath <- item.imagePath!)

Xcode threw a build time error that the prototype of the insert was not compatible.

JEff




On Aug 5, 2015, at 6:06 PM, Stephen Celis <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you tried breaking it down into smaller chunks to troubleshoot?

let a = title <- item.title
let b = description <- item.description
let c = whereAt <- item.whereAt
let d = imageBlob <- item.imageBlob
let insert = table.insert(a, b, c, d)
let rowid = insert.rowid

**Comment by stephencelis** [comment]
Do you mean runtime? `let results = table.insert()` does an `INSERT INTO "{table}" DEFAULT VALUES` statement, which will only work if every single column allows for default values? What happens when you use the snippet I provided before?

**Comment by madskunker** [comment]
No when I put the

db.insert(title <- item.title)

xCode thows an error

[cid:38EBE844-477E-4C8D-87E1-F71EDCAD1E98]

So I reverted to the insert with defaultValues and then doing an update

Jeff


On Aug 5, 2015, at 7:38 PM, Stephen Celis <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you mean runtime? let results = table.insert() does an INSERT INTO "{table}" DEFAULT VALUES statement, which will only work if every single column allows for default values? What happens when you use the snippet I provided before?

**Comment by stephencelis** [comment]
I don't think your email attachment came through. Can you post via GitHub web?

**Comment by madskunker** [comment]
![screen shot 2015-08-05 at 7 42 10 pm](https://cloud.githubusercontent.com/assets/13667282/9101498/2f7039b6-3bad-11e5-88ba-75734c303643.png)

**Comment by madskunker** [comment]
done

Also I was trying to save an image NSData to the database but could not figure it out

I create a column SQLite.Blob

but no matter what I did I could never figure out how to update the column with the NSData

J

On Aug 5, 2015, at 7:43 PM, Stephen Celis <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't think your email attachment came through. Can you post via GitHub web?

**Comment by stephencelis** [comment]
Ah, you need to use `Blob` or conform `NSData` to the `Value` protocol as instructed in the documentation.

``` swift
let blob = Blob(data) // given data: NSData
```

**Comment by stephencelis** [comment]
Again, if you break the original single line down into it's individual parts per line it should surface the error more easily:

``` diff
+let a = title <- item.title
+let b = description <- item.description
+let c = whereAt <- item.whereAt
+let d = imageBlob <- item.imageBlob
+let insert = table.insert(a, b, c, d)
+if let rowid = insert.rowid {
-if let results = table.insert(title <- item.title, description <- item.description, whereAt <- item.whereAt, imageBlob <- item.imageBlob).rowid {
```

**Comment by madskunker** [comment]
let a = title <- item.title!
        let b = description <- item.description!
        let c = whereAt <- item.whereAt!
        let d = imagePath <- item.imagePath!
        let insert = table.insert(a, b, c, d)
        if let rowid = insert.rowid {
            if let results = table.insert(title <- item.title, description <- item.description, whereAt <- item.whereAt, imagePath <- item.imagePath).rowid {
                
            }
        }

Still get this error

![screen shot 2015-08-05 at 8 26 50 pm](https://cloud.githubusercontent.com/assets/13667282/9101757/5b9061e4-3bb0-11e5-97d5-d05469576dc3.png)

**Comment by stephencelis** [comment]
My last comment was a diff, meaning to remove your final, red line in exchange for the green ones above it. `if let results = insert.rowid` is equivalent to the line that's throwing an error. If you notice, the other lines work but only because you've added `!` to them. So that's your problem: you're sending optional values to expressions that are non-optional.
