### ISSUE TITLE
Segmentation Fault 11

### ISSUE THREAD

**Issue by hakangs** [stephencelis/SQLite.swift#173]
0  swift                    0x000000010ecb92b8 llvm::sys::PrintStackTrace(__sFILE*) + 40
1  swift                    0x000000010ecb9794 SignalHandler(int) + 452
2  libsystem_platform.dylib 0x00007fff8eb7ff1a _sigtramp + 26
3  libsystem_platform.dylib 0x00007fff5165ea88 _sigtramp + 3266177928
4  swift                    0x000000010e86a263 swift::serialization::Serializer::writeAllDeclsAndTypes() + 2163
5  swift                    0x000000010e86b2f8 swift::serialization::Serializer::writeAST(llvm::PointerUnion<swift::Module*, swift::SourceFile*>) + 2600
6  swift                    0x000000010e86d960 swift::serialization::Serializer::writeToStream(llvm::raw_ostream&, llvm::PointerUnion<swift::Module*, swift::SourceFile*>, swift::SILModule const*, swift::SerializationOptions const&) + 144
7  swift                    0x000000010e86e521 swift::serialize(llvm::PointerUnion<swift::Module*, swift::SourceFile*>, swift::SerializationOptions const&, swift::SILModule const*) + 321
8  swift                    0x000000010e5a2c1a frontend_main(llvm::ArrayRef<char const*>, char const*, void*) + 5514
9  swift                    0x000000010e5a14e6 main + 1814
10 libdyld.dylib            0x00007fff905e75c9 start + 1
11 libdyld.dylib            0x0000000000000083 start + 1872857787
Stack dump:

**Comment by stephencelis** [comment]
Thanks for your issue. I'd love to help but will have to close this as it does not contain enough information. Please read the [Contributing Guidelines](https://github.com/stephencelis/SQLite.swift/blob/master/CONTRIBUTING.md) and update this ticket accordingly and I'll happily reopen it.
