### ISSUE TITLE
Swift 2: Can't disable logging/tracing

### ISSUE THREAD

**Issue by schickling** [stephencelis/SQLite.swift#177]
It seems that it's not possible to disable logging for the swift-2 branch. Any ideas?

Note:
I've tried to set `db.trace(nil)`

**Comment by stephencelis** [comment]
@schickling Do you mean after initially enabling it?

**Comment by schickling** [comment]
It's enabled per default for me.

**Comment by stephencelis** [comment]
I'm definitely not seeing that behavior. Are you on the latest version of the `swift-2` branch?

**Comment by schickling** [comment]
Any update on this?

```swift
        let db = try! Connection(path)
        
        // enable console logging
        db.trace { msg in
            print("message: \(msg)")
        }
```

For this setup for example I always get the following output:

```
SELECT * FROM "person" WHERE ("person"."person_id" = ?) LIMIT 1 [Optional("1064fd0e-833b-4a6b-b4bc-d90a03074eba")]
message: SELECT * FROM "person" WHERE ("person"."person_id" = '1064fd0e-833b-4a6b-b4bc-d90a03074eba') LIMIT 1
```

**Comment by stephencelis** [comment]
@schickling Ahhh...that's an errant debug statement. Fixing now!

**Comment by stephencelis** [comment]
Should be good to go!

**Comment by schickling** [comment]
Thanks!
