### ISSUE TITLE
Show invalid SQL statement on error

### ISSUE THREAD

**Issue by schickling** [stephencelis/SQLite.swift#180]
When executing an invalid SQL statement one just gets the following error. It would be very helpful when the error would be catched, the invalid statement logged and than rethrown again.

```
fatal error: 'try!' expression unexpectedly raised an error: SQL logic error or missing database: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-700.0.52.2/src/swift/stdlib/public/core/ErrorType.swift, line 47
```

Note: This was also the initial reason for https://github.com/stephencelis/SQLite.swift/issues/176

**Comment by stephencelis** [comment]
This is done! Error messages are also properly extracted from the connection handle rather than relying on error code alone (which doesn't provide enough detail).
