### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by dfgdrtgdrfg** [stephencelis/SQLite.swift#183]
![screen shot 2015-08-25 at 11 51 27](https://cloud.githubusercontent.com/assets/10977094/9462628/bebb0872-4b1f-11e5-923c-357d8d95ee85.png)

**Comment by stephencelis** [comment]
Hi @dfgdrtgdrfg. Thanks for your report. As instructed in the README and from the open issue page, please read the Contributing Guidelines and update this ticket with as much information as possible:

https://github.com/stephencelis/SQLite.swift/blob/master/CONTRIBUTING.md

The only guess I have is that you're using the `master` branch with Xcode 6.4, but you've moved Xcode to a location other than **/Applications/Xcode.app**.

To avoid noise, I'll be closing this issue in the near future till more information is gathered and posted here.

**Comment by stephencelis** [comment]
Closing this for now. If updated with more information I'll be happy to re-open.
