### ISSUE TITLE
SQLite swift-2.0 branch does not compile with Beta 6

### ISSUE THREAD

**Issue by fluffyemily** [stephencelis/SQLite.swift#184]
Compiling our migrated swift 2.0 project with XCode 7.0 Beta 6 this morning highlighted some compilation errors in SQLite.swift Swift 2.0 branch.

I forked the project & ran through the errors fixing what I could, but was left with a series EXC_BAD_ACCESS crashes in ConnectionTests related to logging and commits.

I am continuing to try and resolve these issues on my fork, but felt a bug report would be useful as you would probably be able to resolve this faster :)

You can find my fork at https://github.com/mozilla/SQLite.swift

**Comment by stephencelis** [comment]
Thanks for your work on this so far! I've been tied up and just managed to download the beta this morning, but won't be able to take a look till tonight at earliest. If you'd like to gather things into a pull request, I'd love to merge!

**Comment by fluffyemily** [comment]
Would you like me to raise the PR even if I can't get the tests to pass? I
suppose it would give you a starting point....

**Comment by stephencelis** [comment]
I won't merge it till the tests pass, but I can work with you to help solve the problem when I have the bandwidth.

**Comment by stephencelis** [comment]
Should be good to go here now thanks to #185! :smile:
