### ISSUE TITLE
Back Blob with [UInt8] instead of NSData?

### ISSUE THREAD

**Issue by lukescott** [stephencelis/SQLite.swift#188]
Can Blob be backed by [UInt8] instead of NSData? It would be one less Foundation dependency. Something like:
```swift
public struct Blob {
	let data: [UInt8]

	public init(data: [UInt8]) {
		self.data = data
	}

	public init(bytes: UnsafePointer<Void>, length: Int) {
		data = [UInt8](UnsafeBufferPointer<UInt8>(
			start: UnsafePointer<UInt8>(bytes),
			count: length
		))
	}
}
// deprecate (backwards compatibility)
extension Blob {
	public var bytes: UnsafePointer<Void> {
		return UnsafePointer<Void>(data)
	}

	public var length: Int {
		return data.count
	}
}
```

**Comment by stephencelis** [comment]
When moving to `swift-2` I actually lost that dependency, though I manually alloc the memory, so it's slightly messier: https://github.com/stephencelis/SQLite.swift/blob/swift-2/Source/Core/Blob.swift

Any idea how the performance would compare with your version?

**Comment by lukescott** [comment]
It looks like in both cases a copy is being made, which has to be done either way: the NSData instance owns the memory at UnsafePointer<Void>.

Beyond that, I'm sure they are comparable. Although an Array might be more performant as Swift might have some tricks to keep the memory on the stack vs the heap. For example, it might pre-allocate 64 bytes of memory for `let data: [UInt8]` and use the heap after it expands. If you allocate the memory yourself and have to free it later, it's likely always going to be on the heap.

I also noticed that your version adds a null byte at the end. That is only necessary for a C string where length is not given (serves as a marker). Since a Blob is binary data (could contain null bytes) and length is provided you don't need to add the null byte at the end.

**Comment by stephencelis** [comment]
Good calls. If you'd like to submit a PR against `master` I'd love to accept it. I'll rebase `swift-2` against it after.
