### ISSUE TITLE
loop to add statements in transaction

### ISSUE THREAD

**Issue by ipeisong** [stephencelis/SQLite.swift#19]
How can I do this:

```
db.transaction(
    for obj in objects { stmt.run(obj.username, obj.password) }
)
```

thanks.

**Comment by confile** [comment]
@stephencelis Is this the state of the are in the way this lib handles transaction. I mean there are a lot of String statements like ``"BEGIN DEFERRED TRANSACTION"``which cannot be evaluated at compile time?

**Comment by stephencelis** [comment]
This is an _old_ issue, @confile. See the documentation: https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#transactions-and-savepoints

It should be enhanced, though, you can also use a block that returns `.Commit` or `.Rollback`:

``` swift
db.transaction { _ in
    for obj in objects {
        stmt.run(obj.username, obj.password)
    }
    return .Commit
}
```
