### ISSUE TITLE
Struggling with the update statement

### ISSUE THREAD

**Issue by boogdan** [stephencelis/SQLite.swift#193]
Hello,

I'm trying to update a row into my database but even if the code seems to work, the value is not updated in the database.

I have this attached to a button:

 let value = additivesTable.filter(keyColumn == passedDetails)
        let update = value.update(isBookmarkColumn <- 1)
        if let changes = update.changes where changes > 0 {
            println("updated bookmark")
        } else if update.statement.failed {
            println("update bookmark: \(update.statement.reason)")
        }

When I click on the button, the "updated bookmark" appears but there's nothing updated in the database. Do you have any ideas why?

**Comment by boogdan** [comment]
Hmmm...I think the reason of my problem is that I'm trying to modify the databased bundled with my project. I'm new to this and let me know if I'm wrong: the app creates a local database?

**Comment by stephencelis** [comment]
Have you read the documentation on "Connecting to a Database"?

https://github.com/stephencelis/SQLite.swift/blob/d87e05da167bdded01ae74001c5adda865346867/Documentation/Index.md#connecting-to-a-database

**Comment by boogdan** [comment]
Hi Stephen,

Yes, and I can retrieve data from the database without any problems.

**Comment by stephencelis** [comment]
@boogdan Did you see the note there that specifically addresses bundled databases?

> _Note:_ Signed applications cannot modify their bundle resources. If you bundle a database file with your app for the purpose of bootstrapping, copy it to a writable location before establishing a connection (see Read-Write Databases, above, for typical, writable locations).

**Comment by boogdan** [comment]
oooooh now it makes sense. 

In the guide you said that I can create one in the apps' Documents directory. I suppose that I can add my existing database there instead of creating a new one, right? 

Also, what is exactly "app's Documents directory"? Sorry if I'm bothering you with this...I'm sure it's something extremely easy to do but I'm new to iOS dev so I'm struggling a bit :)

Thank you so much for your terrific work that you did with this project.
