### ISSUE TITLE
Swift 2: userVersion gone

### ISSUE THREAD

**Issue by patr1ck** [stephencelis/SQLite.swift#194]
I see in the `swift-2` branch that getting and setting the userVersion was removed. Would you accept a PR that brought this back or was this intentionally left out?

Thanks for your hard work!

**Comment by stephencelis** [comment]
@patr1ck I want to rethink a more unified `PRAGMA` interface, but hadn't had time to finalize it yet. In the meantime, this should get you where you need to be:

``` swift
extension Database {
    public var userVersion: Int {
        get { return Int(scalar("PRAGMA user_version") as! Int64) }
        set { run("PRAGMA user_version = \(transcode(Int64(newValue)))") }
    }
}
```

**Comment by patr1ck** [comment]
Cool, makes sense. Thank you!

**Comment by violabg** [comment]
I did try to use the extension above but then when I try to set the value of userVersion I get this error:

fatal error: 'try!' expression unexpectedly raised an error: attempt to write a readonly database

even if I explicitly use try! Connection(localPdfDbPath.relativePath!, readonly:false)

**Comment by mikemee** [comment]
I've just confirmed that extension appears to be working in the current release version so I'm closing this out. (_PS: @stephencelis  I love how easy it is to add this functionality via the extension!_)

@violabg, I tried the playground example below and everything seemed to behave as expected. E.g. I set `readonly` to be true and it was able to read ok and failed on writing. Then I set it false, and I was able to update it.  If you can make this fail and/or have more info, please re-open with some details. Thanks!

```swift
import SQLite

let db = try! Connection("foo.sqlite", readonly: false)
db.trace { print($0) }

extension Connection {
    public var userVersion: Int {
        get { return Int(scalar("PRAGMA user_version") as! Int64) }
        set { try! run("PRAGMA user_version = \(newValue)") }
    }
}

db.userVersion = 7
print(db.userVersion)
```
