### ISSUE TITLE
sqlite3.h not found

### ISSUE THREAD

**Issue by madskunker** [stephencelis/SQLite.swift#197]
I have pulled the latest cocoa pod for swift-2 after I installed the GM seed of Xcode 7

SQLite wont build.  I am sure I am missing something stupid.

Thanks

J

**Comment by tanglx61** [comment]
If you look under Pods/SQLite.swift/Support Files/SQLite.swift.modulemap, on line 8, you'll see: 

`header "/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/sqlite3.h"
`

change the `Xcode-beta.app` into `Xcode.app` and the `sqlite3.h not found` error should go away. On the other hand, I still experience "Use of undeclared type' for `Query` and `Database` classes, but not `Expression< >` ever since I changed from manual integration to cocoapods.

**Comment by tanglx61** [comment]
My bad, it seems like those classes have been renamed (it's been a while since I updated) to Table and Connection, respectively.

**Comment by stephencelis** [comment]
This should be working now. The GM has a different SDKROOT and CocoaPods does not currently support SDKROOT-relative files.

**Comment by madskunker** [comment]
Do I need to reinstall the Pod?

**Comment by madskunker** [comment]
Now it gets past that point but 

var db : Database throws an error Unsupported Datatype

Yes I import SQLite

J

**Comment by stephencelis** [comment]
@madskunker That interface changed during the update. It should be `db: Connection` (or `db: SQLite.Connection`) now.

**Comment by tanglx61** [comment]
@stephencelis  can confirm things work with swift 2.0 now. Maybe you could add a quick notice on the readme on Master branch to let people know that there are some API breaking changes for Swift 2.0 and point them to the documentation of the new 2.0 branch. Really appreciate your work! :)

**Comment by madskunker** [comment]
That would be helpful

A quick reference of Prior and New

Jeff

On Sep 10, 2015, at 10:57 AM, tanglx61 <notifications@github.com<mailto:notifications@github.com>> wrote:


@stephencelis<https://github.com/stephencelis> can confirm things work with swift 2.0 now. Maybe you could add a quick notice on the readme on Master branch to let people know that there are some API breaking changes for Swift 2.0 and point them to the documentation of the new 2.0 branch. Really appreciate your work! :)

**Comment by tanglx61** [comment]
@madskunker In the meantime you could refer to the updated doc here: https://github.com/stephencelis/SQLite.swift/blob/swift-2/Documentation/Index.md#connecting-to-a-database

**Comment by madskunker** [comment]
Thanks

I guess the conversion is a bit more complicated.  more of a rewrite :)

J
On Sep 10, 2015, at 11:00 AM, tanglx61 <notifications@github.com<mailto:notifications@github.com>> wrote:


@madskunker<https://github.com/madskunker> In the meantime you could refer to the updated doc here: https://github.com/stephencelis/SQLite.swift/blob/swift-2/Documentation/Index.md#connecting-to-a-database

**Comment by mikemee** [comment]
Hi, I'm doing a pass to close some old issues and it seems this may now be moot. Please re-open if you have more information or feel this should still be active. Thanks!
