### ISSUE TITLE
Binding Issues Swift 2

### ISSUE THREAD

**Issue by hcatlin** [stephencelis/SQLite.swift#200]
So, after hitting a lot of bugs (detailing each of them) in the new swift-2 branch, I decided to try and go as low-level as I could figure out, so I tried the run(NSString) method. Here is my code:

```
        for lang in try db.run("select code, name, id from langs") {
            let code = lang[0]!;
            let name = lang[1]!;
            let id = lang[2]!;
            //langs.append(Lang(code: code, name: name, referenceId: id))
        }
```

I was unable to do `lang["name"]`, which the documentation seemed to indicate, but numeric indexes were working. However, when I unwrapped these, each one of them *claimed* to be a String or Int in the debugger, but the last comment out line (where I create a struct to hold the data) would doggidly declare that they were of type `Binding`. I attempted to use `as! Int` and `as! String` to cast them... but they wouldn't work. I also tried `dataBindingValue()` (or whatever is similiarily named), but that wasn't defined on `Binding`.

I used debugger, I tried reading the code... and I just couldn't even get the numeric value out at all. :(

**Comment by stephencelis** [comment]
> I was unable to do `lang["name"]`, which the documentation seemed to indicate, but numeric indexes were working.

Can you point out where in the `swift-2` branch docs that indicates `lang["name"]` should work? This kind of subscripting hasn't been supported in awhile. I may support it again in the future but will throw an assertion failure on ambiguity (when two or more columns in a select statement have the same name).

> However, when I unwrapped these, each one of them *claimed* to be a String or Int in the debugger, but the last comment out line (where I create a struct to hold the data) would doggidly declare that they were of type `Binding`. I attempted to use `as! Int` and `as! String` to cast them... but they wouldn't work. I also tried `dataBindingValue()` (or whatever is similiarily named), but that wasn't defined on `Binding`.

`Binding` is a protocol. You'll need to cast values into the type you expect them to be when using the low-level API:

``` swift
let code = lang[0] as! String // or Int64?
let name = lang[1] as! String
let id = lang[2]! as Int64
```

The low-level SQLite.swift API could definitely be a bit more friendly in this respect, and will be a focus for the next release after the Swift 2 branch is merged into `master`.
