### ISSUE TITLE
Subscript String

### ISSUE THREAD

**Issue by hcatlin** [stephencelis/SQLite.swift#201]
This is on the swift-2 branch where I would expect the following to work, based off the docs.

```
self.db = try Connection(path!, readonly: true)
var table = db["users"]
```

Everytime the last line executes, it says there is no subscript for type String.

Not sure if it's a bug, or if I'm just being an idiot.

**Comment by stephencelis** [comment]
Are you reading the docs on the `swift-2` branch? Can you point out where so they can be updated? Queries are now objects independent of database connections:

``` swift
self.db = try Connection(path!, readonly: true)
var table = Table("users")

// insert
let rowid = try db.run(table.insert(email <- "foo@bar.info"))

// select
for row in db.prepare(table) {
    // …
}
```

**Comment by hcatlin** [comment]
That might be my issue that's confusing me...



—

**Comment by stephencelis** [comment]
Keep me posted! Thanks!

**Comment by hcatlin** [comment]
Yeah, this was me being confused about the documentation!
