### ISSUE TITLE
Inconsistent deployment targets

### ISSUE THREAD

**Issue by st3fan** [stephencelis/SQLite.swift#203]
I think the swift-2.0 branch has inconsistent deployment targets for iOS. At the project level it is set to 8.0 but then the individual targets are at 9.0.

Is it possible to change them all to 8.0? I don't think there is an iOS 9 dependency? (Other than Swift 2.0, which should run on iOS 7 and up)

**Comment by st3fan** [comment]
I created a PR https://github.com/stephencelis/SQLite.swift/pull/204

**Comment by mikemee** [comment]
I'm doing a pass to close some old issues and it seems this is resolved via 723e19b6ce67a23b3acff0ebdc95d6825c8a4643. Please re-open if you have more information or feel this should still be active. Thanks!
