### ISSUE TITLE
Xcode7 GM Build Error

### ISSUE THREAD

**Issue by little2s** [stephencelis/SQLite.swift#206]
There is an error after I update SQLite.swift today, how to fix that? Thank you!

Installing SQLite.swift 1.0.0.pre (was 0.1.0.pre)

/*******/Pods/SQLite.swift/Source/Core/SQLite-Bridging.h:28:9: Include of non-modular header inside framework module 'SQLite.SQLite_Bridging'
Could not build Objective-C module 'SQLite'

**Comment by stephencelis** [comment]
What's your Podfile look like? Are you on the `swift-2` branch?

**Comment by little2s** [comment]
@stephencelis Thanks for your response, my Podfile like this:

**Comment by little2s** [comment]
@stephencelis Thanks for your response, my Podfile looks like this:

platform :ios, '8.0'
use_frameworks!
pod 'SQLite.swift', git: 'https://github.com/stephencelis/SQLite.swift.git', branch: 'swift-2'

I switch my project to swift-2 last Friday, there is no problem that time, but it's not fine after I use `pod update`, finally I delete these lines:

#ifndef COCOAPODS
#import "sqlite3.h"
#endif

And it is okay now. But this is not a good way, right? There maybe something wrong with me, please tell me, thank you!

**Comment by stephencelis** [comment]
Definitely not. I'll take a look at this tonight to see if I can repro. Thanks!

**Comment by troylelandshields** [comment]
I am also experiencing this issue. Any help is appreciated, thanks!

**Comment by vineethvijayan** [comment]
I am also experiencing the same issue 

Could not build Objective-C module 'SQLite'

**Comment by abiaad** [comment]
Same for me

**Comment by aceiii** [comment]
I'm having the same issue and was able to fix it the same way.

I noticed there are almost the same 3 lines in the 2 files SQLite-Bridging.h and SQLite-Bridging.m.
But in the .h file, it is
```
#ifndef COCOAPODS
#import "sqlite3.h"
#endif
```
whereas in the .m file it is
```
#import "SQLite-Bridging.h"

#ifdef COCOAPODS
#import "sqlite3.h"
#endif
```

Notice the .m file imports the .h file, and there is a difference between the `#ifdef` and `#ifndef`.

**Comment by hiltonc** [comment]
Adding this to my `Podfile` solved the problem for me:

    post_install do |installer|
        installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
            configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        end
    end

**Comment by mikemee** [comment]
Pretty sure this is fixed now as part of the pending PR #314, and possibly in the main branch already. Closing this and keeping #230 open as a placeholder for CocoaPod build problems until/if that PR is accepted.

**Comment by Tom29** [comment]
I still have this issue today after using cocoapod.

**Comment by Tom29** [comment]
I have to delete 3 lines like @little2s . 
The way of @hiltonc doesn't help.

**Comment by posix88** [comment]
Same for me

**Comment by ChaosTong** [comment]
in SQLite.h i change the code like this #import "SQLite-Bridging.h"
work for me 
cocoapod 1.0.1 xcode 7.3.1 swift 2.2

**Comment by IskanderNazarov** [comment]
Hello @stephencelis.
I have the same issue on Xcode 8.3.1 and swift 3. No one solution doesn't work for me. How can I fix it?

In podfile I have the next line `pod 'SQLite.swift', '~> 0.11.4'`

**Comment by sashwini** [comment]
@stephencelis I am trying to migrate my project to swift 3 in xcode 8.3. I am getting this error and none of the suggested solutions seem to work. Any update on it?

**Comment by IskanderNazarov** [comment]
@sashwini I also had the same problem until I saw the next line in 'Installation' block of SQLite.swift:

> Note: SQLite.swift requires Swift 4 (and Xcode 9).

So, all you need is to migrate to Swift 4 and Xcode 9 and everything will work fine
