### ISSUE TITLE
library not found for -lsqlite3 for swift1.2

### ISSUE THREAD

**Issue by woderchen** [stephencelis/SQLite.swift#209]
Hello stephencelis，
I met an issue for iPhone 5s during buid, but the issue does not happened for Xcode simulator. I have followed your guide and make sure everything is right. could you please give some suggestion for this?

ld: library not found for -lsqlite3
clang: error: linker command failed with exit code 1 (use -v to see invocation)
my environment as below list

xcode 6.4, swift1.2.

**Comment by stephencelis** [comment]
Hi there, can you let me know if this is still an issue with Swift 2?

**Comment by mikemee** [comment]
Hi, I'm doing a pass to close some old issues and it seems this may have been resolved already with the move to Swift 2. Please re-open if you have more information or feel this should still be active. Thanks!
