### ISSUE TITLE
Raw SQL query with results. Statement.bind() unexpected error Row vs Element object?

### ISSUE THREAD

**Issue by acrookston** [stephencelis/SQLite.swift#210]
Hi,
I'm using SQLite.swift on the swift-2 branch. Looks like commit fb7128e0bb45f932a98e1c168182bfe723ef3103 according to my `Podfile.lock`. My Podfile gets SQLite.swift with
```ruby
pod 'SQLite.swift', git: 'https://github.com/stephencelis/SQLite.swift.git', branch: 'swift-2'
```

According to the documentation, which I'm guessing is wrong here
```Swift
let stmt = try db.prepare("SELECT * FROM attachments WHERE typeConformsTo(UTI, ?)")
for row in stmt.bind(kUTTypeImage) { /* ... */ }
```

I tried implementing something similar, my code:
```Swift
class User {
    init(row: Row) { ... }

    class func get() {
        let stmt = db.prepare("SELECT DISTINCT users.*  FROM users ...")
        for row in stmt.bind(arg1, arg2, arg3) {
            User(row: row)
        }
    }
}
```

and I get the following error from Xcode for the `User(row: row)` code:
```
(row: Element)' (aka '(row: Array<Optional<Binding>>)') is not convertible to '(row: Row)
```

I haven't found any way around this so figured I might post a question. Any thoughts on what's going on here? Any tips on getting a Row object instead of this or handling the Element object (which I can't find in the SQLite.swift source)?

Running Xcode 7 GM.
Great library btw! Thanks for all the hard work.

**Comment by acrookston** [comment]
Sorry for the false alarm, I seem to have solved this. I already had an init method for `[Binding]?`
```
    init(raw: [Binding?]) { ... }
```
Which in turn checks the table info and gets the right data for the right column. It seems in my migration from Swift 1.2 to 2.0 I changed the call from the correct initializer.

**Comment by stephencelis** [comment]
Glad you got things sorted!
