### ISSUE TITLE
 unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by Boli-CS** [stephencelis/SQLite.swift#211]
Thanks for your awesome work.

I get a problem like this and I hope you could help me.
1. I defined a Table like this:
```
public class GlobalSetting {
   static let dbPath = NSHomeDirectory() + "/Documents/db.sqlite3";
   static let themeTable = Table("Theme")
    public struct Theme {
        static let themeID = Expression<Int64>("ThemeID")
    }
}
```
2. I created the table:
```
let db = try! Connection(GlobalSetting.dbPath)
try db.run(GlobalSetting.themeTable.create{t in
                    t.column(GlobalSetting.Theme.themeID, primaryKey : true)
                })
```
3. when I try to insert data like this:
```
try db.run(GlobalSetting.themeTable.insert(GlobalSetting.Theme.themeID <- 0))
```
I got the problem at 934 line of Query.swift(return self.lastInsertRowid!), it says:fatal error: unexpectedly found nil while unwrapping an Optional value. But the data has already inserted into the database.

**Comment by Boli-CS** [comment]
after i search the function"sqlite3_last_insert_rowid", I found this:https://www.sqlite.org/c3ref/last_insert_rowid.html. It says:If no successful INSERTs into rowid tables have ever occurred on the database connection D, then sqlite3_last_insert_rowid(D) returns zero.

so when I insert data at the first time:
```
public var lastInsertRowid: Int64? {
        let rowid = sqlite3_last_insert_rowid(handle)
        return rowid > 0 ? rowid : nil
    }
```
the rowid here is zero, and the exception occurs.

This is my analysis and looking for your response.

**Comment by stephencelis** [comment]
Hm, let me think about how to best handle this. The common use case is to let primary keys assign themselves automatically, in which case they will start at `1`, not `0`, and go from there. It's rarer still to use `0` as a primary key. The function `sqlite3_last_insert_rowid`, for example, says this:

> If no successful INSERTs into rowid tables have ever occurred on the database connection D, then sqlite3_last_insert_rowid(D) returns zero.

By assigning `0` to a primaryKey, you are creating an unexpected state that becomes confused with an error.

I do wonder if this would work, though:

    ``` swift
    public var lastInsertRowid: Int64? {
        let rowid = sqlite3_last_insert_rowid(handle)
        return changes > 0 ? rowid : nil
    }
    ```

**Comment by Boli-CS** [comment]
yes, you are right. It is not appropriate to use zero as the primaryKey. I should change to code to make it better. I tried the method you offered and it truly works. And in my opinion, this method is better and easy to understand.

Thanks for your help.

**Comment by S4TNEW** [comment]
Could you reconsider changing the ``lastInsertRowid`` to accept a negativ rowid?

Something like:

```
public var lastInsertRowid: Int64? {
    let rowid = sqlite3_last_insert_rowid(handle)
    return changes != 0 ? rowid : nil
}
```

We are using the negative primaryKey values for transfer tables. The ``sqlite3_last_insert_rowid`` method would return the negativ rowid (e.g. -1) without problems and you would still have the "no insert = 0" value.

**Comment by stephencelis** [comment]
I'd consider the patch. Wanna open a PR for discussion?

**Comment by S4TNEW** [comment]
Thanks, I opened a PR.
