### ISSUE TITLE
Use of unresolved identifier 'Database'

### ISSUE THREAD

**Issue by donald3hamilton** [stephencelis/SQLite.swift#213]
This may end up being just a stupid mistake, but I've installed SQLite.swift successfully in the past and the only difference now is XCode 7 and the new Swift2 master. I've gone through all the installation steps three times and I still get "Use of unresolved identifier 'Database'" in my code. The SQLite.swift code compiles fine on its own in swift 2. Same with my code without SQLite. But together they have this problem that they didn't have before.

Thanks for your time and thought, any help is appreciated.

**Comment by martindobrev** [comment]
'Database' seems to be replaces by 'Connection' - check out the source code

**Comment by donald3hamilton** [comment]
You are right. Thank you very much.
