### ISSUE TITLE
Problem with aggregate functions in Swift 2.0 branch

### ISSUE THREAD

**Issue by ifau** [stephencelis/SQLite.swift#214]
Hello. I just installed this library to my project (manually, not through cocoapods) and I have following problem. In the [documentation](https://github.com/stephencelis/SQLite.swift/blob/swift-2/Documentation/Index.md#aggregation) there is an example of using average function:
```swift
let average = try db.scalar(users.select(balance.average)) // -> Double?
// SELECT avg("balance") FROM "users"
```
But when I try this, the compiler displays error:
>Cannot invoke 'scalar' with an argument list of type '(Table)'

My code is:
```swift
let db = try Connection(databasePath)
let table = Table("MyTable")
let bbbb = Expression<Double>("bbbb")
let average = try db.scalar(table.select(bbbb.average)) // error here
```
For some reason, `table.select()` return `Table`, not `ScalarQuery<>`.
Can you help?

**Comment by stephencelis** [comment]
Sorry about that. I've added some test coverage around this and it should work now. Can you re-pull and try?

**Comment by ifau** [comment]
Yes, it works. Thank you very much!
