### ISSUE TITLE
Use of unresolved identifier ' Database'

### ISSUE THREAD

**Issue by deermapper** [stephencelis/SQLite.swift#215]
Unfortunately I ran in the same problem with Xcode 7.0 like #54:

<img width="631" alt="bildschirmfoto 2015-09-18 um 22 29 50" src="https://cloud.githubusercontent.com/assets/6825724/9970404/3a39bd34-5e55-11e5-872a-baf269f241fb.png">

Do you have any idea where there could be the problem?

**Comment by stephencelis** [comment]
Sorry about that! Database has been renamed Connection on the `swift-2` branch. Please see the updated README/documentation.

**Comment by deermapper** [comment]
Thank's a lot for the quick reply!
