### ISSUE TITLE
Empty database on iOS device

### ISSUE THREAD

**Issue by pk1** [stephencelis/SQLite.swift#216]
Hi,

I just recently migrated my whole project to Swift 2 and I'm now trying to run my app for the first time on a real iOS device. Until now everything was working as expected in the simulator.
My problem is that as soon I try to access the SQLite database on the iOS device from within my app (opening a connection to the database seems not to be an problem) I get an error that table [tablename] is not available (no such table). But the packaged SQLite database contains several tables with data. The SQLite database file has been also added to the Copy Bundle Resources build phase but still no luck.

Would be great if someone can point me in the right direction.

**Comment by stephencelis** [comment]
Would you please share the code you're using the load the database?

**Comment by blkbam** [comment]
@pk1 Sounds like a case-sensitivity problem. The simulator is not case-sensitive with file names but the device is.

**Comment by stephencelis** [comment]
Hi @pk1. I'm going to close this for radio silence. If you're still having the problem, please let me know! If you were able to solve, please share with us!
