### ISSUE TITLE
Wrong syntax of foreign key

### ISSUE THREAD

**Issue by C4Grey** [stephencelis/SQLite.swift#217]
Hi!
Just finished migration to the swift-2 branch and encountered the problem with foreign key:
````swift
t.foreignKey(columnGroupId, references: groups, groups[Expression<String>("id")], delete: TableBuilder.Dependency.Cascade)
````
Such instruction will generate the next SQL code:
````SQL
FOREIGN KEY ("group_id") REFERENCES "groups" ("groups"."id") ON DELETE CASCADE
````
And this is where my app thorows an error:
````
fatal error: 'try!' expression unexpectedly raised an error: near ".": syntax error: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-700.0.59/src/swift/stdlib/public/core/ErrorType.swift, line 50
````
It seems like the syntax is a little bit wrong, it shoul be something like this(according to [the specification](https://www.sqlite.org/foreignkeys.html)):
````SQL
FOREIGN KEY(group_id) REFERENCES groups(id) ON DELETE CASCADE
````
I think that the main part is that the referenced column inside brackets should be not prefixed with a table name.

**Comment by stephencelis** [comment]
The syntax changed a little. Try this:

``` swift
let id = Expression<String>("id")
t.foreignKey(columnGroupId, references: groups, id, delete: TableBuilder.Dependency.Cascade)
```

**Comment by C4Grey** [comment]
Yes, my bad, just figured out how expressions transforms in SQL code...Looks like this moment should be described in [the documentation](https://github.com/stephencelis/SQLite.swift/blob/swift-2/Documentation/Index.md#table-constraints)(I mean that foreign key now requires a table and an expression, instead of table subscript by an expression).
