### ISSUE TITLE
Getting `[Byte]` out of `Blob`

### ISSUE THREAD

**Issue by alecthomas** [stephencelis/SQLite.swift#22]
In order to serialize protobufs using protobuf-sqlite I need to provide it with a `[Byte]` array. The only way I'm aware of constructing this from an `UnsafePointer` is via an NSData object:

```swift
let col = row[self.data]
var bytes = [Byte](count: col.length, repeatedValue: 0)
col.data.getBytes(&bytes)
```

With `Blob.data` private I am unable to do this. I guess my question is a) is there another way to get a `[Byte]` from the `Blob` or b) could `Blob.data` be public?

**Comment by stephencelis** [comment]
So, you can actually use an UnsafeBufferPointer to accomplish this.

``` swift
let ptr = UnsafeBufferPointer<Byte>(start: UnsafePointer<Byte>(blob.bytes), count: blob.length)
let bytes = Array(ptr) // [Byte]
```
