### ISSUE TITLE
Swift 2: runtime error during failed statement preparation

### ISSUE THREAD

**Issue by kujenga** [stephencelis/SQLite.swift#220]
I'm trying to access a db that is very occasionally locked by another process and am experiencing a runtime error at the following line: https://github.com/stephencelis/SQLite.swift/blob/swift-2/Source/Core/Statement.swift#L34

A simple way to recreate this issue is to open the SQLite db that your application will be reading using the command line `sqlite3` tool and place an exclusive lock on it using `PRAGMA locking_mode = EXCLUSIVE; BEGIN EXCLUSIVE;`. The run any code or test that also accesses the db.

Since statement preparation call can fail, it seems like the `try!` should instead be a `try`, allowing the error to propagate up and be handled appropriately. I've implemented this change in a [fork](https://github.com/kujenga/SQLite.swift). Happy to submit a pull request if you think that would be appropriate.

**Comment by stephencelis** [comment]
That's fair. Have you tried setting `busyTimeout` or `busyHandler` as a workaround? https://github.com/stephencelis/SQLite.swift/blob/swift-2/Source/Core/Connection.swift#L345-L373

**Comment by kujenga** [comment]
Yeah, I actually went there first but it didn't seem to have much of an effect. I'm no SQLite expert though, it's possible I'm doing something wrong. Here's a pared down version of the code in question.

```swift
let db = try Connection(dbURL.path!, readonly: true)

db.busyHandler({ tries in
    tries < 3
})

for row in db.prepare("SELECT example FROM table WHERE something == 'value'" { // runtime error here
    // processing
}
```

**Comment by mikemee** [comment]
@kujenga Are you ok if this is closed, now that https://github.com/stephencelis/SQLite.swift/pull/290 has been merged?

**Comment by kujenga** [comment]
@mikemee Yep, sounds good to me!
