### ISSUE TITLE
Use of unresolved identifier 'Connection'

### ISSUE THREAD

**Issue by deermapper** [stephencelis/SQLite.swift#222]
Any ideas where the error could come from?

<img width="717" alt="bildschirmfoto 2015-09-21 um 20 48 44" src="https://cloud.githubusercontent.com/assets/6825724/10001545/84d6e962-60a2-11e5-8314-cd7d2cfa94a5.png">

In my test project the database connection ran well. In my productive project there comes this error. This is how my Build phases look like - identical to my test project:

<img width="672" alt="bildschirmfoto 2015-09-21 um 20 54 55" src="https://cloud.githubusercontent.com/assets/6825724/10001685/3e66ff02-60a3-11e5-9899-7e6747ec4099.png">

Thank's for helping!

**Comment by stephencelis** [comment]
Could you please try again with the master branch? The swift-2 branch was recently merged in.

**Comment by deermapper** [comment]
I got everything to work so far! Thank's a lot for the great framework!

**Comment by stephencelis** [comment]
Closing this out! Glad you got everything working!
