### ISSUE TITLE
SQLITE : Segmentation Fault 11 on upgrading to Xcode 7 Swift 2.0 Query.swift

### ISSUE THREAD

**Issue by irshad9998** [stephencelis/SQLite.swift#224]
i have upgraded swift 1.2 to swift 2.0 then  Segmentation Fault 11 error occurs

here is code where is problem

    var (columnNames, idx) = ([String: Int](), 0)
        column: for each in self.query.columns ?? [Expression<Void>(literal: "*")] {
            let pair = split(each.expression.SQL) { $0 == "." }
            let (tableName, column) = (pair.count > 1 ? pair.first : nil, pair.last!)

            func expandGlob(namespace: Bool) -> Query -> Void {
                return { table in
                    var query = Query(table.database, table.tableName.unaliased)
                    if let columns = table.columns { query.columns = columns  }
                    var names = query.selectStatement.columnNames.map { quote(identifier: $0) }
                    if namespace { names = names.map { "\(table.tableName.SQL).\($0)" } }
                    for name in names { columnNames[name] = idx++ }
                }
            }

            if column == "*" {
                let tables = [self.query.select(*)] + self.query.joins.map { $0.table }
                if let tableName = tableName {
                    for table in tables {
                        if table.tableName.SQL == tableName {
                            expandGlob(true)(table)
                            continue column
                        }
                    }
                    assertionFailure("no such table: \(tableName)")
                }
                tables.map(expandGlob(self.query.joins.count > 0))
                continue
            }

            columnNames[each.expression.SQL] = idx++
        }
        return columnNames
    }()"

**Comment by stephencelis** [comment]
@irshad9998 Upgrading to Swift 2 requires an upgrade to the `swift-2` branch of SQLite.swift. Please give that a shot and let me know if you're still having problems.

**Comment by wildonr** [comment]
Im also having the same issue, i have downloaded the latest sqlite.swift, coverted the project to swift 2 Xcode 7

**Comment by stephencelis** [comment]
The `master` branch (Swift 1.2-compatible) does not cleanly update via Xcode conversion. You must download from the `swift-2` branch.

**Comment by wildonr** [comment]
Thanks, just realised that after reading this post again, sorry

**Comment by irshad9998** [comment]
thnx stephencelis problem solved
