### ISSUE TITLE
Binary operator '==' cannot be applied to operands of type 'Expression<String>' and 'String!'

### ISSUE THREAD

**Issue by boogdan** [stephencelis/SQLite.swift#226]
Hello,

I have the following:

``` swift
var passedDetails:String! (it gets a value before the filtering)
let additivesTable = Table("Additives")
let keyColumn = Expression<String>("key")
```

When I try to filter:

``` swift
let valueAdditive = additivesTable.filter(keyColumn == passedDetails)
```

I'm getting this error: `Binary operator '==' cannot be applied to operands of type 'Expression<String>' and 'String!'`

The same thing worked perfectly on Swift 1.2. Any ideas?

**Comment by stephencelis** [comment]
Hm, this may be a bug in Swift 2 type resolution. I'll see if I can repro and file a bug with Apple if need be. In the meantime, does the problem go away if you call `passedDetails!`? Is there a way to refactor this code so that you don't have to use an implicitly-wrapped optional?

**Comment by boogdan** [comment]
Nope, the error appears even if its "passedDetails!".
It also appears if I simply add a string instead of the variable.

**Comment by boogdan** [comment]
Oh, stupid me. 
I forgot to add "import SQLite" into the class and that's why the error occurs. Geez...

**Comment by vineethvijayan** [comment]
Is it fixed? I am trying like this 

var index = String 
let Index = Expression<String?>("Index")
for row in DataManager.con.prepare(table).filter(index == Index){
}

gives me compile error like below.
/Common Files/GitHiub/vesseltracker-xcode/vesseltracker/vesseltracker/Model/CrewList.swift:155:64: Cannot convert value of type 'Expression<Bool?>' (aka 'Expression<Optional<Bool>>') to expected argument type '@noescape (Row) throws -> Bool'

Am I doing anything wrong?

**Comment by stephencelis** [comment]
@vineethvijayan The `filter` method needs to be called on the `table`, not the prepared statement. Did you find an error in the docs that had you code it this way?

**Comment by vineethvijayan** [comment]
Yes my mistake @stephencelis Sorry about that

**Comment by lethianqt94** [comment]
How about this case? Did I make something wrong?
![31a50d06089b79d661784c7e0e82dab1](https://cloud.githubusercontent.com/assets/10287585/16546526/c7468a44-4177-11e6-9abb-b1d96cfb7509.png)
