### ISSUE TITLE
Swift 2 - Use of unresolved identifier 'sqlite3_rekey'

### ISSUE THREAD

**Issue by wildonr** [stephencelis/SQLite.swift#227]
Ive added the Swift-2 version of sqlite.swift to my project since upgrading to swift 2 today Xcode 7, after resolving all sorts of issues, i now have one problem preventing me from building my project, the Cipher.Swift module is complaining about Use of unresolved identifier 'sqlite3_rekey'

I didn't use Cipher or need it in my previous version. All header files are correct importing slqite3.h, all of the source files for sqlite are manually added as frameworkless.

Any help would be greatly appreciated.

![error_1](https://cloud.githubusercontent.com/assets/12153427/10024884/1f6ae59c-6151-11e5-9971-3bee1a2b2243.png)

**Comment by stephencelis** [comment]
Going Frameworkless is going to always require a bit more effort, so I'd recommend looking at some usage numbers to see if it's still worth supporting iOS 7.

In this case you need to delete the Cipher.swift file unless you're using SQLCipher.

**Comment by wildonr** [comment]
Thanks for the reply, if i remove the Cipher.Swift file it throws loads of other errors, I'm going frameworkless as when i deployed for testing in app store it failed, going frameworkless resolved the issue, could you tell me which other source files are dependant on the Cipher.Swift file ?

**Comment by wildonr** [comment]
I'm only supporting is iOS 8 not 7, I'm now upgraded to Xcode 7

**Comment by wildonr** [comment]
Wow, I'm really sorry for wasting your time, deleting the Cipher.Swift file before seemed to cause errors, just done it and its all compiling again, thanks and sorry for wasting your time.

**Comment by stephencelis** [comment]
@wildonr If you're only supporting iOS 8 please follow the installation instructions that add the SQLite framework to your project. Dragging the source files directly into your project is a lot more work and prone to failure.

**Comment by wildonr** [comment]
Hi, its ok, I'm sorted now, thanks
