### ISSUE TITLE
With Swift 2, without block other threads from executing statements within the transaction

### ISSUE THREAD

**Issue by isurukej** [stephencelis/SQLite.swift#229]
Cann't we get SQLite.swift lib, without block other threads from executing statements within the transaction, when threads that open transactions and savepoints.

**Comment by stephencelis** [comment]
@isurukej This is by design to ensure that a single connection executes everything in a transaction and doesn't add accidental executed statements into that transaction. Have you tried creating new connections for these transactions or work that happens outside of them concurrently?

**Comment by mikemee** [comment]
We're doing a pass to close some old issues that haven't had activity in a while. Please re-open if you have more information or feel this should still be active. Thanks!
