### ISSUE TITLE
performance issue iterating over a query

### ISSUE THREAD

**Issue by violabg** [stephencelis/SQLite.swift#23]
I'm having big performance issue iterating over a query, this is my code:

``` swift
func getPdfWithCategory(language:Language) -> CategoriesForLanguage {
        let categoriesForLanguage = CategoriesForLanguage()

        let PDFs = pdfDb!.pdfsTb.table
        let categories = pdfDb!.categoriesTb.table
        start = NSDate()
        let query = PDFs.select(PDFs[*], categories[pdfDb!.categoriesTb.id], categories[pdfDb!.categoriesTb.name], categories[pdfDb!.categoriesTb.thumb], categories[pdfDb!.categoriesTb.orderid])
.join(categories, on: categories[pdfDb!.categoriesTb.id] == PDFs[pdfDb!.pdfsTb.categoryId])
.filter(PDFs[pdfDb!.pdfsTb.languageId] == language.id)

        let timeInterval:NSTimeInterval = start!.timeIntervalSinceNow
        println("query \(timeInterval)")

        println("query count = \(query.count)")

        start = NSDate()
        for row in query {

        }

        let timeInterval2:NSTimeInterval = start!.timeIntervalSinceNow
        println("for row in query \(timeInterval2)")
        return categoriesForLanguage
    }
```

and this is the print results:

query -0.0109010338783264
query count = 88
for row in query -2.39910697937012

I have even removed the join to see if it was that:

``` swift
func getPdfWithCategory(language:Language) -> CategoriesForLanguage {
        let categoriesForLanguage = CategoriesForLanguage()

        let PDFs = pdfDb!.pdfsTb.table
        let categories = pdfDb!.categoriesTb.table
        start = NSDate()
        let query = PDFs.select(PDFs[*]).filter(PDFs[pdfDb!.pdfsTb.languageId] == language.id)

        let timeInterval:NSTimeInterval = start!.timeIntervalSinceNow
        println("query \(timeInterval)")

        println("query count = \(query.count)")

        start = NSDate()
        for row in query {

        }

        let timeInterval2:NSTimeInterval = start!.timeIntervalSinceNow
        println("for row in query \(timeInterval2)")
        return categoriesForLanguage
    }
```

it improved a little bit, but still too long:

query -0.00782698392868042
query count = 88
for row in query -1.40383696556091

P.S. I'm testing on a iPad

**Comment by androidcn** [comment]
so slow ....
using 
for about 2000rows

**Comment by stephencelis** [comment]
@androidcn Please try to constructively contribute to the conversation and read this thread thoroughly (check my questions to others throughout, including whether you've compiled for "Release" or not, and what device you're running on).

In short:

- The basic iteration API should be as fast as interfacing with libsqlite3 directly, while the typed API is as fast as adding type-checking logic for each row. You're likely hitting a Swift or SQLite bottleneck.

- In the end, iterating over 2,000 rows seems a bit heavy-handed when SQLite provides aggregation APIs and when you can scope/batch your queries.

**Comment by androidcn** [comment]
@stephencelis but i want to use typed API

**Comment by stephencelis** [comment]
@androidcn The typed API is as fast as manually-typed, so please do. It will improve with Swift. Scope your queries for performance.

**Comment by stephencelis** [comment]
An update to those listening: Swift 1.2 performs 2x+ faster for me. If you end up re-running your benchmarks (off the `swift-1-2` branch), please share your experiences.

**Comment by androidcn** [comment]
i will check it out later

**Comment by violabg** [comment]
I have tested my code with branche Swift 1.2.
I get 1,3 sec.
with Swift 1.1 I get 6,9 sec.  

using raw sql I get 0,28 sec. with Swift 1.2

**Comment by stephencelis** [comment]
Thanks @violabg! Hopefully things will continue to improve steadily.

**Comment by TomasLinhart** [comment]
A little bit OT. When will you merge the Swift 1.2 branch into master, @stephencelis ?

**Comment by stephencelis** [comment]
@TomasLinhart Per https://github.com/stephencelis/SQLite.swift/pull/62:

> This PR is open to track changes against the Swift 1.2 beta. It won't be merged till Swift 1.2 goes GM, but will be continuously rebased onto `master`.

**Comment by sehgalsaheel** [comment]
Is the limit set to 1000? Or is there a way to do more than 1000 (8000 to be specific)

**Comment by stephencelis** [comment]
@sehgalsaheel Have you tried it? Have you had problems? You should have the same ability, limit-wise, as you'd have with raw sqlite3. If the device can't handle 8,000, you should be batching.
