### ISSUE TITLE
Length in Blob - Swift 2

### ISSUE THREAD

**Issue by semjavier** [stephencelis/SQLite.swift#233]
I need to use the length property of the Blob type but it seems that it has disappeared in Swift's 2 branch. Is there anyway to know the length of Blob type?

**Comment by stephencelis** [comment]
The `bytes` property is public and `[UInt8]`, so you can call `blob.bytes.count`.

https://github.com/stephencelis/SQLite.swift/blob/swift-2/Source/Core/Blob.swift#L27
