### ISSUE TITLE
Request: ability to run select queries on a separate thread

### ISSUE THREAD

**Issue by isurukej** [stephencelis/SQLite.swift#236]
'Insert and 'Select' quarries run separate thread in swift - 2 at the same time. Because in swift 2 version "Threads that open transactions and savepoints will block other threads from executing statements while the transaction is open."

**Comment by stephencelis** [comment]
@isurukej Everything should be running in the same queue as long as it's the same connection. Do you have code that reproduces the issue?

**Comment by isurukej** [comment]
Thanks your reply, But I mean that when 'insert' more 2000 records in 'transactions' block and run 'select' quarry in that time. So 'select' quarry run after finished finished 'insert' quarries. I think because "Threads that open transactions and savepoints will block other threads from executing statements while the transaction is open." in Swift 2. So I run 'insert' quarries in separate Connection. is that OK?

**Comment by stephencelis** [comment]
@isurukej Ah, so it doesn't sound like this is a bug then. You were asking for a feature request to run SELECT statements in a different thread? Let me think about the repercussions of that.

**Comment by isurukej** [comment]
Thanks.

**Comment by mikemee** [comment]
Added to [Feature Requests](https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Planning.md).
