### ISSUE TITLE
Crashing on iOS 8.0/8.1 due to sqlite3_close_v2

### ISSUE THREAD

**Issue by shnhrrsn** [stephencelis/SQLite.swift#239]
We're experiencing crashing on iOS 8.0/8.1 due to the use of `sqlite3_close_v2` in `Connection.swift`/`deinit`:

```
dyld: lazy symbol binding failed: Symbol not found: _sqlite3_close_v2
  Referenced from: /Users/.../DerivedData/Build/Products/Debug-iphonesimulator/SQLite.framework/SQLite
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.1.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libsqlite3.dylib
```

Based on a bit of research, it looks like `sqlite3_close_v2 ` was added to libsqlite3 in 3.7.14, and iOS 7 through 8.1 used 3.7.13.  iOS 8.2 was upgraded to 3.8.5.

**Comment by stephencelis** [comment]
This was fixed about a week and a half ago. Can you pull down the latest version of the `swift-2` branch? https://github.com/stephencelis/SQLite.swift/blob/swift-2/Source/Core/Connection.swift#L94

**Comment by stephencelis** [comment]
This should be fixed in master now. Please report any further difficulties!

**Comment by shnhrrsn** [comment]
Yep that looks good, thanks!
