### ISSUE TITLE
Query.swift issues

### ISSUE THREAD

**Issue by eraser2021999** [stephencelis/SQLite.swift#241]
1.	While type-checking getter for columnNames at /Users/bogdancoticopol/Desktop/SQLite.swift/SQLite/Query.swift:740:22
2.	While type-checking declaration 0x7f9d824bc768 at /Users/bogdancoticopol/Desktop/SQLite.swift/SQLite/Query.swift:740:51
3.	While type-checking expression at [/Users/bogdancoticopol/Desktop/SQLite.swift/SQLite/Query.swift:740:51 - line:774:7] 

        RangeText="{
        var (columnNames, idx) = ([String: Int](), 0)
        column: for each in self.query.columns ?? [Expression<Void>(literal: "*")] {
            let pair = each.expression.SQL.characters.split { $0 == "." }.map { String($0) }
            let (tableName, column) = (pair.count > 1 ? pair.first : nil, pair.last!)

            func expandGlob(namespace: Bool) -> Query -> Void {
                return { table in
                    var query = Query(table.database, table.tableName.unaliased)
                    if let columns = table.columns { query.columns = columns  }
                    var names = query.selectStatement.columnNames.map { quote(identifier: $0) }
                    if namespace { names = names.map { "\(table.tableName.SQL).\($0)" } }
                    for name in names { columnNames[name] = idx++ }
                }
            }

            if column == "*" {
                let tables = [self.query.select(*)] + self.query.joins.map { $0.table }
                if let tableName = tableName {
                    for table in tables {
                        if table.tableName.SQL == tableName {
                            expandGlob(true)(table)
                            continue column
                        }
                    }
                    assertionFailure("no such table: \(tableName)")
                }
                tables.map(expandGlob(self.query.joins.count > 0))
                continue
            }

            columnNames[each.expression.SQL] = idx++
        }
        return columnNames
        }()"

**Comment by stephencelis** [comment]
Are you on the `master` branch or `swift-2`?

**Comment by eraser2021999** [comment]
I tried with both, so yes. when I opened the project in XCode it asked for Swift Syntax Conversion. However, I manage to fix most of the issues which were very easy, but this last one.

**Comment by stephencelis** [comment]
@eraser2021999 What I mean is there's a `swift-2`-specific branch in Git that already has done these conversions, including the above one (which caused a segfault).

**Comment by eraser2021999** [comment]
hmmm....I must be doing something wrong then, I'll have a look and keep you posted. Thanks for your quick response

**Comment by eraser2021999** [comment]
I just checked it out, it seems it was my bad, the swift-2 branch compiles with no issues. Thanks a lot!!
