### ISSUE TITLE
A more functional example?

### ISSUE THREAD

**Issue by reduxdj** [stephencelis/SQLite.swift#242]
How about a more functionall easy example, soup to nuts?  

I am going through this stuff just to get to compile to get started easily with fail
![screen shot 2015-10-04 at 3 37 22 pm](https://cloud.githubusercontent.com/assets/322547/10270660/d6f3048c-6aad-11e5-8328-d46f6fdf6891.png)

**Comment by andersonacs** [comment]
This blog post helped me alot, [SQLiteDataAccessLayer](https://github.com/hoffmanjon/SQLiteDataAccessLayer), has a good example how to use this library.
