### ISSUE TITLE
How to return values for multiple columns - swift 2

### ISSUE THREAD

**Issue by skinnee** [stephencelis/SQLite.swift#245]
I am stuck on how to get the values from the follow query.  Any help would be greatly appreciated, thank you
``` swift
let query = tableName.select(columnName.count, columnName).group(columnName)
for item in connectToDB.prepare(query) {
    print(item)
}    
```
Results:
> Row(columnNames: ["count(\"catchLocationName\")": 0, "\"catchLocationName\"": 1], values: [Optional(3), Optional("Berri")])

**Comment by stephencelis** [comment]
You can index a row by the same column expression:

``` swift
let count = item[columnName.count]
let name = item[columnName]
```

**Comment by skinnee** [comment]
Thanks Stephen - simple but stumped me.
