### ISSUE TITLE
method fromDatatypeValue in non-final class NSDate must return Self to conform to protocol value

### ISSUE THREAD

**Issue by arnoldschmid** [stephencelis/SQLite.swift#246]
Hi,
I was  using your extension for nsdate and the corresponding protocol without problems under swift 1.x but now under swift 2 I receive this strange error. Furthermore it says that initializing from a metatype value must reference init explicity. The error occurs under the class fromDatatypeValue in the extension NSDate. It's the same as in your documentation.
thanks
arnold

**Comment by stephencelis** [comment]
The `swift-2` branch has been merged and conforms to `NSDate` by default. I can see this being an issue if you have an existing database with a custom date format, so I'll be exploring options of providing a "SQLite.swift+Foundation" framework in the near future.

**Comment by arnoldschmid** [comment]
Thank you a lot for your tip. Yes I have an existing database, but I save the date as normal integer values. What I have to do with the extension? I have to remove it? and where to put the struct, so that it is visible for all the classes. I'm a newbie in using swift and Thanks in advance 
Arnold

**Comment by arnoldschmid** [comment]
Unfortunately I am not able to solve the problem. As attachment I post a screenshot of my changes. In my code I am trying to access the new Date struct like:
 let dateMaker = NSDateFormatter()
 dateMaker.dateFormat = "yyyy-MM-dd"
...
  let curDate = (Date.fromDatatypeValue(w.workDate!))
 

![bildschirmfoto 2015-10-13 um 11 11 05](https://cloud.githubusercontent.com/assets/12458700/10450571/71b69cec-719b-11e5-90f9-69cf5152d86c.png)

**Comment by skinnee** [comment]
Under swift 2 , you shouldn't need a NSDate extension.

I am no expert and just been learning last 6 months.

I use the following expression for database  Create, Delete, Update Delete (CRUD) queries in my DB helper class.

 static let someDateTime = Expression<NSDate?>("someDateTime")

I write to the database using this formatter as NSDate in my viewController classes.

      let formatter = NSDateFormatter()
      formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSS"
      formatter.locale = NSLocale(localeIdentifier: "en_US_POSIX")
      formatter.timeZone = NSTimeZone(forSecondsFromGMT: 0)

     let dateValue = formatter.dateFromString(someTextDateValue)

dateValue is written directly as NSDate and not changed to another type.

When i read it back from the database i convert it to my custom formatter.

Not sure if its any help, happy to provide examples if I'm on the right track.

**Comment by arnoldschmid** [comment]
Thanks to all for your help. Now I solved it, converting the Int-Date in NSDate manually.
