### ISSUE TITLE
RTree.swift 

### ISSUE THREAD

**Issue by harveyxiacn** [stephencelis/SQLite.swift#247]
Hi there,

I tried to fix sqlite.swift for my app because I updated to xcode 7 by misclick...

I could not fix this one. Does anyone know that? Thanks.

SQLite/RTree.swift:27:46: Function signature '(Expression<U>) -> Expression<U>' is not compatible with expected type '(Expression<U>) throws -> Expressible'

**Comment by iNoles** [comment]
is this is under swift-2 branch?

**Comment by harveyxiacn** [comment]
Oops, I just modified on the old version :p I'll try swift 2 branch. Thanks for notifying.

**Comment by stephencelis** [comment]
No worries :) The swift-2 branch needs to be merged to avoid confusion. This weekend is my goal!

**Comment by harveyxiacn** [comment]
Good luck!

2015-10-06 21:13 GMT-03:00, Stephen Celis <notifications@github.com>:

**Comment by stephencelis** [comment]
Did the swift-2 branch work for you in the meantime?

**Comment by developertas** [comment]
So how can I use or get swift-2 branch via cocoa pods ? Is it possible ? I just updated to Xcode 7 and then boom. I've RTree error too. Same one.

**Comment by stephencelis** [comment]
The branch has been merged. Please chime in here (or open a new ticket) if you're having problems with RTree in master!
