### ISSUE TITLE
How to read a Blob

### ISSUE THREAD

**Issue by gobozgz** [stephencelis/SQLite.swift#248]
Hi,
Im trying to use SQLite.swift (v2 branch) to read a Blob containing a PDF File and I want to load into a NSDATA for loading into a webview. Anyone does have a clue? Im really lost. My code right now (https://gist.github.com/gobozgz/9d1b02364f878bc1a026):

// I want to load a pdf from a swift database, stored in a blob into a UIWebView 
// But I event didn't know how to load the data from database.
// My source for now:

import UIKit
import SQLite

class AreaInfoViewController: UIViewController {
    @IBOutlet weak var webView: UIWebView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Here I Will load the webView PDFFile into the webView
        // webView.loadRequest(getAreaPdf())
        }
        
    func getAreaPdf () -> NSDATA {
        var myPdf:NSDATA // I think this is wrong
        
        let dirPaths = NSSearchPathForDirectoriesInDomains(.DocumentDirectory, .UserDomainMask, true)
        let docsDir = dirPaths[0]
        let databasePath = docsDir.stringByAppendingString("/db.sqlite")
        let db = try! Connection(databasePath, readonly: true)
        
        let areas = Table("areas")
        let id = Expression<Int64>("id")
        let name = Expression<String>("name")
        let pdffile = Expression<SQLite.Blob>("pdffile")
        let query = areas.select(id,name,pdffile)
            .filter(id == 1)
            .limit(1)
        let result = db.prepare(query)
        for row in result {
            myPdf = row[pdffile] // Obviusly this is wrong
        }
        return myPdf // Obviusly this is wrong too
    }
}

Please, any help will be great. Thanks a lot.

**Comment by skinnee** [comment]
Look up nskeyedarchiver to convert to NSData object https://developer.apple.com/library/prerelease/ios/documentation/Cocoa/Reference/Foundation/Classes/NSKeyedArchiver_Class/index.html

This is how I'm storing NSdata objects

**Comment by gobozgz** [comment]
Please, could you give me a little example. I'm really lost at this point.

Thanks!

**Comment by skinnee** [comment]
In a few hours I can.

I store and retrieve as NSData not blob with location arrays. Assuming file object can be done 

My SQLite expressions are NSData not blob



1. Create the file object
2. Convert to NSData

Let abc = nskeyedarchivrer with root object (file)

Insert to database 

3.Read from database 
4. Let xyz = nskeyedunarcher(query result)
5. Load to web view 

https://www.hackingwithswift.com/example-code/system/how-to-save-and-load-objects-with-nskeyedarchiver-and-nskeyedunarchiver

**Comment by gobozgz** [comment]
I'm gonna have a try, but if you send me a example when you can You will
save my ass ;o)

Thanks a lot.

2015-10-08 6:18 GMT+02:00 skinnee <notifications@github.com>:

**Comment by skinnee** [comment]
How is the file written to the database in your code ?

**Comment by gobozgz** [comment]
The sqlite file comes from an external backend source. The whole file its
downloaded to the Documents App storage, and it's used in the app as
readonly.

2015-10-08 6:29 GMT+02:00 skinnee <notifications@github.com>:

**Comment by skinnee** [comment]
Ok will be home in 15mins

**Comment by skinnee** [comment]
TripDataHelper is  a class the supports various queries on trips.

 static func findWhere(columnName: String, value: String) -> [T]? {
        
        let columnToReturn = Expression<String?>(columnName)
        
        let query = table.filter(columnToReturn == value)
 var retArray = [T]()
        
        for item in connectToDB.prepare(query)  {

          // append item[columnToReturn] to array of type [T]() where T is as trip object
      
            }
          
} 

        if let someTrips = TripDataHelper.findWhere("TripType", value: "someTrip") {
            
      // cycle through array
        for trips in someTrips { 

        // retrieve each object property
        // an array of CLLocation - note use casting
        locationReturns = NSKeyedUnarchiver.unarchiveObjectWithData(trips.someTripCoordinates!) as! [CLLocation]
            
           // an array of Strings - note use casting   
        let tripDescription = NSKeyedUnarchiver.unarchiveObjectWithData(trips.someTripDescription!) as! [String]
// etc etc
}

}

**Comment by skinnee** [comment]
Also its NSData not NSDATA

example when declaring expressions
static let tripCoordinates = Expression<NSData>("tripCoordinates")

**Comment by skinnee** [comment]
i have tied up your code but I'm no expert,  var myPDF assumes you never get a nil value for a PDF so you might want to change it to optional

 func getAreaPdf () -> NSData {
        
// assumes no nil values change to NSData? is it might be nil and test for nil 
// using if let 

        var myPdf:NSData!   
        
        let dirPaths = NSSearchPathForDirectoriesInDomains(.DocumentDirectory, .UserDomainMask, true)
        let docsDir = dirPaths[0]
        let databasePath = docsDir.stringByAppendingString("/db.sqlite")
        let db = try! Connection(databasePath, readonly: true)
        
        let areas = Table("areas")
        let id = Expression<Int64>("id")
        let name = Expression<String>("name")
        let pdffile = Expression<NSData>("pdffile")
        let query = areas.select(id,name,pdffile)
            .filter(id == 1)
            .limit(1)
        let result = db.prepare(query)
        for row in result {
            
            myPdf = row[pdffile]
        }
        
        
        return myPdf
    }

**Comment by gobozgz** [comment]
Thanks, but it seems like my problem is another. Im reading this and hoping
getting more info. Thanks a lot for everything.

David

2015-10-08 9:02 GMT+02:00 skinnee <notifications@github.com>:

**Comment by stephencelis** [comment]
@gobozgz If you switch to using `Expression<NSData>` instead of `Expression<Blob>`, that should all work. `Blob` is available as a lower-level wrapper for when you're not using APIs that expect NSData.

**Comment by gobozgz** [comment]
Thanks a lot, now everything is solved.

**Comment by Tybion** [comment]
Thank you, also.  This saved me lots of time.  Some working Swift 4 code (where tile_data is a blob) ..

```
        let tiles = Table("tiles")
        let tile_data = Expression<Data>("tile_data")
        let tile_column = Expression<Int>("tile_column")
        let tile_row = Expression<Int>("tile_row")
        let zoom_level = Expression<Int>("zoom_level")
        do {
            if let row = try database!.pluck(tiles.select(tile_data)
                .filter(tile_column==x && tile_row==y && zoom_level==z)) {
                return row[tile_data]
            }
        } catch {
            return nil
        }
```
