### ISSUE TITLE
Is the swift2 branch "production ready?"

### ISSUE THREAD

**Issue by fredwaltman** [stephencelis/SQLite.swift#250]
That is, are you all using it in apps released to customers? Or is it considered still in development? (I realize *everything* is still in development in some sense or the other)

**Comment by stephencelis** [comment]
swift-2 for all extents and purposes is production ready. It just doesn't have complete feature parity with master. I plan on merging it to master this weekend, though.

**Comment by stephencelis** [comment]
Merged!
