### ISSUE TITLE
Swift-2 UIImage Binary Data Extension Errors

### ISSUE THREAD

**Issue by austin94** [stephencelis/SQLite.swift#256]
I am attempting to implement the extensions necessary to allow UIImage blob data to be returned from a column.

I was able to use the documentation to complete the process with swift-1, but am having trouble with the upgrade to swift-2.

When adding the extension below:
```
extension NSData: Value {
    class var declaredDatatype: String {
        return Blob.declaredDatatype
    }
    class func fromDatatypeValue(blobValue: Blob) -> Self {
        return self(bytes: blobValue.bytes, length: blobValue.length)
    }
    var datatypeValue: Blob {
        return Blob(bytes: bytes, length: length)
    }
}
```
I get the error:
```
Redundant conformance of 'NSData' to protocol 'Value'
```
So I assume that extension has already been applied elsewhere in the application.

When applying the UIImage extension:
```
extension UIImage: Value {
    class var declaredDatatype: String {
        return NSData.declaredDatatype
    }
    class func fromDatatypeValue(blobValue: Blob) -> Self {
        return self(data: NSData.fromDatatypeValue(blobValue))
    }
    var datatypeValue: Blob {
        return UIImagePNGRepresentation(self).datatypeValue
    }
}
```
I get the following error:
```
Type 'UIIMage does not conform to protocol 'Value'
and
Ambiguous use of 'fromDataTypeValue'
```

I have attempted to change the methods to public and other suggested tips, but am unable to compile.

Any suggestions or help would be appreciated.  It would be nice if that section of the documentation is updated (I'll do a pull-request if I can figure it out).

**Comment by nicklinn** [comment]
Having the same issue.  Anyone have a solution?

**Comment by stephencelis** [comment]
Docs need to be updated. Can you try the following?

``` swift
extension UIImage: Value {
    public class var declaredDatatype: String {
        return Blob.declaredDatatype
    }
    public class func fromDatatypeValue(blobValue: Blob) -> UIImage {
        return UIImage(data: NSData.fromDatatypeValue(blobValue))!
    }
    public var datatypeValue: Blob {
        return UIImagePNGRepresentation(self)!.datatypeValue
    }

}
```

**Comment by nicklinn** [comment]
Worked for me.  Thanks Stephen!

**Comment by austin94** [comment]
Works for me also!  And it looks like the documentation has been updated also.  Thanks for the help!
