### ISSUE TITLE
Is INTEGER PRIMARY KEY AUTOINCREMENT supported?

### ISSUE THREAD

**Issue by liweiz** [stephencelis/SQLite.swift#26]
Hello,

I'm trying to implement INTEGER PRIMARY KEY AUTOINCREMENT. But I do not find where to add AUTOINCREMENT keyword. Perhaps it is already supported but I failed to locate it:)

The reason to use the keyword:
http://www.sqlite.org/autoinc.html

> The behavior implemented by the AUTOINCREMENT keyword is subtly different from the default behavior. With AUTOINCREMENT, rows with automatically selected ROWIDs are guaranteed to have ROWIDs that have never been used before by the same table in the same database. 

Thanks in advance,

Liwei

**Comment by FarshidRoohi** [comment]
it works Thanks :)
` try db.run(users.create { t in
                t.column(id, primaryKey: .autoincrement)
                t.column(userId)
                t.column(tooken)

            })`
