### ISSUE TITLE
dropping virtual table causes sql syntax error

### ISSUE THREAD

**Issue by warn4n** [stephencelis/SQLite.swift#261]
This looks like a regression that may have been introduced with the swift 2 version.  Trying to drop a virtual table through the swift DSL now generates "DROP VIRTUAL TABLE..." which causes a syntax error from sqlite.  Sqlite seems to accept "DROP TABLE..." for a virtual table. In our case this manifested specifically with a FTS virtual table.

**Comment by stephencelis** [comment]
Definitely sounds like a regression! Thanks for the report. I'll look into it shortly.
