### ISSUE TITLE
ld: framework not found SQLite

### ISSUE THREAD

**Issue by confile** [stephencelis/SQLite.swift#262]
When I remove this pod and compile my project I get the following error: 

```
ld: framework not found SQLite
```

![majestella_xcworkspace](https://cloud.githubusercontent.com/assets/64265/10718099/99743716-7b6a-11e5-82d0-d8963201e9ac.jpg)

**Comment by stephencelis** [comment]
Have you tried cleaning your build folder and making sure you removed all references to the library?

**Comment by confile** [comment]
How do I do that?

**Comment by stephencelis** [comment]
This query got me what you're looking for: https://encrypted.google.com/search?hl=en&q=xcode%20clean%20build%20folder
