### ISSUE TITLE
I update my Xcode to 7.1 today, and the code to connection database turn to wrong.

### ISSUE THREAD

**Issue by Hastingou** [stephencelis/SQLite.swift#263]
here are some pics for this problem.
<img width="494" alt="31e73c24-0d76-4131-864e-17e8d4b77668" src="https://cloud.githubusercontent.com/assets/12121231/10723879/86b740a6-7bfa-11e5-89ea-f0ae90c9104b.png">
<img width="780" alt="49da8ac3-74fb-4fb9-bf63-1aefb87eb724" src="https://cloud.githubusercontent.com/assets/12121231/10723917/d85fcaea-7bfa-11e5-902e-872acee37673.png">
<img width="788" alt="ef59a04c-4ae3-4400-8b17-361a2dbcc46d" src="https://cloud.githubusercontent.com/assets/12121231/10723918/d8f1ddf4-7bfa-11e5-8005-3f7bf3ab5218.png">

**Comment by stephencelis** [comment]
Hi there. Sorry you're having issues! Can you post your integration code that triggers the problem? I haven't been able to reproduce.

**Comment by Hastingou** [comment]
I copy the whole project to a new file and this bug has gone.But the original project still have this bug. So maybe it is a Xcode BUG. Thanks for your reply

**Comment by stephencelis** [comment]
Sorry to hear about the Xcode bug. Going to close this out now that you were able to fix the problem. Glad you got unblocked!
