### ISSUE TITLE
Non-functional custom SQL functions in Swift 2 version (update+check docs)

### ISSUE THREAD

**Issue by voltaek** [stephencelis/SQLite.swift#266]
When trying to declare a custom SQL function as shown in the documentation, I'm getting an error of `"Cannot invoke 'createFunction' with an argument list of type '(String, deterministic: Bool, (CFString, CFString) -> Bool)'"`. This error happens even when trying to use the exact example given in the documentation. These declarations were operating fine before I updated this library to the Swift 2 version in my project. I've done a full removal of the old version, cleaned the project, properly added the new version per the documentation, and updated my code to account for the changes (Table and Connection, etc).

**Comment by hiltonc** [comment]
+1

**Comment by hiltonc** [comment]
This works:

```
let typeConformsTo: (Expression<String>, Expression<String>) -> Expression<Bool> = (
    try db.createFunction("typeConformsTo", deterministic: true) { UTI, conformsToUTI in
        return UTTypeConformsTo(UTI, conformsToUTI)
    }
)
```
