### ISSUE TITLE
Can not include SQLite.swift in podspec file

### ISSUE THREAD

**Issue by Ryannnnnnn** [stephencelis/SQLite.swift#268]
I wanna include SQLite.swift as a dependency of a sub-project, but in my .podspec file, both

`s.dependency "SQLite.swift", :git => 'https://github.com/stephencelis/SQLite.swift.git'`
and
`s.dependency "SQLite.swift"`

not work, which causes an error like **```[!] Unable to find a specification for `SQLite.swift` depended upon by `MySubProject````**.

I've searched around and found a issue here, **[Cannot reference git projects on a podspec file](https://github.com/CocoaPods/CocoaPods/issues/885)**. It seems that only dependencies from official source are accepted.

Is there workaround here or would you add this to the official Cocoapods spec?

Related issue: #257

**Comment by spronin** [comment]
+1

**Comment by argie9999** [comment]
+1

**Comment by irvingruan** [comment]
+1

**Comment by mikemee** [comment]
#257 appears to cover this, so I'm closing this out as part of a general pass to get the issue count down to a manageable level. Please re-open with a comment if you feel this is not appropriate. Thanks!
