### ISSUE TITLE
Need TV OS Support

### ISSUE THREAD

**Issue by srkrambo** [stephencelis/SQLite.swift#272]
I get following  errors when trying to build for TV os 

 "Target 'SQLiteCipher.swift' of project 'Pods' was rejected as an implicit dependency for 'SQLiteCipher.framework' because it doesn't contain platform 'appletvsimulator' in its SUPPORTED_PLATFORMS 'iphonesimulator, iphoneos'"

There is a similar error for "Target 'SQLCipher' of project 'Pods' was rejected as an implicit dependency for 'SQLCipher.framework' because it doesn't contain platform 'appletvsimulator' in its SUPPORTED_PLATFORMS 'iphonesimulator, iphoneos'".

Here in Cocoapods, http://blog.cocoapods.org/CocoaPods-0.39/
Its mentioned we need to explicitly add in podspec to support TV OS.

**Comment by stephencelis** [comment]
I have a fix for this in the works, but it looks like the upstream version of SQLCipher hasn't had its project file updated for tvOS or watchOS support.

**Comment by mikemee** [comment]
Update: [SQLCipher](https://github.com/sqlcipher/sqlcipher) has merged support into their `prerelease` branch on Nov 17 (here 71691b6a1ccd2a7ae2d0fa8f03ad822ae6aaac9e), but they haven't merged to `master` since July :(

**Comment by srkrambo** [comment]
Yes @mikemee, I am keeping an eye on the release of SQLCipher, will reach out to again once they release next version.

**Comment by stephencelis** [comment]
Maybe we can point the submodule to `prerelease` in the meantime?

**Comment by mikemee** [comment]
@srkrambo Do you need the SQLCipher support for your tvOS project (i.e. encrypted data in your sqlite database)?

If not, please try the branch in PR https://github.com/stephencelis/SQLite.swift/pull/314 that I just submitted and please let me know if that works for you. It should be trivial to add a tvos target. 

It would be nice to confirm it works and I'll add the target into the build if the PR is accepted and once the dust settles.

**Comment by rajkumariosdev** [comment]
@mikemee, we do need SQLCipher support since it contains data if exposed can be used by competitor apps.

**Comment by srkrambo** [comment]
@mikemee, we do need SQLCipher support since it contains data if exposed can be used by competitor apps.

**Comment by mikemee** [comment]
Ah, fair enough.  Not trusting the sandbox eh :)  (Or doesn't it exist on tv?)

Once that PR is closed and the corresponding #311, we can add it back via a separate repo, and hopefully add the ability to "choose your own version" of SQLCipher, so you can trivially use `prerelease` if you want.

**Comment by mikemee** [comment]
Added TV support to the [Feature Requests](https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Planning.md).

SQLCipher.swift can now be found here: https://github.com/stephencelis/SQLiteCipher.swift (working but very newly packaged)

**Comment by srkrambo** [comment]
Thanks @mikemee. Will check it out.
