### ISSUE TITLE
Want to integrate in Swift 1.2. 

### ISSUE THREAD

**Issue by sumitjain7** [stephencelis/SQLite.swift#273]
I need this library for Swift 1.2 Xcode 6.4.
Please provide me the branch url or commit number so that I can download.

Thanks

**Comment by stephencelis** [comment]
Xcode 7 and Swift 2 target to and compile for the same platforms, so I can't think of a reason why you'd need to continue to use Xcode 6.4 and Swift 1.2. Why haven't you downloaded the latest version of Xcode?

You _could_ check out this commit: https://github.com/stephencelis/SQLite.swift/commit/d87e05da167bdded01ae74001c5adda865346867

I wouldn't recommend or support it, though.

**Comment by sumitjain7** [comment]
Actualy my project is older was initially developed with swift 1.2 so we want code for swift 1.2. The next app we are going to develop in swift 2.0.

**Comment by stephencelis** [comment]
If you're actively developing this project, I'd recommend taking the hopefully minimal time it takes to upgrade to Swift 2. Xcode has an integrated upgrader that should make it pretty painless.
