### ISSUE TITLE
Filtering Rows with array of parameters

### ISSUE THREAD

**Issue by andersonacs** [stephencelis/SQLite.swift#274]
Hi,

I'm doing a generic crud, and I need to do a dynamic query, there is some way to call `table.filter()` method with array of parameters? 

thanks;

**Comment by stephencelis** [comment]
Could you use `&&` to reduce?

``` swift
table.filter(filters.reduce { $0 && $1 })
```

**Comment by andersonacs** [comment]
Thanks for replying,

I'll check that out! 

Anyways, I'm trying to implement Android SQLite as below. What would below code be?

```Cursor cursor = db.query(TABLE_NAME, new String[] { KEY_ID,
            KEY_NAME, KEY_PH_NO }, KEY_ID + "=?",
            new String[] { String.valueOf(id) }, null, null, null, null);```

**Comment by stephencelis** [comment]
Have you tried asking on StackOverflow?

**Comment by andersonacs** [comment]
Yes, the most close to my question : 

http://stackoverflow.com/questions/31595212/sqlite-swift-create-dynamic-complex-queries

but I was thinking that you could have someway more clear and elegant to do this, as using array of parameters.

**Comment by stephencelis** [comment]
I think you could add an extension to support that, but it doesn't belong in core. I think the `reduce` solution above is pretty elegant, though. Is this safe to close out?

**Comment by andersonacs** [comment]
Yes, I also think it's really a good solution, if I really need I'll add an extension!

Thank you!

**Comment by stephencelis** [comment]
Great!
