### ISSUE TITLE
Aggregate functions and NSDate

### ISSUE THREAD

**Issue by greuff** [stephencelis/SQLite.swift#277]
Hello,
is there a way to make "max" work with an NSDate column?

This compiles without any problem:
```swift
let max = db.scalar(Table("message").filter(Expression<Int64>("chat_id") == chat._id!)
			.select(Expression<NSDate>("timestamp").count))
```

But this results in a compiler error:

```swift
let max = db.scalar(Table("message").filter(Expression<Int64>("chat_id") == chat._id!)
			.select(Expression<NSDate>("timestamp").max))
```

The error is: **Ambiguous reference to member 'max'**

The table definition is:

```swift
try db.run(Table("message").create {
			t in
			...
			t.column(Expression<NSDate>("timestamp"))
			...
			})
```

Thank you

**Comment by stephencelis** [comment]
Should be fixed now! `NSDate` doesn't conform to `Comparable`, so the protocol extension now looks to the underlying type.

**Comment by greuff** [comment]
Thank you very much!
