### ISSUE TITLE
References on foreign key just possible with `Int64`

### ISSUE THREAD

**Issue by schickling** [stephencelis/SQLite.swift#278]
It seems that using the `references` syntax for building a schema is just possible when using keys of type `Int64` (see [Source Code](https://github.com/stephencelis/SQLite.swift/blob/master/Source/Typed/Schema.swift#L270-L283)). Is that a limitation of SQLite itself?

What would be the best way to use this functionality when my keys are of type `String`?

**Comment by stephencelis** [comment]
You can use the dedicated `foreignKey` functions: https://github.com/stephencelis/SQLite.swift/blob/master/Source/Typed/Schema.swift#L378-L409

**Comment by stephencelis** [comment]
Closing this out as there are alternative ways of handling this. I'm open to discussion, though!

**Comment by schickling** [comment]
Thanks. The `foreignKey` function worked perfectly. :+1:
