### ISSUE TITLE
Playground issue in Xcode 7.1 Failed to import the framework

### ISSUE THREAD

**Issue by bryan1anderson** [stephencelis/SQLite.swift#279]
Playground execution failed: <module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/Users/Bryan Anderson/Library/Developer/Xcode/DerivedData/Chats-dwkoxdfwcycztagyqitrtxvrhiko/Build/Products/Debug-iphonesimulator/SQLite.framework/Headers/SQLite.h"
        ^
/Users/Bryan Anderson/Library/Developer/Xcode/DerivedData/Chats-dwkoxdfwcycztagyqitrtxvrhiko/Build/Products/Debug-iphonesimulator/SQLite.framework/Headers/SQLite.h:9:9: note: in file included from /Users/Bryan Anderson/Library/Developer/Xcode/DerivedData/Chats-dwkoxdfwcycztagyqitrtxvrhiko/Build/Products/Debug-iphonesimulator/SQLite.framework/Headers/SQLite.h:9:
#import <SQLite/SQLite-Bridging.h>
        ^
/Users/Bryan Anderson/Library/Developer/Xcode/DerivedData/Chats-dwkoxdfwcycztagyqitrtxvrhiko/Build/Products/Debug-iphonesimulator/SQLite.framework/Headers/SQLite-Bridging.h:28:9: error: include of non-modular header inside framework module 'SQLite.SQLite_Bridging'
#import "sqlite3.h"
        ^
could not build Objective-C module 'SQLite'

Is the error I'm getting every time I try to run the playground in my CocoaPods workspace. Xcode 7.1

**Comment by stephencelis** [comment]
Have you built the framework? Framework playgrounds are a bit finicky, unfortunately, and sometimes require building, replaying, quitting, reopening, etc. I wish I could guarantee that a playground play-through would build the framework beforehand, but that's up to Apple :disappointed:

**Comment by bryan1anderson** [comment]
really is crazy how sketchy playgrounds to be. It worked suddenly this morning, but stopped after i restarted my mac
