### ISSUE TITLE
Mind guide us with CRUD example project using TableView?

### ISSUE THREAD

**Issue by htarwara6245** [stephencelis/SQLite.swift#280]
It will be pleasure if you really support or guide us CRUD example using this library...Thanks..

**Comment by stephencelis** [comment]
Could you be more specific? The README gives an example of creating, fetching, updating, and deleting a row from a table.

**Comment by htarwara6245** [comment]
I am the beginner to swift as well as to using coreData.I just want an example project which I can learn with this library basic thing only(CRUD) that's all.Whatever i gonna try it first...Thanks for faster support

**Comment by stephencelis** [comment]
Check out https://github.com/stephencelis/SQLite.swift/issues/130 for an example project (https://github.com/hoffmanjon/SQLiteDataAccessLayer).
