### ISSUE TITLE
try db.run() inside an UIAlertController

### ISSUE THREAD

**Issue by rikenmon** [stephencelis/SQLite.swift#281]
Hello,

After update to swift2 the following code I am struggling with: 

``` swift
alert.addAction(UIAlertAction(title: "OK", style: .Default) { alert in
    // get user input
    let TF = (inputTextField! as UITextField).text
    // make dbase query for note name
    let rcd = users.filter(Expression<Int>("_id") == self.RecordNumber)
    // put TF in record note
    if !TF!.isEmpty { // OK is clicked
        try db.run(rcd.update(Expression<String>("RM") <- TF!)) {}catch{}
        // rcd.update(Expression<String>("RM") <- TF!) // previous working code
    }         
})
```

This code update the dbase if OK is clicked, the rcd.update worked well however the new structure (try db.run) It gives an error in the handler of the alert and I have no idea how to solve it. Can anyone help me?

Much regards,
Erik

**Comment by stephencelis** [comment]
It looks like you aren't wrapping the `try` in a `do` block (required by Swift). Check out the error handling documentation here:

https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/Swift_Programming_Language/ErrorHandling.html

**Comment by rikenmon** [comment]
Thanks very much, that was exactly the problem!
