### ISSUE TITLE
case insensitive like

### ISSUE THREAD

**Issue by vicmosin** [stephencelis/SQLite.swift#286]
It seems that the following construction doesn't work:
```
database.prepare(dictionary.filter(nameColumn.lowercaseString.like("\(query)%"))
```
Is there any alternative for like which is case insensitive?

**Comment by stephencelis** [comment]
That should work just fine. Can you give more context / an error / etc.?

**Comment by vicmosin** [comment]
There is no any error.. It just returns empty result. Do you have the way to see the sql query?

**Comment by stephencelis** [comment]
Do you have enough code to paste into the playground to reproduce?

**Comment by vicmosin** [comment]
Is it possible that it only happens with cyrillic data?

**Comment by vicmosin** [comment]
Just checked the query in databseviewer..
The following query doesn't work as well:
```
SELECT * FROM "Dictionary" WHERE (lower("Name") LIKE 'ва%') ORDER BY "Name" ASC
```

**Comment by stephencelis** [comment]
I'm pretty sure the built-in SQLite `lower` function is only for ASCII (and does a mere byte shift). You'll need to define a custom function or convert the content to lowercase before inserting it into the database and query.

**Comment by mikemee** [comment]
Hi, I'm doing a pass to close some old issues and it seems this may have been resolved. I.e. `lower` only works with ASCII, per https://www.sqlite.org/lang_corefunc.html

> The lower(X) function returns a copy of string X with all ASCII characters converted to lower case. The default built-in lower() function works for ASCII characters only. To do case conversions on non-ASCII characters, load the ICU extension. 

Please re-open if you have more information or feel this should still be active. Thanks!
