### ISSUE TITLE
file is encrypted or is not a database

### ISSUE THREAD

**Issue by Ollstar** [stephencelis/SQLite.swift#287]
I'm using SQLite in my project and getting this error:

```
EXC_BAD_INSTRUCTION
```

And the console prints:

```
fatal error: 'try!' expression unexpectedly raised an error: file is encrypted or is not a database: file /Library/Caches/com.apple.xbs/Sources/swiftlang_PONDEROSA/swiftlang_PONDEROSA-700.1.101.6/src/swift/stdlib/public/core/ErrorType.swift, line 50
```

In Statement.swift, on this line of code:
```
try! connection.check(sqlite3_prepare_v2(connection.handle, SQL, -1, &handle, nil))
```
![screen shot 2015-11-26 at 11 40 53 am](https://cloud.githubusercontent.com/assets/10384072/11429871/9bf66320-9432-11e5-9339-c8379ec76587.png)

I've tried:
- cleaning project
- removing SQLite and running `git submodule update --init`
- switch the branch of SQLite to swift-2

Also the project runs fine on my colleagues computer and he didn't have to do any of this.

**Comment by stephencelis** [comment]
Are you running SQLCipher? Are you using an encrypted database and running a statement before running `Connection.key()`?

**Comment by Ollstar** [comment]
This was actually an issue with the filePath used being damaged or invalid.
```
db = try Connection(filePath, readonly: true)
```
Works after switching filePath.

**Comment by stephencelis** [comment]
Glad you were able to resolve! Is this safe to close out now?

**Comment by Ollstar** [comment]
Yes, thanks for your help.
