### ISSUE TITLE
NODIACRITIC COLLATE doesnt work with LIKE query

### ISSUE THREAD

**Issue by Tom29** [stephencelis/SQLite.swift#292]
I've tried many times and i realize that NODIACRITIC collation only work with equall query, not like query.

`SELECT * FROM users WHERE name COLLATE NODIACRITIC LIKE 'jane%'`
~> doesnt work. only returns jane

`SELECT * FROM users WHERE name COLLATE NODIACRITIC = 'jane'`
~> it works and return jane,janè

How to get it work with like query?

**Comment by Tom29** [comment]
It has been 2 weeks and there is not answer from the author.
I'm still stucking here.

**Comment by stephencelis** [comment]
@Tom29 This is more of a general SQLite question (rather than SQLite.swift wrapper-specific). I'm not intimately familiar with how `LIKE` queries and collation works, but I do see several workarounds:

1. Store the diacritic-free version of the user's name in a separate column (which should be faster anyway)
2. Use FTS for indexing and use unicode61 or a custom, Foundation-backed indexer

**Comment by Tom29** [comment]
Tks for your reply. I submitted my question here because i think it's so strange, because it works with equal operator but doesn't work with LIKE queries. I thought it because of this SQLite wrapper error.

So, equal operator with NODIACRITIC collage, does it impact to the query performance?

**Comment by mikemee** [comment]
Closing this as part of a general cleanup, with the following notes:

I did some research, starting with entries like: https://stackoverflow.com/questions/3480999/using-collate-in-android-sqlite-locales-is-ignored-in-like-statement. The SQLite documentation on COLLATE is here: https://www.sqlite.org/datatype3.html#collation - which suggests it only natively supports BINARY, NOCASE and RTRIM.  I tried searching for Apple docs on SQLite to see if they document new collation sequences they may have added but came up blank.

I also tried some things in terminal which suggest that `COLLATE NODIACRITIC` is not working with sqlite3 irrespective of SQLite.swift.
```
$ sqlite3
SQLite version 3.8.10.2 2015-05-20 18:17:19
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> create table "users" ( name TEXT );
sqlite> select * from users;
sqlite> insert into users (name) values ("jane");
sqlite> insert into users (name) values ("janè");
sqlite> select * from users;
jane
janè
sqlite> select * from users where name like 'jan%';
jane
janè
sqlite> select * from users where name = 'jane';
jane
sqlite> select * from users where name COLLATE NODIACRITIC = 'jane';
Error: no such collation sequence: NODIACRITIC
```

**Comment by stephencelis** [comment]
@mikemee It's a custom collation (which SQLite.swift supports creating), but I don't think custom collations support `LIKE` queries. I think this requires a custom function to work correctly, though it likely won't be fast. The best solution is probably to use FTS and an indexer (like `unicode61`) that normalizes diacritics. I'd suggest @Tom29 do research into this or seek general SQLite advice on StackOverflow, as this really goes beyond SQLite.swift.
