### ISSUE TITLE
   connect error

### ISSUE THREAD

**Issue by yanglichuan** [stephencelis/SQLite.swift#293]
let db =  try Connection("db.sqlite3",readonly: false);
  
          connect error

         error info  below
          Error Domain=SQLite.Result Code=0 "(null)"

**Comment by mikemee** [comment]
Hi @yanglichuan , did you work this out?  Do you have more information?  I'm closing this now as we don't have enough information to help you more, but if you can please try with the latest release and provide more information we'd love to help out.

In case this helps, here is an example that contains what you're trying to do and it works in a Playground without any problems:

```swift
import SQLite

let db = try! Connection("db.sqlite3", readonly: false)
db.trace { print($0) }

let emails = Table("emails")
let to = Expression<String>("to")
let subject = Expression<String?>("subject")

try! db.run(emails.create(ifNotExists: true) {t in t.column(to); t.column(subject)} )
try! db.run(emails.insert(to <- "stephen@example.com", subject <- "Hello, world!" ))

for user in try db.prepare(emails) {
    print("id: \(user[to])")
}

try db.run(emails.delete())```
