### ISSUE TITLE
Can't build release

### ISSUE THREAD

**Issue by brandenr** [stephencelis/SQLite.swift#294]
I can build debug and run fine, but if I archive release, I get:
binary operator '!=' cannot be applied to operands of type 'Expression<Int>' and 'Int'

try db?.run(DownloadTable.table.filter(DownloadTable.statusType != DownloadStatus.Downloaded.rawValue).update(DownloadTable.statusType <- DownloadStatus.Paused.rawValue))

DownloadTable.statusType is an Expression<Int> and DownloadStatus.Paused.rawValue is an Int

If I use == instead of != it archives fine. I can also do this: [DownloadStatus.Downloading.rawValue, DownloadStatus.Error.rawValue].contains(DownloadTable.statusType)

But I'd much prefer to use the !=

**Comment by brandenr** [comment]
Any word on if != will get supported in release?

**Comment by stephencelis** [comment]
This seems like a bug that might be in Swift proper. Any chance you can provide an example project exhibiting the issue?

**Comment by brandenr** [comment]
Well, I have been trying to create a sample project, but it works fine. I'm trying to continue to include and match more of my real project until it fails to narrow it down, but no luck so far.

**Comment by brandenr** [comment]
Here's the project with a method that should fail to build in release (based on it not working in my actual project), though this project builds fine. 
[SQLiteReleaseFail.zip](https://github.com/stephencelis/SQLite.swift/files/67890/SQLiteReleaseFail.zip)

**Comment by mikemee** [comment]
Love to know if you can still repo this with your own project?  Or any other insights?

**Comment by brandenr** [comment]
Yes, it still happens in my main project, but I haven't been able to narrow it down yet. I can't get it to happen in that other project.

**Comment by jberkel** [comment]
@brandenr is this still the case with Swift 3?

**Comment by brandenr** [comment]
Seems to work fine in Swift 3, thanks.
