### ISSUE TITLE
How to do migration with SQLite.swift? Would you please provide some demo projects or documents?

### ISSUE THREAD

**Issue by Johnny-Li** [stephencelis/SQLite.swift#297]
How to do migration with SQLite.swift? 
Would you please provide some demo projects or documents?
Thanks~

**Comment by mikemee** [comment]
@Johnny-Li Take a look at this: https://github.com/garriguv/SQLiteMigrationManager.swift.  It looks pretty comprehensive!

We'll add a link to it...
