### ISSUE TITLE
Impossible to join VirtualTable (FTS4) with usual one

### ISSUE THREAD

**Issue by t4ec** [stephencelis/SQLite.swift#299]
Hi,

I have run into an issue: joining FTS4 table with regular one seems impossible. May be I am missing something, but documentation does not clarify this point.

The issue:

I have two tables:
nodeTable = Table("node") - usual table
nodeIndex = VirtualTable("nodeindex")  - FTS4 table

both tables were created using peewee in python (prepopulated DB is shipping with app)

The queries look like:

```
Array(self.db!.prepare(nodeTable.join(nodeIndex, on: nodeTable[id] == nodeIndex.match(searchText + "*")[docid]) ))
```

OR

```
Array(self.db!.prepare(nodeTable.join(nodeIndex, on: nodeTable[id] == nodeIndex[docid]) ))
```

when I run joins on nodeIndex I see following exception:

```
fatal error: 'try!' expression unexpectedly raised an error: **no such column: nodeindex.id**: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-700.1.101.15/src/swift/stdlib/public/core/ErrorType.swift, line 50
error: Execution was interrupted, reason: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0).
The process has been returned to the state before expression evaluation.
```

And it is correct: nodeindex does not have column **id**

```
sqlite> select id from nodeindex;
Error: no such column: id
```

it has **docid** instead.

Please advise. 
Thank you beforehand!

**Comment by jberkel** [comment]
The queries you posted look correct. If you still have the problem, please post the generated SQL.
