### ISSUE TITLE
Carthage build fails with problems in SQLiteCipher

### ISSUE THREAD

**Issue by DigitalWolfca** [stephencelis/SQLite.swift#300]
Brians-iMac:ScaffoldersGuide Brian$ carthage update --platform iOS
*** Fetching SQLite.swift
*** Checking out SQLite.swift at "da2d43422a72ae0e91356fccfde1959d43b97385"
*** xcodebuild output can be found in /var/folders/y0/z1pws7ts5cs7ggfhpw57pg7c0000gn/T/carthage-xcodebuild.cYAD5Z.log
*** Building scheme "SQLite iOS" in SQLite.xcodeproj
*** Building scheme "SQLiteCipher iOS" in SQLite.xcodeproj
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/Brian/Library/Developer/Xcode/DerivedData/SQLite-fmqbcdxermetnmdgajhzahorxofx/Build/Intermediates/sqlcipher.build/Release-iphoneos/sqlcipher.build/Objects-normal/armv7/sqlite3.o sqlite3.c normal armv7 c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/Brian/Library/Developer/Xcode/DerivedData/SQLite-fmqbcdxermetnmdgajhzahorxofx/Build/Intermediates/sqlcipher.build/Release-iphoneos/sqlcipher.build/Objects-normal/arm64/sqlite3.o sqlite3.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
configure: error: in `/Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher':
configure: error: C compiler cannot create executables
clang: error: no such file or directory: '/Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c'
clang: error: no input files
clang: error: no such file or directory: '/Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c'
clang: error: no input files
A shell task failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/Brian/Library/Developer/Xcode/DerivedData/SQLite-fmqbcdxermetnmdgajhzahorxofx/Build/Intermediates/sqlcipher.build/Release-iphoneos/sqlcipher.build/Objects-normal/armv7/sqlite3.o sqlite3.c normal armv7 c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/Brian/Library/Developer/Xcode/DerivedData/SQLite-fmqbcdxermetnmdgajhzahorxofx/Build/Intermediates/sqlcipher.build/Release-iphoneos/sqlcipher.build/Objects-normal/arm64/sqlite3.o sqlite3.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)

#################################################################################
/var/folders/y0/z1pws7ts5cs7ggfhpw57pg7c0000gn/T/carthage-xcodebuild.cYAD5Z.log
#################################################################################

Build settings from command line:
    BITCODE_GENERATION_MODE = bitcode
    CODE_SIGN_IDENTITY =
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos9.0

=== BUILD TARGET SQLite iOS OF PROJECT SQLite WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/Brian/Library/Developer/Xcode/DerivedData/SQLite-fmqbcdxermetnmdgajhzahorxofx/Build/Intermediates/SQLite.build/all-product-headers.yaml

ProcessInfoPlistFile /Users/Brian/Library/Developer/Xcode/DerivedData/SQLite-fmqbcdxermetnmdgajhzahorxofx/Build/Products/Release-iphoneos/SQLite.framework/Info.plist Supporting\ Files/SQLite/Info.plist
    cd /Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/Brian/.rvm/gems/ruby-2.2.1/bin:/Users/Brian/.rvm/gems/ruby-2.2.1@global/bin:/Users/Brian/.rvm/rubies/ruby-2.2.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Brian/.rvm/bin"
    builtin-infoPlistUtility /Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift/Supporting\ Files/SQLite/Info.plist -expandbuildsettings -format binary -platform iphoneos -o /Users/Brian/Library/Developer/Xcode/DerivedData/SQLite-fmqbcdxermetnmdgajhzahorxofx/Build/Products/Release-iphoneos/SQLite.framework/Info.plist

CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
    cd /Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/Brian/.rvm/gems/ruby-2.2.1/bin:/Users/Brian/.rvm/gems/ruby-2.2.1@global/bin:/Users/Brian/.rvm/rubies/ruby-2.2.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Brian/.rvm/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name SQLite -O -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -target arm64-apple-ios8.0 -g -module-cache-path /Users/Brian/Library/Developer/Xcode/DerivedData/ModuleCache -Xfrontend -serialize-debugging-options -application-extension -embed-bitcode -I /Users/Brian/Library/Developer/Xcode/DerivedData/SQLite-fmqbcdxermetnmdgajhzahorxofx/Build/Products/Release-iphoneos -F /Users/Brian/Library/Developer/Xcode/DerivedData/SQLite-fmqbcdxermetnmdgajhzahorxofx/Build/Products/Release-iphoneos -c -j2 /Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift/Source/Core/Connection.swift /Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift/Source/Core/Statement.swift /Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift/Source/Core/Value.swift /Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift/Source/Core/Blob.swift /Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift/Source/Typed/Expression.swift /Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift/Source/Typed/Query.swift /Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift/Source/Typed/Schema.swift /Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift/Source/Typed/Collation.swift /Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift/Source/Typed/Operators.swift /Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift/Source/Typed/AggregateFunctions.swift /Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift/Source/Typed/CoreFunctions.swift /Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift/Source/Typed/CustomFunctions.swift /Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift/Source/Typed/Setter.swift /Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift/Source/Extensions/FTS4.swift /Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift/Source/Extensions/R*Tree.swift /Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift/Source/Foundation.swift /Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift/Source/Helpers.swift -output-file-map /Users/Brian/Library/Developer/Xcode/DerivedData/SQLite-fmqbcdxermetnmdgajhzahorxofx/Build/Intermediates/SQLite.build/Release-iphoneos/SQLite\ iOS.build/Objects-normal/arm64/SQLite\ iOS-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/Brian/Library/Developer/Xcode/DerivedData/SQLite-fmqbcdxermetnmdgajhzahorxofx/Build/Intermediates/SQLite.build/Release-iphoneos/SQLite\ iOS.build/Objects-normal/arm64/SQLite.swiftmodule -Xcc -I/Users/Brian/Library/Developer/Xcode/DerivedData/SQLite-fmqbcdxermetnmdgajhzahorxofx/Build/Intermediates/SQLite.build/Release-iphoneos/SQLite\ iOS.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/Brian/Library/Developer/Xcode/DerivedData/SQLite-fmqbcdxermetnmdgajhzahorxofx/Build/Intermediates/SQLite.build/Release-iphoneos/SQLite\ iOS.build/SQLite-generated-files.hmap -Xcc -I/Users/Brian/Library/Developer/Xcode/DerivedData/SQLite-fmqbcdxermetnmdgajhzahorxofx/Build/Intermediates/SQLite.build/Release-iphoneos/SQLite\ iOS.build/SQLite-own-target-headers.hmap -Xcc -I/Users/Brian/Library/Developer/Xcode/DerivedData/SQLite-fmqbcdxermetnmdgajhzahorxofx/Build/Intermediates/SQLite.build/Release-iphoneos/SQLite\ iOS.build/SQLite-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/Brian/Library/Developer/Xcode/DerivedData/SQLite-fmqbcdxermetnmdgajhzahorxofx/Build/Intermediates/SQLite.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/Brian/Library/Developer/Xcode/DerivedData/SQLite-fmqbcdxermetnmdgajhzahorxofx/Build/Intermediates/SQLite.build/Release-iphoneos/SQLite\ iOS.build/SQLite-project-headers.hmap -Xcc -I/Users/Brian/Library/Developer/Xcode/DerivedData/SQLite-fmqbcdxermetnmdgajhzahorxofx/Build/Products/Release-iphoneos/include -Xcc -I/Users/Brian/Library/Developer/Xcode/DerivedData/SQLite-fmqbcdxermetnmdgajhzahorxofx/Build/Intermediates/SQLite.build/Release-iphoneos/SQLite\ iOS.build/DerivedSources/arm64 -Xcc -I/Users/Brian/Library/Developer/Xcode/DerivedData/SQLite-fmqbcdxermetnmdgajhzahorxofx/Build/Intermediates/SQLite.build/Release-iphoneos/SQLite\ iOS.build/DerivedSources -emit-objc-header -emit-objc-header-path /Users/Brian/Library/Developer/Xcode/DerivedData/SQLite-fmqbcdxermetnmdgajhzahorxofx/Build/Intermediates/SQLite.build/Release-iphoneos/SQLite\ iOS.build/Objects-normal/arm64/SQLite-Swift.h -import-underlying-module -Xcc -ivfsoverlay -Xcc /Users/Brian/Library/Developer/Xcode/DerivedData/SQLite-fmqbcdxermetnmdgajhzahorxofx/Build/Intermediates/SQLite.build/Release-iphoneos/SQLite\ iOS.build/unextended-module-overlay.yaml -Xcc -working-directory/Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift

CompileSwift normal arm64 /Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift/Source/Core/Connection.swift
    cd /Users/Brian/Desktop/ScaffoldersGuide/ScaffoldersGuide/Carthage/Checkouts/SQLite.swift

**Comment by DigitalWolfca** [comment]
This has been the error last few times I have run the program, Im hoping this is in the right location and someone will be able to help.

THankyou

**Comment by delannoyk** [comment]
Having the same issue here. Have you figured out a way to bypass this yet?

**Comment by mikemee** [comment]
See also #208

**Comment by mikemee** [comment]
Merging comment from #208 to here prior to closing @208:

---
FYI, this is still a problem using the current master (2b8c8d28415cc6460f518d18348f9c462b4617bb) . The Carthage console errors are as follows. The errors above are in the Carthage build logs.

```
configure: error: in `/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher':
configure: error: C compiler cannot create executables
```
There are 46 warnings, mostly repeats of these:
```
SQLite.swift/Vendor/sqlcipher/sqlite3.c:28978:6: warning: "gethostuuid() is disabled." [-W#warnings]
SQLite.swift/Vendor/sqlcipher/sqlite3.c:9057:26: warning: unused variable 'sqlite3one' [-Wunused-const-variable]
SQLite.swift/Vendor/sqlcipher/sqlite3.c:30362:14: warning: implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
SQLite.swift/Vendor/sqlcipher/sqlite3.c:76542:21: warning: implicit conversion loses integer precision: 'i64' (aka 'long long') to 'int' [-Wshorten-64-to-32]
```
Here is the full output:

```
$ carthage update
*** Cloning SQLite.swift
*** Checking out SQLite.swift at "2b8c8d28415cc6460f518d18348f9c462b4617bb"
*** xcodebuild output can be found in /var/folders/fn/m4qv73410870r7xf2fpppwmm0000gn/T/carthage-xcodebuild.Fkotf5.log
*** Building scheme "SQLite Mac" in SQLite.xcodeproj
*** Building scheme "SQLiteCipher Mac" in SQLite.xcodeproj
*** Building scheme "SQLiteCipher iOS" in SQLite.xcodeproj
*** Building scheme "SQLite iOS" in SQLite.xcodeproj
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:9057:26: warning: unused variable 'sqlite3one' [-Wunused-const-variable]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:9057:26: warning: unused variable 'sqlite3one' [-Wunused-const-variable]
ld: warning: object file (/Users/asdfasdf/Library/Developer/Xcode/DerivedData/SQLite-dryqnsnrorqaeihiqxntpsvtlyic/Build/Products/Release/libsqlcipher.a(sqlite3.o)) was built for newer OSX version (10.11) than being linked (10.9)
configure: error: in `/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher':
configure: error: C compiler cannot create executables
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:28978:6: warning: "gethostuuid() is disabled." [-W#warnings]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:9057:26: warning: unused variable 'sqlite3one' [-Wunused-const-variable]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:28978:6: warning: "gethostuuid() is disabled." [-W#warnings]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:9057:26: warning: unused variable 'sqlite3one' [-Wunused-const-variable]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:28978:6: warning: "gethostuuid() is disabled." [-W#warnings]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:30362:14: warning: implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:32081:42: warning: implicit conversion loses integer precision: 'unsigned long long' to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:32244:11: warning: implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:32356:10: warning: implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:33556:33: warning: implicit conversion loses integer precision: 'long long' to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:35226:17: warning: implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:35537:11: warning: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:35545:11: warning: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:35838:19: warning: implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:36001:37: warning: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:36216:53: warning: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:76542:21: warning: implicit conversion loses integer precision: 'i64' (aka 'long long') to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:81870:44: warning: implicit conversion loses integer precision: 'long long' to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:105825:26: warning: implicit conversion loses integer precision: 'u64' (aka 'unsigned long long') to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:105827:36: warning: implicit conversion loses integer precision: 'unsigned long long' to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:105873:26: warning: implicit conversion loses integer precision: 'u64' (aka 'unsigned long long') to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:105875:36: warning: implicit conversion loses integer precision: 'unsigned long long' to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:28978:6: warning: "gethostuuid() is disabled." [-W#warnings]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:9057:26: warning: unused variable 'sqlite3one' [-Wunused-const-variable]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:28978:6: warning: "gethostuuid() is disabled." [-W#warnings]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:30362:14: warning: implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:32081:42: warning: implicit conversion loses integer precision: 'unsigned long long' to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:32244:11: warning: implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:32356:10: warning: implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:33556:33: warning: implicit conversion loses integer precision: 'long long' to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:35226:17: warning: implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:35537:11: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:35545:11: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:35838:19: warning: implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:36001:37: warning: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:36216:53: warning: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:76542:21: warning: implicit conversion loses integer precision: 'i64' (aka 'long long') to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:81870:44: warning: implicit conversion loses integer precision: 'long long' to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:105825:26: warning: implicit conversion loses integer precision: 'u64' (aka 'unsigned long long') to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:105827:36: warning: implicit conversion loses integer precision: 'unsigned long long' to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:105873:26: warning: implicit conversion loses integer precision: 'u64' (aka 'unsigned long long') to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:105875:36: warning: implicit conversion loses integer precision: 'unsigned long long' to 'int' [-Wshorten-64-to-32]
/Users/asdfasdf/eg/temp/sqlitetest/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c:9057:26: warning: unused variable 'sqlite3one' [-Wunused-const-variable]

```

**Comment by fluffyemily** [comment]
I am also experiencing this issue when running `carthage bootstrap --platform ios --no-use-binaries`

```*** Building scheme "SQLite iOS" in SQLite.xcodeproj
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/emilytoop/Library/Developer/Xcode/DerivedData/SQLite-abjdlqjvubxjtlboiztqxwarkqup/Build/Intermediates/sqlcipher.build/Release-iphoneos/sqlcipher.build/Objects-normal/armv7s/sqlite3.o sqlite3.c normal armv7s c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/emilytoop/Library/Developer/Xcode/DerivedData/SQLite-abjdlqjvubxjtlboiztqxwarkqup/Build/Intermediates/sqlcipher.build/Release-iphoneos/sqlcipher.build/Objects-normal/arm64/sqlite3.o sqlite3.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/emilytoop/Library/Developer/Xcode/DerivedData/SQLite-abjdlqjvubxjtlboiztqxwarkqup/Build/Intermediates/sqlcipher.build/Release-iphoneos/sqlcipher.build/Objects-normal/armv7/sqlite3.o sqlite3.c normal armv7 c com.apple.compilers.llvm.clang.1_0.compiler
(3 failures)
configure: error: in `/Users/emilytoop/Development/firefox-ios/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher':
configure: error: C compiler cannot create executables
clang: error: no such file or directory: '/Users/emilytoop/Development/firefox-ios/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c'
clang: error: no input files
clang: error: no such file or directory: '/Users/emilytoop/Development/firefox-ios/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c'
clang: error: no input files
clang: error: no such file or directory: '/Users/emilytoop/Development/firefox-ios/Carthage/Checkouts/SQLite.swift/Vendor/sqlcipher/sqlite3.c'
clang: error: no input files```

**Comment by stephencelis** [comment]
@fluffyemily Hm, the "SQLite iOS" scheme went away a bit ago. Are you locked to an old commit, branch, or fork?

**Comment by fluffyemily** [comment]
@stephencelis we've not upgraded since the swift 2.0 stuff got merged so yeah, old commit.

**Comment by fluffyemily** [comment]
@stephencelis I've just checked out the latest and there is still a SQLite iOS scheme there that I can see.

**Comment by stephencelis** [comment]
@fluffyemily My bad. I was the one on a branch! :flushed:

**Comment by fluffyemily** [comment]
awesome, thanks @stephencelis

**Comment by DigitalWolfca** [comment]
Sorry, I haven't had time to go back to this. I will close it and revisit it again later when I'm able to spend more time on if. Thank you for the replies.
