### ISSUE TITLE
I check leak it's show connection db is leak,how to fix

### ISSUE THREAD

**Issue by ai277014717** [stephencelis/SQLite.swift#303]
I don't  know why I upload picture is failed.
I will upload a demo project with simple code to show the leak.

**Comment by ai277014717** [comment]
oh no when I copy the origin code to test project and check leak it's all right. :(

**Comment by stephencelis** [comment]
I'm sorry, could you explain more? Is there a problem here?

**Comment by ai277014717** [comment]
Sorry,I just found the problem it only found in ios8
Now I upload a demo project  on https://github.com/ai277014717/test 
and with screenshot. could you give me some advice.
My project didn't want to have any memory leak.
download it and open with Xcode 7.
Product-profile-leak.
It will check memory on ios8. but ios9 is all right.

**Comment by ai277014717** [comment]
Luckly,when I reset computer and test memory leak.It's all right.
Perhaps  the xcode or libswiftcore.dylib have bug.
Now you can close this issue.

**Comment by mikemee** [comment]
Closing per above comment. Thanks!
