### ISSUE TITLE
umbrella header 'SQLiteCipher.h' not found

### ISSUE THREAD

**Issue by ammoqq** [stephencelis/SQLite.swift#308]
Hi followed the instructions and got this problem 

umbrella header 'SQLiteCipher.h' not found
could not build Objective-C module 'SQLiteCipher'

//-------------------this is my podfile<<<<<<<<<<<
    # Uncomment this line to define a global platform for your project
     # platform :ios, '6.0'
platform :ios, '8.0'
use_frameworks!

target 'Kik' do

pod 'AFNetworking', '~>2.5.4'
pod 'Fabric'
pod 'Crashlytics'
pod 'SwiftyJSON'
pod 'ObjectMapper'
pod 'MQTTClient'
pod 'JSQMessagesViewController'
pod 'KDCircularProgress'
pod 'CSwiftV'
pod 'MarqueeLabel'
pod 'SQLiteCipher.swift',
git: 'https://github.com/stephencelis/SQLite.swift.git'

end

target 'KikTests' do

end

//-------------------this is my bridging header<<<<<<<<
    #ifndef Kik_Bridging_Header_h
    #define Kik_Bridging_Header_h

#import "AFNetworking.h"
#import "MQTTClient.h"
#import <JSQMessagesViewController/JSQMessages.h>
#import <CommonCrypto/CommonHMAC.h>
#import <sqlite3.h>

#endif /* Kik_Bridging_Header_h */

I'm using xcode 7.2, I followed this tutorial first https://www.zetetic.net/sqlcipher/ios-tutorial/
then the tutorial for SQLite.swift. (I've installed via cocoapods obviously) 
I also tried to install sqlite only and it cannot find the umbrella header too

//-------------------The code i tried to compile is like this:<<<<<<<<<<<<
import Foundation
import SQLiteCipher

class SQLService {
    
    
    func doSomeTask() {
        
        let db = Database("path/to/ciphered.sqlite3")
        db.key("your_key")
    }
}

Do you have any idea how to solve that ? thanks in advance!

**Comment by mikemee** [comment]
Please try installing a new release via the instructions in https://github.com/stephencelis/SQLite.swift/pull/314 (Carthage is preferred, but CocoaPods should work too).

If you're just trying to get SQLite database access without encryption, it should fix the problem you were seeing.

**Comment by ammoqq** [comment]
Well thanks, but my client wants the sqlcipher encryption in the app, so that wont help unfortunately

**Comment by mikemee** [comment]
Ok thanks, will definitely be adding it back. Just trying to resolve a lot of problems like you're seeing.

**Comment by stephencelis** [comment]
SQLCipher is moving here: https://github.com/stephencelis/SQLiteCipher.swift. It's a WIP right now, so if you're depending on SQLCipher _right now_, please lock to the following commit SHA:

```
cc986766c44d450b65b8cb7ed43e3df8f98c9a90
```

**Comment by mikemee** [comment]
Closing this as sqlcipher has now officially moved from this codebase. Please give https://github.com/stephencelis/SQLiteCipher.swift a try and log any cipher specific issues there, thanks!
