### ISSUE TITLE
Insert / Update / Delete statement failed

### ISSUE THREAD

**Issue by griffonixjp** [stephencelis/SQLite.swift#310]
Hello 
First of all, SQLite.swift is great library, thanks.
Now I'm trying to very simple Insert / Update / Delete statement but always error occurs as belows.
The SQL statement succeeded in SQLite Browser.

Swift Code:

    do {
        let sql = NSString(format: "INSERT OR REPLACE INTO schedules (date, start_time, end_time, title) VALUES ('%@', '%@', '%@', '%@')", date, startTime, endTime, title) as String
        try db.run(sql)
    } catch let err as NSError
    {
        print("error \(err)")
    }

Error Message:
    
    error Error Domain=SQLiteCipher.Result Code=0 "(null)"

Select statement is no problem.
Is there any thing I need to do before call run method?

**Comment by stephencelis** [comment]
That definitely shouldn't be failing (result code 0 means success). Do you have a self-contained set of code that reproduces the issue? (E.g., something that creates the table?)

BTW, you should avoid using `NSString(format:)` and instead use the bindings API to avoid things like SQL injection:

``` swift
try db.run(
    "INSERT OR REPLACE INTO schedules (date, start_time, end_time, title) " +
    "VALUES (?, ?, ?, ?)", date, startTime, endTime, title
)
```

**Comment by griffonixjp** [comment]
stephencelis, thanks for your replay.

I finally found my issue.
I was overwriting the DB file before the sql statement.

Also I appreciate your suggestion for SQL injection.
