### ISSUE TITLE
Build fails when both a project and subproject depend on SQLite.swift

### ISSUE THREAD

**Issue by 0xpablo** [stephencelis/SQLite.swift#324]
Hello,
I have a project with a subproject both depending on SQLite.swift. Since the 0.9.0 version released the other day, the SQLite3 module. The problem is that since both the project and subproject import SQLite, the SQLite3 module map is redefined, something not allowed by Xcode.

I am using Carthage and while the `carthage update/bootstrap` command works well, once I try to build my project the following error appears:

```
ChildProject/Carthage/Checkouts/SQLite.swift/SQLite3/module.modulemap:1:8: error: redefinition of module 'SQLite3'
module SQLite3 [system] {
       ^
ParentProject/ChildProject/Carthage/Checkouts/SQLite.swift/SQLite3/module.modulemap:1:8: note: previously defined here
module SQLite3 [system] {
       ^
<unknown>:0: error: could not build Objective-C module 'SQLite'
```

Thanks in advance!

**Comment by stephencelis** [comment]
Ah, this may need to be a dependency, rather than an embedded module (which is similar to what the Swift Package Manager requires). Good catch! To unblock you in the meantime, you can lock to this SHA: `cc986766c44d450b65b8cb7ed43e3df8f98c9a90`.

**Comment by 0xpablo** [comment]
Great, thanks Stephen

**Comment by mikemee** [comment]
@0xpablo is the other project public? I'm interested to see how they handle their usage of SQLite.

I wonder if creating a 3rd Carthage library that just defines SQLite3 might be a solution... but it would involve everyone using it. 

Regardless, we definitely want to get it fixed somehow... I'm looking at it.

**Comment by mikemee** [comment]
@0xpablo We're working on it.  Can you try this in your `Cartfile` please?
```
github "mikemee/SQLite.swift"
```
With a bit of luck, this should pull version 0.9.2 and resolve the problem you're seeing.  (It doesn't work yet for CocoaPods).

**Comment by 0xpablo** [comment]
Thank you Mike. If it doesn't work I'll send you a sample project so yo can reproduce the issue. I'll test your PR tomorrow and I'll get back to you.

**Comment by 0xpablo** [comment]
I updated SQLite.swift recently and this seems to be happening again :(

**Comment by acrookston** [comment]
You need to be running Xcode 7.3 for 0.10.0 and above to work. This should probably be in a changelog if not already.

**Comment by 0xpablo** [comment]
Yes, I'm running the latest version. I'm using Carthage instead of CocoaPods. Commit 5652283be519024b32578f58f869ee8f0103f2db also requires Xcode 7.3 and I am able to run my project. 

Thanks!

**Comment by lcoderre** [comment]
I also have the same problem.

Using Carthage, Xcode 7.3,  sqlite 0.10.1.  I bundled my framework without problem, but when using my framework within another app, it doesn't like it.


```
/Users/xxx/repo/Carthage/Checkouts/SQLite.swift/CocoaPods/iphoneos/module.modulemap:1:8: error: redefinition of module 'CSQLite'
module CSQLite [system] {
       ^
/Users/xxx/repo/Carthage/Checkouts/SQLite.swift/CocoaPods/iphoneos/module.modulemap:1:8: note: previously defined here
module CSQLite [system] {
       ^
<unknown>:0: error: could not build Objective-C module 'SQLite'
```

**Comment by iNoles** [comment]
Looks like Xcode doesn't like the module system to built twice.

**Comment by andreuke** [comment]
Any news about this issue? I am also currently facing it.

Thanks for your time :)

**Comment by idris** [comment]
Does anyone know why XCode is looking in the `Carthage/Checkouts` directory at all?  Is there a way to have XCode ignore that directory?
