### ISSUE TITLE
Please add tvOS support to the podspec

### ISSUE THREAD

**Issue by brandenr** [stephencelis/SQLite.swift#325]
s.tvos.deployment_target = '9.0'

**Comment by mikemee** [comment]
@brandenr - I'm not a CocoaPod expert. Do you know if it is as simple as just adding that, and CocoaPods will magically add a new target?  Or should we first add 2 new targets (`tvos` and `tvos test`) and then it will _probably_ work?

**Comment by brandenr** [comment]
You should just be able to add that one line to your pod spec and then people can put it in their tvOS targets in their pod file. It had been working for me before it got version 0.9.1 or whatever (I'm guessing you officially added it to the pod spec repo)

**Comment by brandenr** [comment]
That's also all I had to do for another couple of pods to get them to work for tvOS

**Comment by mikemee** [comment]
Great, thanks. We're working on another fix now, so I'll include that for 0.9.2.  Hopefully out in the next few hours.

**Comment by mikemee** [comment]
Should be fixed now, per #327. Please let us know ;)

**Comment by brandenr** [comment]
That did it, thanks!

**Comment by mikemee** [comment]
Fantastic!  Thanks for closing the loop.

Hmm, now I wonder how we make it work for Carthage. Just break down and add the extra targets I guess. Or something magical like: https://github.com/mrackwitz/xcconfigs

**Comment by stephencelis** [comment]
@mikemee I think that's the best path forward. It was more difficult to implement with SQLCipher still bundled.
