### ISSUE TITLE
ld: framework not found SQLite

### ISSUE THREAD

**Issue by jfbomber** [stephencelis/SQLite.swift#326]
I am installing using the following PodFile

~~~~ 
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'

pod 'GoogleMaps'	
use_frameworks!
pod 'SQLite.swift','~> 0.9.1'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
~~~~

This is the error I get :

ld: framework not found SQLite
clang: error: linker command failed with exit code 1 (use -v to see invocation)

• I have tried a clean build
• Libraries added are
libsqlite3.tbd
Pods.framework
Pods_example.framework

**Comment by mikemee** [comment]
@jfbomber We're working on a couple of updates for 0.9.2 that should be out shortly with a bit of luck and might fix this problem.  I'll give you a heads up when it's available.

**Comment by mikemee** [comment]
Fwiw, you shouldn't have to add `libsqlite3.tbd` (though I'm not sure how it would hurt). And I'm not a CocoaPods expert, but in my working example, I only have `Pods.framework` added as a library.  Fwiw, here's a screenshot of the relevant Xcode page of my working CocoaPod example:

![2016-01-13_17-34-12](https://cloud.githubusercontent.com/assets/550990/12313406/07815fa0-ba1c-11e5-8451-75bee6a34bd1.png)
