### ISSUE TITLE
Idea: Add gitter chat room

### ISSUE THREAD

**Issue by mikemee** [stephencelis/SQLite.swift#328]
It appears that https://gitter.im/ provides a free chat room that you can associate with an open source Github project. I've seen it in a of couple projects I use.  Not sure if this project has enough active users to make it worthwhile, but it might be interesting to try.  I'm willing to keep a window open sometimes to see how it goes.

@stephencelis I think you need to do the signup, after which we can add a badge to the readme (I suggest right near the top).

_Of course, one might argue that the last thing anyone needs is another chat room, but it might be useful and costs little effort to try... we can always close it if it turns out to be unproductive._

**Comment by mikemee** [comment]
I think this might be active now: https://gitter.im/stephencelis/SQLite.swift, in case anyone wants to try it...

Another idea while editing readme: move the StackOverflow link prominently to the top. Perhaps put it and Gitter under a new heading called "Support".

**Comment by stephencelis** [comment]
I like the idea in practice, but it's hard to guarantee such a thing will be active, so maybe we could add it on a trial basis, see if it sticks, and remove it if it grows stale?
