### ISSUE TITLE
Carthage and OS X 10.10

### ISSUE THREAD

**Issue by tylerlong** [stephencelis/SQLite.swift#335]
I installed 0.9.2 via Carthage, get the following error:

```
.../MainWindowController.swift:11:8: Module file's minimum deployment target is OS X v10.11: .../Carthage/Build/Mac/SQLite.framework/Modules/SQLite.swiftmodule/x86_64.swiftmodule
```

Which means that it cannot run on OS X older than 10.11. I suggest to also support 10.10 (and probably 10.9).

**Comment by mikemee** [comment]
Thanks Tyler. I'll take a look. I know we have an explicit OS X setting for CocoaPods but I forgot to double check that it was the same in the Xcode scheme used by Carthage. I'll check it out later today with a bit of luck. Or PRs are always welcome!

**Comment by mikemee** [comment]
Hi @tylerlong - I've created PR #336 and you should be able to test by changing your `Cartfile` line to be:

`github "stephencelis/SQLite.swift" "36f311b"`

If you have a chance, it would be nice to confirm before merging, thanks!

**Comment by tylerlong** [comment]
`github "stephencelis/SQLite.swift" "36f311b"`

I just tested and it works! I think it is safe to merge now.
