### ISSUE TITLE
[Question] Can you please update the documentation?

### ISSUE THREAD

**Issue by jlevesque** [stephencelis/SQLite.swift#337]
The title says it all update your doc.

I've wasted 2 hours on a creation of a custom type. I've searched in the issues for my problem, and I'm not the only with it.

```
extension NSData : Value {

    typealias Datatype = NSData

    static var declaredDatatype: String {
        return Blob.declaredDatatype
    }

    static func fromDatatypeValue(blobValue: Blob) -> Self {
        return self.init(bytes: blobValue.bytes, length: blobValue.bytes.count)
    }

    var datatypeValue: Blob {
        return Blob(bytes: bytes, length: length)
    }
}
```

Type 'NSData' does not conform to protocol Value

And notice that im using 

```
 blobValue.bytes.count
```

Instead of 

```
 blobValue.length
```

Because the doc is not updated.

Please update your the doc, I'm sure that I'm not the only one who has waste his time.

**Comment by mikemee** [comment]
Hi Julien, that must be a change from an older version. Thanks for pointing it out and sorry for the pain!

This is an all volunteer unpaid effort (thanks Stephen). There is no company sponsor, so it's just people like you and me, contributing for all. 

So, it would be fantastic if you could go and edit the documentation with this info and do a Pull Request. GitHub is making that increasingly easy and it would save everyone some time - and especially the future readers. 

Regardless, thanks for the report!

**Comment by cuddergambino** [comment]
Hey,

Ran into the same issue. Thanks for finding the fix @mikemee and saving everyone else the time!

cheers

**Comment by carlosen14** [comment]
Thanks for the info to solve one problem, i spent a couple of days trying to solve by myself.

What about this?

```
extension UIImage {
  public class var declaredDatatype: String {
    return Blob.declaredDatatype
  }
  public class func fromDatatypeValue(blobValue: Blob) -> UIImage {
    return UIImage(data: NSData.fromDatatypeValue(blobValue))! // ->ERROR "Ambiguous use of 'fromDatatypeValue' "
  }
  public var datatypeValue: Blob {
    return UIImagePNGRepresentation(self)!.datatypeValue
  }
}
```

i got this error, and solved deleting my NSData extension, because there is one already defined in SQLite.swift/Foundation.swift

thanks!

**Comment by jberkel** [comment]
no longer applies, closing
