### ISSUE TITLE
Divide Row item by table prefix?

### ISSUE THREAD

**Issue by cjwirth** [stephencelis/SQLite.swift#338]
This is just a proposition, and I'm not completely sure it makes sense. 

If we run 

```
SELECT * FROM users, profiles WHERE user.id = 123
```

We will get back a Row item that looks something like this:

```
users.id = 123
users.name = "steveyman123"
users.password = "password"
profiles.id = 456
profiles.name = "Steve Harlan"
profiles.age = 25
```

I was thinking it would be nice if we could divide the Row item into 2, having one for the "users" prefix and one for the "profiles" prefix. 

The reason being that, I have a `map` or `decode` method that works fine just mapping `user.id = row[id]`, but if I have a query with multiple tables, I can't use that method anymore, because `row[id]` won't know if I'm talking about `users.id` or `profiles.id`.

**Comment by jberkel** [comment]
use [column namespacing](https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#column-namespacing) for this.
