### ISSUE TITLE
insert driving nuts!

### ISSUE THREAD

**Issue by rakaramos** [stephencelis/SQLite.swift#34]
Hi,

I'm trying to use SQLite.swift (iOS version) but I got stuck with the following insert statement.
XCode keeps telling me: 
"Could not find an overload for 'insert' that accepts the supplied arguments"

let userDirectory = NSSearchPathForDirectoriesInDomains(.DocumentDirectory, .UserDomainMask, true).first as String
let name = "test.sqlite3"
let db = Database(path)
let package: Query = db["package"]
let id: Expression<Int> = Expression<Int>("id")
db.create(table: package, ifNotExists: true) { table in
    table.column(id)
}
package.insert(id <- 0) ERROR HERE!

I can't see what I'm doing wrong!

**Comment by stephencelis** [comment]
`insert` returns multiple types, which can be indeed confusing. I try to document the discrepancy but I wish I had control over the error message. Adding a `?`, `!`, or checking for error/success should remedy the situation. E.g.,

``` swift
package.insert(id <- 0)?
```
