### ISSUE TITLE
Dynamic filter and extracting BLOB

### ISSUE THREAD

**Issue by joederoche** [stephencelis/SQLite.swift#341]
I'm trying to get my feet wet with developing on the Mac with Xcode.  I have an application that I'm tinkering with that uses SQLLite on the back end and I'm using your utility (GREAT JOB!!!!).  I have the data going in and out of the DB just fine except for one scenario.  I let the user key a filter that then is used to filter the grid data displayed down.  For example:  FirstName = "Joe".  I then create the SQL statement: select \* from owners where FirstName = "Joe". 

Example (filterData is the where clause keyed by the user):

```
  let whereStmt = "Select * from Owners where \(filterData)"
    let stmt = try!self.database.prepare(whereStmt)
    for row in stmt {
        self.OwnerArray.append(Owners(statement: row))
    }

    return self.OwnerArray
```

I then iterate through this and pass the retrieved records to the NSObject init method to populate the values.

```
    self.init()
    self.id               = Int(statement[0] as! Int64)
    self.FirstName        = statement[1] as! String
    self.LastName         = statement[2] as! String
    self.Street           = statement[3] as! String
    self.City             = statement[4] as! String
    self.State            = statement[5] as! String
    self.Zip              = statement[6] as! String
    self.Phone            = statement[7] as! String
    self.Cellular         = statement[8] as! String
    self.Email            = statement[9] as! String
    self.Picture          = statement[10] as! NSData
```

I can cast everything except for the last line.  I get an error that states:  Could not cast value of type 'SQLite.Blob' (0x10022fc28) to 'NSData' (0x1009ef068).

Is there a method for function in the SQLite.Swift that I can pass this element to that will convert it from SQLite.Blob to NSData.  I have tried to find something in the code, but I can't seem to find it.  

Thanks in advance.

Joe

**Comment by jberkel** [comment]
You can just pass the raw bytes from Blob to `Data`, using https://developer.apple.com/reference/foundation/data/1779744-init
