### ISSUE TITLE
Can do select after join

### ISSUE THREAD

**Issue by mamcx** [stephencelis/SQLite.swift#342]
I'm triying to select some columns after join, but the compiler reject it.

This is the code:

```
import SQLite

let cobros = Table("cobro")
let deudas = Table("deuda")
let clientes = Table("cliente")

//Columnas
let the_id = Expression<Int>("id")
let codigo = Expression<String>("codigo")

//Consultas

let selectClientes = clientes.order(nombre)
let selectDeudas = deudas.join(clientes, on: the_id == deudas[cliente_id])
let s1 = selectDeudas.select(deudas[*])

```

The last line give:

**Cannot invoke 'select' with an argument list of type '(Expression<Void>)'**

In fact I have the problem that both tables have a column named "Id". So then running the query, it say the column is ambiguos. So, I need to drop a column on any of them.

**Comment by MrMage** [comment]
Just do the select first and then the join. This is actually how the SQL code will be generated anyway: 'SELECT ... JOIN ON ...'

**Comment by lethianqt94** [comment]
How can I fetch the data after join?
Please take a look at my image? Is there anything wrong?
Or this library can't support this function.

![31a50d06089b79d661784c7e0e82dab1](https://cloud.githubusercontent.com/assets/10287585/16546494/7d44d8ac-4176-11e6-8e98-e55cea336102.png)
