### ISSUE TITLE
Can't Detect if a Column exists

### ISSUE THREAD

**Issue by jjohnsonvng** [stephencelis/SQLite.swift#343]
I was looking at the Query file and noticed that it would be possible to convert
public struct Row {

    private let columnNames: [String: Int]

    private let values: [Binding?]

    private init(_ columnNames: [String: Int], _ values: [Binding?]) {
        self.columnNames = columnNames
        self.values = values
    }

    /// Returns a row’s value for the given column.
    ///
    /// - Parameter column: An expression representing a column selected in a Query.
    ///
    /// - Returns: The value for the given column.
    public func get<V: Value>(column: Expression<V>) -> V {
        return get(Expression<V?>(column))!
    }
    public func get<V: Value>(column: Expression<V?>) -> V? {
        func valueAtIndex(idx: Int) -> V? {
            guard let value = values[idx] as? V.Datatype else { return nil }
            return (V.fromDatatypeValue(value) as? V)!
        }

        guard let idx = columnNames[column.template] else {
            let similar = Array(columnNames.keys).filter { $0.hasSuffix(".\(column.template)") }

            switch similar.count {
            case 0:
                fatalError("no such column '\(column.template)' in columns: \(columnNames.keys.sort())")
            case 1:
                return valueAtIndex(columnNames[similar[0]]!)
            default:
                fatalError("ambiguous column '\(column.template)' (please disambiguate: \(similar))")
            }
        }

        return valueAtIndex(idx)
    }

    // FIXME: rdar://problem/18673897 // subscript<T>…

    public subscript(column: Expression<Blob>) -> Blob {
        return get(column)
    }
    public subscript(column: Expression<Blob?>) -> Blob? {
        return get(column)
    }

    public subscript(column: Expression<Bool>) -> Bool {
        return get(column)
    }
    public subscript(column: Expression<Bool?>) -> Bool? {
        return get(column)
    }

    public subscript(column: Expression<Double>) -> Double {
        return get(column)
    }
    public subscript(column: Expression<Double?>) -> Double? {
        return get(column)
    }

    public subscript(column: Expression<Int>) -> Int {
        return get(column)
    }
    public subscript(column: Expression<Int?>) -> Int? {
        return get(column)
    }

    public subscript(column: Expression<Int64>) -> Int64 {
        return get(column)
    }
    public subscript(column: Expression<Int64?>) -> Int64? {
        return get(column)
    }

    public subscript(column: Expression<String>) -> String {
        return get(column)
    }
    public subscript(column: Expression<String?>) -> String? {
        return get(column)
    }

}

To make the columnNames public.  

Thoughts

**Comment by stephencelis** [comment]
The type-safe interface assumes you're building a contract that matches the database's state. I'm not sure your use case, but generally you should already know if the column exists or not before writing a query or accessing the data.

In the end, though, you can run a query to see if the column exists. See: http://stackoverflow.com/a/18920161/86910

**Comment by teronivala** [comment]
What about when adding a column - need to insert a default value? 
App may need need to know if value is "empty"  or "missing"
I think that for a data model need to support a missing / optional value annotated in Swift by question mark and supported by Sqlite ( Java and returning null for a missing attribute ).
Perhaps get() should support optional output ?
