### ISSUE TITLE
Issue when referencing SQLite (ios project)

### ISSUE THREAD

**Issue by eric-b** [stephencelis/SQLite.swift#345]
Hi,

I try to add SQLite library to an ios project but it doesn't work. Perhaps I missed something obvious because I'm new to ios development.

I first tried the manual approach: I dropped SQLite.framework from ios folder to my project tree in xcode, and I added it to my linked frameworks and libraries. But then, `import SQLite` statement in a swift class did not work.

Then I tried with Carthage: `import SQLite` works well but the project does not compile, with the error 

```
/../Documents/../Carthage/Build/iOS/SQLite.framework/Headers/SQLite.h:6:9: 'SQLite/SQLite-Bridging.h' file not found
Could not build Objective-C module 'SQLite'
```

When I check the package content of SQLite.framework, I see that "Headers" folder contains:
  SQLite-Bridging.h
  SQLite-Swift.h
  SQLite.h
  sqlite3.h

Is there a bug or did I done something wrong ?
I use XCode 7.2 with a single view template ios project.

Thanks
Eric

**Comment by TKim18** [comment]
I have the same exact problem. Is this answered elsewhere?

**Comment by eric-b** [comment]
No, I had no feedback, so I used another library. I have not the name in mind now but I can find it later if you don't find.

**Comment by jandoornbos** [comment]
I fixed it by cleaning the project folder. You can do this by holding alt, then Product -> Clean build folder.

**Comment by eric-b** [comment]
Thank you for the tip, I'll give it a try!

**Comment by mohamede1945** [comment]
@jandoornbos That was helpful. Thank you.
