### ISSUE TITLE
Update installation instructions (manual install)

### ISSUE THREAD

**Issue by berndlutz** [stephencelis/SQLite.swift#347]
Hi,
I've just installed SQLite.swift using the instructions "Manually". Initially it did not work despite the "General" section in Xcode everything looked good compared to other issues described here.

In the Simulator it worked, but on the device the app crashed. The error was very unspecific, but this hint did help: http://stackoverflow.com/questions/34027882/ios-dyld-library-not-loaded-with-sqlite

So, maybe it is a good idea to update installation instructions with another step: Add the "SQLite.framework" additionally to the "Embedded Binaries" section. Or just add it to the "Embedded Binaries" section, because it adds an entry in "Linked Frameworks and Libraries", too.

I just wanted to contribute this, because this is a great project. Thanks!

Regards,
Bernd

![sqlite-framework](https://cloud.githubusercontent.com/assets/224740/12808531/cbb282bc-cb17-11e5-8c84-8063726ce50e.png)

**Comment by wooque** [comment]
I couldn't make it work until a found out this issue, SQLite.framework need to be added in Embedded Binaries. Please update instructions.

**Comment by ritesh124** [comment]
Hi There, i am new to sqlite & installing it manually & it suggest to include the SQLite.xcodeproj into my own project etc ( i followed the steps.) 
but i am not able to use it (unresolved identifier connection 🤔), (But i can create object of connection class in SQLite.xcodeproj , but not in myProject.xcodeproj 😔)
More Over i already have a sqlite database file, which i would like to show on UITableView.
Could you please help me with it.

**Comment by jberkel** [comment]
Related #536
