### ISSUE TITLE
scalar 

### ISSUE THREAD

**Issue by pablopetek** [stephencelis/SQLite.swift#348]
Hello, I am running into trouble to get this working:

private static func scalarInteger(DB: Connection,_ sql:String) -> Int    {
       let value = DB.scalar(sql) as! Int64
        return value
}
(the sql column in question is INTEGER)

How should a convert value (binding? or Int64) to Int ?

Can I, maybe get here a little light on this?
Thanks!

**Comment by ryanholden8** [comment]
From the [documentation here](https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#executing-arbitrary-sql):

```
let stmt = try db.prepare("SELECT count (*) FROM users")
let count = try stmt.scalar() as! Int64
```

**Comment by pablopetek** [comment]
thanks :)
