### ISSUE TITLE
How to Use NSDate

### ISSUE THREAD

**Issue by androidcn** [stephencelis/SQLite.swift#35]
let question_date = Expression<NSDate>("question_date")
          let chapter_id = Expression<Int>("chapter_id")
        var filteredDB = dbQuestions.filter(chapter_id == incomeChapter.chapter_id)
        if let searchText = searchTxt {
            filteredDB = filteredDB.filter(like("%" + searchText + "%",question_content))
        }
        var filteredQuestion:[question]
        for q in filteredDB {
            let fuc = question()
            fuc.question_content = q[question_content]
            fuc.question_date = q[question_date] <================ ISSUE
        }

class question
{
    var question_content : String = "" 
    var question_date : NSDate = NSDate()

}

**Comment by stephencelis** [comment]
Please [see the documentation](https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#date-time-values) for examples:

https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#date-time-values

I'd recommend reading through the whole page, though. You also need to type your expressions.
