### ISSUE TITLE
Decimals and floats not supported?

### ISSUE THREAD

**Issue by mamcx** [stephencelis/SQLite.swift#351]
I try to  get a value with NSDecimalNumber and Float and it not work:

```
let valor = Expression<Float32>("valor")
let valorPagar = Expression<NSDecimalNumber>("valorPagar")

I get this error here:

$0.value = deuda[valorPagar]
```

> Type 'Row!' has no subscript members

However, If I change the expression to Int or Str it work fine.

**Comment by iNoles** [comment]
Well, Double works too.

**Comment by mamcx** [comment]
I get the same error with Double

**Comment by jberkel** [comment]
dup of #331
