### ISSUE TITLE
Include of non-modular header inside framework module 'SQLite.SQLite_Bridging'

### ISSUE THREAD

**Issue by amayne** [stephencelis/SQLite.swift#353]
Hi,

I recently added SQLite to my project through cocoapods. I am having trouble running the test target, getting these errors:

<img width="287" alt="screen shot 2016-02-08 at 9 17 55 am" src="https://cloud.githubusercontent.com/assets/3215117/12887995/c37f1be2-ce45-11e5-96f1-96da427836dd.png">

Any thoughts on how to fix this?

**Comment by nickmshelley** [comment]
I was getting that error as well, but I found a workaround for now. I noticed that import was wrapped in a `#ifndef cocoapods`, so I added SQLite.swift as a pod of my test target, which at least let me run tests. Here's what my podfile looks like:

```
target 'MyProject' do
    pod 'Alamofire'
    pod 'SQLite.swift'
    ...
    
    target 'MyProjectTests' do
        pod 'SQLite.swift'
    end
end
```

**Comment by amayne** [comment]
Thanks @nickmshelley ! That resolved the issue!

**Comment by tannooba** [comment]
Hello,

Resurrecting this thread as I am having the same issue on Xcode8 + Swift 3.
I added SQLite.swift to PodFile.
I set "Allow non-modular includes in Framework Modules" to "yes" as suggested by other forums.
Yet, my build still fails with the same issue.

Any clue to how I can resolve?

Thank you

**Comment by sashwini** [comment]
Any updates on Xcode 8 + Swift 3 environment.

**Comment by tannooba** [comment]
Unfortunately i have not found a solution.  I am trying to use other wrappers.  The SQLite.Swift page on Github says it requires Xcode 9 + Swift 4, which is not supported on my late 2009 Mac mini.

**Comment by LaraDevelopment** [comment]
Specify the correct version of the SQLite pod, like so:
  pod 'SQLite.swift', '~> 0.10.1'
That version works on xCode 7.3.1
