### ISSUE TITLE
access first result?

### ISSUE THREAD

**Issue by tirrorex** [stephencelis/SQLite.swift#356]
Hello, my issue is simple, i only have one element per row in my table, there will not be more than one per row ever.
There is swift generators which allows us to loop through a result but i don't want to, i just want to get the .first element of my result.
I check the documentation and i didn't see any way to do that easily, did i miss something?

**Comment by ryanholden8** [comment]
You can use the pluck method. Documented [Here.](https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#plucking-rows)

**Comment by tirrorex** [comment]
From the example i saw, the pluck method select * from the table, that's not what i want, i want to target a specific row.
The method says it takes a query : Query type as parameter so at first i thought i could pass it a query i made but i failed to do this.

**Comment by tirrorex** [comment]
Thought this was a close when it was actually optionnal chaining, that explains the error.
