### ISSUE TITLE
Mac app sandbox issue

### ISSUE THREAD

**Issue by tylerlong** [stephencelis/SQLite.swift#358]
I created a sample project to reproduce the issue: https://github.com/tylerlong/sqlite-sandbox

It is just a very simple app. I turned on sandbox and grant read/write access to user selected file:

![screen shot 2016-02-15 at 10 44 17 pm](https://cloud.githubusercontent.com/assets/733544/13051712/b88c0132-d435-11e5-9942-e63a21562a07.png)

I created the UI:

![screen shot 2016-02-15 at 10 45 46 pm](https://cloud.githubusercontent.com/assets/733544/13051740/dffa7e74-d435-11e5-820f-e1c8aae6a2a9.png)

The first button triggers the following code:

``` swift
    @IBAction func choose(sender: AnyObject) {
        let savePanel = NSSavePanel()
        let result = savePanel.runModal()
        if result == NSFileHandlingPanelCancelButton {
            return
        }
        db = try? Connection(savePanel.URL!.path!)
        let alert = NSAlert()
        if db != nil {
            alert.messageText = "db created successfully"
        } else {
            alert.messageText = "failed to create db"
        }
        alert.runModal()
    }
```

It runs without problem:

![screen shot 2016-02-15 at 10 47 53 pm](https://cloud.githubusercontent.com/assets/733544/13051796/2b25e118-d436-11e5-9439-1b7d6d6d0fbb.png)

So it is safe to say that the app has permission to access the db file.

The second button triggers the following code:

``` swift
    @IBAction func save(sender: AnyObject) {
        createTable()
        insertData()
    }

    func createTable() {
        try! db!.execute("create table if not exists test (id integer, content text)")
    }

    func insertData() {
        let stmt = try! db!.prepare("INSERT INTO test (id, content) VALUES (?, ?)")
        try! stmt.run(1, "hello world")
    }
```

It failed with the following error message:

![screen shot 2016-02-15 at 10 53 42 pm](https://cloud.githubusercontent.com/assets/733544/13051946/ff9fbef0-d436-11e5-9ac9-9fd981c3f486.png)

 I don't understand why this happens. The app should have permission to access user selected files.

Does SQLite.swift support Mac app sandbox? If no, then it's a bad news for me, because Mac App Store requires sandbox.

By the way, no error was thrown when I turned sandbox off.

Thank you for your wonderful work!

**Comment by iNoles** [comment]
you only allows the app to have "Read/write access to files the user has selected using an Open or Save dialog."

**Comment by tylerlong** [comment]
https://forums.developer.apple.com/thread/13691

I think I've found the root cause: SQLite creates temp files when updating data, and the app doesn't have permission to create and access temp files.

**Comment by tylerlong** [comment]
According to the doc: https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#read-write-databases

> On OS X, you can use your app’s **Application Support directory**

It DOES work.

The only disadvantage is: user is unable to select directory freely. But at least it works. I hope this helps others.

**Comment by jberkel** [comment]
closing (config issue)
