### ISSUE TITLE
Empty SQL Double field crashes app

### ISSUE THREAD

**Issue by forbze** [stephencelis/SQLite.swift#364]
Hi,

I have two columns in my database which are optional - sometimes I have the GPS coordinates, sometimes I don't. 

So I have the following columns defined:
        
```
        let latitude = Expression<Double>("latitude")
        let longitude = Expression<Double>("longitude")

        let items = try! db!.prepare(query)
        
        for item in items {
            item[latitude] //this crashes the app
        }
```
Is this the right approach?

Because the expression is a double - I'm unable to check if the value is nil.

**Comment by hiltonc** [comment]
Try `Expression<Double?>`

**Comment by forbze** [comment]
Thanks! Thought I'd tried that...
