### ISSUE TITLE
multi threading support?

### ISSUE THREAD

**Issue by music4kid** [stephencelis/SQLite.swift#365]
It appears that all read and write operations happens on the same serial queue, which could be quite inefficient if there is a read task (from the main thread) behind a heavy write task. 

 maybe a new api for specifying custom queue, and let developers build their own threading model?

**Comment by ryanholden8** [comment]
Each connection should be a serial queue, this is how a sqlite connection should work. Threading at query level would cause issues.

Threading should be done with multiple connections. For example: First, setup a UI connection that is read-only and is prioritized. Second, setup a background connection with read-write access. Your thread management code should deal with those connections. Thus this library is one step lower than than threading coordination code, your app should manage that and this library will work with it.

Also see WAL mode for sqlite: https://www.sqlite.org/wal.html

**Comment by jberkel** [comment]
see the various pool related issue, e.g. #411
