### ISSUE TITLE
Error messages (update documentation)

### ISSUE THREAD

**Issue by BinaBinaBina** [stephencelis/SQLite.swift#366]
Hi!
I am trying to use SQLite and it's really good, but please help me:
when an error occurs, how an I get the actual message from the database?
It is too difficult to track errors without it.
Maybe if you create a method runDebug, without try and throw?
Thanks.
Bina.

**Comment by SalDevGH** [comment]
I would also like to know more about error handling, it's really hard to find out what am I doing wrong.
