### ISSUE TITLE
Build fails on iPad? (manual install)

### ISSUE THREAD

**Issue by berndlutz** [stephencelis/SQLite.swift#368]
Hi,
SQLite works perfect on my iPhone 4S device and in all iPhone simulators. iPad Air simulator works great, too. But on an actual iPad Air 50+ errors occure.
I have reinstalled SQLite manually and it worked for one day, but then for any reason not any more.

Excerpt of the the error messages:

> Undefined symbols for architecture arm64:
>   "SQLite.TableBuilder.column <A where A: SQLite.Value> (SQLite.TableBuilder)(SQLite.Expression<A>, primaryKey : Swift.Bool, check : SQLite.Expression<Swift.Bool>?, defaultValue : SQLite.Expression<A>?) -> ()", referenced from:
>       static MyApp.Database.(createTableDirectories (MyApp.Database.Type) -> () -> ()).(closure #1) in Database.o
>       static MyApp.Database.(createTableDocuments (MyApp.Database.Type) -> () -> ()).(closure #1) in Database.o
>       static MyApp.Database.(value (MyApp.Database.Type) -> (Swift.String, value : Swift.String?) -> Swift.String?).(closure #1) in Database.o

Any idea? Since it doesn't work, "SQLite.xcodeproj" is read colored in the project navigation.

Kind regards,
Bernd

**Comment by iNoles** [comment]
"Undefined symbols for architecture arm64"

**Comment by berndlutz** [comment]
I already googled that, but build settings seem to be correct. Any idea?

**Comment by stephencelis** [comment]
How have you installed SQLite.swift into your project?

**Comment by berndlutz** [comment]
Yes, manually.

**Comment by jberkel** [comment]
that was 5 years ago. closing.
