### ISSUE TITLE
Insert : expression was too complex to be solved

### ISSUE THREAD

**Issue by Defoncesko** [stephencelis/SQLite.swift#37]
Hey,

I am trying to use .insert() as follow :

```swift
        var revisionQ: Query?
        if let insertedID = revisionT.insert(element1 <- "0", element2<-"0", element3<-"0", element4<-"0", element5<-"0", element6<-"0", element7<-"0", element8<-"0", element9<-"0", element10<-"0")? {
            println("inserted id: \(insertedID)")
        }
```

Am I doing something wrong for having this error :
```error
Expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions
```
When I remove the element10, the error just disappears. When the count is at 9 it is ok, but not 10 ... I don't get it.

Btw, in your example you forgot a parenthesis, at the end of println():
```swift
for user in users {
    println("id: \(user[id]), name: \(user[name]), email: \(user[email])"
    // id: 1, name: Optional("Alice"), email: alice@mac.com
}
```

Thanks

**Comment by stephencelis** [comment]
An unfortunate limitation of Swift. This'll be resolved by https://github.com/stephencelis/SQLite.swift/pull/31

**Comment by Defoncesko** [comment]
thanks

**Comment by Defoncesko** [comment]
You merged a new commit (4f2baec7ac) into master. How is it possible to use what you did within your framework ? It just changed Query.swift, not the SQLite.xcodeproj.

Thanks for helping.

**Comment by stephencelis** [comment]
`insert` now accepts an array, so you can build the setters up over more than a single expression:

``` swift
var values = [Setter]()
values.append(element1 <- "0")
values.append(element2 <- "0")
values.append(element3 <- "0")
// etc.
if let insertedID = revisionT.insert(values) {
    println("inserted id: \(insertedID)")
}
```

**Comment by Defoncesko** [comment]
So I need to re-download SQLite.xcodeproj and re-install it in Xcode ?

**Comment by stephencelis** [comment]
@Defoncesko SQLite.xcodeproj is just the project file. Whenever there are updates to SQLite.swift that you want to incorporate into your app, you'll need to update the project accordingly. If you check SQLite.swift out with git, it should be as simple as running `git pull` from the SQLite.swift directory. Otherwise, yes, you'll need to manually update everything.

**Comment by ericcgu** [comment]
Merge the changes from upstream/master into your local master branch. This brings your fork's master branch into sync with the upstream repository, without losing your local changes.

**Comment by Defoncesko** [comment]
Got it, thanks again.
