### ISSUE TITLE
Create ifNotExists Block

### ISSUE THREAD

**Issue by justdan0227** [stephencelis/SQLite.swift#373]
First off, great job on the code!!!

Am I miss understanding the ifNotExists on a create?  
If i have the following and the table exists, I would think the print statement would NOT be executed?

```
do {
            let users = Table("users")
            
            let id = Expression<Int64>("id")
            let email = Expression<String>("email")
            let name = Expression<String?>("name")
            try self.db!.run(users.create(ifNotExists: true) { t in     // CREATE TABLE "users" (
                t.column(id, primaryKey: true) //     "id" INTEGER PRIMARY KEY NOT NULL,
                t.column(email, unique: true)  //     "email" TEXT UNIQUE NOT NULL,
                t.column(name)                 //     "name" TEXT
                print("DB Created")
                })
        }
        catch {
        }
```

**Comment by stephencelis** [comment]
Hi there, the closure attached to `users.create` _builds_ the SQL string but it has no executed yet. If you move the `print` statement _below_ the `try db.run` statement, it will print after execution only.

**Comment by justdan0227** [comment]
Thanks .. I thought that too, however that's where I had it originally.  It still gets called if moved.  Thoughts?

**Comment by stephencelis** [comment]
Ah, so if you want the statement to fail (and hit the error path), you need to remove the `ifNotExists`. `IF NOT EXISTS` means: silently swallow failure if the table already exists.

**Comment by justdan0227** [comment]
BINGO!  That's it! Works now. thanks. now I understand.  This is way cool!
