### ISSUE TITLE
Concurrency issue - database locked when applying custom query method

### ISSUE THREAD

**Issue by dsafaric** [stephencelis/SQLite.swift#374]
Dear, 

as an extension of the Connection class, I've decided to write the following method:

```
 func query(query : String) -> [[String : AnyObject]] {
        do {

            let statement : Statement = try self.run(query)

            return statement.flatMap{binding -> [String : AnyObject]? in
                var data : [String : AnyObject] = [:]

                for (index, element) in statement.columnNames.enumerate() {
                    let key : String = element.uppercaseString

                    if binding[index] != nil {
                        switch binding[index]! {
                        case is Int: data.updateValue(Int(binding[index]! as! Int), forKey: key)
                        case is Double: data.updateValue(Int(binding[index]! as! Double), forKey: key)
                        case is Int64: data.updateValue(Int(binding[index]! as! Int64), forKey: key)
                        case is String: data.updateValue(binding[index]! as! String, forKey: key)
                        case is Bool: data.updateValue(binding[index]! as! Bool, forKey: key)
                        default: XCLog.logInformative(message: "Column type not really specified?")
                        }
                    }
                }

                return data
            }

        }
        catch let error {
            XCLog.logError(error, t: XCLogInformationTypeError(), message: "Error while querying database with query: \(query)")
            return []
        }
    }
```

What exactly is the reason behind writing the custom query method? Well, quite often I need to query the database for data originating from an unknown table. To simplify things, while preparing the data to be sent to the server, I'm at first querying a communication table, storying the information required to retrieve the initially changed record. For example, if I add an record to table X, with primary key name equal to X_PK, then the table will store information describing that there has been a change in table X, whereas the corresponding PK name and value are equal to some value.

However, when applying this approach and method, I keep getting the error that the database is locked, crashing the app in the following method:

```
extension Statement : GeneratorType {

    public func next() -> [Binding?]? {
        return try! step() ? Array(row) : nil
    }

}
```

My question is: (1) how can I avoid getting the database locked, while only select queries are being executed - and while using the block handler, (2) any suggestion onto the above method and possible improvements?

Thanks in advance!

**Comment by ryanholden8** [comment]
The issue is in your DB connection management, which is not in the code you posted.
The only way you can get a DB lock issue is if you have more than one connection to the same DB.

**Comment by dsafaric** [comment]
True, shouldn't using busy handlers and timeouts partially solve this issue?

**Comment by ryanholden8** [comment]
Yep, see here: https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#thread-safety

**Comment by dsafaric** [comment]
Unfortunately, when experimenting with concurrent execution by executing the code below, the database gets locked once again - while I'm using a single database database i.e. Connection instance.

```
    func testConcurentQueryExecution() {
        let operationQueue : NSOperationQueue = NSOperationQueue()
        operationQueue.maxConcurrentOperationCount = 10000
        
        for _ in 1...1000 {
            let operations : [NSOperation] = [selectOperation(CRMDB.sharedInstance), insertOperation(CRMDB.sharedInstance)]
            operationQueue.addOperation(operations[Int.random(0...operations.count-1)])
        }
        
        operationQueue.waitUntilAllOperationsAreFinished()
    }
    
    ///
    /// - returns:
    
    func selectOperation(database : DatabaseConnectionProtocol) -> NSOperation {
        return NSBlockOperation(block: {
            let databaseTables : [String] = self.databaseTables(database)
            let randomDatabaseTable : String = databaseTables[Int.random(0...databaseTables.count-1)]
            
            do {
                for _ in try database.connection!.prepare(Table(randomDatabaseTable).select(*)) {
                    print("SELECT * FROM \(randomDatabaseTable)")
                }
            }
            catch let error {
                XCTFail("Select operation failed due to: \(error)")
            }
        })
    }
    
    ///
    /// - parameter database:
    /// - returns: 
    
    func insertOperation(database : DatabaseConnectionProtocol) -> NSOperation {
        return NSBlockOperation(block: {
            do {
                let databaseTables : [String] = self.databaseTables(database)
                let randomDatabaseTable : String = databaseTables[Int.random(0...databaseTables.count-1)]
                
                let record = Table(randomDatabaseTable).select(*).order(SQLite.random())
                try database.connection!.run(record.delete())
                try database.connection!.run(record.insert())
                print("DELETE FROM - INSERT INTO \(randomDatabaseTable) \(database.connection!.changes)")
            }
            catch let error {
                XCTFail("Insert operation failed due to: \(error)")
            }
        })
    }

```

**Comment by ryanholden8** [comment]
Are you inspecting this DB file using a external DB browser? (ie http://sqlitebrowser.org/)

**Comment by dsafaric** [comment]
No I am not - why? 

I forgot to mention, if you want to replicate the same issue I'm having, just replace the CRMDB.sharedInstance.connection variable with a Connection variable.

**Comment by groue** [comment]
@dsafaric You should be more clear than "I keep getting the error that the database is locked". I think that @ryanholden8 assumes that you have a SQLITE_BUSY error (code 5) sent by SQLite itself. But I'm not so sure. What error do you get exactly? Do you have a stack trace?

**Comment by ryanholden8** [comment]
> No I am not - why?

If you are inspecting the DB file while these tests are being ran you would have multiple connections to the DB.. which would cause a locked DB.

> I think that @ryanholden8 assumes that you have a SQLITE_BUSY error (code 5) sent by SQLite itself.

That is a very valid point.. I am assuming DB locked == Busy signal.
A error or stack trace should be posted.

> I forgot to mention, if you want to replicate the same issue I'm having, just replace the CRMDB.sharedInstance.connection variable with a Connection variable.

To replicate the code to `CRMDB.sharedInstance.connection` is required.. There are a number of ways this code could be the culprit. 
A full project/workspace zipped up that reproduces this error would make it easy for others to help.

**Comment by jberkel** [comment]
stale
