### ISSUE TITLE
Use of unresolved identifier Connection

### ISSUE THREAD

**Issue by cnovelini** [stephencelis/SQLite.swift#376]
Hey, I'm having an issue when trying to connect with a database.
I'm getting the following error:
![screen shot 2016-03-21 at 7 06 32 pm](https://cloud.githubusercontent.com/assets/17994099/13936995/22de7ce0-ef98-11e5-9ad6-31834cdc13bf.png)

I'm linking the framework:

![screen shot 2016-03-21 at 7 06 43 pm](https://cloud.githubusercontent.com/assets/17994099/13937015/547f64ee-ef98-11e5-8faa-2309fcf75b3f.png)

I'm using Xcode 7.2.1 and downloaded the latest files of SQLite.swift!

Why am I facing this problem?

Thanks in advance!

**Comment by nickmshelley** [comment]
@cnovelini: My best guess is that you added NewClass.swift to the SQLite target instead of your app target.

**Comment by kikily** [comment]
I also have this problem and I can't solve it. 
Does anyone have any good ideas? 
Thanks.

**Comment by quanguyen** [comment]
I am having the exactly same problem. Have you got any fix so far? I refer to [this thread](https://github.com/stephencelis/SQLite.swift/issues/222) but it seems this problem is no more?

Regards

**Comment by jberkel** [comment]
Looks like an installation error, closing.
