### ISSUE TITLE
Header SQLite-Swift.h not found

### ISSUE THREAD

**Issue by pgudivada** [stephencelis/SQLite.swift#377]
My configuration : XCode 7.3 (7D175)

SQLite (0.9.2)

<img width="454" alt="sqliteswiftnotfound" src="https://cloud.githubusercontent.com/assets/2045222/13939319/6f2cb96a-efaa-11e5-8f3a-7aee8662a921.png">

   Am I doing something wrong?

**Comment by shnhrrsn** [comment]
Checkout #349 for more info on this

**Comment by pgudivada** [comment]
@shnhrrsn  thanks for the pointer.
