### ISSUE TITLE
[Question] Adding UIImage as Blob

### ISSUE THREAD

**Issue by carl2013** [stephencelis/SQLite.swift#38]
I'm trying out the project but I am getting tied up on using Blobs. I have a UIImage (png) but when trying to insert a row using it I am getting "Type Blob? does not conform to protocol Value" error. I cannot see how it is not being conformed to after drawing upon your documentation. 
```
let uuid = Expression<Int>("uuid")
let png = Expression<Blob?>("png")

if let insertedID = ingredientTable.insert(uuid <- createUUID() ,png <- pic?.datatypeValue) {
        println("inserted id: \(insertedID)")
}
```
I've used the following extensions from your documentation ...
```
extension NSData: Value {
    public class var declaredDatatype: String {
        return Blob.declaredDatatype
    }
    public class func fromDatatypeValue(blobValue: Blob) -> Self {
        return self(bytes: blobValue.bytes, length: blobValue.length)
    }
    public var datatypeValue: Blob {
        return Blob(bytes: bytes, length: length)
    }
}

extension UIImage: Value {
    public class var declaredDatatype: String {
        return NSData.declaredDatatype
    }
    public class func fromDatatypeValue(blobValue: Blob) -> Self {
        return self(data: NSData.fromDatatypeValue(blobValue))!
    }
    public var datatypeValue: Blob {
        return UIImagePNGRepresentation(self).datatypeValue
    }
}
```

**Comment by stephencelis** [comment]
Using the extensions means you can bypass `Blob` and not need to call `datatypeValue` directly. _E.g._:

``` swift
let uuid = Expression<Int>("uuid")
let png = Expression<UIImage?>("png")

if let insertedID = ingredientTable.insert(uuid <- createUUID() ,png <- pic) {
        println("inserted id: \(insertedID)")
}
```

Beyond that, I've copied and pasted your code above and have had no issue compiling. Can you provide more code? I faked the data using the following:

``` swift
let ingredientsTable = Database()["ingredients"]
func createUUID() -> Int { return 1 }
let pic = UIImage(named: "test")
```

**Comment by carl2013** [comment]
Thanks for the clarification on the extension usage. 

I did get my code above to compile when I changed ```png <- pic?.datatypeValue``` to ```png <- pic!.datatypeValue``` although I think that is not exactly what I want to be doing here. 

I plan on updating my code to follow your extension instructions.

Thanks again. The project is a godsend.

**Comment by stephencelis** [comment]
What is `png` exactly? In your example, it's:

``` swift
Expression<Blob?>
```

But I'd expect the behavior you were getting above if it were:

``` swift
Expression<Blob>
```

**Comment by stephencelis** [comment]
Is it safe to close this issue now?

**Comment by carl2013** [comment]
Oh yes. It's working great now! Thanks again
