### ISSUE TITLE
Umbrella header warning while using Carthage

### ISSUE THREAD

**Issue by SebastianOsinski** [stephencelis/SQLite.swift#382]
Hi, due to recent problems with SQLite.swift and Cocoapods, I use Carthage to import SQLite.swift to my project. Everything builds fine, but I get a warning: Umbrella header for module 'SQLite' does not include header 'sqlite3.h'. Is this warning something I can ignore, or can it cause any problems in the future, e.g. during submission to the App Store?

I use Carthage 0.15.2 along with Xcode 7.3

**Comment by Huato115** [comment]
+1 same problem
Redefinition of module "Compression","Darwin","OS","libkern"

**Comment by stephencelis** [comment]
@Huato115 Are you sure you have the same problem using Carthage? @SebastianOsinski's warning appears to be different?

**Comment by Huato115** [comment]
Xcode version 7.3 . You should try yourself.

**Comment by SebastianOsinski** [comment]
@Huato115 This is not the same problem. I have minor issue with Carthage, you seem to have major build errors with resemble issues #378 #380

**Comment by filipmelik** [comment]
I have exactly the same issue. Tried to switch from Pod to Carthage, but this gives me exactly the same warning.

**Comment by Huato115** [comment]
@filipmelik thank a lot

**Comment by filipmelik** [comment]
For me this warning  somehow disappeared today. I cannot really remember what I did, but i reckon it was only something like Clean and Clean Build Folder. Nothing special. Can you try it @SebastianOsinski to see if the problem disappear?

**Comment by SebastianOsinski** [comment]
@filipmelik Thanks! It dissapeared after Cleaning build folder. Maybe it was some 'left over' after previous builds

**Comment by stephencelis** [comment]
Ah, the zen of **Clean Build Folder…**

Is this safe to close out?

**Comment by stephencelis** [comment]
Closing out for now. Feel free to chime in and I'll reopen if this continues to be an issue.
