### ISSUE TITLE
dyld: Library not loaded: @rpath/SQLite.framework/SQLite

### ISSUE THREAD

**Issue by justdan0227** [stephencelis/SQLite.swift#384]
After going through #380 and getting a test app to work I returned to my project.  Got the code to compile (clean / build / run) ; however upon execution I get the following in the Xcode debugger window:

dyld: Library not loaded: @rpath/SQLite.framework/SQLite
  Referenced from: /Users/xxxx/Library/Developer/CoreSimulator/Devices/7D94F26E-B21B-4F37-83F1-AD9DE8E06DA3/data/Containers/Bundle/Application/BF6876A3-A927-41A4-8DFA-47753DCE1289/NewProject.app/NewProject
  Reason: image not found
(lldb) 

**I'm using the following podfile:**

platform :ios, '9.0'
use_frameworks!

target 'UpCheck' do
	pod "SQLite.swift",
  git: "https://github.com/stephencelis/SQLite.swift",
  branch: "cocoapods-xcode-7-3"
  pod 'CVCalendar', '~> 1.2.9'
end

Thoughts?

**Comment by stephencelis** [comment]
@justdan0227 Were you able to resolve by following any of the fixes in #380? Cleaning the build folder, upgrading cocoapods, deleting and reinstalling pods, reinstalling Xcode, etc.?

**Comment by brandenr** [comment]
Do you get that on this simple app that just imports SQLite.swift? I'm not seeing this problem in my app or in this simple demo app to test #380 

[SqliteTest-master 2.zip](https://github.com/stephencelis/SQLite.swift/files/189665/SqliteTest-master.2.zip)

**Comment by justdan0227** [comment]
I created a new project and it worked just fine.  Its the old one that has all of my updated project code in it that I can't get to work.  Its has to do with a previous install I think.  I tried removing the pod folder and doing another 'pod install' however still same issue.  (also did a clean / build).  Odd...

**Comment by brandenr** [comment]
Did you delete the derived data folder? Or "Clean Build Folder" instead of just "Clean"?

**Comment by justdan0227** [comment]
Did  Clean and then Build.  When that didn't work I tried deleting the Pod folder from Finder, removing the .xcworkspace, and running pod install again.   Where do you delete the derived data folder?

**Comment by stephencelis** [comment]
From a console it's at `~/Library/Developer/Xcode/DerivedData`, though holding the **option** key and selecting **Clean Build Folder…** from the **Product** menu in Xcode should clear most related build products from that directory.

**Comment by justdan0227** [comment]
BINGO!  that was it!  Running now!

**Comment by stephencelis** [comment]
Great! Closing this out. Let us know if you have more problems!
