### ISSUE TITLE
AppSotre validation fails with ERRORS ITMS-90087 90209 90125 90080

### ISSUE THREAD

**Issue by roma86** [stephencelis/SQLite.swift#387]
Hello. 

I can not integrate library using cocoapods after upgrade to xcode 7.3, so i moved to carthage.
On last stage of submission to store i have multiple error messages (last screenshot)

I actually trying some stupid thing like manually remove `i386.swiftdoc i386.swiftmodule x86_64.swiftdoc x86_64.swiftmodule` from `SQLite.framework/Modules/SQLite.swiftmodule`, clean project and build folder, remove derivedData. After that project build is still success, but fail with same error on store validation.

```
// iOS target 9.0
// Carhtage version 0.11.0
// Cartfile
github "stephencelis/SQLite.swift" ~> 0.10.0

carthage update --platform iOS
```

Note:
Bitcode is set to NO
When i try use cocoapods (for xcode 7.3 branch or 0.10.0 no matter) i have error [similar to this comment](https://github.com/stephencelis/SQLite.swift/pull/380#issuecomment-201743016)
Also on archive phase i have warning:
```
/path_to_project/<module-includes>:1:1: Umbrella header for module 'SQLite' does not include header 'sqlite3.h'
```
Build can pass validation 
![pass](https://api.monosnap.com/rpc/file/download?id=HD56TMz5cQwEWZSsdxrFY9vJ0g6ke8)

But still fail on real submition to store
![fail](https://api.monosnap.com/rpc/file/download?id=3HK4va4MoCsDH54S5fGaD8xwOLvLXT)

**Comment by stephencelis** [comment]
This looks like a Carthage issue. I'm unfamiliar with Carthage, but assume that a build phase needs to strip the other architectures before submission. By default, using Carthage to build a framework for iOS means building for both the device _and_ simulator. In this case, the simulator architectures need to be stripped before submission. I'd check out the Carthage docs for more details.

**Comment by stephencelis** [comment]
As an aside: many CocoaPods users were able to resolve the issue by upgrading to 0.10.0 and:

- Cleaning the build folder.
- Sometimes deleting and reinstalling Pods from scratch.
- Sometimes deleting and reinstalling Xcode (many had issues with 7.3 after the initial release)

Did you try all the above?

**Comment by roma86** [comment]
@stephencelis thank you for answer. Should i send same issue report to the carthage repo? What do you think?

**Comment by stephencelis** [comment]
@roma86 I don't think so. This sounds like it's how Carthage is _supposed_ to work. You're just missing a build phase that they should be documenting.

**Comment by roma86** [comment]
About cocoapods. 
I tried everything that I found in this issue tracker and on stackowerflow and what i can imagine by my self.
- Previously xcode was upgraded from appstore, i remove it and download from developer portal
- Clean and clean build folder is my handy friend for now same with remove DerivedData followed xcode restart, system reboot
- Remove ./Pods and Podfile.lock is also every time when any changes was applied
And many other tips and tricks which i can found while researching  for solution. After 2-nd day i try to switch to carthage and bump - it is build success, but not passing final validation.

**Comment by stephencelis** [comment]
Check out this part of Carthage's README:

> On your application targets’ “Build Phases” settings tab, click the “+” icon and choose “New Run Script Phase”. Create a Run Script in which you specify your shell (ex: `bin/sh`), add the following contents to the script area below the shell:
>
>  ```sh
>  /usr/local/bin/carthage copy-frameworks
>  ```
>
>  and add the paths to the frameworks you want to use under “Input Files”, e.g.:
>
>  ```
>  $(SRCROOT)/Carthage/Build/iOS/Box.framework
>  $(SRCROOT)/Carthage/Build/iOS/Result.framework
>  $(SRCROOT)/Carthage/Build/iOS/ReactiveCocoa.framework
>  ```
>  This script works around an [App Store submission bug](http://www.openradar.me/radar?id=6409498411401216) triggered by universal binaries and ensures that necessary bitcode-related files and dSYMs are copied when archiving.

— https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos

**Comment by roma86** [comment]
@stephencelis thank you. This looks like what i missed out. I thought that the description of this repo about how to carthage should be used is enough. 
Just `carthage update` looked very attractive.
I am sorry to bother you.

**Comment by stephencelis** [comment]
No worries! Glad you got things sorted!
