### ISSUE TITLE
Framework less targets: Copy the SQLite.swift source files (from its SQLite directory) into your Xcode project.

### ISSUE THREAD

**Issue by helmutkaufmann** [stephencelis/SQLite.swift#393]
I'd like to use SQLite in an OSX command line tool. The installation instructions say: _Copy the SQLite.swift source files (from its SQLite directory) into your Xcode project._ What exactly does that mean? Drag and drop the SQLite folder (which is on the same level as Documentation or CocoaPods) onto the project folder of my application in Xcode? That I did with the bridging file now reading

_#import <sqlite3.h> (note: it should read sqlite3.h here but somehow it does not show)
#import "SQLite/Core/SQLite-Bridging.h"_

However, that does not compile. Two issues: 
(1) Helps.swift reports that there is no such module CSQLite
(2) the command line app says that Connection is an unresolved identifier when calling let db = try Connection("<path to my dircetory>db.sqlite3")

**Comment by iNoles** [comment]
The easier way to do drag SQLite project into your Xcode app project.

**Comment by jberkel** [comment]
outdated, closing
