### ISSUE TITLE
header "SQLite-Swift.h" not found, among other errors

### ISSUE THREAD

**Issue by coharness** [stephencelis/SQLite.swift#397]
I've been using this library in my project for over a year, but I ran pod update this morning and now I have this error and 89 others. I assume it's all coming down to this. I found [this answer](http://stackoverflow.com/a/30594349/4660161), which didn't help at all. Tried [all these steps](http://stackoverflow.com/a/36284663/4660161) which also didn't work.
@stephencelis

**Comment by ryanholden8** [comment]
Please include specifics on "the 89 others" errors. Also which Xcode version and cocoapod version are you running?
