### ISSUE TITLE
How to know sql

### ISSUE THREAD

**Issue by wei18810109052** [stephencelis/SQLite.swift#399]
I have a question. if I want to know the actual sql sentence. What should i do? thinks. 

I use:
```
try db.run(users.create { t in
    t.column(id, primaryKey: true)
    t.column(name)
    t.column(email, unique: true)
})
```
I want to get:
```
// CREATE TABLE "users" (
//     "id" INTEGER PRIMARY KEY NOT NULL,
//     "name" TEXT,
//     "email" TEXT NOT NULL UNIQUE
// )
```
if I know the actual sql sentence, I can transform to Object-C easily. When I want to do.^_^
My English is bad..^_^^_^

**Comment by PranKe01** [comment]
Good question. I also asked myself how to do this...

**Comment by stephencelis** [comment]
Are you asking how to convert a typed SQLite.swift expression to a SQL string? You can technically use `Expression.asSQL()`:

https://github.com/stephencelis/SQLite.swift/blob/master/SQLite/Typed/Expression.swift#L77

``` swift
users.create { t in
    t.column(id, primaryKey: true)
    t.column(name)
    t.column(email, unique: true)
}.asSQL() // "CREATE TABLE "users" …

**Comment by wei18810109052** [comment]
yeah. very thinks.
And It is very excellent. I use it now.
