### ISSUE TITLE
How to write a "if exists" clause before inserting & updating

### ISSUE THREAD

**Issue by FateRiddle** [stephencelis/SQLite.swift#405]
I'm building a login view for my app. Need to check if userID is in SQLite tb_user table everytime I login. If there exists a matching userID, then proceed to update field isUserLoggedIn to true; else insert userID, userName, password, and true for isUserLoggedIn.

just wondering how to write `if exists( select 1 from tb_user where userID = @in_userID ) update tb_user set isUserLoggedIn = true where userID = @in_userID` in SQLite.swift?

**Comment by jberkel** [comment]
not a bug, closing

**Comment by FalconBFR** [comment]
Hey @jberkel  that is not very helpful. Same problem here 4 years later
