### ISSUE TITLE
Project will not build

### ISSUE THREAD

**Issue by AaronBorns** [stephencelis/SQLite.swift#410]
This very could be my inexperience with Swift, Xcode, and/or Cocoa Pods. But I'm getting 83 build errors on SQLite.swift. Here is my Podfile.
```
use_frameworks!

target ‘Percent’ do
	pod 'SQLite.swift', '~> 0.10.1'
end
```
Is there any good way to share the errors with this community? The error that perplexes me the most is "Expected declaration" on `associatedtype UnderlyingType = Void` of Expression.swift. Thanks!

**Comment by julepka** [comment]
Try to update your Xcode. You need the latest version for 0.10.1

**Comment by AaronBorns** [comment]
@julepka I'm running xcode 7.2 (7C68) which was what i updated yesterday from the app store. Is this the correct version?

**Comment by AaronBorns** [comment]
@julepka saw #394. I'll update again

**Comment by jakooistra** [comment]
Using Xcode 7.3.1, I successfully built to 0.10.1 version this morning. Perhaps this issue can be closed?

**Comment by stephencelis** [comment]
Thanks for the update! Closing for now.

**Comment by kumaresan-cgvak** [comment]
I Face the same issue and am in a situation, where i cannot update my xcode. So, is there any other previous version which will work in Xcode 7.2
