### ISSUE TITLE
Pluck does not throw

### ISSUE THREAD

**Issue by PranKe01** [stephencelis/SQLite.swift#414]
The pluck function does not throw an exception, but in the documentation you use the try keyword:
let user = try db.pluck(query)

Also in the documentation the menu point "Migrations and Schema Versioning" is not linked.

**Comment by t4ec** [comment]
+1 

Currently I try to check 1 field in DB to make sure it is valid, in case it is not valid app crashes and "try" cannot be used as pluck does not through.
