### ISSUE TITLE
try Connection("\(path)/db.sqlite3") not handled

### ISSUE THREAD

**Issue by tom-soft** [stephencelis/SQLite.swift#417]
let path = NSSearchPathForDirectoriesInDomains(
            .DocumentDirectory, .UserDomainMask, true
        ).first!
self.db = try Connection("\(path)/db.sqlite3")

error:
Errors thrown from here are not handled

xcode version:
Version 7.3 (7D175)

**Comment by acrookston** [comment]
Just to make sure, you have enclosed your code with:
` do { <your code> } catch { <handle error or ignore> }`

**Comment by tom-soft** [comment]
successed,thanks
