### ISSUE TITLE
Store and retrieve data from column with type decimal

### ISSUE THREAD

**Issue by MaximNklv** [stephencelis/SQLite.swift#418]
Hi, all
In our project we work with existing database, so we wouldn't change db scheme. 
The issue with "decimal" column type.

Store:

let decNumber = NSDecimalNumber(string:"555")
let SQL : String = "INSERT INTO ....
 var bindings : [Binding?] = []
bindings.append(decNumber.stringValue)
try db.run(SQL,bindings)

At this point the value in database ("555")
Read: 
`let maxHeightValue : String? = row[index!] as? String
`
maxHeightValue is always nil
The column index is wright. This happens in all project with other values in columns with type decimal.

**Comment by MaximNklv** [comment]
It's a duplicate of #331

**Comment by jberkel** [comment]
closing as dup of #331
