### ISSUE TITLE
Add Copy Bundle Resouces Image to Documentation

### ISSUE THREAD

**Issue by ericcgu** [stephencelis/SQLite.swift#42]
Before this section:

Read-Only Databases

If you bundle a database with your app, you can establish a read-only connection to it.

Before you do this, you have to copy the db.sqlite into your Bundle Resources. I believe adding a  quick snapshot in the documentation and telling new users this step will help.

![screen shot 2015-01-18 at 2 05 59 pm](https://cloud.githubusercontent.com/assets/4943759/5793698/a559fe84-9f1b-11e4-820c-4372d5721995.png)

**Comment by stephencelis** [comment]
Duplicated by #43.
