### ISSUE TITLE
(Regression) Reopen #324 (Build fails when both a project and subproject depend on SQLite.swift)

### ISSUE THREAD

**Issue by 0xpablo** [stephencelis/SQLite.swift#421]
Hello,

I don't have permission to reopen issues. Could you please reopen #324? It is broken again. See https://github.com/stephencelis/SQLite.swift/issues/324#issuecomment-204305896 for more details.

Thanks in advance!

**Comment by toshi0383** [comment]
I guess this has been fixed in 38ece82483475784b2d2377671e5367427992a72
