### ISSUE TITLE
Alter query in sqlite.swift to change column data type 

### ISSUE THREAD

**Issue by isurukej** [stephencelis/SQLite.swift#422]
I need to change column data type  ('int' to 'float' ). How can I do it in sqlite.swift?

**Comment by nickmshelley** [comment]
SQLite doesn't support altering tables: http://stackoverflow.com/questions/2685885/sqlite-modify-column.

**Comment by groue** [comment]
SQLite does allow you to alter tables in any fashion, but it's a little more involved than a simple ALTER TABLE query: https://www.sqlite.org/lang_altertable.html#otheralter

**Comment by jberkel** [comment]
more recent versions of sqlite (3.26.0) support this natively, so you don't need extra libraries.
