### ISSUE TITLE
module map for sqlite is absolute path

### ISSUE THREAD

**Issue by nealsun** [stephencelis/SQLite.swift#425]
Hi, I found SQLite.swift use absolute path to import system sqlite lib, `"/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/sqlite3.h"`, and I rename my Xcode to Xcode7.3 cause I have two version of xCode， so compiler can't find this file

**Comment by stephencelis** [comment]
This is an unfortunate limitation of module map files and CocoaPods. If you install SQLite.swift manually or via Carthage you can avoid this issue. You can also manually update the module map file, but that solution is more cumbersome and brittle.

**Comment by mgrebenets** [comment]
Is there a way to have a custom build phase in auto-generated pod target?
We could patch module maps with correct paths in that build phase.

**Comment by mgrebenets** [comment]
So, in our case, since we are using `fastlane`, we have added a custom script to fastlane lanes, which does the modulemap patching, similar to this:

```ruby
# Patch modulemap files in the project with correct Xcode path
def patch_modulemaps
  puts "Patching modulemap files..."
  Dir["../**/*.modulemap"].each do |modulemap|
    puts "Patching #{modulemap.yellow}..."
    contents = File.read(modulemap)
    contents.gsub!("/Applications/Xcode.app/Contents/Developer", ENV["DEVELOPER_DIR"])
    File.open(modulemap, "w") { |f| f.puts contents }
  end
end
```

This way modulemap files have correct path matching current `DEVELOPER_DIR`, which we always set as part of CI.

**Comment by davedelong** [comment]
This also breaks for any Xcode that is installed in a location other than `/Applications` or is not named `Xcode.app`.
