### ISSUE TITLE
Could you please write a simple example in code to show what is good practice?

### ISSUE THREAD

**Issue by FateRiddle** [stephencelis/SQLite.swift#427]
It is my first app, I used sqlite.swift for data storage, then I find my data-dealing code everywhere, lots of MVCs need to import SQLite, I guess it's not a good practice. Also I'm confused whether should I introduce a class to store, handle and pass on data from sqlite(which I didn't do, I purely read data from sqlite table and put them into tableview).

Please just one simple example with a UITableView showing data from SQLite storage, to show me what is supposed to do, thanks!

**Comment by jberkel** [comment]
@FateRiddle SQLite.swift takes a minimalistic approach in this regard and does not recommend one way or the other.

Maybe take a look at [GRDB.swift](https://github.com/groue/GRDB.swift) which already comes with ready-to-use components to integrate into table view controllers, AFAIK.

**Comment by groue** [comment]
Thanks @jberkel. @FateRiddle, see http://github.com/groue/GRDBDemo for a sample app which keeps a table view synchronized with the content of the database.
