### ISSUE TITLE
(Question) SELECT with inner SELECT

### ISSUE THREAD

**Issue by Jabelriera** [stephencelis/SQLite.swift#432]
Hello everyone! Sorry if this is an obvious question, I have been reading the documentation carefully but I am not very familiar to JOIN use so I post it here:

I want to run the following query (and some other of the style) but I can't see the way to do it:

`SELECT  col_2, col_3, col_4 FROM table_1 WHERE col_1 IN ( SELECT col_5 FROM table_2 WHERE col_6 = a_value)`

If it helps to understand the situation, *Table 2* is a relational table so there is a relation *1-** from *Table 1* to *Table 2*

Thank you everyone by advance!

**Comment by MaikoHermans** [comment]
@Jabelriera how did you end up fixing this.

I'm having issues with the col_1 IN () section specifcally
