### ISSUE TITLE
tvOS target not supported in app extensions

### ISSUE THREAD

**Issue by Tableau-David-Potter** [stephencelis/SQLite.swift#445]
I'm working on integrating this framework into one of my frameworks which we need to work in app extensions.  When building for tvOS, I get a warning saying that I'm "linking against a dylib which is not safe for use in application extensions."  If I check the checkbox on the General tab for the tvOS target, the problem goes away.  Is this safe to do?  If so, could this be changed in the repo?

Thanks,
**_David_**

**Comment by stephencelis** [comment]
This should probably be added to the repo proper!

**Comment by Tableau-David-Potter** [comment]
I submitted a pull request with a fix for this:  https://github.com/stephencelis/SQLite.swift/pull/478

**Comment by Tableau-David-Potter** [comment]
When do you think you can accept this pull request?

**Comment by jberkel** [comment]
change has been merged. closing

**Comment by Tableau-David-Potter** [comment]
Thanks.
