### ISSUE TITLE
Adding SQLIte to other project/workspace  fails with Carthage and POD.

### ISSUE THREAD

**Issue by dhf0820** [stephencelis/SQLite.swift#446]
I get this error after doing a carthage install.  
![screen shot 2016-06-08 at 5 25 41 pm](https://cloud.githubusercontent.com/assets/23723/15916106/0b2ee1bc-2da4-11e6-8034-26bd8d7e63a3.png)

Attempting to use pod with: 
platform :ios, '9.0'
use_frameworks!

target 'TestSqliteSwiftV2' do
pod 'SQLite.swift', '~> 0.10.1'
end

gives: [!] Unable to find a specification for SQLite.swift (~> 0.10.1) when i run pod install

**Comment by jberkel** [comment]
outdated, closing.
