### ISSUE TITLE
Is this supported any longer

### ISSUE THREAD

**Issue by dhf0820** [stephencelis/SQLite.swift#448]
It does not seem as though this is supported any longer.

**Comment by cfilipov** [comment]
The lack of responses to recent issues makes it seems otherwise but based on the commit history it looks like @stephencelis is still actively contributing to this project and looking at PRs, which is what counts.

**Comment by stephencelis** [comment]
It's community-supported by a few active contributors. SQLite.swift, like a lot of open source, isn't company-supported (at the moment), so contributions happen when we have free time to work on it.
