### ISSUE TITLE
Plans for Swift 3?

### ISSUE THREAD

**Issue by cfilipov** [stephencelis/SQLite.swift#455]
I'm not trying to rush anything, just wanted ask if you are planning to support Swift 3 at some point in the future since it doesn't seem to have been mentioned yet.

**Comment by stephencelis** [comment]
I have a (broken, unpushed) branch going. It's a big migration :)

**Comment by peymankh** [comment]
Cannot wait to try it out @stephencelis

**Comment by peymankh** [comment]
Hey @stephencelis. Any plans on when you will be pushing the branch?

**Comment by bytegh** [comment]
Hey, guys:

so I we start to use this PR in my project(migrated to swift3.0 already). Or I still need to wait?

thanks! this is a amazing library :)

**Comment by iNoles** [comment]
@bytegh you still need to wait. It is still broken in Xcode 8 GM.

**Comment by mbryantkreactive** [comment]
@stephencelis 
hi, is there an eta on the Swift 3 migration process ?

**Comment by jberkel** [comment]
There's now a branch with a working test suite ([swift3-mariotaku](https://github.com/stephencelis/SQLite.swift/tree/swift3-mariotaku)). Would be helpful to see if it works in actual projects though, please give it a try if you can.

**Comment by iLandes** [comment]
I have a compilation error using Swift3-mariotaku branch

Pods/SwiftyMarkdown/SwiftyMarkdown/SwiftyMarkdown.swift:295:75: Cannot convert value of type 'ClosedRange<String.Index>' (aka 'ClosedRange<String.CharacterView.Index>') to expected argument type 'Range<String.Index>' (aka 'Range<String.CharacterView.Index>')

**Comment by jberkel** [comment]
@iLandes that's an unrelated project (which might not have been converted to swift3 yet)

**Comment by edswafford** [comment]
I'm getting an 'ambiguous for type lookup error' using swift3-mariotaku branch.  I'm subclassing Operation (which was NSOperation in swift 2) in my code.  Looks like the conflict is 'enum Operation' in Connection.swift.

**Comment by stephencelis** [comment]
@edswafford A workaround would be to specify `Foundation.Operation`. We should probably nest that in `Connection` to avoid the conflict.

**Comment by MrMage** [comment]
Works great for me, thanks a lot!

I would make the run() functions on Connection `@discardableResult`, though - I use them for updates where I don't need the result, and this leads to  pollution with warnings about unused results.

**Comment by pablopetek** [comment]
Hello,
this used to worked, but with swift3-mariotaku gives 
"Ambiguous reference to member "column(_:primaryKey:check:defaultValue:)"


...
            try self.db!.run(self.magnets!.create(ifNotExists: true) { t in
                t.column(columns.id, primaryKey: .Autoincrement)  <--- Here
                t.column(columns.TITLE)
                t.column(columns.MSG)
                t.column(columns.PARENT_ID)
                t.column(columns.TYPEMAGNET)
                })
...

But this works (but how then to do the autoincrement?):

                t.column(columns.id, primaryKey: true)

thank you!
pablo

**Comment by bennettl** [comment]
Having issues with the 
![screen shot 2016-09-20 at 2 46 02 pm](https://cloud.githubusercontent.com/assets/1672224/18690041/05cbd90c-7f41-11e6-9deb-03b0e8d00290.png)
Swift3-mariotaku branch...

**Comment by suragch** [comment]
The swift3-mariotaku branch is working for me in Xcode 8.

I'm using this line in my Carthage cartfile:

    github "stephencelis/SQLite.swift" "swift3-mariotaku"

And I updated Carthage with this:

    carthage update --platform iOS --no-use-binaries

**Comment by SerenadeX** [comment]
Hey, any progress with Swift 3? Is that an update we will be seeing in the foreseeable future?

**Comment by jberkel** [comment]
@SerenadeX still WIP but should get merged soon

**Comment by jberkel** [comment]
closed with #502
