### ISSUE TITLE
How to upgrade database version or data migration

### ISSUE THREAD

**Issue by lawgimenez** [stephencelis/SQLite.swift#456]
Like in Android, we just increment the database version and it will be updated. Is there any similar method?

**Comment by stephencelis** [comment]
That's generally handled by `PRAGMA user_version`. Here's an extension:

``` swift
extension Database {
    public var userVersion: Int {
        get { return Int(scalar("PRAGMA user_version") as! Int64) }
        set { try! run("PRAGMA user_version = \(newValue)") }
    }
}
```

In use:

```
if db.userVersion == 0 {
  // run migrations for version 1
  db.userVersion = 1
}
if db.userVersion == 1 {
  // run migrations for version 2
  db.userVersion = 2
}
// etc.
```

**Comment by lawgimenez** [comment]
Thanks man! Appreciate it!

**Comment by leaphawk** [comment]
I'm sorry but can you be more specific where to use it? What is Database here?

**Comment by leaphawk** [comment]
I got confused with the newValue . It's placeholder in extentions. all good👍 
Database is nothing but your DatabaseHelper class.
