### ISSUE TITLE
Expression fails when Field Contains a Number

### ISSUE THREAD

**Issue by ericcgu** [stephencelis/SQLite.swift#46]
After numerous testing, I believe that Query fails when Column heading contains a Number:

Here is my repo: If anyone can shed some light, I would appreciate it:
https://github.com/ericcgu/RWEGSeed/blob/NumericalColumnNames/Seed/RWEGFrequencyByLocationTableViewController.swift

```Swift
    //Success
    let firstValue = Expression<String>("ON")

    //Failure
    let firstValue = Expression<String>("ON_1950")

    //Failure
    let secondValue = Expression<String>("19500301_OFF")
    let thirdValue = Expression<String>("19500301_TOTAL")
```
As a workaround, I tried using a literal to avoid expressions but this did not work:
```Swift
 //Success
 var query = "SELECT * FROM STOCKS_CORN_LOCATION"
    let statement = db.prepare(query)
    while ((statement.next()) != nil){
      let row = statement.columnNames
      println(row)
    }

 //Failure
 var query = "SELECT 2011301_ON FROM STOCKS_CORN_LOCATION"
    let statement = db.prepare(query)
    while ((statement.next()) != nil){
      let row = statement.columnNames
      println(row)
    }
```

**Comment by stephencelis** [comment]
When was the last time you updated your SQLite.swift submodule? I can get the following to run just fine on master:

``` swift
let db = Database()
let users = db["users"]
let field = Expression<String>("19500301_OFF")

db.create(table: users) { $0.column(field) }
users.insert(field <- "Hello")!
for user in users.select(field) {
    println(user[field])
}
```

Console output:
```
CREATE TABLE "users" ("19500301_OFF" TEXT NOT NULL)
INSERT INTO "users" ("19500301_OFF") VALUES ('Hello')
SELECT "19500301_OFF" FROM "users"
Hello
```

**Comment by stephencelis** [comment]
Ah, you know what, I think your issue is in your raw SQL syntax:

``` sql
SELECT 2011301_ON FROM STOCKS_CORN_LOCATION
```

The above is invalid. You must quote identifiers (generally using `"` or `\``) that contain spaces or begin with numbers. SQLite.swift automatically quotes expressions for you, so as long as you're using the type-safe interface, things should just work. If you're writing raw SQL, however, you'll need to be careful to quote things yourself wherever necessary.

**Comment by ericcgu** [comment]
Thank you Stephen. I appreciate it.
