### ISSUE TITLE
Xcode 8 Build failed

### ISSUE THREAD

**Issue by Kayl51** [stephencelis/SQLite.swift#460]
When I put the library in xcode 8 I am always "build Failed"

Help me

Thx

**Comment by nickmshelley** [comment]
@Kayl51 Xcode 8 is still in beta. The current release of this library works fine in the latest official release of Xcode, which is Xcode 7.3.1.

It looks like the conversion to make it work in Swift 3 is underway: https://github.com/stephencelis/SQLite.swift/issues/455. If you need it sooner, you can always do the conversion yourself and submit a pull request, which I'm sure would be appreciated.

**Comment by jberkel** [comment]
Dup of #465
