### ISSUE TITLE
Loading extensions

### ISSUE THREAD

**Issue by kuhnza** [stephencelis/SQLite.swift#461]
Is there a way to load sqlite extensions? I'd like to work with the JSON1 extension specifically but it's not clear how I'd go about loading it. Is there a way to override the built in libsqlite3.dylib and build from the amalgamation file with the necessary compiler flags turned on? Is there an easier way?

Great lib BTW, thanks!

**Comment by S4TNEW** [comment]
Same point here, we want to use the ICU extension in SQLite.swift.

**Comment by jberkel** [comment]
Right now the easiest way is to integrate SQLite as a pod and require a standlone version of SQLite, cf. 

https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#requiring-a-specific-version-of-sqlite

**Comment by jberkel** [comment]
This can be done via pods, closing.
