### ISSUE TITLE
"Errors thrown from here are not handled"

### ISSUE THREAD

**Issue by rajeshm20** [stephencelis/SQLite.swift#462]
![screen shot 2016-06-28 at 6 17 54 pm](https://cloud.githubusercontent.com/assets/8141399/16415805/b5a22be6-3d5c-11e6-9a6a-63352c69f423.png)

Why this error "Errors thrown from here are not handled"...though i already add the framework manually to my project.

**Comment by rajeshm20** [comment]
![screen shot 2016-06-28 at 6 25 32 pm](https://cloud.githubusercontent.com/assets/8141399/16416013/c64a3e88-3d5d-11e6-8cc9-57ff051df2d2.png)

**Comment by nickmshelley** [comment]
I'd suggest reading up on Swift error handling: https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/ErrorHandling.html

Basically, Swift forces you to handle errors. `try` can only appear in a `do/catch` block:

``` swift
do {
  let db = try Connection("path/to/db.sqlite")
} catch {
  // Handle error
}
```

If you want to avoid the `do/catch` block you use either `try?` or `try!`.
