### ISSUE TITLE
(NOT an Issue) Dumb Question about Expression<String> to String conversion

### ISSUE THREAD

**Issue by DJManas** [stephencelis/SQLite.swift#463]
Hello,

I just want to ask dumb question. I have table cards, which has cardID and cardName.

I have this code:
```
        let cards = Table(„cards“)
        let cardID = Expression<Int64>(„cardID“)
        let cardName = Expression<String?>(„cardName“)
        
        let card = cards.filter(cardID == 1)
        let cell = tableView.dequeueReusableCellWithIdentifier("cardName", forIndexPath: indexPath)
        

        
        cell.textLabel?.text = card[cardName]
```

And I am unable to get it to work since it has problems with converting Expression<String> to String and I am lost.

Thank you,
Regards,

**Comment by DJManas** [comment]
It is dumb question indeed, I didn’t get the documentation right (I was thinking, that Table will do the work) so I had implemented db.pluck and all working, please close and delete this question.

**Comment by fitzco01** [comment]
@DJManas Same dumb question here.  Re(re(re))reading the docs hasn't pointed me in the right direction yet so I'm wondering if you could point me in the right direction or post a snippet of your solution.  Thanks in advance
