### ISSUE TITLE
How to batch insert?

### ISSUE THREAD

**Issue by longlylong** [stephencelis/SQLite.swift#464]
How to batch insert?

**Comment by iNoles** [comment]
is this is like transactions?

https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#transactions-and-savepoints

**Comment by longlylong** [comment]
thk!!!! like this
try db.transaction {
    for user in usersList{
       try db.run(users.insert(email <- user.email))
    }
}

**Comment by jberkel** [comment]
not a bug, closing
