### ISSUE TITLE
Custom function cuts characters

### ISSUE THREAD

**Issue by S4TNEW** [stephencelis/SQLite.swift#468]
I am using custom functions for simple string manipulations but receive some weird results.

Background: I learned that SQLite doesn't handle lower/upper for characters outside the ASCII. So I wrote custom functions for those cases that look like this:

```
static let s4tToLower: (Expression<String>) -> Expression<String?> = (
    try! db.createFunction(function: "s4tToLower")
    { value in
        return value.lowercaseString
    }
)
```

Then I use it in a query:

```
var vehicleQuery = Table(DatabaseTables.Vehicle)
let condition = FLFDbFunctions.s4tToLower(FLFVehicle.kLicense) == licenseNo.lowercaseString
vehicleQuery = vehicleQuery.filter(condition)
```

Problem: In some cases the searched string contains unicode characters (eg the German umlauts "äöü").
The problem in those cases is that the custom function returns the correct lowercaseString (verified by debugging in Xcode), but SQLite gives a right-side trimmed string.
Please see the following example code:

```
let testString = "TÖL-AA 12"
let test1: String = db.scalar("select ? ", testString.lowercaseString) as! String
print(test1)
//töl-aa 12
let test2: String = db.scalar("select s4tToLower(?) ", testString) as! String
print(test2)
//töl-aa 1
```

**Comment by jberkel** [comment]
@NathanFallet a similar bug is in the new `createAggregation` function (which presumably just copied the code). it should be moved into a method

**Comment by NathanFallet** [comment]
@jberkel If you know how to fix it then go, you'll be quicker than me on that
