### ISSUE TITLE
How to check database schema?

### ISSUE THREAD

**Issue by 2ndGAB** [stephencelis/SQLite.swift#474]
Hello,
The doc is missing `Migrations and Schema Versioning`. Bad luck it's maybe what I was looking for.
I've added 2 columns to an existing table in my new version of my application, and of course after application update, it won't be able to access to an existing db.
So when the application starts, I should first check if the table is still the same or migrate/recreate it.

How to do?

**Comment by jberkel** [comment]
The documentation has been re-added: 
https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#migrations-and-schema-versioning
