### ISSUE TITLE
Database ifExists argument not recognized.

### ISSUE THREAD

**Issue by nicholaslocascio** [stephencelis/SQLite.swift#48]
I'm trying to run the following code:

        let db : Database = getDb()
        let onegram = db["onegram"]
        db.drop(table: onegram, ifExists: true) 

but Xcode throws a compiler error:
``Incorrect argument labels in call (have 'table:ifExists:', expected 'index:on:')``

**Comment by stephencelis** [comment]
I have a test for this, so it should compile just fine:

https://github.com/stephencelis/SQLite.swift/blob/1af591ac2ff4b409b5542e7b5241d186260beded/SQLite%20Common%20Tests/SchemaTests.swift#L306

Any chance your SQLite.swift submodule is out of date? Or could you provide a sample project to better troubleshoot? I'm not sure I can do much more with the information given.

**Comment by nicholaslocascio** [comment]
Turns out my submodule was out of date. Anyway- thanks!
