### ISSUE TITLE
watchOS scheme not built when using Carthage

### ISSUE THREAD

**Issue by Tableau-David-Potter** [stephencelis/SQLite.swift#480]
I am using Carthage to include this framework in my project.  I have targets for iOS, macOS, tvOS, and watchOS.  Unfortunately, Carthage does not build the watchOS target.  Upon further inspection, I found that the watchOS scheme was not shared.

I've submitted pull request with the required changes:  https://github.com/stephencelis/SQLite.swift/pull/479.  It would be great if you could accept the pull request and it would also be great if you could release another version (e.g. 0.10.2).

Thanks,
**_David_**

**Comment by Tableau-David-Potter** [comment]
When can you accept this merge request?

**Comment by jberkel** [comment]
this should work now (w/ 0.11.0). reopen if needed.

**Comment by Tableau-David-Potter** [comment]
Thanks.
