### ISSUE TITLE
R*Tree.swift filename causes git problems in Windows

### ISSUE THREAD

**Issue by TyrantFox** [stephencelis/SQLite.swift#486]
There is a file in SQLite/Extensions/R*Tree.swift and corresponding test class file. The use of the asterisk in the file name works fine for OSX, and I know the vast majority of users would only ever be using this repository on OSX.

However when used as part of a larger project in a repository that is also checked out by Windows Users, the asterisk gets git into a state of confusion since it does not quote filenames when interacting with the file system.

I propose simply renaming the offending files to RTree.swift and RTreeTests.swift. I'll create a pull request for this change.

**Comment by stephencelis** [comment]
Closed via #487.
