### ISSUE TITLE
Foreign Key Constraints are disabled

### ISSUE THREAD

**Issue by ezCoding** [stephencelis/SQLite.swift#49]
When trying to set a foreign key for a column an assertion fails with the message:
*assertion failed: foreign key constraints are disabled*

Are they disabled by default? If yes, how can I enable them?
Thank you for this lib. It is awesome btw ;)

**Comment by stephencelis** [comment]
Please see https://www.sqlite.org/foreignkeys.html#fk_enable for more information. (Note that you'll have to enable it per database connection at this time, so if you call `Database()` multiple times in your app, you'll need to execute the given statement, as well.)
