### ISSUE TITLE
Carthage SQLite.framework not portable to different systems: CSQLite missing

### ISSUE THREAD

**Issue by maun** [stephencelis/SQLite.swift#492]
When I build the framework using carthage everything works as expected locally, but on other systems I get this error:
```
error: missing required module 'CSQLite'
```
Rebuilding with carthage on these systems fixes the error, but the framework then does not work on the first system anymore.

**Comment by jerrywell** [comment]
+1 for Xcode 8.0 GM

**Comment by maun** [comment]
This was with 7.3.1

**Comment by jberkel** [comment]
ah, I actually misread your bug report. weird, is the module loaded on runtime? can you explain what exactly you mean by "on other system"? do you take the compiled framework and include it another app, on a different machine?

**Comment by maun** [comment]
We have a project checked in to git including the compiled framework. It is imported using the normal import statement in swift. By my system I meant my computer with my os, my coworker uses his mac.

**Comment by lyc2345** [comment]
Same here, I think I misopen my project with Xcode 8, then I open Xcode 7.3, then run the project, error appeared.
header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/sqlite3.h" not found

And In Connection.swift
Could not build Objective-C module 'CSQLite'

**Comment by tuchangwei** [comment]
@lyc2345  There is a tmp fix - You can change your Xcode app name `Xcode7.3` to `Xcode` to solve this issue.

**Comment by maun** [comment]
Both our Xcodes where named Xcode.app, still got the error.

**Comment by jberkel** [comment]
fix has been released now (0.11.0). reopen if needed.

**Comment by maun** [comment]
This is fixed, thanks.

**Comment by ChanchalW** [comment]
![screen shot 2017-03-03 at 1 19 54 pm](https://cloud.githubusercontent.com/assets/21195828/23542611/3105f068-0014-11e7-8c67-7280e31c0b11.png)

Any suggestion? I was using this in another project in swift 2.2. Now i am using xcode 8.2 and facing this issue. Nothing helped about it.

**Comment by raybradley** [comment]
Hi, I'm having this problem as of 11 March 2017 using Xcode 8.2.1, SQLite 0.11.2, and Carthage. Ideas?

**Comment by nealsun** [comment]
same issue with @raybradley .

**Comment by jberkel** [comment]
will be fixed once #615 is merged

**Comment by phildow** [comment]
I'm now seeing this issue using the Swift Package Manager, XCode 8.3.2, SQLite v0.11.3
