### ISSUE TITLE
Compile errors in Xcode8 release builds (Swift 2.3)

### ISSUE THREAD

**Issue by Douvi** [stephencelis/SQLite.swift#496]
When I compile project with swift 2.3 I got this issue for the filed `userIdField` :
```
Cannot convert value of type 'Expression<Int>' to expected argument type 'Int'
```

Code:
``` swift
private static let myTable = Table("my_table")
private static let userIdField = Expression<Int>("user_id")

static func getInfo() {
     let select = myTable.filter(userIdField != 1)
.....
}

```

UPDATE:
This bug do appear only with the operation `!=` and not with `==`, `>`, `<`, `>=` and `<=`

UPDATE2:
Same bug when I cast my Int to Expression<Int>

Error:
```
Binary operator '!=' cannot be applied to two 'Expression<Int>' operands
```

Code:
``` swift
private static let myTable = Table("my_table")
private static let userIdField = Expression<Int>("user_id")

static func getInfo() {
     let val = Expression<Int>(value: 1)
     let select = myTable.filter(userIdField != val)
.....
}

**Comment by soltea** [comment]
Same here, for me it just happens during Building for Lease, when Building for Debug it doesn't, any workaround?

**Comment by MattGrdinic** [comment]
Same issue here (debug fine, Release or Archive no go).

Unfortunately the clever hack of using !(expression == val) doesn't work for me. I just get a different error about == being "**Ambigguous reference to member '=='**"

Fortunately one instance (!= 0), I just changed to > 0, and the others were both string comparisons (prevent empty strings), that I now just filter after the fact in a loop. 

Good old Swift. Charging bravely ahead as we follow bravely, but often blindly, behind : )

**Comment by fefranca** [comment]
Just went through the same problem on Swift 2.3, Xcode 8, it only failed on Release builds.

The issue was a `field != nil` condition.

`value of type 'Expression<String?>' (aka 'Expression<Optional<String>>') can never be nil, comparison isn't allowed`

For this particular case the same workaround soltea mentioned above was applied, i.e. `!(field == '')`.  That is most likely translating into `sql_text_field != ''`, which returns the same results as `sql_text_field IS NOT NULL` in our app.

**Comment by jberkel** [comment]
This is related to "whole module optimization" (`-Owholemodule`) which is enabled in release builds in Xcode8.

**Comment by MattGrdinic** [comment]
@jberkel - Interesting. I fixed my code already it's tough hard to test this retroactively, but I could swear I actually tried that first, disabling Whole Module Optimization, and it didn't work. Please do take with a grain of salt though, as this is quite easy to test for anyone else having this issue: 

![screen shot 2016-10-02 at 4 10 09 pm](https://cloud.githubusercontent.com/assets/877972/19024558/b734ecf6-88ba-11e6-96db-ccc5ade60940.png)

**Comment by jberkel** [comment]
I've seen this problem on a larger project, but have trouble reproducing it with a minimal project setup from scratch.

**Comment by jberkel** [comment]
Migrating to Swift 3.0 solved the problem for me. Don't think there's much which can be done on our side, closing.
