### ISSUE TITLE
Swift 3: No such module 'SQLite'

### ISSUE THREAD

**Issue by deermapper** [stephencelis/SQLite.swift#503]
After update to Xcode 10 and Swift 3 the error: "Noch such module 'SQLite'".

What I've done so far:
- Download Swift 3 branch
- Drag SQLite.xcodeproj to my app
- Added SQLite.framework as Framework to Linked Frameworks and Libraries

![bildschirmfoto 2016-09-19 um 17 00 56](https://cloud.githubusercontent.com/assets/6825724/18636957/0dd318ce-7e8b-11e6-8161-0068ea86694b.png)

- Try to build the project

What I've also tried is to build SQLite.xcodeproj (for iOS) with multiple errors:
![bildschirmfoto 2016-09-19 um 17 03 08](https://cloud.githubusercontent.com/assets/6825724/18636941/ff7ca3da-7e8a-11e6-8f2a-1f218825f114.png)

Any ideas?

**Comment by iNoles** [comment]
Try the swift3-mariotaku branch

**Comment by deermapper** [comment]
Thanks for your help. 

In Xcode 8 I reverted back to Swift 2.3 and integrated the xcode8-Branch into my project.
