### ISSUE TITLE
SQLite/SQLite-Bridging.h not found, Could not build Objective-C module SQLite

### ISSUE THREAD

**Issue by bennettl** [stephencelis/SQLite.swift#505]
Currently I'm using Xcode 8, Swift 3, Cocoapods (version 1.1.0.rc.2) and SQLite.swift (0.10.1). In my podfile..

pod 'SQLite.swift', :git => 'https://github.com/stephencelis/SQLite.swift.git', :branch => 'swift3-mariotaku'

Getting these two error messages:

![screen shot 2016-09-20 at 2 46 02 pm](https://cloud.githubusercontent.com/assets/1672224/18690272/2ce4ac02-7f42-11e6-9fcb-164f266165e0.png)

**Comment by jberkel** [comment]
Just tried with a simple project set up from scratch and it works there. Must be related to some other setting in your project. Can you post the full compiler error log?

**Comment by ghks1353** [comment]
I have 2 errors too, my build log is here: http://pastebin.com/38Wv2DX9
Xcode 8, swift 3
pod 'SQLite.swift', :git => 'https://github.com/stephencelis/SQLite.swift.git', :branch => 'swift3-mariotaku'

![image](https://cloud.githubusercontent.com/assets/6275109/18948380/cbed90a8-8671-11e6-84b2-ffa3046c2414.png)

**Comment by jberkel** [comment]
can you verify the installation path of Xcode? Very likely it is set to a non-standard path.

**Comment by ghks1353** [comment]
I solved this problem to cleaning up deriveddata folder of Xcode.

**Comment by jberkel** [comment]
When using CocoaPods your Xcode needs to be installed in the default location.

**Comment by jberkel** [comment]
Closing, reopen if needed

**Comment by DingSoung** [comment]
Xcode 9.4 & simulator 
CocoaPod 1.5.2
use static library

**Comment by unknown-account** [comment]
The same issue when try to use use **static library** (remove **use_frameworks!**)

**Comment by ArmsZhou** [comment]
i unlock and modify the SQLite.h file

from

```
#import <SQLite/SQLite-Bridging.h>
```

to 

```
#import <SQLite-Bridging.h>
```

it works!
