### ISSUE TITLE
Xcode 7.3 and 8 problem

### ISSUE THREAD

**Issue by wolie** [stephencelis/SQLite.swift#508]
Xcode 8 does not work at all. Downgraded to Xcode 7.3. Im under Sierra, and the instructions for adding a framework are wrong, or something is broken. Results are: "No such module 'SQLite'" or Cann not sign, or my favorite 999+ errors.

**Comment by iNoles** [comment]
7.3 doesn't work in Sierra.

**Comment by wolie** [comment]
Yes it does. :-) Downgraded yesterday. With a symbolic link you can even deploy to iOS10 targets..

**Comment by jberkel** [comment]
You'll need the xcode8 branch and make sure that Xcode is installed under the standard path

**Comment by jberkel** [comment]
Please try the latest master branch, with Xcode 8.

**Comment by jberkel** [comment]
Closing, reopen if needed.
