### ISSUE TITLE
Error convert to swift 3 in Xcode 8

### ISSUE THREAD

**Issue by tranthanhepu** [stephencelis/SQLite.swift#512]
I'm using Xcode 8, and it's recommend to upgrade to Swift 3. After I'm do that, it's show errors like attached file.
![screen shot 2016-10-03 at 9 23 54 am](https://cloud.githubusercontent.com/assets/4176709/19026080/9380753c-894b-11e6-9ac4-06202fd46521.png)

**Comment by jberkel** [comment]
see #502
