### ISSUE TITLE
Result of call to 'run' is unused

### ISSUE THREAD

**Issue by irshad9998** [stephencelis/SQLite.swift#514]
When i create table,then i got warning 

>  Result of call to 'run' is unused

and app crash 

     ` do
        {
        try db.run(users.create(ifNotExists: true) { t in
            t.column(id, primaryKey: PrimaryKey.autoincrement)
            t.column(videoId)
            t.column(videoname)
            t.column(author_name)
            t.column(imgPath)
            })
        }
        catch
        {
        
        }`

**Comment by jberkel** [comment]
the warning is harmless. can you post the logs of the crash?

**Comment by irshad9998** [comment]
Thanks for reply found nil value on this line

> db = try Connection("\(path)/musi_db.sqlite3")

**Comment by jberkel** [comment]
hm, looks like an error with your filesystem / path name. closing this for now.

**Comment by iNoles** [comment]
@jberkel you can use @discardableResult to avoid warning.

**Comment by jberkel** [comment]
@iNoles thanks for the hint, I added the annotation.
