### ISSUE TITLE
Xcode7 reporing stdatomic.h not found?

### ISSUE THREAD

**Issue by justdan0227** [stephencelis/SQLite.swift#518]
I have both Xcode7 and Xcode8 installed.  I'm using 7 on a project that I have yet to migrate over to Swift3 and getting the error "module.modulemap Header 'stdatomic.h' not found.  pointing to:

```
module stdatomic {
            header "stdatomic.h" // note: supplied by the compiler
            export *
        }
```

Thoughts?
(also using cocoapods 0.39.0

**Comment by tuchangwei** [comment]
To see if the path of "stdatomic.h" file is existing. If the path is "xxx/**Xcode**/xxx", but your xcode named **Xcode8*", then you know maybe the path is not existing. I have Xcode7 and Xcode8 too. Now I totally use Xcode8 to develop Swift project, so I named xcode8 to Xcode, the I can build it successfully.

Hope it can help you.

**Comment by justdan0227** [comment]
I'll investigate.  For now I have to do both xCode7 and xCode8.  My xCode8 is just called xCode, however my xCode 7 is called xCode7 until I can get compatible xCode8 libraries.  Where is that path set that I can override where xCode7 is looking?  Thoughts?

**Comment by tuchangwei** [comment]
Please note when you use Xcode 7, you should use the main branch, but if
you use Xcode 8, you should use swift3-mariotaku branch for supporting
Swift 3.

I don't think you can build the same code with Xcode 7 and Xcode 8 even
though you don't use the third libraries.

So actually, when I migrated the code, I used two branches to manage them.
And when I use Xcode 7, I named it Xcode, when I use Xcode 8, I named it
Xcode too.

It's not a good way if you have more than one project which use the library.

And I have not deeply learnt how to edit the path. Maybe you can fork one
code and change its configuration file.

**Comment by justdan0227** [comment]
thanks @tuchangwei; I understand about using the same code for Xcode7 and Xcode8.  For now I have to stick with 7 for just one of my projects.  It will get convereted to Xcode7 and Swift3 but for now I need to fix something and get it out under Xcode7.  Still can't get past the stdatomic.h

**Comment by kreonjr** [comment]
@justdan0227 I have had the same issue and I needed to stay with the older Xcode version for now. I solved this issue by naming my Xcode7 to plain "Xcode" and Xcode 8 to "Xcode8". I was then able to get past this compilation error.

**Comment by jberkel** [comment]
The master branch now requires Xcode8 so closing this.

**Comment by lyimin** [comment]
Thinks
