### ISSUE TITLE
Pod does not match master branch

### ISSUE THREAD

**Issue by zackdh9** [stephencelis/SQLite.swift#520]
When installing via cocoapods, xcode complains about old syntax right away.  I compared the files that you get when you download a zip and the swift 3 changes are there in the download but not the pod.

**Comment by davelyon** [comment]
There has not been a release that includes the Swift 3 changes, though they are on the master branch. 

Until there is an updated release, you might consider updating your `Podfile` to use the `master` branch directly as is documented here: https://guides.cocoapods.org/syntax/podfile.html#pod

**Comment by zackdh9** [comment]
Awesome, thanks for the tip. I was trying to do just that!

**Comment by jberkel** [comment]
@stephencelis maybe time to get a new version out? 0.11?

**Comment by zackdh9** [comment]
Manually pointing to the master branch in cocoapods worked perfectly.
`  use_frameworks!
  pod 'SQLite.swift', :git => 'https://github.com/stephencelis/SQLite.swift'`

**Comment by jberkel** [comment]
#524
