### ISSUE TITLE
How to use db.prepare 

### ISSUE THREAD

**Issue by androidcn** [stephencelis/SQLite.swift#53]
for row in db.prepare("SELECT * FROM users") {
    println("id: \(row["id"]), email: \(row["email"])")
}
not work

**Comment by stephencelis** [comment]
Please see https://github.com/stephencelis/SQLite.swift/issues/18.

The basic gist: column names can collide so a dictionary is not the appropriate storage mechanism without the means to disambiguate. You can include the extension.
