### ISSUE TITLE
dyld: Library not loaded (only on device, using manual install)

### ISSUE THREAD

**Issue by adamek314** [stephencelis/SQLite.swift#536]
I get this error when trying to build and run on my iPhone 6 Plus device, but _not_ when I build and run on the iPhone 6 Plus simulator.

dyld: Library not loaded: @rpath/SQLite.framework/SQLite
  Referenced from: /var/containers/Bundle/Application/44FA4EA5-07F9-4AE3-BAED-036BE69970FA/Foody16.app/Foody16
  Reason: image not found

I am not using cocoa pods, I used the manual install approach.

I've done Product: Clean
I've done Product: Clean Build Folder

My iPhone 6 Plus is running 10.1 (14B72).
Xcode Version 8.1 (8B62)

Any ideas why it will run on the simulator, but not the phone?

**Comment by adamek314** [comment]
I've also tried deleting the app from the iPhone and reinstalling. No luck.

**Comment by adamek314** [comment]
Trying to install with cocoapods now.

ld: warning: directory not found for option '-F/Users/adamek/Library/Developer/Xcode/DerivedData/Foody16Workspace-copqncjgbsqltvfxdajhpldmxtuq/Build/Products/Debug-iphoneos/SQLite.swift'
ld: warning: directory not found for option '-F/Users/adamek/Library/Developer/Xcode/DerivedData/Foody16Workspace-copqncjgbsqltvfxdajhpldmxtuq/Build/Products/Debug-iphoneos/sqlite3'
ld: framework not found SQLite
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Will not build with cocoapods

**Comment by ryanholden8** [comment]
Can you verify step 1 here: https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#cocoapods

**Comment by rikenmon** [comment]
I know it is closed. I did have the same issue and resolved it by adding SQLite iOS (SQLite) to
target Dependencies. Now it works but with 3 compiler warnings

1:  (/Downloads/SQLite.swift-master 2/<module-includes>:1:1: Umbrella header for module 'SQLite' does not include header 'sqlite3.h'
2 (2 times from Connection.swift): /Downloads/SQLite.swift-master 2/SQLite/Core/Connection.swift:424:13: 'sqlite3_trace' is deprecated 

Does this mean manual install is no longer possible and one always need to use cocoapod if install goes to an actual device?

**Comment by jberkel** [comment]
@rikenmon I'm not sure, i think there's another step missing when you do a manual install. will investigate.

**Comment by rikenmon** [comment]
Yes, from my limited knowledge: it also should be added to build phase before it works.

**Comment by jberkel** [comment]
OK, verified: you'll need to make sure the framework is copied into the app bundle. There are two ways of doing this:

1. Application target, General tab, Embedded Binaries, Click "+", select SQLite.framework
2. Application target, Build phases tab, click "+" on top left, select "New Copy Files Phase", select Destination: "Frameworks", click "+", select SQLite.framework

**Comment by iNoles** [comment]
@jberkel I get same warning too. It looks like it is missing module map file for SQLite to import sqlite.h
