### ISSUE TITLE
Not work on real device, fine on simulator

### ISSUE THREAD

**Issue by aloveric** [stephencelis/SQLite.swift#538]
dyld: Library not loaded: @rpath/SQLite.framework/SQLite
  Referenced from: /var/mobile/Containers/Bundle/Application/086B446B-AB51-449B-955F-B421F72ACDBE/xxx.app/xxx

  Reason: image not found

![screen shot 2016-11-03 at 12 18 14 am](https://cloud.githubusercontent.com/assets/8198881/19937161/0ffd6620-a15b-11e6-981d-29f552484886.png)

**Comment by iNoles** [comment]
I do get this on the simulator by run the app in the Simulator, but not run it from Xcode.

**Comment by 1424667164** [comment]
do you fixed it?

**Comment by jberkel** [comment]
Dup of #536
