### ISSUE TITLE
Can't install 0.11.0 with as a dependency for pod for Swift 3

### ISSUE THREAD

**Issue by victorbarskov** [stephencelis/SQLite.swift#540]
The error: 

" None of your spec sources contain a spec satisfying the dependency: `SQLite.swift (~> 0.11.0)`." 

All done with Cocoa pods  1.1.1

**Comment by jberkel** [comment]
Have you run `pod repo update` recently?

**Comment by victorbarskov** [comment]
Oh, now it works, thanks a lot!
