### ISSUE TITLE
Regarding Database

### ISSUE THREAD

**Issue by mohamamdkalim** [stephencelis/SQLite.swift#542]
Hello,

I am new in Swift i am experienced in Objective C but now i want to make apps in Swift so kindly do help me little bit.

1) I have a db named "songs.sqlite"
--> i want to add the database in my project folder then i want to follow the basic wiki tutorial but i am unable to access the songs database and there tables successful can some on help me.

--> i want to add the fetch all the songsList table from songs database in my tableView ! kindly help me out. I am very thankful.

--> I want to fetch all the results in the dictonary of class array and then resultant will show upon the tableView. The class array is saved one time on the the singleton ! so required one time one.

Thanks.

**Comment by iNoles** [comment]
This is my SQLite Wrapper https://github.com/iNoles/iOS/blob/master/Noles%20Football/Noles%20Football/SQLiteDataStore.swift

**Comment by mohamamdkalim** [comment]
@iNoles sir first a fall thanks for the code but i want to know my database is songs.sqlite and you loaded .db format can i rename is it work ?

Thanks !

**Comment by iNoles** [comment]
@mohamamdkalim Yes.

**Comment by mohamamdkalim** [comment]
@iNoles Thanks so much ! can i ask few more question ?

**Comment by iNoles** [comment]
Sure.

**Comment by mohamamdkalim** [comment]
@iNoles 

1) What is the Extension of Connection function ?
2) Is you fetch all the data in SQLDataSource in Feed Class ?
3) Can you let me know how can i fetch the data in AppDelegate.swift using DataSource Class ! and access all the data in the Array of Class ! (Little bit code structure required to understand.

Thanks so much you are so great that's help me a lot !

Have a good Day !

**Comment by mohamamdkalim** [comment]
can you let me know how do you access this function:

`    static func findAll() -> [Feed] {
`

because when I was trying to send the Array of class in the parameter it was not accessible. Error throwing

```
var feedArray = feed()
        
        let dbMngr = DatabaseManager()
        
        feedArray = dbMngr.findAll()
```

not working

**Comment by mohamamdkalim** [comment]
Hi I have following issues:

       ```
 var feedArray: Array<feed>
        let dbMngr = DatabaseManager()
        feedArray = dbMngr.findAll()
        print("Feed Array: \(feedArray)")
```

But i get error in the following line in the var sharedInstance so i will remove the singleton in the databaseClass and also in the findAll function but i got the another error:

`for row in try! db.prepare(FeedTable.order(id.asc)){
`
//Thread Exec Error  👎

**Comment by iNoles** [comment]
1) Extension is like Objective-C's Category.
2) Feed is just a Swift class that I created to create an array for it. I load all values in certain columns into certain field in the Feed class. 

About your issue, it is extremely hard to know what is exactly went wrong.

**Comment by jberkel** [comment]
Please, use stackoverflow or similar websites to get help on how to use SQLite.swift. github should only be used to discuss bugs and features, not how to use the library.

**Comment by mohamamdkalim** [comment]
@jberkel you are very rude person you closed the thread infect the @iNoles is very good !! see your attitude where you take your attitude i really hate you MR !

**Comment by jberkel** [comment]
@mohamamdkalim I closed this issue since it is not a bug report. To ask general questions use a different forum.
