### ISSUE TITLE
Cursor subscript returning String leading to crash

### ISSUE THREAD

**Issue by vkaltchev** [stephencelis/SQLite.swift#543]
In the Cursor struct there's this subscript definition:

public subscript(idx: Int) -> String {
        return String(cString: UnsafePointer(sqlite3_column_text(handle, Int32(idx))))
}

The thing is sqlite3_column_text(handle, Int32(idx)) could return nil, thus leading to crash.
I did a very quick fix for my own project, but a proper fix is needed.

**Comment by jberkel** [comment]
Notice that the type signature is  `-> String` and not `-> String?` which would expect nils.

**Comment by vkaltchev** [comment]
Yes, I know, and it probably should be optional, once a proper fix is made.

The line that could cause a crash is this:
`return String(cString: UnsafePointer(sqlite3_column_text(handle, Int32(idx))))`
As `sqlite3_column_text(handle, Int32(idx))` returns nil, it turns into:
`String(cString: UnsafePointer(nil))`

It wouldn't crash this way:
```
    public subscript(idx: Int) -> String {
        let cString = sqlite3_column_text(handle, Int32(idx))
        return cString != nil ? String(cString: UnsafePointer(cString!)) : ""
    }
```

**Comment by jberkel** [comment]
Returning an empty string is not a good solution. Why don't you use the following method which returns an optional?

`public subscript(idx: Int) -> Binding?`

**Comment by vkaltchev** [comment]
I know it's not a good solution, and I am using this method `public subscript(idx: Int) -> Binding?`. The thing is `sqlite3_column_type(handle, Int32(idx))` returns `SQLITE_TEXT`, thus entering the corresponding switch case:
``
case SQLITE_TEXT:
            return self[idx] as String
``
Which calls `public subscript(idx: Int) -> String`, thus crashing.

**Comment by jberkel** [comment]
If you have a NULL value in your db it will just enter the `SQLITE_NULL` case and return nil.
