### ISSUE TITLE
FTS5 Query craches, while the same Query works with the same FTS4-VirtualTable

### ISSUE THREAD

**Issue by flandy84** [stephencelis/SQLite.swift#544]
Hi,

when using with fts5-virtualtables this type-safe query raises an error, while it works perfectly on fts4-virtualtables: (fatal error: 'try!' expression unexpectedly raised an error: unable to use function MATCH in the requested context)

`            let foundRows = Array(try db.prepare(
                emails.select(rowid, subject, body, rank).order(rank)            
                    .filter(
                        emails.match("wonder* was* check*") ||
                        body.match("alar*"))
                ))`
It seems FTS5-Support is not fully provided at this time? (expecially column-specific FTS-queries).
Do you plan to support FTS5 next time?

**Comment by jberkel** [comment]
The FTS5 query syntax is very similar and should just work in most cases. However with FTS5 you can't select columns on the left hand side any longer, the query needs to be rewritten as

```swift
emails.match("wonder* was* check*") || emails.match("body:alar*")
```

or even

```swift
emails.match("wonder* was* check* OR body:alar*")
```

See https://www.sqlite.org/fts5.html#_changes_to_select_statements_ for more information.

**Comment by flandy84** [comment]
thx.
