### ISSUE TITLE
Error Copying existing database

### ISSUE THREAD

**Issue by mohamamdkalim** [stephencelis/SQLite.swift#545]
Hello,

I am facing issues following please find the attachment

[AppDelegate.txt](https://github.com/stephencelis/SQLite.swift/files/592004/AppDelegate.txt)
[DatabaseManager.txt](https://github.com/stephencelis/SQLite.swift/files/592005/DatabaseManager.txt)

the issue is that when i check the simulator directory the database is there but there is zero kb data ! and i have a around 30+ recipe data i want to fetch all the data into the class but it's not fetching the data please it i am very thankful and let me know what i was doing wrong.

i just want to fetch the existing database i tried too much infect insert data is also not working... 

Database filename and extension is recipes.sqlite not .db i though that's not creating issue

Always throwing error in console either write or read:
**Error: Error Domain=SQLite.Result Code=0 "(null)"**

**Comment by mohamamdkalim** [comment]
can i don't uses existing sqlite database ! Please let me know ? because there is lot of data inside the database !

**Comment by jberkel** [comment]
Please use [stackoverflow](http://stackoverflow.com/questions/tagged/sqlite.swift) to ask general questions.

**Comment by mohamamdkalim** [comment]
@jberkel very rude attitude you have really insane at github ! Like you people of guys never bee happy and sleep well !
