### ISSUE TITLE
Spatialite?

### ISSUE THREAD

**Issue by nitrag** [stephencelis/SQLite.swift#547]
Do you think that it is **possible** to extend this for spatial/geo functions that Spatialite provides? I really like what you've done with this library and would love to see them married. 

https://aaronparecki.com/2015/05/21/11/

**Comment by nitrag** [comment]
@stephencelis @jberkel Thoughts? Is it possible? I'd put a OpenSource bounty on it if so.

**Comment by jberkel** [comment]
Seems to be a very specific use case. What exactly would you expect from SQLite.swift? 

Using CocoaPods you might be able to use the spatialite pod to get a version of SQLite.swift which has the extension enabled. Then you can use raw SQL to do whatever you need to do to make use of the extension, without SQLite.swift itself knowing about it.

**Comment by nitrag** [comment]
In all my googling I did not realize there was a spatialite pod already. Thanks for clue'ing me in.

> use the spatialite pod to get a version of SQLite.swift which has the extension enabled

This is where I don't know where to start. I'll try some things and report back.

Thanks

**Comment by jberkel** [comment]
You should be able to use:

``` ruby
pod 'SQLite.swift/standalone', '~> 0.11.0''
pod 'spatialite'
```

in your `Podfile`.

**Comment by davenquinn** [comment]
Is there a way to build this "standalone" version using Carthage?

**Comment by jberkel** [comment]
@davenquinn Not easily I'm afraid. Maybe you can create a project which pulls in SQLite and builds a framework named "CSQLite" or similar, and then use the right compiler flags on your main project to wire everything up.

**Comment by pkMinhas** [comment]
@jberkel, I tried modifying the Podfile as per your suggestion but this does not seem to have any effect on the sqlite version that SQLite.swift loads up. I am not able to run any spatial queries on the database. Any suggestions?

**Comment by jberkel** [comment]
@pkMinhas yes, looks like it's not so easy. I tried to pull in the spatialite pod but can't even get standard imports to work with swift (`import spatialite`). Maybe try something like https://github.com/andreacremaschi/SpatialDBKit ?
