### ISSUE TITLE
What about AUTOINCREMENT for integer keys??

### ISSUE THREAD

**Issue by reflectivist** [stephencelis/SQLite.swift#55]
One feature I rely on is the AUTOINCREMENT feature, and I can't find any support for that in the documentation. Is it there? I hate to have to create my table definition uses SQL strings just for that.

**Comment by stephencelis** [comment]
It's there: https://github.com/stephencelis/SQLite.swift/commit/798ee8eb9ba3f637031d0099bc792caac4a1a458

**Comment by reflectivist** [comment]
OK, after reading the AUTOINCREMENT description again, apparently it's got high overhead and is usually unnecessary and the default behavior is sufficient, probably for my needs.  I will try it out without autoincrement and then use it if necessary.  BTW: *GREAT* job on this API.  Really fantastic/prodigious, timely, convenient, complete, etc...  major kudos.

**Comment by stephencelis** [comment]
Yep, avoid AUTOINCREMENT unless you really need it!

And thanks! Glad you like it :)

**Comment by reflectivist** [comment]
Yes. Compared to ugly libsqlite and Objective C which I used to use, this is far cleaner, makes easier to read more maintainable code, and it actually works!

**Comment by ericcgu** [comment]
Stephen Celis is the man.

**Comment by stephencelis** [comment]
:blush:
