### ISSUE TITLE
[!] Unable to find a specification for 'SQLiteCipher.swift'.

### ISSUE THREAD

**Issue by abdallahnh** [stephencelis/SQLite.swift#551]
Hi @stephencelis 

please can you help me in this issue, i'm doing exactly what is mentioned in the readme but still stuck in this error.

Thanks.

**Comment by jberkel** [comment]
Don't forget to run `pod repo update`.

**Comment by leminhtuan2015** [comment]
I am sorry, I am a new dev. May you please help me how can I use SQLiteCipher.swift (https://github.com/stephencelis/SQLiteCipher.swift) 

My purpose is make a key for access my sqlite database, I want to prevent someone access to my database.

I am waiting for your help or any suggestion about this problem.

Thank sir so much.

**Comment by jberkel** [comment]
SQLiteCipher is deprecated, see the updated instructions:

https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#using-sqliteswift-with-sqlcipher
