### ISSUE TITLE
Querying FTS table with row but empty external content table crashes

### ISSUE THREAD

**Issue by DivineDominion** [stephencelis/SQLite.swift#554]
It's this line in `Query.get`: https://github.com/stephencelis/SQLite.swift/blob/e2633a40d66e9b84f306e99723e9f5a56e959f8f/SQLite/Typed/Query.swift#L1029

Setup:

* Fresh in-memory DB
* Content table `foo` created
* FTS table `foo_fts` created with ``.externalContent(foo)`
* Inserting directly into the FTS table without inserting into the content table, like: `connection.run(foo_fts.insert(docId <- 1, content <- "baz"))`

It crashes when accessing a value after a fetch:

```swift
let queryResults = try connection.prepare(foo_fts.match("irrelevant"))
if let match = queryResults.first? {
    print(match[content]) // crash
}
```

I'd expect an error to be thrown or `nil` or whatever, but this is a runtime condition the app cannot recover from if the setup of inserting new rows is wonky for whatever reason. Throwing subscripts aren't very sexy, either, though, so I'm not sure what to make of this except maybe use `preconditionFailure` instead of force unwrapping and indicate potential sources of the error.

**Comment by jberkel** [comment]
What is the actual crash / error message?

**Comment by DivineDominion** [comment]
Just a simple `EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)` -- in other words: force-unwrapped optional with `.none`

**Comment by jberkel** [comment]
How is content defined? The query will return null values since the docid  doesn't exist. So maybe you just need to declare it as optional. 

```swift 
let content = Expression<String?>
```

**Comment by DivineDominion** [comment]
Will try that. With some spare time, I'd like to review places with force-unwrapping and see if there are more defensive mechanisms available and create a PR for that. For example, if we expect a non-nil value here, guard-let-unwrap the value and provide a more detailed problem description.

**Comment by jberkel** [comment]
There might be places where force unwrapping happens but in case of column expression it really is the user's responsibility to declare potential nullable columns with optional types.

**Comment by DivineDominion** [comment]
Ok. So you're essentially against making the error description more detailed? 🤔

**Comment by jberkel** [comment]
From the docs: 

> Expression<T> column values are automatically unwrapped (we’ve made a promise to the compiler that they’ll never be NULL), while Expression<T?> values remain wrapped.

https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#iterating-and-accessing-values

In a way, that's just idiomatic Swift behaviour, the crash indicates a programming error. What kind of error message would you expect?

**Comment by DivineDominion** [comment]
Oh, I'd still crash! With a fatalError including explanation if possible, though, with this particular special case of FTS without external table data in mind.

**Comment by jberkel** [comment]
Hmm, would be weird it the Expression / row unwrapping code knew about those implementation details. As far as SQLite.swift is concerned, it's just a plain old query.

And as the sqlite docs say:

> The FTS4 module never writes to the content table, and writing to the content table does not affect the full-text index. It is the responsibility of the user to ensure that the content table and the full-text index are consistent. [...] When a users query on the FTS table requires a column value other than docid, FTS attempts to read the requested value from the corresponding column of the row in the content table with a rowid value equal to the current FTS docid. Or, if such a row cannot be found in the content table, a NULL value is used instead. 


To sum it up: you're fully responsible :-)

**Comment by DivineDominion** [comment]
Ok I give in 🤗
