### ISSUE TITLE
Adding functions to database

### ISSUE THREAD

**Issue by horcs** [stephencelis/SQLite.swift#56]
In my project I would like to add some custom sqlite function to my database supporting my queries (using: sqlite3_create_function(...)).
Is there currently any possibility to do that without changing SQLite's code?

**Comment by stephencelis** [comment]
Could you please let me know all of the function signatures of your custom functions? I have a WIP of this going but would like some examples to better support what people do.

My current work supports the following:

``` swift
import MobileCoreServices

let typeConformsTo: (String, Expression<String>) -> Expression<Bool> = (
    db.create(function: "UTTypeConformsTo") { (UTI: String, base: String) -> Bool in
        return UTTypeConformsTo(UTI, base) != 0
    }
)

let images = db["images"]
let type = Expression<String>("UTType")

let query = images.filter(typeConformsTo(kUTTypeJPEG, UTType))
```

I have to shim each type-safe permutation. Function input can be one of `Value`, `Value?`, `Expression<Value>`, and `Expression<Value?>`, and output can be `Value` or `Value?`, so this creates a large number of iterations to support different function signatures out of the box.

For example, all the different signatures a 2-argument function can take on:
```
Value, Value -> Value
Value, Value -> Value?
Value, Value? -> Value
Value, Value? -> Value?
Value?, Value -> Value
Value?, Value -> Value?
Value?, Value? -> Value
Value?, Value? -> Value?
Value, Expression<Value> -> Value
Value, Expression<Value> -> Value?
Value, Expression<Value?> -> Value
Value, Expression<Value?> -> Value?
Value?, Expression<Value> -> Value
Value?, Expression<Value> -> Value?
Value?, Expression<Value?> -> Value
Value?, Expression<Value?> -> Value?
Expression<Value>, Value -> Value
Expression<Value>, Value -> Value?
Expression<Value>, Value? -> Value
Expression<Value>, Value? -> Value?
Expression<Value?>, Value -> Value
Expression<Value?>, Value -> Value?
Expression<Value?>, Value? -> Value
Expression<Value?>, Value? -> Value?
Expression<Value>, Expression<Value> -> Value
Expression<Value>, Expression<Value> -> Value?
Expression<Value>, Expression<Value?> -> Value
Expression<Value>, Expression<Value?> -> Value?
Expression<Value?>, Expression<Value> -> Value
Expression<Value?>, Expression<Value> -> Value?
Expression<Value?>, Expression<Value?> -> Value
Expression<Value?>, Expression<Value?> -> Value?
```

You can imagine what supporting 3-argument functions would do.

**Comment by stephencelis** [comment]
Closing via https://github.com/stephencelis/SQLite.swift/commit/b63e359ddf889f01f6e0a88d36166b4c2647be6a
