### ISSUE TITLE
Null pointer when fetching an empty BLOB

### ISSUE THREAD

**Issue by brunokoga** [stephencelis/SQLite.swift#561]
According to the [SQLite Documentation](https://www.sqlite.org/c3ref/column_blob.html):

> The return value from sqlite3_column_blob() for a zero-length BLOB is a NULL pointer

But this is the way SQLite.swift handles BLOB (on `struct Cursor` in `Statements.swift`):

```swift
  public subscript(idx: Int) -> Blob {
        if let pointer = sqlite3_column_blob(handle, Int32(idx)) {
            let length = Int(sqlite3_column_bytes(handle, Int32(idx)))
            return Blob(bytes: pointer, length: length)
        } else {
            fatalError("sqlite3_column_blob returned NULL")
        }
    }
```

Shouldn't the `else` return an empty BLOB (`Blob(bytes: [])`) in this case?

**Comment by jberkel** [comment]
Good catch, just pushed a fix for this.
