### ISSUE TITLE
Android compatibility

### ISSUE THREAD

**Issue by philippmayrth** [stephencelis/SQLite.swift#565]
Hi,

Are there any plans to make this lib compatible with Swift running on Android?

Regards
Philipp

**Comment by jberkel** [comment]
There's Swift Package Manager support now (#560) which is a first step. Not sure what else is needed.

**Comment by philippmayrth** [comment]
Good to know thats at least not out of the scope for this project ;-)

**Comment by jberkel** [comment]
I think @zmeyc has done a lot work in this area already (getting SQLite.swift to work on Linux). See #315.

**Comment by flangel** [comment]
Hi, 

yes it does. See my article here. Swift Android compiler picks up the shared library. https://medium.com/@SCADE/extending-your-swift-on-android-project-with-c-libraries-560d3c452370

Best
Frank

**Comment by jberkel** [comment]
@flangel interesting, what license does SCADE use? it's not mentioned on the site (or hidden somewhere, and the ToS page is empty).

**Comment by flangel** [comment]
@jberkel Jan, sorry for the late reply. I don't want to abuse this thread, so I sent you an email.

**Comment by flangel** [comment]
Added Android support. Run on Android without any code change. Please see documentation here https://medium.com/p/9fdf02e235f2

**Comment by jberkel** [comment]
@flangel nice, just checked but I never received an email from you. i guess this can be closed then?

**Comment by jberkel** [comment]
Looks  like this is still supported: https://docs.scade.io/docs/data-persistency-with-sqliteswift
closing.
