### ISSUE TITLE
include module on ios project

### ISSUE THREAD

**Issue by mjason** [stephencelis/SQLite.swift#57]
i use this project in my project, is error: 

Undefined symbols for architecture arm64:
  "__TMaC6SQlite8Database", referenced from:
      _globalinit_func1 in Record.o
  "__TIFC6SQlite8DatabasecFMS0_FTGSqSS_8readonlySb_S0_A0_", referenced from:
      _globalinit_func1 in Record.o
  "__TFC6SQlite8DatabaseCfMS0_FTGSqSS_8readonlySb_S0_", referenced from:
      _globalinit_func1 in Record.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```swift
import Foundation
import SQlite

let path = NSSearchPathForDirectoriesInDomains(
    .DocumentDirectory, .UserDomainMask, true
).first as String

let db =  Database("\(path)/db.sqlite3")
```

**Comment by mjason** [comment]
i include version: eee33ef0e17005894f65bf85462298543ecc761e

**Comment by stephencelis** [comment]
Can you change SQlite to SQLite? (Capital L.) I think module imports are case sensitive.
