### ISSUE TITLE
Using SQLite.swift with SQLCipher

### ISSUE THREAD

**Issue by muvic08** [stephencelis/SQLite.swift#570]
I get the following error when try to add SQLCipher subspec on Xcode 8 in a Swift 3 project:

dyld: lazy symbol binding failed: Symbol not found: _sqlite3_key
  Referenced from: /Users/USER/Library/Developer/Xcode/DerivedData/myproject/Build/Products/Debug/myproject.app/Contents/MacOS/../Frameworks/SQLite.framework/Versions/A/SQLite
  Expected in: /usr/lib/libsqlite3.dylib

dyld: Symbol not found: _sqlite3_key
  Referenced from: /Users/USER/Library/Developer/Xcode/DerivedData/myproject/Build/Products/Debug/myproject.app/Contents/MacOS/../Frameworks/SQLite.framework/Versions/A/SQLite
  Expected in: /usr/lib/libsqlite3.dylib

I tried the solution from [zetetic](https://discuss.zetetic.net/t/important-advisory-sqlcipher-with-xcode-8-and-new-sdks/1688) to no avail.

**Comment by jberkel** [comment]
Looks like it's trying to link against the system libsqlite3.dylib. Have you done any other modifications in your project (manual linking for example?) Check 'Build Phases / Link Binary with Libraries'.

A simple  `pod 'SQLite.swift/SQLCipher', '~> 0.11.1'` should just work.

Interesting though that zetetic categorically is against the use of CocoaPods.

**Comment by muvic08** [comment]
Thank you @jberkel. I only have Pods_projectname.framework under 'Build Phases / Link Binary with Libraries'. I am building a MacOS (not an iOS) app, would that make a difference when it comes to how _sqlite3_key is bound?

**Comment by jberkel** [comment]
Should not make a difference. I've just tested it with a new OSX project from scratch and it compiled and linked without problems there.
Maybe you reference another pod which has a dependency to `libsqlite3`?

**Comment by muvic08** [comment]
I can connect to the sqlite3 database without a problem. It is only when I try to key or rekey the db that I get the error. 

            let db = try Connection("/path/db.sqlite3") // works
            try db.key("secret") // fails
            try db.rekey("mysecret") // fails

I got the following in my Podfile. Please lemme know if I am doing anything wrong because I am new to Cocoapods. 

  use_frameworks!

target 'SQLCipherTest' do
  use_frameworks!

  # Pods for SQLCipherTest
  pod 'SQLite.swift', '~> 0.11.1'
  pod 'SQLite.swift/SQLCipher', '~> 0.11.1'

  target 'SQLCipherTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SQLCipherTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

I tried the same thing in a different computer. Same error! Both using Xcode 8

**Comment by jberkel** [comment]
get rid of the first `pod 'SQLite.swift', '> 0.11.1'`, you only need to include it once, with subspec

**Comment by muvic08** [comment]
That was it! Thank you @jberkel
