### ISSUE TITLE
The filter method CAN be renamed to where

### ISSUE THREAD

**Issue by Evertt** [stephencelis/SQLite.swift#571]
First of all I want to say, what an awesome library. I love being able to communicate with an SQLite database in a type-safe way.

So let's get to the point. In the docs you say you called the query method used for the `WHERE` clause in a query `filter`, because `where` was a reserved name. iIf you write the function like this:

```swift
extension QueryType {
    public func `where`(_ predicate: Expression<Bool?>) -> Self {
        var query = self
        query.clauses.filters = query.clauses.filters.map { $0 && predicate } ?? predicate
        return query
    }
}
```

You can actually use it like: `users.where(id == 1)`.

**Comment by jberkel** [comment]
Thanks for the hint. My guess is that at the point the code was written the keyword quoting was not available in the particular version of Swift.

**Comment by nhunghuynhthihong** [comment]
@jberkel it is not single quote ' , it is `.

**Comment by jberkel** [comment]
@nhunghuynhthihong yes, I was just referring to "quoting" in a more general sense of the term.

**Comment by jberkel** [comment]
#572
