### ISSUE TITLE
No Package.swift

### ISSUE THREAD

**Issue by Evertt** [stephencelis/SQLite.swift#575]
I'm trying to install this package using swift package manager, but then I get:

`The package at '/Users/evert/Code/sqlitetest/Packages/SQLite.swift.git' has no Package.swift for the specific version: 0.11.1`

**Comment by iNoles** [comment]
@jberkel it is looking to git tag for versions.

**Comment by jberkel** [comment]
right, will release soon 0.11.2 soon. i think there's no way to pull in a head dependency with SPM.
