### ISSUE TITLE
SPM - Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by neoneye** [stephencelis/SQLite.swift#577]
I have made a [SQLite.swift fork](https://github.com/neoneye/SQLite.swift/tree/0.11.2) that I have tagged with 0.11.2, so that I can use it with SPM. I have not made any commits.

When I try to build, then I'm getting errors like this:

```
PROMPT> swift build
Cloning https://github.com/neoneye/SQLite.swift.git
HEAD is now at f6d7593 Merge pull request #572 from stephencelis/where-alias
Resolved version: 0.11.2
Compile SQLiteObjc SQLite-Bridging.m
Linking SQLiteObjc
Undefined symbols for architecture x86_64:
  "_sqlite3_bind_blob", referenced from:
      __SQLiteRegisterTokenizer in SQLite-Bridging.m.o
  "_sqlite3_bind_text", referenced from:
      __SQLiteRegisterTokenizer in SQLite-Bridging.m.o
  "_sqlite3_finalize", referenced from:
      __SQLiteRegisterTokenizer in SQLite-Bridging.m.o
  "_sqlite3_free", referenced from:
      ___SQLiteTokenizerDestroy in SQLite-Bridging.m.o
      ___SQLiteTokenizerClose in SQLite-Bridging.m.o
  "_sqlite3_malloc", referenced from:
      ___SQLiteTokenizerCreate in SQLite-Bridging.m.o
      ___SQLiteTokenizerOpen in SQLite-Bridging.m.o
  "_sqlite3_prepare_v2", referenced from:
      __SQLiteRegisterTokenizer in SQLite-Bridging.m.o
  "_sqlite3_step", referenced from:
      __SQLiteRegisterTokenizer in SQLite-Bridging.m.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: build had 1 command failures
error: exit(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/johndoe/MyServer/.build/debug.yaml

```

#  Package.swift 
```
import PackageDescription

let package = Package(
	name: "MyServer",
	targets: [],
	dependencies: [
		.Package(url: "https://github.com/PerfectlySoft/Perfect-HTTPServer.git", majorVersion: 2, minor: 0),
//		.Package(url: "https://github.com/stephencelis/SQLite.swift.git", majorVersion: 0)
		.Package(url: "https://github.com/neoneye/SQLite.swift.git", versions: Version(0,11,1)..<Version(0,11,.max))
    ]
)

```

# Setup

 * Xcode 8.1 (8B62)
 * macOS 10.12.1

**Comment by jberkel** [comment]
You need to pass in some linker flags, see the [docs](https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#swift-package-manager):

```sh
$ swift build -Xlinker -lsqlite3
``` 

Not sure if there's an easy way around that.

**Comment by neoneye** [comment]
This works.

Have a great day @jberkel

**Comment by neoneye** [comment]
@jberkel I think the linker flag problem has been solved in the [Perfect-sqlite3-support project](https://github.com/PerfectlySoft/Perfect-sqlite3-support/blob/master/Package.swift). Maybe useful?

**Comment by TimothyMDean** [comment]
It seems like this should be possible to avoid in SPM using the approach described in the [SPM documentation](https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#require-system-libraries) for depending on a system library. The last comment from @jberkel suggested that this limitation is by design, but reading the history of that SPM issue it seems to apply only to additional flags like `-fblocks`. It seems like simply linking to the sqlite3 system library should be possible without additional flags.
