### ISSUE TITLE
Example to update BLOB type column

### ISSUE THREAD

**Issue by nitishrana28** [stephencelis/SQLite.swift#580]
Could you share an example for updating BLOB type. I could not find one.
Here is what I am doing :

// ImageData data type is Data
let statement = try db.prepare("Update SpecialityModule SET ImageData = ? where ServerId = ?")
        try statement.run(module.ImageData as! Binding?, module.ServerId)

Error received on statement.run :

Could not cast value of type 'Foundation.Data' (0xd0fad8) to 'SQLite.Binding' (0x2bd6058).

**Comment by iNoles** [comment]
What happens if you remove as Binding?

**Comment by nitishrana28** [comment]
Complie time error of type casting.

**Comment by jberkel** [comment]
`Data` needs to be converted to `Blob` using `datatypeValue`:

`try statement.run(module.ImageData.datatypeValue, module.ServerId)`

Also see https://github.com/stephencelis/SQLite.swift/issues/142#issuecomment-268911949

**Comment by nitishrana28** [comment]
This saves the value as BLOB. So we can close this.
