### ISSUE TITLE
Sqlite migration handler

### ISSUE THREAD

**Issue by nitishrana28** [stephencelis/SQLite.swift#581]
May I know how are you handling Sqlite migration when app is updated on AppStore ? Since an update in app might feature change in Sqlite DB like addition/modification of new table, storing old data, etc.
Request you to share an example by code.

**Comment by jberkel** [comment]
☞ https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#migrations-and-schema-versioning
