### ISSUE TITLE
Using SQLite.swift with SQLCipher on a Manual Install

### ISSUE THREAD

**Issue by muvic08** [stephencelis/SQLite.swift#584]
Has anyone been able to do that?

**Comment by jberkel** [comment]
I think this should be possible via integrating and linking the individual component and compiling everything with `SQLITE_HAS_CODEC=1` and `-DSQLITE_SWIFT_SQLCIPHER`.

Since it's a nontrivial setup I'd like to avoid supporting this combination "officially" though.
