### ISSUE TITLE
Use of unresolved identifier

### ISSUE THREAD

**Issue by haukeschrills** [stephencelis/SQLite.swift#585]
In the documantation:
```

for user in try db.prepare(users) {
    print("id: \(user[id]), email: \(user[email]), name: \(user[name])")
    // id: 1, email: alice@mac.com, name: Optional("Alice")
}
// SELECT * FROM "users"
```
My code:

```
let tableSpieler = Table("spieler")
for sp in try! db.prepare(tableSpieler) {
  print("Vorname:  \(sp[vorname])")
}
```

I get the Error:  Use of unresoved identifier 'vorname'
I can't see what's wrong ?

**Comment by iNoles** [comment]
do you have vorname variables?

**Comment by haukeschrills** [comment]
Yes . when 
'''
print(sp) 
'''
I get 

Row(columnNames: ["\"geschlecht\"": 11, "\"punkte\"": 4, "\"TIMESTAMP\"": 9, "\"id\"": 0, "\"eingetreten\"": 3, "\"punkte_gesamt\"": 5, "\"nachname\"": 2, "\"aus\"": 6, "\"## vorname\"": 1, "\"kennwort\"": 8, "\"rang\"": 10, "\"aus_gesamt\"": 7], values: [Optional(1), Optional("Hauke"), Optional("Schrills"), Optional("2002-10-01"), Optional(29), Optional(232), Optional(6), Optional(811), Optional("gussy"), Optional("2016-12-18 19:33:15"), Optional(147.0), Optional("m")])

**Comment by jberkel** [comment]
see the declaration at https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#expressions

in your case you would need 
```swift
let vorname = Expression<String>("vorname")
```

**Comment by haukeschrills** [comment]
sure. I was wrong.

Not the name of the row, I need the variable

Thanks
