### ISSUE TITLE
sql int just can convert to swift.Int64 not to Swift.Int

### ISSUE THREAD

**Issue by shafaghi** [stephencelis/SQLite.swift#589]
convert int database field to swift Int return nil but convert to Int64 work correctly.
this just happen when i use raw string query.

table declaration:
CREATE TABLE groups (grGuid long UNIQUE, grName TEXT, grType int, grAccess long)

query:
prepare("select grGuid, grName, grType, grAccess from groups")

let x: item[2] as! Int -> return nil
but
let x: item[2] as! Int64 -> return number

alseo using expression of type int is work correctly if you use insert, select function(not raw string query)
let grType = Expression<Int>("grType")

**Comment by jberkel** [comment]
It has to be `Int64`, this is the type that SQLite uses internally.
