### ISSUE TITLE
Syntax error when insert a row.

### ISSUE THREAD

**Issue by bobzkobob** [stephencelis/SQLite.swift#59]
Hi,

I am using your framework to manage a database.
But I can't insert a row.  Just syntax error.  Here is my code.

func saveWeatherInfo(weatherInfo: WeatherInfo) {
        let weather_table = database!["weather"]
        let latitude = Expression<Double>("latitude")
        let longitude = Expression<Double>("longitude")
        let ob_time = Expression<String>("ob_time")
        let weather = Expression<String>("weather")
        let temperature = Expression<String>("temperature")
        let wind = Expression<String>("wind")
        let pressure = Expression<String>("pressure")
        let tide = Expression<String>("tide")
        let moonPhase = Expression<String>("moon_phase")
        
        let formatter = NSDateFormatter()
        formatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
        let timeString = formatter.stringFromDate(weatherInfo.time)
        
        // should insert weatherInfo object and syntax error on this line.
        weather_table.insert(values: tide <- "", moonPhase <- "")
    }

I already opened database and created a table with name "weather".
Please help me to compile and use this framework to insert my data.

Thanks.

**Comment by stephencelis** [comment]
Please read the docs on insert/update for how to disambiguate. A direct fix is to add `?` or `!` to the end of the insert line, or use `if`–`let`.

**Comment by stephencelis** [comment]
Tracking as a duplicate of https://github.com/stephencelis/SQLite.swift/issues/34
