### ISSUE TITLE
Ambiguous use of 'match'

### ISSUE THREAD

**Issue by rishi420** [stephencelis/SQLite.swift#590]
Hi,

Great repo. 

I was going through the documentation. In the `Full-text Search` part, I'm getting this compiler error on this line:

    let wonderfulEmails = emails.match("wonder*")  // ‼️ Ambiguous use of 'match'

I'm using Xcode 8.0 with pod 0.11.2. Other search option works alright. 

    let replies = emails.filter(subject.match("Re:*"))  // 👍 compiles ok.

Thanks
Warif

**Comment by getaaron** [comment]
There are 6 `match` functions:

    public func match(_ pattern: String) -> Expression<Bool>

    public func match(_ pattern: Expression<String>) -> Expression<Bool>

    public func match(_ pattern: Expression<String?>) -> Expression<Bool?> 

    public func match(_ pattern: String) -> QueryType

    public func match(_ pattern: Expression<String>) -> QueryType

    public func match(_ pattern: Expression<String?>) -> QueryType

In your second code sample, the compiler can infer your intended type.

If you want to call `match()` on a separate line you can just specify the type so it knows which function to execute. For example:

    let wonderfulEmails: QueryType = emails.match("wonder*")

**Comment by rishi420** [comment]
👍 
Added a pull request to change the doc
