### ISSUE TITLE
Database paths are type connection

### ISSUE THREAD

**Issue by Mopar440** [stephencelis/SQLite.swift#598]
How do you assign a connection type to a variable?

I have created a database and table in >>> func viewDidLoad. 
Let db = try Connection("\(path)/db.sqlite3")
Now i want to save a row in the IBAction of a button.
How do I access this opened table from the button action code?  Error complains  that db is an unresolved identifier, how do I use "db"which is type Connection elsewhere else in the code?  I was thinking I could assign it to a global variable but how do you do this?  You can't intialize it to type "string" even though printing "db" looks like a string. Do i have to reopen the table in my button code?  Thank you

**Comment by jlawton** [comment]
You may have to provide more specific code if I'm not understanding you (so forgive me if I'm completely off-base), but you should be able to use a `Connection` like any other class.

Your problem may be that you can't use `try` to assign to a global variable directly, so you can't just have a global of type `Connection`. It would have to be something like `Connection?`, and then you need code instantiating it somewhere else.

I don't really suggest just putting this logic in your view controller, or not having error handling, but as an example:

```swift
class ViewController {
    // Somewhere to store your connection
    private var _db: Connection?
    // Open your connection on first use
    var db: Connection? {
        if (!_db) {
            do {
                _db = try Connection("path/to/db")
            } catch {
                print("Error opening database: \(error)")
            }
        }
        return _db
    }
    // Use your connection
    @IBAction func doSomething(sender: UIButton) {
        guard let db = self.db else {
            return // Couldn't open database
        }
        db.scalar(users.count)
    }
}
```
