### ISSUE TITLE
Truncate Table

### ISSUE THREAD

**Issue by starsoheil2007** [stephencelis/SQLite.swift#599]
Hi
In sql we have 2 Options for clear a table. 
1 - delete all record : This will delete all the content of the table, not reseting the autoincremental id .

2 - truncate : This will reset the table i.e. all the auto incremental fields will be reset. 

 This library can do one way but i can't find second way in the documentation ?
How can do this ?

**Comment by jberkel** [comment]
Sqlite automatically does truncate optimization: http://sqlite.org/lang_delete.html

**Comment by jberkel** [comment]
actually, SQLite doesn't even have a truncate command. closing.
