### ISSUE TITLE
New Helper method - Check if table exists in DB

### ISSUE THREAD

**Issue by bassgzm** [stephencelis/SQLite.swift#6]
I would love to see a new helper method that would return a BOOL if the table name I pass it exists in the database or not.

**Comment by vineethvijayan** [comment]
@stephencelis 

The above code didn't work 

extension Database {
    func tableExists(tableName: String) -> Bool {
        let count:Int64 = DataManager.db.scalar(
            "SELECT EXISTS(SELECT name FROM sqlite_master WHERE name = ?)", tableName
        ) as! Int64
        if count>0{
            return true
        }
        else{
            return false
        }
    }
}

**Comment by stephencelis** [comment]
@vineethvijayan Need more context/information. Do you have an error message, etc.?

**Comment by vineethvijayan** [comment]
Yes, @stephencelis when I tried your code it was trying  ur code and it was trying to convert int64 to bool which was throwing an error, so just converted it in the above way. Hope it is correct(It worked for me).

**Comment by stephencelis** [comment]
@vineethvijayan Gotcha. You should be able to remove `DataManager.db.` to ensure `scalar` gets called on `self`.

**Comment by vineethvijayan** [comment]
@stephencelis Sorry about that I have a scalar variable DataManager.db which I use as a singleton object. actually you don't need it. Will update code. Thanks :)

**Comment by blkbam** [comment]
I have a use case for this.  In my app I'm building the database dynamically in code and keeping track of my own version in the database itself. In this way I don't always have the tables created up front and would need to know if an object exists prior to attempting to use it. 
With the absense of error handling in Swift, for now at least, if I try to access the table I get an exception "no such table"

**Comment by stephencelis** [comment]
@blkbam Have you looked into querying against the `sqlite_master` table for table data? Something like the following should work:

``` swift
func tableExists(tableName: String) {
    return db.scalar(
        "SELECT EXISTS (SELECT * FROM sqlite_master WHERE type = 'table' AND name = ?",
        tableName
    ) as! Int64 > 0
}
```

**Comment by blkbam** [comment]
@stephencelis I'm using something like that now to get me by. I just thought I would throw in my 2 cents on having it be a part of the library.
