### ISSUE TITLE
How do you close an open database or table

### ISSUE THREAD

**Issue by Mopar440** [stephencelis/SQLite.swift#602]
How do you close an open database? I looked in Index.md but didn't find it.  

How do you close a table?

Thank you

**Comment by nestserau** [comment]
See [`Connection::deinit`](https://github.com/stephencelis/SQLite.swift/blob/master/Sources/SQLite/Core/Connection.swift).

**Comment by Mopar440** [comment]
@Using Microsoft .MDB you can close a table so I thought there is an equivalent in SQLite.

In ViewController I have this code:

      import UIKit
      import SQLite

      class ViewController: UIViewController {
    

    @IBOutlet weak var cmdSave: UIButton!
    @IBOutlet weak var cmdClose: UIButton!
    
    
    private var dbs: Connection?
    let users = Table("users")
    let id = Expression<Int64>("id")
    let email = Expression<String>("email")
    let name = Expression<String?>("name")  //allow null
    
//--------------------------
    @IBAction func cmdRead(_ sender: AnyObject) {
 
        if sqlite3_close(dbs) != SQLITE_OK {
            print("error closing database")
        }
        
        dbs  = nil
    }
    
//-------------------------- 
      @IBAction func cmdClose(_ sender: AnyObject) {
 
        if sqlite3_close(dbs) != SQLITE_OK {
            print("error closing database")
        }
        
        dbs  = nil
    }
    
I have successfully installed Sqlite.swift from GitHub but ...
I have been able to successfu
I am getting 2 errors:  

unresolved identifier on 'SQLITE_OK'
unresolved identifier on 'sqlite3_close'

So I must not be importing a module correctly, how do I fix this?

**Comment by icoco** [comment]
sqlite3_close_v2  is ok, but sqlite3_close does not return SQLITE_OK

also, I feeling it can not free the connection
