### ISSUE TITLE
Dynamically generate SQLite modulemap

### ISSUE THREAD

**Issue by davedelong** [stephencelis/SQLite.swift#603]
(Related to #425)

I do not know how this would affect the CocoaPod setup, since I don't use CP, but I've found that I can avoid compilation errors with a hard-coded SQLite header path in the modulemap by dynamically generating it.

I put in a "Run Script" build phase that simply executes:

    cat <<EOT > "CocoaPods/module.modulemap"
    module CSQLite [system] {
        header "${SDKROOT}/usr/include/sqlite3.h"
        export *
    }
    EOT

And then I change the build setting to just search "CocoaPods" path for module files, instead of the SDK-specific folders.

**Comment by stephencelis** [comment]
Thanks, @davedelong! The reason we use a module map at all is because of CocoaPods (I much preferred [your project file solution](https://github.com/stephencelis/SQLite.swift/issues/163)), so we'd need to further investigate the CocoaPods requirements.

**Comment by davedelong** [comment]
Oh hey, look at that! I completely forgot about that approach. :)

**Comment by jberkel** [comment]
no longer relevant with Swift4/Xcode9
