### ISSUE TITLE
Xcode complains: "Umbrella header for module 'SQLite' does not include header 'sqlite3.h'

### ISSUE THREAD

**Issue by cwoloszynski** [stephencelis/SQLite.swift#607]
I am not using CocoaPods; just including SQLite.xcodeproj as a sub-project in my xcworkspace. 

I would like to figure out how to get rid of this warning message.  I have looked at the code and I cannot seem to find a way to address this.

Any suggestions?

**Comment by curtclifton** [comment]
I solved this locally by adding the following at the top of FTS4.swift (in the Extensions folder):

```swift
#if SQLITE_SWIFT_STANDALONE
    import sqlite3
#elseif COCOAPODS
    import CSQLite
#endif
```

I am also not using CocoaPods, so don't know whether this will break things there. I cribbed the code from Helpers.swift. If someone wants to verify that this works with CocoaPods to, I could put together a pull request.

**Comment by cwoloszynski** [comment]
I think you must have made other changes.  That change does not work for me.  Still the same error.

I even commented out the other block of imports but that didn't do it either....  Any chance you recall any other changes you made to make this warning go away?

#if SQLITE_SWIFT_STANDALONE
    import sqlite3
#elseif COCOAPODS
    import CSQLite
#endif

// #if SWIFT_PACKAGE
// import SQLiteObjc
// #endif

**Comment by curtclifton** [comment]
Shoot. I had some other local changes from experimenting, but didn't think they worked so backed them out. Now the error reappears on a clean build. I'll try to recreate the other changes.

**Comment by curtclifton** [comment]
The plot thickens. My other changes didn't have an effect. I was messing with module maps and imports, but after tracing the existing imports, those changes didn't add anything.

However, if I add the conditional imports I mentioned originally to whatever swift file Xcode is complaining about, like `CoreFunctions.swift` in the attached screenshot, then the warning goes away until the next clean build. On the next clean build it reappears for a different file.

<img width="636" alt="screen shot 2017-02-26 at 11 58 21 am" src="https://cloud.githubusercontent.com/assets/163466/23343118/1aa1c52e-fc1b-11e6-97bf-1f514eb349fa.png">

I'm just waving rubber chickens at the problem now, but I'm starting to suspect a bad diagnostic message from the compiler.

**Comment by curtclifton** [comment]
Argh. Those lines of code are also a red herring. After cycling through several files, I got the warning for a file that already had the conditional imports. *Removing* them from that file made the warning go away.

I'm going to put my chickens away and return to this with Xcode 8.3 later.

**Comment by mzbik** [comment]
For me, a clean build isn't quite clean. There's stuff left in /Users/<user>/Library/Developer/Xcode/DerivedData/SQLite-<some-random-text>

Deleting this and restarting XCode permanently fixed things.

YMMV

**Comment by jberkel** [comment]
#615

**Comment by jberkel** [comment]
Please try again with the current master branch

**Comment by curtclifton** [comment]
I updated to master, deleted the DerivedData folder, and re-built. Unfortunately, the same warnings still appear. This is with Xcode 8.2.1. I can try the latest 8.3 beta when I get to my other machine.

**Comment by jberkel** [comment]
I think you can ignore this warning. I'm not sure why Xcode complains, because the header is actually imported.

**Comment by curtclifton** [comment]
It works fine, but these are also the only warnings in my project and I'd prefer to build clean. That said, I'm pretty sure it's an Xcode bug.

**Comment by jberkel** [comment]
@curtclifton Please check if this is still a problem with 0.11.4

**Comment by curtclifton** [comment]
The warning is gone. Thanks!
