### ISSUE TITLE
malloc: *** error for object 0x179a08bc0: pointer being reallocated was not allocated *** set a breakpoint in malloc_error_break to debug

### ISSUE THREAD

**Issue by GRSource** [stephencelis/SQLite.swift#608]
let tableInfo = Array(try db!.prepare("PRAGMA table_info(\(name))"))

crash log:
malloc: *** error for object 0x179a08bc0: pointer being reallocated was not allocated
*** set a breakpoint in malloc_error_break to debug

**Comment by GRSource** [comment]
finally, crash position:
Statement.swift->sqlite3_prepare_v2(connection.handle, SQL, -1, &handle, nil)

**Comment by jberkel** [comment]
Can't reproduce. Do other queries work with the db?
