### ISSUE TITLE
Error when trying to build sqlite "Could not build Objective-C module CSQlite"

### ISSUE THREAD

**Issue by RogelioHIT** [stephencelis/SQLite.swift#609]
I'm having problems adding sqlite to my proyect, my podfile looks like this:

```
platform :ios, '9.0'
workspace 'KnotioniOS.xcworkspace'
xcodeproj 'KnotioniOS.xcodeproj'
use_frameworks!

target 'KnotioniOS' do
    pod 'SwiftyJSON', '~> 3.1.4'
    pod 'Alamofire', '~> 4.3'
    pod 'Alamofire-Synchronous', '~> 4.0'
    pod 'AlamofireImage', '~> 3.1'
    pod 'CVCalendar', '~> 1.4.1'
    pod 'DKImagePickerController'
    pod 'ReachabilitySwift', '~> 3'
    pod 'SSZipArchive', '1.2'
	pod 'lottie-ios'
    pod 'SQLite.swift', '~> 0.11.2'
end
```

And the error looks like this:
![captura de pantalla 2017-02-22 a las 5 54 16 p m](https://cloud.githubusercontent.com/assets/8886223/23238530/f589020c-f927-11e6-9e66-8f2d77e9496f.png)

I'm currently in the process to convert a project from swift 2.3 to 3.0, so i started updating the pods but this was the only one that i could't update, i tried to go back to prev version(0.10.1) but the error persists. I find [THIS](https://github.com/stephencelis/SQLite.swift/issues/120) issue and i followed the response of ehsan-black, i changed my Xcode to applications, i tried deleting derived data and cleaning the proyect but nothing works. I also tried with a clean project just with this pod, but the result was the following:
![captura de pantalla 2017-02-22 a las 5 23 20 p m](https://cloud.githubusercontent.com/assets/8886223/23238715/e9204a7e-f928-11e6-9519-eedb6aae87fa.png)

**Comment by RogelioHIT** [comment]
ok, so the error apparently was that i had two different Xcodes, not open, just installed, when i uninstalled the older (7.3.1), and just leave the 8.2 it worked.

**Comment by nestserau** [comment]
There is Close Issue button under the comment section for the author of the issue.

**Comment by RogelioHIT** [comment]
oh, thanks.
