### ISSUE TITLE
Throws this error message when app runs on iphone, works fine on simulator

### ISSUE THREAD

**Issue by nausho** [stephencelis/SQLite.swift#61]
Hi, I am receiving this error when running the app on device, work fine in simulator. Please advise.

fatal error: unable to open database file: file /Users/Downloads/SQLite.swift-master/SQLite Common/Database.swift, line 376
![error](https://cloud.githubusercontent.com/assets/10930626/6116819/b0277c42-b064-11e4-9926-29d311bf8ef9.jpg)

**Comment by stephencelis** [comment]
What does your code look like that's opening the database?

**Comment by stephencelis** [comment]
The issue is that the file URI you're passing does not point to a valid location in which a database can be found/created when on the device. Please see https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#connecting-to-a-database

**Comment by nausho** [comment]
Yes that was the issue, I corrected the path and now its working fine.

Thanks

<div>-------- Original message --------</div><div>From: Stephen Celis <notifications@github.com> </div><div>Date:02/09/2015  4:06 PM  (GMT-08:00) </div><div>To: "stephencelis/SQLite.swift" <SQLite.swift@noreply.github.com> </div><div>Cc: nausho <nausho@hotmail.com> </div><div>Subject: Re: [SQLite.swift] Throws this error message when app runs on iphone, works fine on simulator (#61) </div><div>
</div>
What does your code look like that's opening the database?

---

**Comment by frtncr** [comment]
Hi,
I have an existed sqlite3 db which I only execute select queries and the db file's location is "Users/frtncr/iOS_Workspace/PostaKodu/PostaKodu/postcode.sqlite3". I start calling the db like, 
let db = Database("Users/frtncr/iOS_Workspace/PostaKodu/PostaKodu/postcode.sqlite3")

By this configuration, I am able to execute the app on the simulator but the device. I get an error exactly @nausho have mentioned about.

Updated to swift 1.2, iOS 8.3 and also the SQLite.swift to the latest version.

@stephencelis Do you have any clue why I am getting the error or what I am missing?

**Comment by stephencelis** [comment]
@frtncr Please read the documentation, search Google, or open an issue on StackOverflow. You're dealing with the fact that your device does not have a file at that path.

**Comment by frtncr** [comment]
Thanks @stephencelis. Last one: As far as I understand the reason I m getting this error is that I have hardcoded the db file path so simulator can found it because it s in mac's file system. When I try to run the app on the device, the path which I have hardcoded can not be found. Right?

**Comment by stephencelis** [comment]
Right. You need to bundle it with the app or otherwise download it and save it to your app's sandbox.
