### ISSUE TITLE
Build error, unresolved identifier, Swift 3

### ISSUE THREAD

**Issue by Mopar440** [stephencelis/SQLite.swift#612]
I have successfully installed Sqlite.swift from GitHub and have
been able to successfully open the database and save a row...

Now I am attempting to include code to close the database but getting 2 build errors:

Unresolved identifier on 'SQLITE_OK'
Unresolved identifier on 'sqlite3_close'

It would have though adding the 'import SQLite' would import any code in the installed pod.
however I must not be importing some module correctly, how do I fix this?

Here is some of the code I have in ViewController:

  import UIKit
  import SQLite

  class ViewController: UIViewController {

@IBOutlet weak var cmdSave: UIButton!
@IBOutlet weak var cmdClose: UIButton!

private var dbs: Connection?
let users = Table("users")
let id = Expression<Int64>("id")
let email = Expression<String>("email")
let name = Expression<String?>("name")  //allow null
//--------------------------
@IBAction func cmdClose(_ sender: AnyObject) {

    if sqlite3_close(dbs) != SQLITE_OK {
        print("error closing database")
    }
    
    dbs  = nil
}

**Comment by Mopar440** [comment]
I added  'libsqlite3.dylib'   >>> in Build Phases >>> Link Binaries with Libraries >>> Add Other >>>. Ctrl Shift G >>> /usr/lib/  

As recommended in my other post but it did not correct the problem :(

**Comment by jberkel** [comment]
You'll most likely need a [bridging  header](http://www.learnswiftonline.com/getting-started/adding-swift-bridging-header/) with
```objc
#import "sqlite3.h"
```

in it.

**Comment by jberkel** [comment]
inactive
