### ISSUE TITLE
Xcode 8.2.1 Swift compiler error

### ISSUE THREAD

**Issue by jianzhi2010** [stephencelis/SQLite.swift#613]
<img width="258" alt="2017-03-05 10 45 53" src="https://cloud.githubusercontent.com/assets/5894473/23588253/b4d11084-01f5-11e7-93ed-be43fad217dd.png">
I download the project, and try to  install SQLite.swift as an Xcode sub-project.
But build fail, what should I do?

**Comment by zackdh9** [comment]
having the same issue

**Comment by bulbuliator** [comment]
Installing standalone subspec resolved the issue for me. Follow this link:
https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#requiring-a-specific-version-of-sqlite

**Comment by jberkel** [comment]
make sure your Xcode is installed in the default location, see step 1 here:
https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#cocoapods

**Comment by jianzhi2010** [comment]
@bulbuliator , @jberkel Thanks! 
I solve the problem by installing Xcode in the default location.

**Comment by zackdh9** [comment]
@jberkel It would be helpful if the step one under manual installation was the same as the cocoa pods one.  I'm curious, why is this a requirement?

**Comment by jberkel** [comment]
@zackdh9 it no longer is – see #615

**Comment by dearbar** [comment]
thanks @jberkel  @bulbuliator . I find the problem because I change my xcode name.
