### ISSUE TITLE
Inner Join fail, ambiguous colum

### ISSUE THREAD

**Issue by LuizFelipeAP** [stephencelis/SQLite.swift#618]
The problem: fatal error: ambiguous column '"ACTIVE"' (please disambiguate: ["\"Country\".\"ACTIVE\"", "\"City\".\"ACTIVE\""]): file /Users/myuser/Documents/Projetos/Mark IX/TwoBillion/Carthage/Checkouts/SQLite.swift/Sources/SQLite/Typed/Query.swift, line 1058

Above is the LOG I receive when I try to make a inner join.

I have a table called **City(id_city, name, id_country, active)**, and a have another table called 
**Country(id_country, name, active)**.

So I frist try this code:  `let cityQuery = City.table.join(.inner, Country.table, on: City.ColumnName.idCountry == Country.ColumnName.idCountry)
`

And The log says please disambiguate. So I read and try column namespacing: `
let query = City.table.select(City.table[*],
			                              Country.table[Country.ColumnName.idCountry],
			                              Country.table[Country.ColumnName.name],
			                              Country.table[Country.ColumnName.active]).join(Country.table, on: City.ColumnName.idCountry == Country.ColumnName.idCountry)`

And the same error occurs.

If somebody already run in this same error our can help me I thank you.

Thanks already.

**Comment by LuizFelipeAP** [comment]
By now the only solution I find was rename the columns, like City_active and Country_Active.
I want a "better solution" if possible because this one seems a little hack.

**Comment by andre991** [comment]
I have the some problem. :/

**Comment by jsi7iv** [comment]
Your statement looks pretty good; however, if the column names are the same, you need to reference the columns in your join also.

For example 
```
City.table.select(City.table[*], Country.table[Country.ColumnName.idCountry], 
                            Country.table[Country.ColumnName.name], 
                            Country.table[Country.ColumnName.active])
      .join(Country.table, on: City.table[City.ColumnName.idCountry] == Country.table[Country.ColumnName.idCountry])
```

**Comment by DavidSouthgate** [comment]
See https://github.com/stephencelis/SQLite.swift/blob/89d16192bb73bf179c08c30227fbd9e52be6bf32/Documentation/Index.md#column-namespacing under "Column Namespacing" for how to prevent ambiguous colums

**Comment by rafaelclaycon** [comment]
ghost's answer helped me. The docs didn't, really.
