### ISSUE TITLE
Build failed with GRDB

### ISSUE THREAD

**Issue by ibadcool** [stephencelis/SQLite.swift#619]
@stephencelis  hi, I got a trouble, need your help.
I use groue/GRDB.swift and GodEye in my project, GodEye dependence your SQLite.swift. Xcode version is 8.3. I created a new project to test it, and podfile: 

pod 'GRDB.swift', :git => 'https://github.com/groue/GRDB.swift.git', :branch => 'Xcode8.3beta'
pod 'SQLite.swift'

then I got an error when build: 
Lexical or Preprocessor Issue
  'sqlite3.h' file not found
      fts3_tokenizer.h
      In file included from /Users/sunny/Desktop/TestProject/Pods/SQLite.swift/Sources/SQLiteObjc/SQLite-Bridging.m:26:9: In file included from /Users/Sunny/Desktop/TestProject/Pods/SQLite.swift/Sources/SQLiteObjc/SQLite-Bridging.m:26:

When I deleted GRDB, build succeeded. But I have to use GRDB, what should I do ?

**Comment by jberkel** [comment]
please use stackoverflow
