### ISSUE TITLE
xcode 8.3 - warnings

### ISSUE THREAD

**Issue by gfoldv** [stephencelis/SQLite.swift#621]
Compiling on Xcode 8.3 gives tons of warnings. Especially for the SQLCipher project. Is there a way to silence these warnings and put it into the SQLite.swift.podspec?

**Comment by ldrr** [comment]
If you only want to silence these warnings you can add the option `inhibit_warnings` to your podfile.

```
pod 'SQLite.swift/standalone', :inhibit_warnings => true
```

But that's definitely not the solution, there is a reason for this warnings. So +1 for fixing them.

**Comment by smhk** [comment]
Many of the warnings seem to be just from "warning: '+=' is deprecated"

**Comment by gfoldv** [comment]
I see 3 issued from the SQLite.swift and 95 issues in the accompanied SQLCipher.
`pod 'SQLite.swift/SQLCipher', '~> 0.11.2'`

**Comment by jberkel** [comment]
I'll have a look later. A new release is due anyway...

**Comment by jberkel** [comment]
Fixed warnings and released as 0.11.3.
