### ISSUE TITLE
Updating to version 10.3 makes SQLCipher have macro issues

### ISSUE THREAD

**Issue by DarkInnocence** [stephencelis/SQLite.swift#623]
I am using pod 'SQLite.swift/SQLCipher', '~> 0.11.3'. However, after the recent update my project has 95 SQLCipher issues. Please can anybody help me resolve this. 
![screen shot 2017-03-30 at 5 59 15 pm](https://cloud.githubusercontent.com/assets/26249846/24504143/b05889ca-1572-11e7-9071-f9f0e173377a.png)

**Comment by jberkel** [comment]
SQLCipher is a separate project. Please report the issue there. https://github.com/sqlcipher/sqlcipher
