### ISSUE TITLE
command to create database

### ISSUE THREAD

**Issue by openmotion** [stephencelis/SQLite.swift#624]
hello 
what is the command to create database file ?
because i have the error : unable to open database file (code 14)
thanks

**Comment by Coupz** [comment]
I've worked a while on that and solved it with the following code:

`
    // MARK: FIRST INITIALIZER
    func firstInitialization() {
        //print(Constants.Database.databaseFilePath)
        let fileManager = FileManager.default
        if fileManager.fileExists(atPath: Constants.Database.databaseFilePath) {
            //print("database file exists")
        } else {
            //print("database file doesnt exist. creating now")
            try! database.prepare(createSystemTableStatement).run()
        }
    }
`

The databaseFilePath is
`static let databaseFilePath = "\(NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0])/\(databaseFileName)"`

databaseFileName is like "mydatabase.db".

Don't know if it's the correct solution, that's how it worked for me.
