### ISSUE TITLE
Now, how do I use SQLite executing a SQL statement?(0.11.2)

### ISSUE THREAD

**Issue by yangxincai** [stephencelis/SQLite.swift#626]
The sample can't perform in the document
i use:
#   try db.prepare(query: QueryType)  #
I need  a example available,thanks

**Comment by Coupz** [comment]
You can find the example to run an SQL statement under the "Usage" part of the README.

```swift
let stmt = try db.prepare("INSERT INTO users (email) VALUES (?)")
for email in ["betty@icloud.com", "cathy@icloud.com"] {
    try stmt.run(email)
}
```

So after preparing the statement with `try db.prepare(SQLStatement)` you need to run the statement with `try statement.run()`

**Comment by yangxincai** [comment]
Thank you for your answer，I understand and solved the problem

**Comment by Coupz** [comment]
Glad that I could help. I'm not a contributor or so, just another user which had the same issue and solved it.
