### ISSUE TITLE
Fix sqlite3_trace is deprecated warning

### ISSUE THREAD

**Issue by mohamede1945** [stephencelis/SQLite.swift#627]
With the latest version of 0.11.3 from cocoapods and Xcode 8.3.1, I'm getting a deprecation warning for the c function `sqlite3_trace`.  Going to the docs, it recommends using `sqlite3_trace_v2` instead.

**Comment by jberkel** [comment]
It's a harmless warning. To make it disappear you'll have to set your deployment target to iOS 10.0.

**Comment by mohamede1945** [comment]
First of all, thank you for this great library. It's really amazing!

My deployment target is 9.0, which I think most of the apps are always supporting at least one major version back, so it would be nice to have this fixed. 

As a workaround, I'm using `:inhibit_warnings => true` in my podfile.

**Comment by jberkel** [comment]
If you target an older platform the deprecated method will have to be called in any case (the `_v2` only exists on 10.x). However in theory this shouldn't issue a warning. I think this stems from the fact that the deprecation is done via 

```
__attribute__((deprecated))
```

and not with the standard `@available` attribute.

**Comment by mohamede1945** [comment]
Oh, I see your point.

**Comment by Ivan-Cantarino** [comment]
I'm targeting to iOS 10+ and it still shows the warning of deprecation, which I don't give much attention since it will be called anyway since as @jberkel said it's not a `@available` check

**Comment by zhangchunyu2016** [comment]
iOS 10+ and it still shows the warning...

**Comment by zhangchunyu2016** [comment]
If you're using Pod , you can add ` inhibit_all_warnings!` to the Podfile file to ignore all of the warnings in the pod project.

**Comment by afern247** [comment]
iOS 13+ and it still shows the warning...

**Comment by bishrant** [comment]
iOS 14 with iOS13.1 as target deployment level is also showing the same warning.
![image](https://user-images.githubusercontent.com/4143738/94731312-2dfd0b00-032a-11eb-9689-855a1239e95e.png)

**Comment by afern247** [comment]
> iOS 14 with iOS13.1 as target deployment level is also showing the same warning.
> ![image](https://user-images.githubusercontent.com/4143738/94731312-2dfd0b00-032a-11eb-9689-855a1239e95e.png)

Bro I just moved away from this lol Use Core Data and that's it.

**Comment by Kashif-Rabbani** [comment]
@afern247 what do you mean by Core Data?

**Comment by jberkel** [comment]
fixed in 0.13.0

**Comment by afern247** [comment]
> @afern247 what do you mean by Core Data?

Core Data is the Apple Way of storing data. I also moved away from it lol I didn't like it.
