### ISSUE TITLE
sqlite3.h file not found

### ISSUE THREAD

**Issue by GabbiOS** [stephencelis/SQLite.swift#629]
I have installed SQLite through cocoa pods. I am facing an error in :
SQLite.swift>>standard>>fts3_tokenizer.h

#import "sqlite3.h" file not found

**Comment by quangdog** [comment]
I've just run into this as well: 

I created a brand new project in XCode.
pod init on the project directory
Added sqlite.swift as well as SQLCipher to the podfile
pod-install

Opened the project .xcworkspace
Pressed run

Tried adding the sqlite3 libraries as dependencies to the workspace, but no joy.  

Help?

**Comment by GabbiOS** [comment]
Ok I found my solution. I was using SQLite with GRDB. 
I removed both of them & then installed them again & it worked..

**Comment by Nahatakyan** [comment]
I have the same error.

**Comment by Nahatakyan** [comment]
Reinstalling pods does not help. Any other ideas?
