### ISSUE TITLE
Long Expressions

### ISSUE THREAD

**Issue by santsys** [stephencelis/SQLite.swift#63]
If you create a very long insert/update expression, it causes xCode to fail (xCode issue).

If you open up the private statement to pass a [Setter] array, in the case of the insert, it would make it so that setters could be built in a manner that better supports Swift and long expressions...

Here is an example of what fails:

table.insert(StudentColumns.PermanentID <- json["PermanentID"].stringValue, StudentColumns.SchoolCode <- json["SchoolCode"].intValue, StudentColumns.StudentNumber <- json["StudentNumber"].intValue, StudentColumns.StateStudentID <- json["StateStudentID"].stringValue, StudentColumns.LastName <- json["LastName"].stringValue, StudentColumns.FirstName <- json["FirstName"].stringValue, StudentColumns.MiddleName <- json["MiddleName"].stringValue, StudentColumns.LastNameAlias <- json["LastNameAlias"].stringValue, StudentColumns.FirstNameAlias <- json["FirstNameAlias"].stringValue, StudentColumns.MiddleNameAlias <- json["MiddleNameAlias"].stringValue, StudentColumns.Sex <- json["Sex"].stringValue, StudentColumns.Grade <- json["Grade"].intValue, StudentColumns.Birthdate <- birthdate, StudentColumns.ParentGuardianName <- json["ParentGuardianName"].stringValue, StudentColumns.HomePhone <- json["HomePhone"].stringValue, StudentColumns.StudentMobilePhone <- json["StudentMobilePhone"].stringValue, StudentColumns.MailingAddress <- json["MailingAddress"].stringValue, StudentColumns.MailingAddressCity <- json["MailingAddressCity"].stringValue, StudentColumns.MailingAddressState <- json["MailingAddressState"].stringValue, StudentColumns.MailingAddressZipCode <- json["MailingAddressZipCode"].stringValue, StudentColumns.ResidenceAddress <- json["ResidenceAddress"].stringValue, StudentColumns.ResidenceAddressCity <- json["ResidenceAddressCity"].stringValue, StudentColumns.ResidenceAddressState <- json["ResidenceAddressState"].stringValue, StudentColumns.ResidenceAddressZipCode <- json["ResidenceAddressZipCode"].stringValue, StudentColumns.EthnicityCode <- json["EthnicityCode"].stringValue,StudentColumns.RaceCode1 <- json["RaceCode1"].stringValue, StudentColumns.RaceCode2 <- json["RaceCode2"].stringValue, StudentColumns.RaceCode3 <- json["RaceCode3"].stringValue, StudentColumns.RaceCode4 <- json["RaceCode4"].stringValue, StudentColumns.RaceCode5 <- json["RaceCode5"].stringValue, StudentColumns.SchoolEnterDate <- schoolEnterDate, StudentColumns.SchoolLeaveDate <- schoolLeaveDate, StudentColumns.DistrictEnterDate <- districtEnterDate, StudentColumns.TeacherNumber <- json["TeacherNumber"].stringValue, StudentColumns.Track <- json["Track"].stringValue, StudentColumns.LockerNumber <- json["LockerNumber"].stringValue, StudentColumns.ParentEmailAddress <- json["ParentEmailAddress"].stringValue, StudentColumns.StudentEmailAddress <- json["StudentEmailAddress"].stringValue, StudentColumns.NetworkLoginID <- json["NetworkLoginID"].stringValue, StudentColumns.AtRiskPoints <- json["AtRiskPoints"].stringValue)!;

To make something that i think will work, opening up the following code will give additional options:

private func insert(values: [Setter]) -> (ID: Int?, statement: Statement) {
        let statement = insertStatement(values).run()
        return (statement.failed ? nil : database.lastID, statement)
    }

Making that public would mean you can build an array of setters and pass them to the insert statement.

var parms: [Setter] = [];
parms.append(StudentColumns.PermanentID <- json["PermanentID"].stringValue);
parms.append(StudentColumns.SchoolCode <- json["SchoolCode"].intValue);
			
let resp = table.insert(parms).ID!;

Is there a better method that i'm missing?

Thank you!

**Comment by stephencelis** [comment]
@santsys That function has already been made public. Please pull the latest code.

See: https://github.com/stephencelis/SQLite.swift/pull/31

**Comment by santsys** [comment]
Awesome! Thanks.

**Comment by stephencelis** [comment]
The following would be a nice alternative syntax:

``` swift
let user = Setters() // HashLiteralConvertible
user[name] = "Alice"
db.insert(user)
```

I haven't had time to explore the option, though.

**Comment by santsys** [comment]
Agreed! That would make for a nice syntax as well.
