### ISSUE TITLE
Using cocoapods import <pod 'SQLite.swift', '~> 0.11.2'>  ，Contribute to project an error and cannot run

### ISSUE THREAD

**Issue by caoyunxiao** [stephencelis/SQLite.swift#633]
Showing Recent Messages
CompileSwift normal arm64 /Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/SQLite.swift/Sources/SQLite/Typed/AggregateFunctions.swift
    cd /Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods
    /Applications/Xcode8.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c -primary-file /Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/SQLite.swift/Sources/SQLite/Typed/AggregateFunctions.swift /Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/SQLite.swift/Sources/SQLite/Core/Blob.swift /Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/SQLite.swift/Sources/SQLite/Typed/Collation.swift /Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/SQLite.swift/Sources/SQLite/Core/Connection.swift /Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/SQLite.swift/Sources/SQLite/Typed/CoreFunctions.swift /Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/SQLite.swift/Sources/SQLite/Typed/CustomFunctions.swift /Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/SQLite.swift/Sources/SQLite/Typed/Expression.swift /Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/SQLite.swift/Sources/SQLite/Foundation.swift /Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/SQLite.swift/Sources/SQLite/Extensions/FTS4.swift /Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/SQLite.swift/Sources/SQLite/Extensions/FTS5.swift /Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/SQLite.swift/Sources/SQLite/Helpers.swift /Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/SQLite.swift/Sources/SQLite/Typed/Operators.swift /Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/SQLite.swift/Sources/SQLite/Typed/Query.swift /Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/SQLite.swift/Sources/SQLite/Extensions/RTree.swift /Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/SQLite.swift/Sources/SQLite/Typed/Schema.swift /Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/SQLite.swift/Sources/SQLite/Typed/Setter.swift /Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/SQLite.swift/Sources/SQLite/Core/Statement.swift /Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/SQLite.swift/Sources/SQLite/Core/Value.swift -target arm64-apple-ios8.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode8.2.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk -I /Users/caoyunxiao/Library/Developer/Xcode/DerivedData/CStoreEdu-iOS-bpbhzgoutpptkffkanmzlbjfbafi/Build/Products/Debug-iphoneos/SQLite.swift -I /Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/SQLite.swift/CocoaPods/iphoneos -F /Users/caoyunxiao/Library/Developer/Xcode/DerivedData/CStoreEdu-iOS-bpbhzgoutpptkffkanmzlbjfbafi/Build/Products/Debug-iphoneos/SQLite.swift -enable-testing -g -import-underlying-module -module-cache-path /Users/caoyunxiao/Library/Developer/Xcode/DerivedData/ModuleCache -D COCOAPODS -serialize-debugging-options -Xcc -I/Users/caoyunxiao/Library/Developer/Xcode/DerivedData/CStoreEdu-iOS-bpbhzgoutpptkffkanmzlbjfbafi/Build/Intermediates/Pods.build/Debug-iphoneos/SQLite.swift.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/caoyunxiao/Library/Developer/Xcode/DerivedData/CStoreEdu-iOS-bpbhzgoutpptkffkanmzlbjfbafi/Build/Intermediates/Pods.build/Debug-iphoneos/SQLite.swift.build/SQLite-generated-files.hmap -Xcc -I/Users/caoyunxiao/Library/Developer/Xcode/DerivedData/CStoreEdu-iOS-bpbhzgoutpptkffkanmzlbjfbafi/Build/Intermediates/Pods.build/Debug-iphoneos/SQLite.swift.build/SQLite-own-target-headers.hmap -Xcc -I/Users/caoyunxiao/Library/Developer/Xcode/DerivedData/CStoreEdu-iOS-bpbhzgoutpptkffkanmzlbjfbafi/Build/Intermediates/Pods.build/Debug-iphoneos/SQLite.swift.build/SQLite-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/caoyunxiao/Library/Developer/Xcode/DerivedData/CStoreEdu-iOS-bpbhzgoutpptkffkanmzlbjfbafi/Build/Intermediates/Pods.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/caoyunxiao/Library/Developer/Xcode/DerivedData/CStoreEdu-iOS-bpbhzgoutpptkffkanmzlbjfbafi/Build/Intermediates/Pods.build/Debug-iphoneos/SQLite.swift.build/SQLite-project-headers.hmap -Xcc -I/Users/caoyunxiao/Library/Developer/Xcode/DerivedData/CStoreEdu-iOS-bpbhzgoutpptkffkanmzlbjfbafi/Build/Products/Debug-iphoneos/SQLite.swift/include -Xcc -I/Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/Headers/Private -Xcc -I/Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/Headers/Public -Xcc -I/Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/Headers/Public/JCore -Xcc -I/Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/Headers/Public/JPush -Xcc -I/Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods/Headers/Public/UMengAnalytics-NO-IDFA -Xcc -I/Users/caoyunxiao/Library/Developer/Xcode/DerivedData/CStoreEdu-iOS-bpbhzgoutpptkffkanmzlbjfbafi/Build/Intermediates/Pods.build/Debug-iphoneos/SQLite.swift.build/DerivedSources/arm64 -Xcc -I/Users/caoyunxiao/Library/Developer/Xcode/DerivedData/CStoreEdu-iOS-bpbhzgoutpptkffkanmzlbjfbafi/Build/Intermediates/Pods.build/Debug-iphoneos/SQLite.swift.build/DerivedSources -Xcc -DPOD_CONFIGURATION_DEBUG=1 -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -Xcc -ivfsoverlay -Xcc /Users/caoyunxiao/Library/Developer/Xcode/DerivedData/CStoreEdu-iOS-bpbhzgoutpptkffkanmzlbjfbafi/Build/Intermediates/Pods.build/Debug-iphoneos/SQLite.swift.build/unextended-module-overlay.yaml -Xcc -working-directory/Users/caoyunxiao/Desktop/CStoreEdu-iOS/CStoreEdu-iOS/Pods -emit-module-doc-path /Users/caoyunxiao/Library/Developer/Xcode/DerivedData/CStoreEdu-iOS-bpbhzgoutpptkffkanmzlbjfbafi/Build/Intermediates/Pods.build/Debug-iphoneos/SQLite.swift.build/Objects-normal/arm64/AggregateFunctions~partial.swiftdoc -Onone -module-name SQLite -emit-module-path /Users/caoyunxiao/Library/Developer/Xcode/DerivedData/CStoreEdu-iOS-bpbhzgoutpptkffkanmzlbjfbafi/Build/Intermediates/Pods.build/Debug-iphoneos/SQLite.swift.build/Objects-normal/arm64/AggregateFunctions~partial.swiftmodule -serialize-diagnostics-path /Users/caoyunxiao/Library/Developer/Xcode/DerivedData/CStoreEdu-iOS-bpbhzgoutpptkffkanmzlbjfbafi/Build/Intermediates/Pods.build/Debug-iphoneos/SQLite.swift.build/Objects-normal/arm64/AggregateFunctions.dia -emit-dependencies-path /Users/caoyunxiao/Library/Developer/Xcode/DerivedData/CStoreEdu-iOS-bpbhzgoutpptkffkanmzlbjfbafi/Build/Intermediates/Pods.build/Debug-iphoneos/SQLite.swift.build/Objects-normal/arm64/AggregateFunctions.d -emit-reference-dependencies-path /Users/caoyunxiao/Library/Developer/Xcode/DerivedData/CStoreEdu-iOS-bpbhzgoutpptkffkanmzlbjfbafi/Build/Intermediates/Pods.build/Debug-iphoneos/SQLite.swift.build/Objects-normal/arm64/AggregateFunctions.swiftdeps -o /Users/caoyunxiao/Library/Developer/Xcode/DerivedData/CStoreEdu-iOS-bpbhzgoutpptkffkanmzlbjfbafi/Build/Intermediates/Pods.build/Debug-iphoneos/SQLite.swift.build/Objects-normal/arm64/AggregateFunctions.o -embed-bitcode-marker

0  swift                    0x00000001115503ad PrintStackTraceSignalHandler(void*) + 45
1  swift                    0x000000011154fb56 SignalHandler(int) + 790
2  libsystem_platform.dylib 0x00007fffaec06b3a _sigtramp + 26
3  libsystem_platform.dylib 0x0000700005b6af80 _sigtramp + 1458979936
4  swift                    0x000000010ec24196 clang::Preprocessor::MacroState::getModuleInfo(clang::Preprocessor&, clang::IdentifierInfo const*) const + 198
5  swift                    0x000000010ec23eba clang::Preprocessor::getMacroDefinition(clang::IdentifierInfo const*) + 330
6  swift                    0x00000001101b8a7b clang::Preprocessor::HandleIdentifier(clang::Token&) + 267
7  swift                    0x000000011014ea38 clang::Lexer::LexIdentifier(clang::Token&, char const*) + 248
8  swift                    0x000000011014a4a6 clang::Lexer::LexTokenInternal(clang::Token&, bool) + 14534
9  swift                    0x00000001101b921e clang::Preprocessor::Lex(clang::Token&) + 142
10 swift                    0x000000011017c937 clang::Preprocessor::ReadMacroName(clang::Token&, clang::MacroUse, bool*) + 55
11 swift                    0x00000001101842d0 clang::Preprocessor::HandleIfdefDirective(clang::Token&, bool, bool) + 48
12 swift                    0x000000011017fb69 clang::Preprocessor::HandleDirective(clang::Token&) + 3769
13 swift                    0x0000000110147374 clang::Lexer::LexTokenInternal(clang::Token&, bool) + 1940
14 swift                    0x00000001101b921e clang::Preprocessor::Lex(clang::Token&) + 142
15 swift                    0x000000010f78e0b7 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) + 391
16 swift                    0x000000010f6c2635 clang::ParseAST(clang::Sema&, bool, bool) + 453
17 swift                    0x000000010f3e825b void llvm::function_ref<void ()>::callback_fn<compileModuleImpl(clang::CompilerInstance&, clang::SourceLocation, clang::Module*, llvm::StringRef)::$_1>(long) + 2331
18 swift                    0x000000011150da86 RunSafelyOnThread_Dispatch(void*) + 38
19 swift                    0x0000000111550a0d ExecuteOnThread_Dispatch(void*) + 13
20 libsystem_pthread.dylib  0x00007fffaec109af _pthread_body + 180
21 libsystem_pthread.dylib  0x00007fffaec108fb _pthread_body + 0
22 libsystem_pthread.dylib  0x00007fffaec10101 thread_start + 13
Stack dump:
0.	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/sqlite3.h:89:2: current parser token 'ifndef'

**Comment by caoyunxiao** [comment]
Can you tell what should I do

**Comment by blackfog** [comment]
The problem occurs when the version of Xcode being used isn't the one at /Applications/Xcode.app. So, in the above case (and mine), I have /Applications/Xcode 8.2.1.app being used, but he modulemap has a hard-coded path to /Applications/Xcode.app, which causes the build error.

Sadly, Clang modulemaps don't have a way to parameterize things, which makes this complicated. The general workaround is to use a shell script to generate the modulemap based on the path expected by Xcode (or reported by xcode-select) dynamically.

Do not know how well this will be supported by CocoaPods, though.

The immediate workaround, if your environment allows it, is to use carthage.

**Comment by jberkel** [comment]
The modulemaps are gone with 0.11.4, please upgrade.
