### ISSUE TITLE
unable to open database file (code: 14)

### ISSUE THREAD

**Issue by FarshidRoohi** [stephencelis/SQLite.swift#635]
hi
I have all the steps in sequence, I'm grateful for help
Thanks
my code:
[link](https://gist.github.com/FarshidRoohi/8ecd0378b904f9a8acacbe179a7befe7)

**Comment by FarshidRoohi** [comment]
find problem 
problem is satabase file Path
`let databaseFileName = "dbtest.sqlite3"
            let databaseFilePath = "\(NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0])/\(databaseFileName)"
            let db = try Connection(databaseFilePath)`

**Comment by Ivan-Cantarino** [comment]
thanks @FarshidRoohi this helped me

**Comment by Coupz** [comment]
I've posted my version here: #624
