### ISSUE TITLE
Not Null Constraint

### ISSUE THREAD

**Issue by StartNinja** [stephencelis/SQLite.swift#639]
Hey, 

How can i generate the "NOT NULL" constraint for columns that are not using "primary key" or "unique" as constraint? 

Thanks.
Stavros

**Comment by Coupz** [comment]
I'm running the following SQL-statement against the database to create the table and "NOT NULL" is working like it should do.

```swift
let createSystemTableStatement = "CREATE TABLE IF NOT EXISTS `T_System` (" +
            "`rowId` INTEGER PRIMARY KEY AUTOINCREMENT," +
            "`C_StrTitle` TEXT NOT NULL UNIQUE," +
            "`C_StrValueType` INTEGER NOT NULL," +
            "`C_StrValue` TEXT NOT NULL" +
            ");"
```

How do you create your table?

**Comment by jsi7iv** [comment]
If you are using a TableBuilder to construct your table, the easiest way is to ensure that your column expression does not support an optional type. 

```
let id = Expression<Int>("idColumn")
let notNull = Expression<String>("notNullColumn")
let nullable = Expression<String?>("nullableColumn")

tableBuilder.column(id, primaryKey: true)
tableBuilder.column(notNull)
tableBuilder.column(nullable)
```
