### ISSUE TITLE
Problems filtering rows

### ISSUE THREAD

**Issue by Gob-Lin** [stephencelis/SQLite.swift#642]
Hello,
I'd like to filter a table using filter, here is my code:

let path = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true).first!
        
        // db connection
        do {
            db = try Connection("\(path)/myDB.sqlite3")
        } catch {
            print (error)
        }

        let currentOrder = Table("currentOrder")
        let itemID:Int64 = Int64(cellInfo.id)!
        
        currentOrder.filter(id == itemID)

the last line generates an error: "id" is unavailable in Swift; use "Any"

Am I doing something wrong?

Thank you.

**Comment by jberkel** [comment]
this is for reporting bugs, please you stackoverflow etc. instead.
