### ISSUE TITLE
SQLCipher

### ISSUE THREAD

**Issue by WilsonCP** [stephencelis/SQLite.swift#643]
Hi, a quick question regarding the title. I'm currently using this on my pod

`pod 'SQLite.swift/SQLCipher', '~> 0.11.2'`
`pod 'SQLite.swift', '~> 0.11.2''`

already imported SQLite, but im getting error

`Value of type Connection has no member key`

Any help would be greatly appreciated. Thanks!

**Comment by jberkel** [comment]
Just use 
```
pod 'SQLite.swift/SQLCipher', '~> 0.11.2'
```

in your Podfile, and remove the last line, otherwise SQLite is imported twice.
