### ISSUE TITLE
crash when getting a number stored as String

### ISSUE THREAD

**Issue by Bjorninn1** [stephencelis/SQLite.swift#644]
I have the newest release of the library and I get a crash in the Query.swift class in the function

          public func get<V: Value>(_ column: Expression<V>) -> V {
                  return get(Expression<V?>(column))!
          }

when I have a request and when trying to get a String value which is a number, like "10" (without the quotation marks). The value is stored in the database and the weird part is that the crash happens as well if I store a number followed by a dot, like "10." and the reason for that is that the library stores "10." as "10" in the database. A value like "a. 10" does not crash.

This is where the crash happens in my code: 

            for l in sqlResult {
                print("userAnswer: \(l.get(sqlUserAnswer))")
            }

Anyone else experienced this, or ideas how to solve it? 

I tried using both Varchar and Text in my sqlite schema. The crash happens with both of those types. I read on stackoverflow about the same type of sqlite problem, but where people were not using this library. The solution there was to use Varchar in the schema and no crash took place when storing an int in the Varchar field.
 
Update: in the query.swift file I changed this method:

 public func get<V: Value>(_ column: Expression<V>) -> V {
    get(Expression<V?>(column))!
}

to this:

public func get<V: Value>(_ column: Expression<V>) -> V {
    let a = get(Expression<V?>(column))
    print("type of expression is: \(type(of: a))")
    print("a is: \(a)")
    return a!
}

and it prints:
type of expression is: String
a is: nil

the value is a number in the database on the simulator, so the value is not nil. The problem (reason for returning nil) must be inside this function:

      get(Expression<V?>(column))

**Comment by Bjorninn1** [comment]
Update: in the query.swift file I changed this method:
     
     public func get<V: Value>(_ column: Expression<V>) -> V {
        get(Expression<V?>(column))!
    }

to this: 

    public func get<V: Value>(_ column: Expression<V>) -> V {
        let a = get(Expression<V?>(column))
        print("type of expression is: \(type(of: a))")
        print("a is: \(a)")
        return a!
    }

and it prints: 
     type of expression is: String
     a is: nil

the value is a number in the database on the simulator, so the value is not nil. The problem (reason for returning nil) must be inside this function: 

          get(Expression<V?>(column))

**Comment by Coupz** [comment]
Could you post some code of your insert and read methods?
