### ISSUE TITLE
not able to add this framework to xcode manually

### ISSUE THREAD

**Issue by ShivakumarIOS** [stephencelis/SQLite.swift#645]
i am trying to add sqlite.swift to my xcode swift project.by following the manual method which is been given in documentation.after following that also i am getting error while importing SQLite into my project

**Comment by ShivakumarIOS** [comment]
![error sqlite swift](https://cloud.githubusercontent.com/assets/25603424/25735030/e918a82e-3185-11e7-811f-589c08187610.JPG)

**Comment by boogiedoll** [comment]
Hi, have you solved your problem?

**Comment by Mlearn** [comment]
I have the same problem, don't know how to solve it.

**Comment by ShivakumarIOS** [comment]
Yes it's got resolved thanks
