### ISSUE TITLE
if possible get the field value by name ? 

### ISSUE THREAD

**Issue by icoco** [stephencelis/SQLite.swift#648]
as the example :
for user in try db.prepare(users.select(id, email)) {
    print("id: \(user[id]), email: \(user[email])")
    // id: 1, email: alice@mac.com
}
// SELECT "id", "email" FROM "users"

but I want know if possible use name  but expression or index ? 

I meaning : 
  let id =  user["email"] then got the  value of the field 'email'

   sorry for this question, but just a bit confuse

**Comment by Coupz** [comment]
Yes it should be possible. Like your example, just remove the double quotes ("") inside the square brackets.

So insted of
```swift
let id = user["id"]
let email = user["email"]
```
just use 
```swift
let id = user[id]
let email = user[email]
```

**Comment by icoco** [comment]
seem you misunderstand my problem...

I modify the code support the feature access the field value via name without define the expression  directly . 

some code as follows:
`public struct Cursor {

    
    fileprivate let handle: OpaquePointer

    //@@ fileprivate
   public let columnCount: Int
    
    fileprivate let stmt:Statement //
    
    fileprivate init(_ statement: Statement) {
        handle = statement.handle!
        columnCount = statement.columnCount
        //@step
        stmt = statement
    }

    public subscript(idx: Int) -> Double {
        
        return sqlite3_column_double(handle, Int32(idx))
    }

    public subscript(idx: Int) -> Int64 {
        return sqlite3_column_int64(handle, Int32(idx))
    }

    public subscript(idx: Int) -> String {
        return String(cString: UnsafePointer(sqlite3_column_text(handle, Int32(idx))))
    }

    public subscript(idx: Int) -> Blob {
        if let pointer = sqlite3_column_blob(handle, Int32(idx)) {
            let length = Int(sqlite3_column_bytes(handle, Int32(idx)))
            return Blob(bytes: pointer, length: length)
        } else {
            // The return value from sqlite3_column_blob() for a zero-length BLOB is a NULL pointer.
            // https://www.sqlite.org/c3ref/column_blob.html
            return Blob(bytes: [])
        }
    }

    // MARK: -

    public subscript(idx: Int) -> Bool {
        return Bool.fromDatatypeValue(self[idx])
    }

    public subscript(idx: Int) -> Int {
        return Int.fromDatatypeValue(self[idx])
    }

    ///////////////////////////////////////////////
    //@by Robin
    public func indexOfColumnName (_ name:String)->Int{
        let names = self.stmt.columnNames
        let i =  names.index(of: name)
        return nil != i ?  Int(i!) : -1
    }
    
    public func columnNameOfIndex (_ index:Int)->String{
        let names = self.stmt.columnNames
        for name in names {
             let i =  names.index(of: name)
            if i == index {
                return name
            }
        }
        return ""
    }
}

/// Cursors provide direct access to a statement’s current row.
extension Cursor : Sequence {

    public subscript(idx: Int) -> Binding? {
        switch sqlite3_column_type(handle, Int32(idx)) {
        case SQLITE_BLOB:
            return self[idx] as Blob
        case SQLITE_FLOAT:
            return self[idx] as Double
        case SQLITE_INTEGER:
            return self[idx] as Int64
        case SQLITE_NULL:
            return nil
        case SQLITE_TEXT:
            return self[idx] as String
        
        case let type:
            fatalError("unsupported column type: \(type)")
        }
    }

    
    public func makeIterator() -> AnyIterator<Binding?> {
        var idx = 0
        return AnyIterator {
            if idx >= self.columnCount {
                return Optional<Binding?>.none
            } else {
                idx += 1
                return self[idx - 1]
            }
        }
    }

    ////////////////////
    //@by Robin
    public subscript(name: String) -> Binding? {
        let idx = self.indexOfColumnName(name)
        return self[idx]
    }
}`

hope clearly . thanks.

**Comment by Coupz** [comment]
Sorry it's still not clear to me what your problem is.
Do you want to access the value by the index of the column like `let id = user[0]`?

**Comment by icoco** [comment]
eg:  table  'Customer' includes a filed name is 'address' 

I want got the value of  field 'address' , I do not want define any Expression like : 

let address = Expression<String>("address"),  

I need a simply way got the value like the code bellow:

for row in try db.prepare("SELECT id, address FROM Customer") {
    print("id: \(row['id']), address: \(row['address'])")
  }

**Comment by groue** [comment]
@icoco, you are looking for better support for raw SQL queries.

You won't find it here, because this library focuses on typed expressions and its query builder, and won't let you access raw columns by name. At least, not in any convenient fashion: the [Executing Arbitrary SQL](https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#executing-arbitrary-sql) documentation chapter of this library only talks about accessing columns by index, not by name.

You may be much happier with another library, such as [FMDB](https://github.com/ccgus/fmdb) or [GRDB](https://github.com/groue/GRDB.swift).

With GRDB:

```swift
for row in try Row.fetchAll(db, "SELECT id, address FROM Customer") {
    let id: Int64 = row.value(named: "id")
    let address: String = row.value(named: "address")
    print("id: \(id), address: \(address)")
}
```

**Comment by icoco** [comment]
... I know the typed expressions is great , but for coding it is trouble, because coder is lazy to type lot of unnecessary code, eg define the field type , name ,etc, we just want retrieve the value , we do not want offer time to list the field again (because it has been defined in table) , another reason the table scheme often changed, if the table field changed then the defined typed expressions or Object have to be updated ... all we just want  a few coding for core purpose.
another reason, if support get field value by name, then we can  define the field name as  Variant then it can be dynamic assign value in run time

**Comment by groue** [comment]
> all we just want a few coding for core purpose

The current state of this library does not focus on your need at all. It wants you to define a full list of tables and columns, what you call "unnecessary code". That's because its purpose is not to access SQLite in all generality. Its purpose is to provide the "One-And-Only-Correct-Way-To-Access-SQLite". A laudable goal, which does not fit all situations.

Just switch to GRDB: you'll get an environment much better suited to your needs. And GRDB will gracefully let you switch to its query builder when you want, if you ever decide that you need it.

**Comment by icoco** [comment]
thanks for advice, but since the lib (SQLIte.swift) support get field value by index , I think that also is acceptable through name...  anyway, will check the GRDB, thanks for your time
