### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftCore.dylib

### ISSUE THREAD

**Issue by willhains** [stephencelis/SQLite.swift#65]
Hi Stephen,

I'm having a similar issue to #25, but I do have the framework added in the "Copy Files" section of my target's Build Settings. Please see a screenshot below. Help?

Cheers,
Will.

![screen shot 2015-02-14 at 16 43 23](https://cloud.githubusercontent.com/assets/1386812/6198986/aa1a7608-b468-11e4-85b1-f69c7253ede9.png)

**Comment by willhains** [comment]
This is a Mac OS X command-line tool project, btw.

**Comment by willhains** [comment]
OK, it seems that frameworks can't be used in command-line tool projects (WTF?): https://github.com/typelift/swiftz/issues/114
Closing this issue for now.

**Comment by stephencelis** [comment]
Tracked as a dupe of #4.
