### ISSUE TITLE
Swift Compiler Warning ('sqlite3_trace' is deprecated)

### ISSUE THREAD

**Issue by yangwulong1978** [stephencelis/SQLite.swift#650]
'sqlite3_trace' is deprecated

**Comment by sicaboy** [comment]
+1

**Comment by ulaserdegor** [comment]
+1

**Comment by Bronts** [comment]
<img width="1270" alt="wx20170522-000205 2x" src="https://cloud.githubusercontent.com/assets/3986255/26285422/247bc05a-3e82-11e7-8360-c262759dca8a.png">
There was a similar issue. https://github.com/stephencelis/SQLite.swift/issues/627

**Comment by TofPlay** [comment]
Same message when I build this component with carthage:
```
../Sources/Carthage/Checkouts/SQLite.swift/Sources/SQLite/Core/Connection.swift:429:13: warning: 'sqlite3_trace' is deprecated
../Sources/Carthage/Checkouts/SQLite.swift/Sources/SQLite/Core/Connection.swift:436:9: warning: 'sqlite3_trace' is deprecated
```

**Comment by arv1989** [comment]
I created a pod which have a dependency on SQLite.swift , but the "pod lib lint" doesn't pass as it have the warning from SQLite.swift

`    - WARN  | xcodebuild:  SQLite.swift/Sources/SQLite/Core/Connection.swift:429:13: warning: 'sqlite3_trace' is deprecated
    - WARN  | xcodebuild:  SQLite.swift/Sources/SQLite/Core/Connection.swift:436:9: warning: 'sqlite3_trace' is deprecated
`

I temporarily solved the problem with the flag "--allow-warnings", It will be good if SQLite.swift is updated .

**Comment by arv1989** [comment]
+1

**Comment by dbaroncelli** [comment]
+1

**Comment by jberkel** [comment]
Apparently this is gone with Xcode 9.x.

**Comment by jberkel** [comment]
#716
