### ISSUE TITLE
Instructions on how to use in command-line tool projects

### ISSUE THREAD

**Issue by willhains** [stephencelis/SQLite.swift#66]
Since frameworks can't be used with command-line tool projects (see #65), could you add some instructions to the README for how to consume SQLite.swift directly, i.e. not as a framework?

**Comment by stephencelis** [comment]
The instructions should be similar to Alamofire's instructions here: https://github.com/Alamofire/Alamofire#source-file

I'll try to include a small section in the near future, though, thanks!

**Comment by willhains** [comment]
Thanks for the response. I read Alamofire's instructions, and it seems just adding one `.swift` file works for that framework. Which `.swift` file(s) should I add for this framework, then? I tried adding everything in `SQLite Common` and `SQLite Mac`, but I still get the following build error.

> .../SQLite Common/Statement.swift:43:21: Use of unresolved identifier 'sqlite3_column_count'

**Comment by stephencelis** [comment]
Good point. You'll also need to link your main target against libsqlite.

**Comment by willhains** [comment]
Thanks for the fast response again! 😊 Unfortunately, I already tried that. Same error. 😞

**Comment by stephencelis** [comment]
Beyond that, make sure you add the following to your bridging header:

```
#include <sqlite3.h>
```

**Comment by willhains** [comment]
That did the trick! Thanks! 😊 

For anyone else who comes across this issue, here are the steps I did in detail:

1. Add the following files to the project directly (i.e. *not* by embedding the `SQLite.xcodeproj` as a sub-project).
   - SQLite Common.xcconfig
   - SQLite-Bridging-Header.h
   - SQLite-Bridging.c
   - SQLite-Bridging.h
   - Database.swift
   - Expression.swift
   - Functions.swift
   - Query.swift
   - Schema.swift
   - Statement.swift
   - Value.swift
2. In my target, I made sure all of the above files, except the `.h` and `.xcconfig` files, are listed in the "Compile Sources" section of "Build Phases".
3. I added `libsqlite3.dylib` to the "Link Binary With Libraries" build phase.
4. I created a new `<ProjectName>-Bridging-Header.h` file in my project, and added the following `import` statement. (I needed to do this because I have to `import` multiple 3rd-party bridging headers in my project.)
```objective-c
#import "SQLite-Bridging-Header.h"
```

Stephen, if any of the above is wrong/misguided/unnecessary/foolish/repulsive, please let me know!

**Comment by stephencelis** [comment]
@willhains Everything above looks right except you shouldn't need to add the `xcconfig` file! These instructions will also work for using SQLite.swift with iOS 7. Thanks!

**Comment by stephencelis** [comment]
Closing by https://github.com/stephencelis/SQLite.swift/commit/09513108703cd3b596b9c23fc312ae74e6965e6e
