### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by webersson** [stephencelis/SQLite.swift#662]
Hi,
I´m trying to setup the SQLite.swift project.
I´m getting different build errors:

_"swift compiler warning"
   -sqlite3_trace is deprecaated

"Apple Mach-O Linker Error"_

I used the following text inside the pod file during install:

----------------------------------------------------------------------------------------------
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SQLite iOS' do
pod 'SQLite.swift', '~> 0.11.3'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SQLite iOS

end

target 'SQLite Mac' do
pod 'SQLite.swift', '~> 0.11.3'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SQLite Mac

end

target 'SQLite tvOS' do
pod 'SQLite.swift', '~> 0.11.3'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SQLite tvOS

end

target 'SQLite watchOS' do
pod 'SQLite.swift', '~> 0.11.3'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SQLite watchOS

end
----------------------------------------------------------------------------------------------

Thankfull for every help!

**Comment by jberkel** [comment]
This is just a warning, you can ignore it
