### ISSUE TITLE
Swift 4: Build Error

### ISSUE THREAD

**Issue by MicroSpecWes** [stephencelis/SQLite.swift#663]
After moving to the swift 4 beta, building an app with this library fails.  The error is on line 497 of Query.swift

<img width="876" alt="screen shot 2017-06-07 at 10 22 37 am" src="https://user-images.githubusercontent.com/5385266/26884224-4266e9ee-4b6d-11e7-9e17-118ae409c922.png">

I made some attempts to fix it but my `map` knowledge is not great.  Other then this error I didn't see anything else show up.

**Comment by jberkel** [comment]
Fixed
