### ISSUE TITLE
SQLITE_DETERMINISTIC not defined in iOS 8.1 SDK

### ISSUE THREAD

**Issue by kklobe** [stephencelis/SQLite.swift#67]
SQLITE_DETERMINISTIC is not defined in sqlite3.h from iOS SDK 8.1, causing a build failure on Xcode 6.1.1 in SQLite-Bridging.c (61).

**Comment by stephencelis** [comment]
Thanks for the report! I've been running tests on the Mac framework (which has a newer version of SQLite) and when I've tested iOS it's been Xcode 6.3 (same story). Let me add an `#ifdef` for iOS 8.1.

**Comment by stephencelis** [comment]
Fixed by https://github.com/stephencelis/SQLite.swift/commit/6355b6d367244ca3d3bd25581536163a9ee78d5e
