### ISSUE TITLE
Cannot update 0.11.3

### ISSUE THREAD

**Issue by wxpasta** [stephencelis/SQLite.swift#671]
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `SQLite.swift (~> 0.11.3)` required by `Podfile`

Specs satisfying the `SQLite.swift (~> 0.11.3)` dependency were found, but they required a higher minimum deployment target.

pod update
 - SQLite.swift/standard (0.11.2)

 pod --version
- 1.2.1

**Comment by jberkel** [comment]
Fixed in 0.11.4
