### ISSUE TITLE
Support for count column

### ISSUE THREAD

**Issue by martheli** [stephencelis/SQLite.swift#674]
I have the below code:

```
let query = mdm.select(os,os.count)
                .filter(os != "")
                .group(os)

let results = try! db.prepare(query)

for items in results
{
    countArray.append(items[os])
    countOSArray.append(items[os.count]) // This does not work

}
```

The result should output two columns, list of OS and a list of the their counts. How do I reference the count column? Is this supported in an expression?

**Comment by pryder-fleetaero** [comment]
Did you find a solution, I'm trying to build a similar query with no luck

**Comment by martheli** [comment]
@pryder-fleetaero I don't remember how I solved this since it was 6 years ago

**Comment by pryder-fleetaero** [comment]
No problems.  Understandable, but thought I'd try my luck just in case :)
