### ISSUE TITLE
Binary operator '==' cannot be applied to operands of type 'Expression<Int64>' and 'Int'

### ISSUE THREAD

**Issue by JerrySir** [stephencelis/SQLite.swift#680]
Hello:
I have a question, It really puzzles me:
`let a = 1`
`let deleteRow1 = templates.filter(id == a) //Binary operator '==' cannot be applied to operands of type 'Expression<Int64>' and 'Int'`
`let deleteRow2 = templates.filter(id == 1) //No error`

I want to pass the argument “id” into the function
Why, Am I doing anything wrong?

**Comment by wukongzhikong** [comment]
just add type annotation to constant a:"let a: Int64 = 1".
Expression<Int64> can only be compared with type Int64's.

**Comment by JerrySir** [comment]
`Int(a) `
it's working
