### ISSUE TITLE
SQLCipher issue

### ISSUE THREAD

**Issue by PeterVanDelft** [stephencelis/SQLite.swift#682]
Trying to get SQLCipher working without any luck. Using Xcode 8 and swift 3 and it is a iOS project.

SQLite.swift work as expected when only using : pod 'SQLite.swift', '~ 0.11.3' in pod file. However when adding dependency for SQLCipher : pod 'SQLite.swift/SQLCipher', '~ 0.11.3' as the only sqlite entry in pod file, I get a nil pointer error when calling:

```
var db: Connection?
        do{
            let dbFileURL = try! FileManager.default.url(for: .documentDirectory, in: .userDomainMask, appropriateFor: nil, create: false)
                .appendingPathComponent("dbname.db3")
            db = try Connection(dbFileURL.absoluteString)
            
        }
        catch
        {
            print(error.localizedDescription)
        }
        return db!
```

Can get SQLite.swift to work if I have two entries in pod file one for sqlite.swift and the other for /Cipher. However in this scenario the following code:

```
var db: Connection?
        do{
            let dbFileURL = try! FileManager.default.url(for: .documentDirectory, in: .userDomainMask, appropriateFor: nil, create: false)
                .appendingPathComponent("dbname.db3")
            db = try Connection(dbFileURL.absoluteString)
            try db?.key("somekeyhere")
        }
        catch
        {
            print(error.localizedDescription)
        }
        return db!
```

never returns from 'try db?.key("somekeyhere")'.

Any help would be greatly appreciated.

**Comment by icoco** [comment]
in pod file : 

pod 'SQLite.swift/SQLCipher', '~> 0.11.3'

in code: 

import SQLite


`func testConn(){

         let fileName = "...my.db"

         self._conn = try Connection(fileName)

        if isSecurity {  // then use  SQLCipher , no other coding work 

            try _conn?.key("xxx")  

       }

}
`

**Comment by jberkel** [comment]
if you still have this problem, can you post a full stacktrace? with this limited information debugging is impossible.
