### ISSUE TITLE
RxSwift support?

### ISSUE THREAD

**Issue by cody1024d** [stephencelis/SQLite.swift#686]
Is there any push to create an RxSwift compatible library for this?  It would be very helpful to be able to perform queries in a reactive manor

**Comment by jberkel** [comment]
I'd love to adopt reactive patterns, especially for error handling. Some of them were discussed in #569, and subsequently implemented in [GRDB.swift](https://github.com/groue/GRDB), so maybe check there. @groue, how did it turn out in the end?

**Comment by cody1024d** [comment]
I know there is a RxGRDB repo: (https://github.com/RxSwiftCommunity/RxGRDB).  I even tried to dig around in there to see how it was being done, to see if I could glean anything to layer over this repo.  Obviously to get it done a PublishSubject would need to be added somewhere, and that's not too hard, but what I'm having trouble with, is how we'd know when the table is updated properly.

Looking at RxGRDB I *think* he's using the SQLite Pre-Update hooks to do so, but I'm not 100% on that at all

**Comment by groue** [comment]
Hello @jberkel, @cody1024d

> what I'm having trouble with, is how we'd know when the table is updated properly.

This does not happen in RxGRDB, which is just a thin layer. The meat belongs to GRDB which has a long history of [database observation features](https://github.com/groue/GRDB.swift/blob/master/README.md#database-changes-observation).

When you mix SQLite [Compile-Time Authorization Callbacks](https://sqlite.org/c3ref/set_authorizer.html), [Commit And Rollback Notification Callbacks](https://sqlite.org/c3ref/commit_hook.html) and [Data Change Notification Callbacks](https://sqlite.org/c3ref/update_hook.html), you can:

- track transactions and the [savepoint stack](https://sqlite.org/lang_savepoint.html)
- know which columns of which tables are modified by a statement
- know about all row insertions, updates, and deletions

All those information together give you a precise enough idea of the changes eventually committed by a transaction. You can package this in the public [TransactionObserver](https://github.com/groue/GRDB.swift/blob/master/README.md#transactionobserver-protocol) protocol, the mother of all database observations features.

[Compile-Time Authorization Callbacks](https://sqlite.org/c3ref/set_authorizer.html) also tell which columns of which tables are *read* by a statement. You can thus write a TransactionObserver that fuels a reactive sequence when a transaction has changed the tracked tables and columns: that's the idea of RxGRDB.

SQLite.swift already has [updateHook](https://github.com/stephencelis/SQLite.swift/blob/0.11.3/Sources/SQLite/Core/Connection.swift#L460), [commitHook](https://github.com/stephencelis/SQLite.swift/blob/0.11.3/Sources/SQLite/Core/Connection.swift#L488) and [rollbackHook](https://github.com/stephencelis/SQLite.swift/blob/0.11.3/Sources/SQLite/Core/Connection.swift#L515): that's the place to start.

**Comment by groue** [comment]
@jberkel, I think @cody1024d wasn't talking about using reactive patterns to consume the results of a single request, but to be notified of changes in the results in a request.

#569 was about the fact that Swift `Sequence` does not quite fit the consumption of the results of a request, and that a cursor whose `next` method can throw is more suitable. That's why GRDB generally provides three fetching methods, depending on the way you want to consume the results of a request:

```swift
let request = Player.all()
// Lazy, does not consume much memory
try request.fetchCursor(db)  // DatabaseCursor<Player>
// Contains copies of database values, may consume a lot of memory
try request.fetchAll(db)     // [Player]
// Consumes a single row
try request.fetchOne(db)     // Player?
```

RxGRDB does not bring any reactive APIs on top of cursors. It's just a couple lines of code away, though:

```swift
// Turns DatabaseCursor into RxSwift Observable
extension DatabaseCursor : ObservableType {
    public typealias E = Element
    public func subscribe<O: ObserverType>(_ observer: O) -> Disposable where O.E == E {
        do {
            while let element = try next() {
                observer.onNext(element)
            }
            observer.onCompleted()
        } catch {
            observer.onError(error)
        }
        return Disposables.create()
    }
}

// Consume a cursor in a reactive way:
try dbQueue.inDatabase { db in
    let cursor = try Player.fetchCursor(db)
    cursor.subscribe(
        onNext: { player in print(player) },
        onError: { error in print(error) }
    )
}
```

What RxGRDB brings is *request observation*, that is to say observable sequences of changes in the results of a request:

```swift
// Observe a single request:
Player.all().rx
    .fetchAll(in: dbQueue)
    .subscribe(onNext: { players: [Player] in
        print("Players have changed: \(players)")
    })

// Observe some request(s) and fetch consistent results from other request(s):
dbQueue.rx
    .changeTokens(in: [Player.all()])
    .mapFetch { (db: Database) -> ([Player], Int) in
        let players = try Player
            .order(Player.Columns.score.desc)
            .limit(10)
            .fetchAll(db)
        let count = try Player.fetchCount(db)
        return (players, count)
    }
    .subscribe(onNext: { (players, count) in
        print("Best players out of \(count): \(players)")
    })
```

I think this is what @cody1024d is after.

Best thing is that RxGRDB eats all GRDB requests, which means that you can observe records, raw database rows, or values fetched from the query builder or even raw SQL:

```swift
// Observe maximum player score:
let request = Player
    .select(max(Player.Columns.score))
    .asRequest(of: Double.self)
request.rx
    .fetchOne(in: dbQueue)
    .subscribe(onNext: { maxScore: Double? in
        print("Maximum score: \(maxScore ?? 0)")
    })

// Observe minimum and maximum player scores:
let request = Player
    .select(
        min(Player.Columns.score).aliased("min"),
        max(Player.Columns.score).aliased("max"))
    .asRequest(of: Row.self)
request.rx
    .fetchOne(in: dbQueue)
    .subscribe(onNext: { row: Row? in
        let minScore: Double? = row!.value(named: "min")
        let maxScore: Double? = row!.value(named: "max")
        print("Score range: \(minScore ?? 0)-\(maxScore ?? 0)")
    })

// Observe players fetched from the occasionally complex SQL query:
let request = SQLRequest("SELECT ...")
    .asRequest(of: Player.self)
request.rx
    .fetchAll(in: dbQueue)
    .subscribe(onNext: { player: [Player] in
        print("Players have changed: \(players)")
    })
```

**Comment by cody1024d** [comment]
Thank you @groue for the hardcore breakdown!  You are right, that that is what I'm after; the ability to subscribe to, essentially a table, and be notified of updates to said table.  I apologize that my initial comment was not well worded.  Looking back on it now, even I was confused by what I was asking.

I think I *probably* could string something together leveraging the hooks built into SQLite.Swift, at least enough so that I could get the end result I wanted.  As long as I have the table that was updated in the commitHook, I could hook up a PublishSubject to it correctly, and store the initial query when it's performed, and then in the commitHook just perform that same query again, and push it out over the PublishSubject.

Or, I guess, I could switch to GRDB; however my only concern with that is it leans more towards the Active Record approach, and I much prefer a DAO/Repository approach :/.  I guess I could query with raw SQLite within the repositories, but would love to avoid that too.  Lol, I want the best of both worlds I guess

**Comment by groue** [comment]
@cody1024d It's good for both you and SQLite.swift that you start experimenting on the subject.

GRDB is just mature enough now so that you can use it and focus of your application domain. I'm not sure one can say it leans towards Active Record, even though it does indeed makes the assumption that application use models more than raw rows, and that forcing the user to explicitly turn raw rows into models is a burden that can be avoided. `Player.fetchAll(db)` is simply easier to the eye than `db.prepare(...).map { ... }` (and I don't talk about possible optimizations such as direct access to SQLite statements for better [performance](https://github.com/groue/GRDB.swift/wiki/Performance), or about error handling troubles behind #569). You'll maybe give GRDB a try in a future project ;-)

**Comment by cody1024d** [comment]
@groue I'm going to start an issue over at GRDB about the syntax stuff; as I think it's an interesting subject, but don't want to clog this issue up any longer.

@jberkel I'm going to do some looking into getting RX up and running for SQLite.Swift; albeit I'm not sure how clean it will be; but it may be a jumping off point.

**Comment by jberkel** [comment]
@cody1024d ok, great! don't worry too much, we can clean it up, it will be good to have a starting point

**Comment by cody1024d** [comment]
@jberkel 

Here are my thoughts so far:


    -The RxConnection will wrap around the standard connection
    -It will register itself as the update hook to it's inner connection
    -It has a prepare method (and all the methods that the connection normally has)
        -This will allow me to store the query type, etc. to perform when a change is found

    The prepare method psuedo code:
        Save the passed in query, associated with a specific table (dictionary)
            -TableName to some object that holds a PublishSubject, and the passed in query.
                          -[String: TableListener] ? (TableListener contains a PublishSubject and the query)
        Execute the query and pass it back through the publish subject that was created before
        Return the publish subject that was just created

    On the Update Hook:

        Look up in the dictionary to see if there is an ObservableListener
        If there is, execute the stored query (that's bound to that ObservableListener), and publish it out through the Publish Subject

I haven't implemented any of this yet, but that's kind of my thinking on how I will go about it.  Thoughts?

**Comment by cody1024d** [comment]
Ok so I am finally getting around to implementing this.

So the above is trivial for insert/delete (atleast in the simplest cases).  The interesting part is knowing what columns have changed, given only the ability to use the Connection API (as it stands now).  Right now I'm thinking I may have to essentially "rip" the column names out of the Update struct that's passed into the Connection, before it's run.

@jberkel Any insight into a better way of potentially capturing what columns are going to be updated in the context of this library?  --This would allow me to give Rx-based observations at the column granularity, as opposed to just at the table; which would be inefficient for updates.  For now, my code will return the query results; but for every action performed on the entirety of the table, even if the query and the update are on unrelated columns.

**Comment by jberkel** [comment]
@cody1024d great, i'll have a closer look at this soon, travelling right now with limited internet

**Comment by cody1024d** [comment]
@jberkel No problem; here is the code I'm using right now.  It is working for Inserts/Deletes based on table; although not at the column granularity I wanted.  Also you'll notice the hack to get the table name out of the query that I very much don't like :P

It could a bit more encapsulation work, to make the implementation a bit cleaner, that's my goal later today, just wanted to get a working concept together first.

```swift
class RxConnection {
    let rawConnection: Connection
    //For every table (and column set eventually) we will have a map of query to subject.  This way, we only perform the query once, even if there are multiple observers for the same query
    //One thing to think about is how do we handle someone make changes when they see a change?  This would end in an endless loop I think
    private var watchedQueries = [ChangesDefinition: [WatchableQuery: [PublishSubject<AnySequence<Row>>]]]()

    init(db: Connection) {
        self.rawConnection = db
        db.updateHook { (operation, db, tableName, rowId) in
            let changesDefinition = ChangesDefinition(tableName: tableName)
            if let queryWatchers = self.watchedQueries[changesDefinition] {
                queryWatchers.forEach { (watchableQuery, subjects) in
                    do {
                        let result = try self.rawConnection.prepare(watchableQuery.query)
                        subjects.forEach { $0.onNext(result) }
                    } catch {
                        subjects.forEach { $0.onError(error) }
                    }

                }
            }
            /**
                TODO--When an update has been done successfully
                If Update:
                    -Need to know which column was to be updated?  --> Need to store which column via the update query?
                    -How do we handle concurrency, two threads call update on this instance,
            **/
        }
    }

    public func scalar<V : Value>(_ query: ScalarQuery<V>) throws -> V {
        return try rawConnection.scalar(query)
    }

    @discardableResult public func run(_ query: Insert) throws -> Int64 {
        return try rawConnection.run(query)
    }

    @discardableResult public func run(_ query: Delete) throws -> Int {
        return try rawConnection.run(query)
    }

    @discardableResult public func run(_ query: Update) throws -> Int {
        return try rawConnection.run(query)
    }
    
    //TODO--Implement all methods on the Connection, and pass through to it

    public func prepare(_ query: QueryType) -> Observable<AnySequence<Row>> {
        //Does not currently handle the granularity of columns, as the update hook does not know which columns were updated
        let tableName: String = query.expression.template.slice(from: "FROM \"", to: "\"")!
        let changesDefinition = ChangesDefinition(tableName: tableName)
        if !watchedQueries.keys.contains(changesDefinition) {
            watchedQueries[changesDefinition] = [:]
        }
        let watchableQuery = WatchableQuery(query: query)
        if !(watchedQueries[changesDefinition]?.keys.contains(watchableQuery) ?? false) {
            watchedQueries[changesDefinition]?[watchableQuery] = []
        }
        let subject = PublishSubject<AnySequence<Row>>()
        watchedQueries[changesDefinition]?[watchableQuery]?.append(subject)

        let originalObs = Observable<AnySequence<Row>>.create { observer in
            do {
                observer.onNext(try self.rawConnection.prepare(query))
            } catch {
                observer.onError(error)
            }
            return Disposables.create {
                self.rawConnection.interrupt()
            }
        }

        return Observable.merge(subject, originalObs)
    }
}



struct WatchableQuery: Hashable {
    let query: QueryType

    public var hashValue: Int {
        return query.asSQL().hashValue
    }

    public static func ==(lhs: WatchableQuery, rhs: WatchableQuery) -> Bool {
        return lhs.query.asSQL() == rhs.query.asSQL()
    }
}

struct ChangesDefinition: Hashable {
    let tableName: String

    public var hashValue: Int {
        return tableName.hashValue
    }

    public static func ==(lhs: ChangesDefinition, rhs: ChangesDefinition) -> Bool {
        return lhs.tableName == rhs.tableName
    }

}
```

**Comment by cody1024d** [comment]
@jberkel Any input on this?  I'm using it and it has worked well for me.  Definitely can be improved, but I'd like to contribute if I can

**Comment by jberkel** [comment]
@cody1024d how would this be integrated? as a subspec with RxSwift dependency?

**Comment by cody1024d** [comment]
Yeah, I would say so.  This way users can choose if they want the RX support or not.  We could either add it as a subspec to this library, or create another github project for it.  

I think the only decision there would be or you (we) would want to support it; if we'd want issues to be lumped together and all, or not.

**Comment by jberkel** [comment]
I'd say lets keep it in one repo, since everything is already set up there

**Comment by cody1024d** [comment]
Ok cool.  I'm coming down to the wire on the project that it's used in.  But I should have time to clean it up, and do a formal PR on it soon(ish).  I may have time after my 9-5 to do it as well, but we'll see.  We can use a formal PR to code review, etc. it, I think would be best?  I'll close this for the time being, and open the PR when I can :)

**Comment by robert-cronin** [comment]
Has there been any progress on adding reactive functionality? This would just be the icing on the cake for SQLite.swift

**Comment by kwstasna** [comment]
bump

**Comment by norbdev** [comment]
bump

**Comment by kwstasna** [comment]
@norbdev I used https://github.com/groue/GRDB.swift eventually :P
