### ISSUE TITLE
App now crashing in SQLite.Statement (with Swift 1.2 branch)

### ISSUE THREAD

**Issue by reflectivist** [stephencelis/SQLite.swift#69]
Is the 1.2 stuff working on iOS 8.3?  Does the Master no longer work (as of Swift Xcode 6.3/Swift 1.2)?  Would the Master branch work if I tried to convert it to Swift 1.2 via the Xcode assistant, and just accept the defaults (for changes like as to as!, etc...)?  

I was 'forced' to upgrade my iPhone to 8.3 when I installed SQLite from the 1.2 branch, this into my project after upgrading to Xcode 6.3 Beta because a framework requirement setting. But for Swift 1.2, I notice it didn't have all the Mac OS X or iOS variants, and  I couldn't select an iOS specific framework. Anyway, it's crashing  in sqlite3_step with [CFString release] message sent to deallocated instance. See screenshot.

Apparently I can't rollback my phone to 8.1.3 now after the upgrade, and I'm in the middle of app development.  I realize this could be caused by my code somehow but I'm not sure. It used to work. Any suggestions?   

![sqlite crash](https://cloud.githubusercontent.com/assets/3528539/6320865/e42ea9cc-ba9e-11e4-88cb-86c266926872.png)

**Comment by stephencelis** [comment]
> Is the 1.2 stuff working on iOS 8.3? Does the Master no longer work (as of Swift Xcode 6.3/Swift 1.2)? Would the Master branch work if I tried to convert it to Swift 1.2 via the Xcode assistant, and just accept the defaults (for changes like as to as!, etc...)?

The `master` branch is for Xcode 6.1/6.2 and Swift 1.1, while `swift-1-2` is for Xcode 6.3 and Swift 1.2 beta.

> I was 'forced' to upgrade my iPhone to 8.3 when I installed SQLite from the 1.2 branch, this into my project after upgrading to Xcode 6.3 Beta because a framework requirement setting. But for Swift 1.2, I notice it didn't have all the Mac OS X or iOS variants, and I couldn't select an iOS specific framework.

Both `master` and `swift-1-2` branches were recently updated to use a universal framework. Separate iOS and Mac targets shouldn't be necessary anymore, as the framework should build appropriately for the platform of the given app target you're developing. You may have needed to redo the steps under "Installation" after upgrading, though.

> Anyway, it's crashing in sqlite3_step with [CFString release] message sent to deallocated instance. See screenshot.

There are a bunch of new memory crashers in Swift 1.2 (a couple that hit when you run the SQLite.swift test suite). Some should be fixed in the next Swift beta (according to Apple/Swift engineers on the dev forums), but you should file a bug report if it's consistent and a new issue that doesn't exist in Swift 1.1 (use Xcode 6.1/6.2 on the simulator to test).

> Apparently I can't rollback my phone to 8.1.3 now after the upgrade, and I'm in the middle of app development. I realize this could be caused by my code somehow but I'm not sure. It used to work. Any suggestions?

You'll likely be unable to submit a build using Swift 1.2 for awhile, and you'll be fighting beta bugginess and crashiness in the meantime. I'd generally recommend sticking with the stable GMs for development till later.

**Comment by stephencelis** [comment]
(Please follow https://github.com/stephencelis/SQLite.swift/pull/62 for Swift 1.2 progress/discussion.)

**Comment by stephencelis** [comment]
@reflectivist Try the latest Xcode beta (released about an hour ago) and see if your crashes are gone.

**Comment by reflectivist** [comment]
I meant to thank you for the quick feedback yesterday.
I reverted my workspace to GM so I could continue to make progress.

But I will test it out when I can over the next few days (work is heating up again so
my time is more limited)

You mentioned you thought it would be awhile before 8.3 apps were accepted for store submission.
If you had to give a crude estimate, what would you suppose based on your experience with Apple?

Anyway - If your code is stable with a relatively stable 1.2, I’d prefer to use that.
My code isn’t going to be ready for the store for at least a few more months.

Paul

**Comment by stephencelis** [comment]
> If you had to give a crude estimate, what would you suppose based on your experience with Apple?

In my experience, this is the first time Apple's had 2 beta tiers going at the same time (Xcode 6.2 and 6.3). We should see 6.2 go GM around the time the Apple Watch is released. Then some additional time will have to pass before we see 6.3 go GM.

**Comment by stephencelis** [comment]
> Anyway - If your code is stable with a relatively stable 1.2, I’d prefer to use that. My code isn’t going to be ready for the store for at least a few more months.

I'll be keeping it as stable as possible but can't make any guarantees that Apple's side of things will go smoothly. Just be careful between beta upgrades as even with beta 1 to beta 2, I had to make some changes to get things compiling again (see  https://github.com/stephencelis/SQLite.swift/commit/49537e4b0d3df330f17d624f8fda5742c55d4a83).

**Comment by reflectivist** [comment]
Thanks for the info.

**Comment by reflectivist** [comment]
> On Feb 23, 2015, at 1:15 PM, Stephen Celis <notifications@github.com> wrote:
> 
> Anyway - If your code is stable with a relatively stable 1.2, I’d prefer to use that. My code isn’t going to be ready for the store for at least a few more months.
> 
> I'll be keeping it as stable as possible but can't make any guarantees that Apple's side of things will go smoothly. Just be careful between beta upgrades as even with beta 1 to beta 2, I had to make some changes to get things compiling again (see49537e4 <https://github.com/stephencelis/SQLite.swift/commit/49537e4b0d3df330f17d624f8fda5742c55d4a83>).
> 
> 

I like Swift 1.2 improvements and would like to use them.

I'll let you know when I can test your project from my proj. w/new Apple bits (probably this week).

If I can get XCode 6.3B + Swift 1.2 works,  I might just trudge forward with that, as there’s no way my
 app will be ready by the Apple Watch release, so angling for 8.3 might be viable. I’m torn.

Thanks,
Paul

**Comment by reflectivist** [comment]
Hi Stephen,

I am too swamped to revert and test XCode 6.3/Swift 1.2 with the SQLite 1.2 branch
for the time being.  I just found out I have to travel next week, and there’s so much to do on my app.

At some point I will test it and let you know.

Thanks for your help and project again!
Paul
