### ISSUE TITLE
SQLCipher Build issue Swift 4

### ISSUE THREAD

**Issue by zinnero** [stephencelis/SQLite.swift#692]
Hi,

when I try to built I got the error (file FTS4.swift / line 156):

'distance(from:to:)' is unavailable: Any String view index conversion can fail in Swift 4; please unwrap the optional indices

How can it changed ?

greeting
Oli

extension Connection {

    public func registerTokenizer(_ submoduleName: String, next: @escaping (String) -> (String, Range<String.Index>)?) throws {
        try check(_SQLiteRegisterTokenizer(handle, Tokenizer.moduleName, submoduleName) { (
                input: UnsafePointer<Int8>, offset: UnsafeMutablePointer<Int32>, length: UnsafeMutablePointer<Int32>) in
            let string = String(cString: input)

            guard let (token, range) = next(string) else { return nil }

            let view = string.utf8
            offset.pointee += Int32(string.substring(to: range.lowerBound).utf8.count)
//*********************************************************************************************      
// 'distance(from:to:)' is unavailable: Any String view index conversion can fail in Swift 4; please unwrap the optional indices

     length.pointee = Int32(view.distance(from: range.lowerBound.samePosition(in: view), to: range.upperBound.samePosition(in: view)))
//*********************************************************************************************
            return token
        })
    }

}

**Comment by tuchangwei** [comment]
me too
