### ISSUE TITLE
How to check if table already exist

### ISSUE THREAD

**Issue by keziia22** [stephencelis/SQLite.swift#693]
How to validation if table already exist ?

**Comment by bpo217** [comment]
Try this out:

```swift
let connection = try Connection()
let table = Table("TableName")
let tableExists = try connection.scalar(table.exists)
if tableExists {
  //The world is yours.
}
```

**Comment by bpo217** [comment]
> 'try connection.scalar(table.exists)' doesn't actually check if the table exists but checks whether the number of rows in this table is not zero. So it will return true iff the table contains one or more rows and false otherwise.

It's been a while since I wrote this out. Did something change? I explicitly said it throws an error if the table doesn't exist. I must've made sure of that when I wrote it. Is this not correct anymore?

**Comment by bpo217** [comment]
Confusing myself. Thanks for the clarification.

**Comment by joelfischerr** [comment]
> > 'try connection.scalar(table.exists)' doesn't actually check if the table exists but checks whether the number of rows in this table is not zero. So it will return true iff the table contains one or more rows and false otherwise.
> 
> It's been a while since I wrote this out. Did something change? I explicitly said it throws an error if the table doesn't exist. I must've made sure of that when I wrote it. Is this not correct anymore?

I have clarified my comment and don't think anything has changed. If the table doesn't exist, the error is always thrown. I just wanted to clarify the behavior if the table does exist.
