### ISSUE TITLE
[Swift 1.2] Query.Swift missing argument in parameter #2 in call

### ISSUE THREAD

**Issue by ssherar** [stephencelis/SQLite.swift#70]
In commit 0bb3a86d, the changes to Query.swift for the new style closure is causing an issue with `split`. reverting the change on that line resolves the compile error on line - `missing argument in parameter #2 in call`.

```swift
let pair = split(each.expression.SQL) { $0 == "." }
```
to

```swift
let pair = split(each.expression.SQL, { $0 == "." })
```

I don't have the brain capacity today to really look into it, so I thought i would inform instead!

**Comment by stephencelis** [comment]
@ssherar Did you download yesterday's newly-released Xcode/Swift beta?

The commit you're referencing requires you're on Xcode 6.3b2 (Swift 1.2b2).

**Comment by ssherar** [comment]
@stephencelis Alas that is the issue once again. How on earth did I miss that update?

Cheers!
