### ISSUE TITLE
How do I catch a specific SQLite error

### ISSUE THREAD

**Issue by lukebar** [stephencelis/SQLite.swift#700]
I have a unique constraint on my database that prevents inserting a row with identical _userId AND _event values. SQLite properly throws an exception when I try to do this, but how can I catch it specifically? Right now, I have no way of knowing if my insert fails because of my constraint (which I can easily handle) or for some other SQLite related reason (that means a more serious problem.)

```
do {
    let insertQuery = logTable.insert(_userId <- event.userId, _event <- event.event)
    try db.run(insertQuery)
} catch {
    print("There's an error \(error)")
}
```

Thanks!

**Comment by jberkel** [comment]
You can use pattern matching:

```swift
do {
    try db.run(users.insert(email <- "alice@mac.com"))
    try db.run(users.insert(email <- "alice@mac.com"))
} catch let Result.error(_, code, _) where code == SQLITE_CONSTRAINT {
    print("constraint failed")
} catch let error {
    print("insertion failed: \(error)")
}
```

**Comment by crabman448** [comment]
@jberkel Hey!

As I understood `SQLITE_CONSTRAINT (19)` is a `Primary Result Code`. However what can I do to get deeper understating of the error? 
From what I found https://www.sqlite.org/rescode.html there is also an `Extended Result Code` which is more precise. In my case I would like to handle this error `SQLITE_CONSTRAINT_UNIQUE (2067)` and say to the user that object was already saved.
Do I miss something or is it not possible?

Thanks in advance!

**Comment by hj24** [comment]
Hi @jberkel , do you have answer to @wow-such-amazing 's question? Same question here, I want to handle SQLITE_CONSTRAINT_UNIQUE, but unable to find it
