### ISSUE TITLE
How do I set a foreign key to  an existing table?

### ISSUE THREAD

**Issue by zhangchunyu2016** [stephencelis/SQLite.swift#702]

**Comment by thomasdik1995** [comment]
I have the same issue.

I want to create two tables. The first is Game, the second is Round. Now a Game has 4 Rounds, so I want to save the foreign key to the Round using the following coding:

        //Tabelle Game
        do {
            try db?.run(Game.create { g in
                g.column(idGame, primaryKey: true)
                g.column(desc)
            })
            print("Created table Game")
        }
        catch {
            print("Create table Round failed")
        }
        
        //Tabelle Round
        do {
            try db?.run(Round.create { r in
                r.column(idRound, primaryKey: true)
                r.foreignKey(idGame, references: Game, idGame)
                r.column(desc)
            })
            
            print("Created table Round")
        }
        catch {
            print("Create table Round failed")   
        }

Im not getting any errors but the catch exception.
Does anybody know why?

Note: the upper code is a minimal setup for testing.

Best

**Comment by zhangchunyu2016** [comment]
@thomasdik1995 Can you paste the exception information?

**Comment by thomasdik1995** [comment]
Can you please tell me how to catch it?

**Comment by jberkel** [comment]
not enough information, closing
