### ISSUE TITLE
iphone 4s, 5 crash

### ISSUE THREAD

**Issue by longhoang2984** [stephencelis/SQLite.swift#704]
Hi,

Crashed on iphone 4s or 5 but other device run ok

<img width="759" alt="screen shot 2017-08-17 at 10 34 01" src="https://user-images.githubusercontent.com/11419002/29394912-b28e4422-8337-11e7-9dd3-2d5671922a6a.png">

**Comment by jberkel** [comment]
Need a full stacktrace with code example.
