### ISSUE TITLE
Weird fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by tuononh** [stephencelis/SQLite.swift#705]
I have a weird fatal error when getting data from database.
[StackOverFlow question](https://stackoverflow.com/questions/45752156/weird-fatal-error-unexpectedly-found-nil-while-unwrapping-an-optional-value)
```
print(row![col1]) -> crash 
print(row![col2]) -> "OK"
```
`col1` is the column I used to filter. Will its value vanish after filter?

**Comment by jberkel** [comment]
The value is probably null.

**Comment by ptaking** [comment]
@jberkel You can see my question on StackOverFlow. The data from that column was used to comparison. How can it be null? :D

**Comment by jberkel** [comment]
Please post your table definition, enable logging, and run the code again:

https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#logging
