### ISSUE TITLE
swift-4 branch receives errors

### ISSUE THREAD

**Issue by appsird** [stephencelis/SQLite.swift#706]
I received an error when using the latest swift-4 branch with Xcode 9 beta 5

In file FTS4.swift, the following lines 155 and 156 . For the first line, the substring(to:) call is deprecated.
For the second line, the distance(from:t0:) need both arguments to be unwrapped.

offset.pointee += Int32(string.substring(to: range.lowerBound).utf8.count)
length.pointee = Int32(view.distance(from: range.lowerBound.samePosition(in: view)!, to: range.upperBound.samePosition(in: view)!))

Also receive some warnings as per the attached image. Please make me aware when a new release is available.

![untitled](https://user-images.githubusercontent.com/8471833/29539577-6fa8a6ca-867f-11e7-9b36-99ad2c2356db.png)

**Comment by jberkel** [comment]
I've updated the branch to address these issues

**Comment by appsird** [comment]
Thanks. Brought down the update, errors and warnings gone.
