### ISSUE TITLE
Sort not working properly for date objects

### ISSUE THREAD

**Issue by uday-naidu** [stephencelis/SQLite.swift#709]
I tried using .order(column.asc) but its not working. It is basically sorting strings

**Comment by jberkel** [comment]
Can you post a complete example?

**Comment by Heromine** [comment]
Same here:
that is my code

`
            let listaordinata = stradaTerrTable.select(civicNumber).order(civicNumber.asc)
            let strada = try self.database.prepare(listaordinata)
            for civici in strada{
                ListaCivici.append(civici[civicNumber])
            }`
My civicNumber column is a string composed by int(s). What is wrong?

**Comment by jberkel** [comment]
@Heromine What type do you use for `civicNumber`? If it's a string/text type then the sorting will be lexical, not numerical. (e.g. "1339" < "988", because "1" < "9")

**Comment by jberkel** [comment]
stale
