### ISSUE TITLE
Does or should "join" clause in Query class support "select" statement?

### ISSUE THREAD

**Issue by lestathc** [stephencelis/SQLite.swift#71]
Hi, 

I am trying to implement such query using Query class.
```sql
select * from some_table
join (select id as fid, max(seq) as fseq from some_table group by some_value) as f
on id = fid and seq = fseq
```

I have code like:
```swift
let filterQuery = myTable.select(
  "id as fid",
  "max(seq) as fseq"
).group(someField).alias("f")
let onExp = Expression<Bool>(literal: "id = fid and seq = fseq")
let mainQuery = myTable.join(filterQuery, on: onExp)
```

But seems the joinClause function only takes the tableName and alias. The query becomes
```sql
select * from some_table
join some_table as f
on id = fid and seq = fseq
```

Should it expand the whole select statement here? Or is there other api I can use for this?

Thanks.

**Comment by stephencelis** [comment]
Do you need the sub-select? For the GROUP BY clause I suppose? This is on the TODO list, but isn't quite supported yet. You can, however, avoid the literal `Expression<Bool>(literal: "id = fid and seq = fseq")`:

``` swift
let filterQuery = myTable.alias("f")
let mainQuery = myTable
    .select(myTable[id], max(filterQuery[seq])
    .join(filterQuery, on: myTable[id] == filterQuery[id] && myTable[seq] == filterQuery[seq])
```

I'll try to sneak sub-SELECT support into a commit soon.

**Comment by lestathc** [comment]
Yes, I need sub-select, but for "join" clause, not "group by" clause.

Glad to know this feature will be here. For now I think I can change query to avoid this problem.

Thanks a lot.

**Comment by stephencelis** [comment]
This should now be possible:

``` swift
let fid = id.alias("fid")
let fseq = max(seq).alias("fseq")
let filterQuery = myTable.select(fid, fseq).group(someField)
let mainQuery = myTable.join(filterQuery, on: id == fid && seq == fseq)
```

**Comment by lestathc** [comment]
Awesome!!! Thank you so much for making this.

**Comment by SWIRIS** [comment]
I think this might be broken.

I have the following code:
```swift
let innerQuery = messageTable.group(messageConstants.roomId)
let outerQuery = roomTable.join(.leftOuter, innerQuery, on: roomConstants.id == messageConstants.roomId)
            .order(messageConstants.date.desc)
```

Inner's query `.asSQL()` returns the following:
`"SELECT * FROM \"Message\" GROUP BY \"roomId\""`

But outerQuery returns this:
`"SELECT * FROM \"Room\" LEFT OUTER JOIN \"Message\" ON (\"Room.id\" = \"roomId\")"`

Ignoring the `GROUP BY` clause of the inner query.

This is the current code in SQLite.swift that generates the join clause (it seems to be ignoring everything in `query` except for the table name)
```swift
    fileprivate var joinClause: Expressible? {
        guard !clauses.join.isEmpty else {
            return nil
        }

        return " ".join(clauses.join.map { type, query, condition in
            " ".join([
                Expression<Void>(literal: "\(type.rawValue) JOIN"),
                query.tableName(alias: true),
                Expression<Void>(literal: "ON"),
                condition
            ])
        })
    }
```

**Comment by 0xpablo** [comment]
I think this might be broken.

I have the following code:
```swift
let innerQuery = messageTable.group(messageConstants.roomId)
let outerQuery = roomTable.join(.leftOuter, innerQuery, on: roomConstants.id == messageConstants.roomId)
            .order(messageConstants.date.desc)
```

Inner's query `.asSQL()` returns the following:
`"SELECT * FROM \"Message\" GROUP BY \"roomId\""`

But outerQuery returns this:
`"SELECT * FROM \"Room\" LEFT OUTER JOIN \"Message\" ON (\"Room.id\" = \"roomId\")"`

Ignoring the `GROUP BY` clause of the inner query.

This is the current code in SQLite.swift that generates the join clause (it seems to be ignoring everything in `query` except for the table name)
```swift
    fileprivate var joinClause: Expressible? {
        guard !clauses.join.isEmpty else {
            return nil
        }

        return " ".join(clauses.join.map { type, query, condition in
            " ".join([
                Expression<Void>(literal: "\(type.rawValue) JOIN"),
                query.tableName(alias: true),
                Expression<Void>(literal: "ON"),
                condition
            ])
        })
    }
```

**Comment by ChanchalW** [comment]
What if I want data from both of the tables?
