### ISSUE TITLE
Swift-4 (iOS 11) Initializer for conditional binding must have Optional type, not 'String.UTF8View.Index'

### ISSUE THREAD

**Issue by askari01** [stephencelis/SQLite.swift#714]
**iOS 11 (swift-4) branch** 

- error: Initializer for conditional binding must have Optional type, not 'String.UTF8View.Index'
- file: FTS4.swift
- extension: Connection
- method: registerTokenizer
- lineNo: 156,157

```
 if let from = range.lowerBound.samePosition(in: view),
               let to = range.upperBound.samePosition(in: view) {
                offset.pointee += Int32(string[string.startIndex..<range.lowerBound].utf8.count)
                length.pointee = Int32(view.distance(from: from, to: to))
                return token
            } else {
                return nil
            }
```
<img width="1280" alt="screen shot 2017-08-25 at 6 04 41 pm" src="https://user-images.githubusercontent.com/6830947/29715236-e54722ce-89bf-11e7-8a7b-73bbf891ceea.png">

for the time being fix:

```
let from = range.lowerBound.samePosition(in: view)
            let to = range.upperBound.samePosition(in: view)
            if from != nil && to != nil {
                offset.pointee += Int32(string[string.startIndex..<range.lowerBound].utf8.count)
                length.pointee = Int32(view.distance(from: from, to: to))
                return token
            } else {
                return nil
            }
```

<img width="883" alt="screen shot 2017-08-25 at 6 10 16 pm" src="https://user-images.githubusercontent.com/6830947/29715525-1cf69c3a-89c1-11e7-882b-f5a3dfb9ae79.png">

**Comment by jberkel** [comment]
i suppose this is with beta6?

**Comment by askari01** [comment]
Using Xcode beta 5 and iOS 11 beta 7

**Comment by jberkel** [comment]
weird. are you sure the xcode beta is active? this got fixed just a few days ago.

**Comment by askari01** [comment]
Yeah i am sure because i am using swift 4 branch which will not compile on xcode 8.3.3

**Comment by jberkel** [comment]
hm, something is odd w/ your setup, it compiles both on travis and on my local machine (using Xcode 9 beta5). if you check the method signature in the API docs you see that it returns an optional value (`samePosition:in`).

**Comment by askari01** [comment]
yeah code works fine on Xcode beta 6

**Comment by jberkel** [comment]
great!
