### ISSUE TITLE
receiving deprecated warnings when compiling in Xcode 8

### ISSUE THREAD

**Issue by appsird** [stephencelis/SQLite.swift#716]
fyi: receive the following warnings 

![untitled](https://user-images.githubusercontent.com/8471833/29788328-06a28ca0-8be7-11e7-9772-66d053acc665.png)

**Comment by rpural** [comment]
I get the same warnings. Haven’t figured out how to correct it, and it gives no hint on what deprecated it.

**Comment by appsird** [comment]
Yes, though I do not receive these warnings in Xcode 9. And the same calls to sqlite3_trace appear in the Connection.swift file.

**Comment by jberkel** [comment]
No longer applies with Xcode9

**Comment by AegerBorder** [comment]
I ran into this in XCode 9.4.1 again when I compiled my app today.

![bildschirmfoto 2018-07-09 um 14 06 14](https://user-images.githubusercontent.com/33864294/42449528-4d85e9f4-8381-11e8-83fd-f1c91c6508e7.jpg)

**Comment by bishrant** [comment]
This still exists as of Xcode 12.0.1.
![image](https://user-images.githubusercontent.com/4143738/94731088-d65e9f80-0329-11eb-9402-a562fc492cb8.png)
