### ISSUE TITLE
How to get index number of a column?

### ISSUE THREAD

**Issue by ghopretz** [stephencelis/SQLite.swift#720]
I have create table using manual query like this :
```

try db!.execute("create table kontak(id INTEGER PRIMARY KEY AUTOINCREMENT, nama varchar(200), telpon varchar(200), alamat varchar(200) )")


```
I want to select it using manual query too like this :
```

        let hasil = try! db.selek(kueri: "select * from kontak")
        for baris in hasil{
                let id = (baris[0] as? Int64)! // <---using column index number
                let name = (baris[1] as? String)! // <---using column index number
                let phone = (baris[2] as? String)! // <---using column index number
                let address = (baris[3] as? String)! // <---using column index number
        }

```
I using column index number to get value.
Can i using column name to get the value instead using column index OR can i get column index using column name?

**Comment by jberkel** [comment]
You can use an `Expression` as subscript argument, see the docs:

https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#iterating-and-accessing-values
