### ISSUE TITLE
Ambiguous reference to member ‘foreignKey(_:reference:_:update:delete:)’

### ISSUE THREAD

**Issue by developerXiong** [stephencelis/SQLite.swift#729]
when I call the method :
```t.foreignKey(user_id, references: users, id, delete: .setNull)```
Compiler error reporting.

**Comment by atomkirk** [comment]
whats the answer here?

**Comment by atomkirk** [comment]
probably was a type. if you don't give it a valid operation, you get this error. I was using `.delete` instead of `.cascade` for example

```
t.foreignKey(categoryId, references: categories, id, update: .cascade, delete: .cascade)
```
