### ISSUE TITLE
Using "Int64" for SQLite type "INTEGER" instead of "Int"

### ISSUE THREAD

**Issue by lestathc** [stephencelis/SQLite.swift#73]
Hi,

From your code, you directly convert 64 bits integer to Swift "Int". It will cause unexpected result on 32-bits device. Could you map the SQLite type "INTEGER" to Swift "Int64"?

Thanks a lot.

```swift
            } else if let result = result as? Int {
                sqlite3_result_int64(context, Int64(result))
```

```swift
                case SQLITE_INTEGER:
                    return Int(sqlite3_value_int64(value))
```

```swift
        } else if let value = value as? Int {
            try(sqlite3_bind_int64(handle, Int32(idx), Int64(value)))
```

```swift
            case SQLITE_INTEGER:
                return Int(sqlite3_column_int64(self.handle, Int32(idx)))
```

**Comment by stephencelis** [comment]
Have you actually encountering a problem here? I think this is basically a non-issue, and changing it would negatively impact the interface. If you're worried about overflow (on an auto-incrementing key, for example), you could use a TEXT column (or UUIDs).

If you have suggestions for supporting `Int64` while letting the average user continue to use `Int`, please let me know.

**Comment by lestathc** [comment]
Hi, I am using an integer to store unix timestamp (comes from server). It is my fault to use Int at beginning. But once I want to switch to Int64, I have no chance to store it properly. 

I can use TEXT, but I don't think it is good idea. The sqlite type INTEGER can be at most 64bits on either 32bits device or 64bits device. So I think it should be nice to let caller has chance to pass or get a 64 bits integer even on 32bits device.

I have forked this repo and define an alias using macro to replace almost all Int:

```swift
#if SQLITE_USING_INT64_AS_INTEGER
public typealias SQLiteInt = Int64
#else
public typealias SQLiteInt = Int
#endif
```

Without "SQLITE_USING_INT64_AS_INTEGER", the common user do not need change anything.
With it, you are right, it indeed badly impact the interface, you must explicitly convert Int literal to Int64. But it is Swift language feature/bug.

Here is the change on my repo (all unit tests with/without the macro are passed), could you please take a look:

https://github.com/lestathc/SQLite.swift/commit/eb8c398be063a8a8be95e4a4964e53340dfe3ff5

Thanks.

**Comment by stephencelis** [comment]
Could you please try the `int64` branch I just pushed? It's off the Swift 1.2 branch for now, but I'll try to get a Swift 1.1-compatible branch up soon.

**Comment by chess92** [comment]
thank you so much for fixing this! saved my day! :)

**Comment by stephencelis** [comment]
Please let me know how this affects your interfaces (and how noisy your code becomes). If you're using the type-safe interface, hopefully it's limited to the times you use `Expression<Int64>`.

**Comment by stephencelis** [comment]
Closed by https://github.com/stephencelis/SQLite.swift/commit/5380d5b502bd76ea99fe0ec54785f6bacd1cb8c1

**Comment by lestathc** [comment]
Thanks for fixing. 

For some reason, I can not install xcode6.3, so I do not try this. But I think it woks like my forked solution with the compile flag. 

Thanks a lot.

**Comment by lestathc** [comment]
Oh, seems you have merged it with main branch, checked and changed my code. Work perfectly, thank you so much.

**Comment by stephencelis** [comment]
@lestathc Hope it's a clean solution for you!
