### ISSUE TITLE
Cannot build Sqlite for release

### ISSUE THREAD

**Issue by aliaziz** [stephencelis/SQLite.swift#730]
Hello, when I build my application in debug mode, it's successful.
But when I change to release, XCode throws Swift compiler errors about SQLite.
<img width="313" alt="screen shot 2017-09-21 at 11 29 48 am" src="https://user-images.githubusercontent.com/2377618/30686226-3aa8bcae-9ec0-11e7-89a5-8c1df9791c4c.png">

**Comment by aliaziz** [comment]
Fixed it, 
Changed CSQLite to SQLite3

**Comment by aliaziz** [comment]
Fixed it, 
Changed `CSQLite` to `SQLite3`

**Comment by jokerham** [comment]
Where did you fix it?

**Comment by jberkel** [comment]
this is already applied in the release branch.
