### ISSUE TITLE
How to do Bulk Insertion

### ISSUE THREAD

**Issue by ezCoding** [stephencelis/SQLite.swift#74]
```swift
let persons = myPersonArray
let personBindStmt = db.prepare("INSERT INTO \(personTable) (\(id) (\(name), \(town), \(birthday)) VALUES (?, ?, ?, ?)")
let friendIdBindStmt = db.prepare("INSERT INTO \(friendsTable) (\(id)) VALUES (?)")
for person in myPersonArray {
     // BULK INSERT HERE
    for friendID in person.friends {
       // BULK INSERT HERE
   }
}
// COMMIT TRANSACTION
```

Sorry, my SQLite skills aren't that good. Maybe it's not even possible. I'm trying to maximize performance. Thank you in advance ;)

**Comment by stephencelis** [comment]
I'm not sure what `personTable`, `id`, etc., are in this context. Are they `Expression` objects or raw strings? I'm also not sure what a `person` is.

If you're trying to use the raw SQL API (and assuming `person` is a struct of sorts), you could do something like this:

``` swift
let persons = myPersonArray
let personBindStmt = db.prepare("INSERT INTO \(personTable) (\(id) (\(name), \(town), \(birthday)) VALUES (?, ?, ?, ?)")
let friendIdBindStmt = db.prepare("INSERT INTO \(friendsTable) (\(id)) VALUES (?)")
db.transaction { _ in
    for person in myPersonArray {
        personBindStmt.run(person.id, person.name, person.town, person.birthday)
        if let lastId = db.lastId {
            for friendId in person.friends {
                friendIdBindStmt.run(lastId)
            }
        }
    }
    return .Commit
}
```

The above code of course was written without knowledge of what your schema intent is and without any kind of error/rollback handling.

If you wanted to run a bulk insert in a single statement, you'll need to somehow aggregate the SQL string and bindings before preparing/binding the statement itself.

If you're having more trouble, questions are generally reserved for www.stackoverflow.com, whereas GitHub Issues is for bug reporting and feature requests.

**Comment by ezCoding** [comment]
Thank you Stephen! That's exactly what I was looking for!
