### ISSUE TITLE
Please disable code coverage

### ISSUE THREAD

**Issue by IceyTH** [stephencelis/SQLite.swift#742]
Please disable code coverage to support Xcode9 with Carthage.

'codeCoverageEnabled' to "NO" in "SQLite iOS.xcscheme".

Thanks
IceyTH

**Comment by crudolf** [comment]
This is required since apple rejects submissions with activated codeCoverageEnabled:

> Invalid Bundle - Disallowed LLVM instrumentation. Do not submit apps with LLVM profiling instrumentation or coverage collection enabled. Turn off LLVM profiling or code coverage, rebuild your app and resubmit the app.

We use sqlite using carthage.

**Comment by jberkel** [comment]
Weird, that's a setting of the test action. Why does this affect the release build?

**Comment by jberkel** [comment]
Anyway, I've just removed the option since it's not needed. closing.
