### ISSUE TITLE
SQLite-Bridging.h  #import "sqlite3.h" error

### ISSUE THREAD

**Issue by daolanghuang** [stephencelis/SQLite.swift#745]
Include of non-modular header inside framework module 'SQLite.SQLite_Bridging': '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/sqlite3.h'

import:
CocoaPods

version:
0.11.4

**Comment by jberkel** [comment]
What's your Xcode version? SQLite.swift requires XCode 9.

**Comment by daolanghuang** [comment]
Thank you！

**Comment by xtazz** [comment]
After updating this started happening to me on Xcode 10 and 0.11.5. But rolling back cocoapods to older version somehow didn't solve the issue. Weird.

**Comment by jonathanrfisher1** [comment]
I'm also experiencing this on Xcode 10.  Searching for a solution...and to fully understand what the issue really is.

**Comment by kliron** [comment]
Same here, on Xcode 10

**Comment by justinTrantham** [comment]
I am having the same issue on Xcode 10. Tried about everything I can think of. Using 0.11.5
