### ISSUE TITLE
Primary Key restricted to Int64?

### ISSUE THREAD

**Issue by xenadu** [stephencelis/SQLite.swift#75]
Is there any reason to force the primary key to be `Int64`? Sqlite supports BLOB primary keys which work rather well for UUIDs.

**Comment by stephencelis** [comment]
Did you read the documentation on the `primaryKey` function?

Only the shorthand should be restricted, since the basic use-case is an integer that autoincrements:

``` swift
db.create(table: users) { t in
    t.column(id, primaryKey: true)
}
// CREATE TABLE "users" (
//     "id" INTEGER PRIMARY KEY NOT NULL
// )
```

You should be able to create a primary key of any type if you use the `primaryKey` function:

``` swift
let uuid = Expression<Blob>("uuid")
db.create(table: users) { t in
    t.column(uuid)
    t.primaryKey(uuid)
}
// CREATE TABLE "users" (
//     "uuid" BLOB NOT NULL,
//     PRIMARY KEY("uuid")
// )
```

**Comment by stephencelis** [comment]
Closing for this now. Please let me know if it actually doesn't work for you!

**Comment by xenadu** [comment]
Ok, I obviously didn't pay enough attention. It might be helpful to call this out in the docs.

Thanks!

**Comment by stephencelis** [comment]
> It might be helpful to call this out in the docs.

Hm...I try to!

> `primaryKey` adds an `INTEGER PRIMARY KEY` constraint to a single column. (See the `primaryKey` function under [Table Constraints](https://github.com/stephencelis/SQLite.swift/blob/10ce76ff94726182dbcb61fb9b25d41c6dba0fca/Documentation/Index.md#table-constraints) for non-integer primary keys).

—https://github.com/stephencelis/SQLite.swift/blob/10ce76ff94726182dbcb61fb9b25d41c6dba0fca/Documentation/Index.md#column-constraints

Any ideas on how to better communicate this?

**Comment by xenadu** [comment]
Honestly, rather than do that I just went ahead and submitted a PR #76 to remove the restriction
