### ISSUE TITLE
XCode Build Error - "ambiguous use of 'sqlite3_value_type'

### ISSUE THREAD

**Issue by mathetesxristou** [stephencelis/SQLite.swift#750]
A build of the current SQLite.swift snapshot, and XCode 9 encounters the following compile issues. Project has SQLCipher enabled, and was building successfully and working well in the past.

**Connection.swift:557:24: error: ambiguous use of 'sqlite3_value_type'
                switch sqlite3_value_type(value) {
                       ^**
SQLite3.sqlite3_value_type:1:13: note: found this candidate
public func sqlite3_value_type(_: OpaquePointer!) -> Int32
            ^
SQLCipher.sqlite3_value_type:1:13: note: found this candidate
public func sqlite3_value_type(_: OpaquePointer!) -> Int32
            ^
**Connection.swift:559:79: error: ambiguous use of 'sqlite3_value_bytes'
                    return Blob(bytes: sqlite3_value_blob(value), length: Int(sqlite3_value_bytes(value)))
                                                                              ^**
SQLite3.sqlite3_value_bytes:1:13: note: found this candidate
public func sqlite3_value_bytes(_: OpaquePointer!) -> Int32
            ^
SQLCipher.sqlite3_value_bytes:1:13: note: found this candidate
public func sqlite3_value_bytes(_: OpaquePointer!) -> Int32
            ^
**Connection.swift:561:28: error: ambiguous use of 'sqlite3_value_double'
                    return sqlite3_value_double(value)
                           ^**
SQLite3.sqlite3_value_double:1:13: note: found this candidate
public func sqlite3_value_double(_: OpaquePointer!) -> Double
            ^
SQLCipher.sqlite3_value_double:1:13: note: found this candidate
public func sqlite3_value_double(_: OpaquePointer!) -> Double
            ^
**Connection.swift:563:28: error: ambiguous use of 'sqlite3_value_int64'
                    return sqlite3_value_int64(value)
                           ^**
SQLite3.sqlite3_value_int64:1:13: note: found this candidate
public func sqlite3_value_int64(_: OpaquePointer!) -> sqlite3_int64
            ^
SQLCipher.sqlite3_value_int64:1:13: note: found this candidate
public func sqlite3_value_int64(_: OpaquePointer!) -> sqlite3_int64
            ^
**Connection.swift:567:58: error: ambiguous use of 'sqlite3_value_text'
                    return String(cString: UnsafePointer(sqlite3_value_text(value)))
                                                         ^**
SQLite3.sqlite3_value_text:1:13: note: found this candidate
public func sqlite3_value_text(_: OpaquePointer!) -> UnsafePointer<UInt8>!
            ^
SQLCipher.sqlite3_value_text:1:13: note: found this candidate
public func sqlite3_value_text(_: OpaquePointer!) -> UnsafePointer<UInt8>!
            ^
**Connection.swift:593:9: error: ambiguous use of 'sqlite3_create_function_v2'
        sqlite3_create_function_v2(handle, function, Int32(argc), flags, unsafeBitCast(box, to: UnsafeMutableRawPointer.self), { context, argc, value in
        ^**
SQLite3.sqlite3_create_function_v2:2:13: note: found this candidate
public func sqlite3_create_function_v2(_ db: OpaquePointer!, _ zFunctionName: UnsafePointer<Int8>!, _ nArg: Int32, _ eTextRep: Int32, _ pApp: UnsafeMutableRawPointer!, _ xFunc: (@convention(c) (OpaquePointer?, Int32, UnsafeMutablePointer<OpaquePointer?>?) -> Swift.Void)!, _ xStep: (@convention(c) (OpaquePointer?, Int32, UnsafeMutablePointer<OpaquePointer?>?) -> Swift.Void)!, _ xFinal: (@convention(c) (OpaquePointer?) -> Swift.Void)!, _ xDestroy: (@convention(c) (UnsafeMutableRawPointer?) -> Swift.Void)!) -> Int32
            ^
SQLCipher.sqlite3_create_function_v2:1:13: note: found this candidate
public func sqlite3_create_function_v2(_ db: OpaquePointer!, _ zFunctionName: UnsafePointer<Int8>!, _ nArg: Int32, _ eTextRep: Int32, _ pApp: UnsafeMutableRawPointer!, _ xFunc: (@convention(c) (OpaquePointer?, Int32, UnsafeMutablePointer<OpaquePointer?>?) -> Swift.Void)!, _ xStep: (@convention(c) (OpaquePointer?, Int32, UnsafeMutablePointer<OpaquePointer?>?) -> Swift.Void)!, _ xFinal: (@convention(c) (OpaquePointer?) -> Swift.Void)!, _ xDestroy: (@convention(c) (UnsafeMutableRawPointer?) -> Swift.Void)!) -> Int32

**Comment by jberkel** [comment]
which version of SQLCipher are you building against?

**Comment by mathetesxristou** [comment]
Version v3.4.1 (last commit: df092f0a Dec 28, 2016). My projects were building and running until recently when I updated Xcode.

Thank you for looking into this.

**Comment by jberkel** [comment]
Hm not sure. I've only tested the SQLCipher integration via CocoaPods (where it works fine).

I think the problem is that now SQLite3 is always imported. You'd have to define `SQLITE_SWIFT_SQLCIPHER` to avoid this, but then you'll probably get errors that the module `SQLCipher` can't be found.

**Comment by mathetesxristou** [comment]
Thank you for pointing out that integration via CocoaPods is working. I chose that route. Again, thanks for looking into this.
