### ISSUE TITLE
Cannot invoke 'filter' with an argument list of type '(Bool) while select * from users

### ISSUE THREAD

**Issue by wtianhaw94** [stephencelis/SQLite.swift#752]
Hi,
im trying to execute the query select * from users where id == 1 but it seems like error.
here are my codes:

 let alice = accounts.filter(id == self.id)

the errors says 'Cannot invoke 'filter' with an argument list of type '(Bool)'

Kindly help. Thanks

**Comment by Z--EN** [comment]
I have the same issue. I can't find suitable type for second parameter for filter and where.

**Comment by jberkel** [comment]
please use stackoverflow for this.
