### ISSUE TITLE
How create one-to-many relationship?

### ISSUE THREAD

**Issue by Diekrul** [stephencelis/SQLite.swift#759]
i recently started using sqlite.swift and i cant figure out how create a one to many relationship. For example, if a i have 2 classes:

    class Equipment{
    
        let equipment = Table("equipment")
        let id = Expression<Int64>("id")
        let name = Expression<String?>("name")
        let equipment_type_id = Expression<Int64>("equipment_type_id")

    }
    func createTable(_ database: Connection){
        let createTable = self.equipment.create(ifNotExists: true) { 
        (table) in
            table.column(self.id, primaryKey: true)
            table.column(self.name)
            table.column(self.equipment_type_id)
        }
        do {
            try database.run(createTable)
        } catch  {
            print(error)
        }
    }

And

    class EquipmentType{
    
        let equipmentType = Table("equipment_type")
        let id = Expression<Int64>("id")
        let name = Expression<String?>("name")
    }

    func createTable(_ database: Connection){
        let createTable = self.equipmentType.create(ifNotExists: true) { (table) in
            table.column(self.id, primaryKey: true)
            table.column(self.name)
        }
        do {
            try database.run(createTable)
        } catch  {
        }
    }

it's possible get the name of the equipment_type of one equipment doing a query like this?:
    
    var name = equipment.equipment_type.name

Thanks

**Comment by Suneel-Gunupudi** [comment]
please check tutorial for one to many relationship,
https://swiftludus.org/create-a-queryable-music-library-using-sqlite-databases/
