### ISSUE TITLE
Reference existing database form another ViewController

### ISSUE THREAD

**Issue by AegerBorder** [stephencelis/SQLite.swift#762]
Hi,

great work on this one!
I've created a table in an iOS App and I'm writing some variables to a few columns in that table. All works fine and I have to admit that I'm a total beginner so I tried everything to load the existing entries to be output in another ViewController. I just didn't find out how to connect to the database because all variables/constants are in the other ViewController where the Table is created/filled with content.

Can anyone tell me how to access the existing Database in another ViewController?

Here's what I did in the first ViewController:

This is a short version of my first ViewController:

```
class FirstViewController: UIViewController {
    
    let movies = ["Movie1", "Movie2", "Movie3", "Movie4", "Movie5"]
    let ratingInt = 8
    var database: Connection!

    let filmTable = Table("films")
    let id = Expression<Int>("id")
    let filmName = Expression<String>("filmname")
    let rating = Expression<Int>("personalrating")

//Just an example of adding a movie from the array above to a database field:

let insertFilm = self.filmTable.insert(self.filmname <- movies[0], self.rating <- ratingInt)
                
                do {
                    try self.database.run(insertFilm)
                } catch {
                    print(error)
                }

override func viewDidLoad() {
        super.viewDidLoad()

        
        do {
        let documentDirectory = try FileManager.default.url(for: .documentDirectory, in: .userDomainMask, appropriateFor: nil, create: true)
        let fileUrl = documentDirectory.appendingPathComponent("films").appendingPathExtension("sqlite3")
        let database = try Connection(fileUrl.path)
        self.database = database
        } catch {
            print(error)
        }
        
        let createTable = self.filmTable.create(block: { (table) in
            table.column(self.id, primaryKey: true)
            table.column(self.filmname)
            table.column(self.personalrating)
        })
        
        do  {
            try self.database.run(createTable)
            print("Created table")
        } catch {
            print(error)
        }
}
```
                
Now for the second ViewController. How would I access this existing and filled database now? It seems that there is a connection with this following code I took from the documentation here. But I'm just not sure if there's really a connection to the database above and how to reference the table fields in there now :-/

```
class SecondViewController: UIViewController {
override func viewDidLoad() {
        super.viewDidLoad()
 
        let path = NSSearchPathForDirectoriesInDomains(
            .documentDirectory, .userDomainMask, true
            ).first!
        
        
            let database = try Connection("\(path)/filme.sqlite3")
            print("Connection established")
}
}
```

I hope it's OK to post this here. I've just started learning to code (in general!) and it took me here... so... sorry if it's misplaced.

Thanks a lot for any hints or code snippets
Regards
Patrick

**Comment by AegerBorder** [comment]
Wait... let's consider this a classical fail-loop. I did not even think about to set all the variables and just open the database instead of creating (create: false).
All data is in my second View Controller now. Sorry for that. There are these moments when you know you're on a thing for too long not seeing the obvious things...

**Comment by Deadly-Elmo** [comment]
Hi,

I might sound stupid saying this, but I was just wondering what you did exactly (like what you mean by "set all the variables and just open the database instead of creating". Thanks!
