### ISSUE TITLE
How to select column from table where id=?

### ISSUE THREAD

**Issue by sunghwan523** [stephencelis/SQLite.swift#763]
Hi.

I want to have column value.

select column from table where column2=a  value....

my column = id, image, title, content, favorite, shop

i checked update, insert , select * from table.

i want to check 'select favorite from table where content="ABC" '

```
func  test() -> AnySequence<Row>? {
  do{
      let filterCondition = (content =="ABC")
      return try Database.shared.connection?.prepare(self.tbTest.select(favorite).filter(filterCondition))
  } catch{ 
      print("Error")
      return nil
  }
}
```
checked. but it was a error

```
if let query: AnySequence<Row> = testDatabase.shared.test(){
  for eachtest in query {
      testDatabase.shared.toString(data:  eachtest) 
  }
}
```

error:
fatal error : 'try!' expression unexpectedly raised an error: No such column '"id"' in columns ["\"favorite\""]: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-900.0.65.2/src/swift/stdlib/public/core/ErrorType.swift, line181

Please help me. Thankyou.

**Comment by mingsai** [comment]
The error indicates that the column expression you are using is not correct, so there is likely nothing wrong with you logic. Check the db and visually confirm that the favorites table has an "id" column and that a row containing "ABC" exists. 

Basic logic:
```
fileprivate static let idColumn = Expression<Int64>("id")
....
(in your method)
let selected = medicineTable.filter(idColumn == itemId)
//gives you an array of rows
let medicines = Array(try db.prepare(medicineTable))
//loop, map, foreach, etc. can be performed on the resulting array. You can convert the row object to a specific type defined in your model.
```

**Comment by Z--EN** [comment]
Interesting what has the type itemId? I tried some and can't find suitable.
