### ISSUE TITLE
Swift 4 characters warning 

### ISSUE THREAD

**Issue by jotaro17** [stephencelis/SQLite.swift#768]
- SQLite.swift 0.11.4
- Xcode 9.2
- Swift 4

- There are five warnings when try to compile in swift 4 with Xcode 9.2:
`'characters' is deprecated: Please use String or Substring directly`

**Comment by YunyueLin** [comment]
me too. Hope you can repair this warning.

**Comment by jberkel** [comment]
This is already fixed on master, but not released yet

**Comment by YunyueLin** [comment]
@jberkel  thanks

**Comment by ethansinjin** [comment]
Any update on this?

**Comment by timbms** [comment]
Also would be curious when this will be released.

**Comment by chrisvanbuskirk** [comment]
How about pointing to the latest commit.

    pod 'SQLite.swift', :git => 'https://github.com/stephencelis/SQLite.swift.git', :commit => 'c052d4153b617d6f16d26ac5b924afe0a6dd5874'

**Comment by ethansinjin** [comment]
While that works well for projects using SQLite.swift directly, projects using pods with SQLite.swift as a dependency can't really get away with this.

**Comment by jberkel** [comment]
closing as stale
