### ISSUE TITLE
Support for Carthage

### ISSUE THREAD

**Issue by JeffBNimble** [stephencelis/SQLite.swift#77]
I'm trying to reference your project using Carthage and it won't resolve since you have no releases. Would you mind creating a release, even if it's something like 0.0.1?

Carthage apparently will not resolve anything that doesn't have a release. See [https://github.com/Carthage/Carthage](here) for more info.

**Comment by stephencelis** [comment]
Carthage shouldn't require a version. You simply need to specify a branch.

```
github "stephencelis/SQLite.swift", "swift-1-2"
```

**However**, SQLite.swift can't be built using Carthage right now, and I'm not sure I'll ever be able to support it. There are two blockers:

- https://github.com/Carthage/Carthage/issues/340
- https://github.com/Carthage/Carthage/issues/341

Beyond this, I think Carthage's pre-compiled frameworks aren't compiled with the same build settings as your project, so things that require `DEBUG` (like assertions) wouldn't work as expected in development.

I highly recommend using the installation instructions given in the README, for now, and checking SQLite.swift as a submodule that integrates into Xcode as a working copy.

**Comment by stephencelis** [comment]
The `wontfix` label is tentative. I'll explore moving back to a non-universal framework sometime in the future, though I'd want to thoroughly test that assertions are properly surfaced. If not, I'll have to also revisit how assertions are raised.

**Comment by stephencelis** [comment]
@ctava Sorry, I missed your comment earlier. If you have a proposed PR fix, please submit it, but at the moment the fixes are needed in Carthage itself. I'd love to have SQLite.swift work out-of-the-box for both Carthage and CocoaPods, but at the moment its setup seems to prohibit it.

**Comment by stephencelis** [comment]
Going to reopen this with a `help wanted` tag. I'd prefer a pull request without compromises in the complexity of how SQLite.swift is structured as a project and repository, but will make compromises where it makes sense.

**Comment by Rupert-RR** [comment]
Looks like https://github.com/Carthage/Carthage/pull/622 fixes part of this!

**Comment by schickling** [comment]
Yes with the next Carthage version universal builds are supported finally! :+1:

**Comment by stephencelis** [comment]
Closing this as support will come with Carthage!

**Comment by lukescott** [comment]
Should probably keep this open until support for universal builds are released. The current release, 0.8, does not include this.

For others that need this now, you have to install the latest version on master by running:
```bash
brew remove carthage
cd ~/Desktop
git clone https://github.com/Carthage/Carthage
cd ./Carthage
make install
```

Keep the cloned repo around until this is released. When it has been released you can return to the brew installed version by doing running:
```bash
cd ~/Desktop/Carthage
make uninstall
brew update
brew install carthage
```

The carthage branch on this repo does work, so it might be good to update it as a secondary option. The iOS target on that branch is iOS 8.3 - it can be set to at least iOS 8.0.

**Comment by stephencelis** [comment]
@lukescott Yeah, the Carthage branch here is out of date and most of the work that went into it was pushed into the Swift 2 migration. I hope to get a bit more time to better organize these efforts in the future, but I've been a little strapped for bandwidth recently.

**Comment by stephencelis** [comment]
Reopening for now. Will close with the next version of Carthage or with the mainlining of the `swift-2` branch, whichever comes first.

**Comment by stephencelis** [comment]
Should be in the shipping version of Carthage!
