### ISSUE TITLE
Performance issue to iterate through a returned array 

### ISSUE THREAD

**Issue by zhouhao27** [stephencelis/SQLite.swift#770]
My code:

```
    // 1
    var array = [T]()
    let query = table.filter(createdBy == userId).order(timeStamp.desc)
    // 2
    let items = try connection.prepare(query)
    for item in items {
    }
    // 3
```

I recorded the time for 1,2,3. Actually the query is quite fast but it's very slow to iterate through the items return (I don't want to past items from Sqlite to my controller class. So I convert them to my own model here). Any suggestion?

**Comment by zhouhao27** [comment]
Take about 4-5s for about 100 records which is too slow.

**Comment by jberkel** [comment]
maybe you're loading a lot of data.  sorry, this is out of scope.
