### ISSUE TITLE
Use of unresolved identifier 'Connection'

### ISSUE THREAD

**Issue by sayansardar91** [stephencelis/SQLite.swift#771]
Hi Stephencelis,

I am trying to make a Database Connection using the SQLite.swift library. But it's giving me the Use of unresolved identifier 'Connection'.

I am using Xcode 9.

<img width="1168" alt="screen shot 2018-01-06 at 11 02 05 pm" src="https://user-images.githubusercontent.com/3690646/34642233-b10343dc-f335-11e7-90c5-fc5d04027e1d.png">

Please help me I am here new to use this Library. I am not getting any way to read of this issue.

**Comment by yaslab** [comment]
I think `SQLite3` is a C library. To use the SQLite.swift library, import `SQLite`. (Not `SQLite3`)

**Comment by sayansardar91** [comment]
Thank You, for your precious suggestion. I have solved it by my-self, I have to create a Bridge-Header for the SQLite3 and the problem solved.
