### ISSUE TITLE
Connection.execute and Connection.run always throw SQLITE_OK

### ISSUE THREAD

**Issue by bpo217** [stephencelis/SQLite.swift#772]
## Build Information

- [x] I have read [CONTRIBUTING](https://github.com/stephencelis/SQLite.swift/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

```
let db = Connection()
let sql = "SELECT * FROM non_existent_table;"

do {
    try db.execute(sql)
    print("success!")
} catch let e as NSError where e.code == 0 {
    print("also success")
} catch {
    print("error")
}
```

### What did you expect to happen?

`error` to be printed.

### What actually happened instead?

`also success` is printed.  

With SQL which should fail, the error code is always zero.  (SQLITE_OK)

### Environment

List the software versions you're using:

 - Carthage: *0.27.0*
 - macOS: *10.13.2*
 - SQLite.Swift: *0.11.4*
 - Swift Version: *4.0*
 - Xcode Version: *9.2 (9C40b)* 

### Notes

It seems the only way I can get `success` to be printed is by passing an empty string.  
I'm pretty sure this is a bug but is this the expected behavior?

**Comment by jberkel** [comment]
a cast to `NSError` always succeeds.

https://developer.apple.com/forums/thread/17431
