### ISSUE TITLE
Getting wrong data type instead defined in table schema

### ISSUE THREAD

**Issue by AshwinDamji** [stephencelis/SQLite.swift#773]
I am using this library in my Swift application.
I am facing issue when executing select query-
**Statement** class has a property  **row** which returns value in another type instead which is defined in table schema.
**row** property is define below-
public lazy var **row**: Cursor = Cursor(self)

datatype is defined while adding elements in **row** as below-
```
extension Cursor : Sequence {

    public subscript(idx: Int) -> Binding? {
        
        switch sqlite3_column_type(handle, Int32(idx)) {
        case SQLITE_BLOB:
            return self[idx] as Blob
        case SQLITE_FLOAT:
            return self[idx] as Double
        case SQLITE_INTEGER:
            return self[idx] as Int64
        case SQLITE_NULL:
            return nil
        case SQLITE_TEXT:
            return self[idx] as String
        case let type:
            fatalError("unsupported column type: \(type)")
        }
    }
}
```

Consider below example-
e.g. I have a table item with below 3 columns
itemId as Text
itemName as Text
itemPrice as Text

While executing SELECT query sometimes itemPrice contains value of type String and sometimes  Double. It should contain value of type as String always which is defined in table schema instead.

```
let statement = try dbConnection?.prepare(query)
for row in statement! {
//row[2] does not matches the type which is defined in database schema.
//sometimes it contains value as Double instead of String(Text)
}
```

Please help me here to get values in correct type which is defined in table schema.

**Comment by jberkel** [comment]
please use stackoverflow for this

**Comment by AshwinDamji** [comment]
Thank you
