### ISSUE TITLE
all joins failing in Swift 4 - 0.11.4, works in 0.11.2

### ISSUE THREAD

**Issue by mtannerfors** [stephencelis/SQLite.swift#775]
First of all - thanks for an amazing lib.

Just been fighting all day with a line that has worked in our code for 2 years, related to a join. Using release 0.11.4 on latest xcode 9.2 (9C40b) - using as Pod.

`let q = table.select(Feature.table[*]).join(Feature.table, on: Feature.table[Feature.idExpr] == Zone.featureIdExpr).filter(ids.contains(Zone.table[idExpr]))`

Until latest release it has worked perfect but now we only get "Unable to read data" in the join. Have attempted with several very basic joins, the main select shows the table, but all joins attempted simpy show "Unable to read data".

Looked through recent commits and there os nothing obvious that has changed.

I just reverted back to 0.11.2 and all works fine and dandy - Someone broken something or am I missing something obvious?

**Comment by jberkel** [comment]
can you try again with 0.13.0?
