### ISSUE TITLE
Does this work on Linux with Swift 3 or 4?

### ISSUE THREAD

**Issue by git-bee** [stephencelis/SQLite.swift#784]
The title says it all.

**Comment by crspybits** [comment]
No love on this? I'm interested in this too, and wondering if this library (or other Sqlite wrappers) could be portable to Android. Of course, there's a couple of questions there including porting a Swift-based library to Android.

**Comment by bpo217** [comment]
I bet it does.  Browsing the import statements in some of the files I came across:
```swift
import Foundation
import Dispatch
```
Foundation should work on Linux.
Dispatch is implicitly imported on macOS but required in Linux. (For DispatchQueue)
So I'd say yes.  On your Linux: install Sqlite3, swift, test it out, then come back and share what happened!

**Comment by jberkel** [comment]
It does work on Linux (#315, #594),  but I just realized that it isn't documented at all.
