### ISSUE TITLE
Ambiguous use of 'init'

### ISSUE THREAD

**Issue by isurukej** [stephencelis/SQLite.swift#787]
I am creating a new column using below steps:

it works fine in version 0.11.3 (in Swift3). But after update my code to Swift 4, I also update SQLite.swift  to 0.11.4 via CocoaPods, and it gives '**Ambiguous use of 'init'**'.
Xcode : 9.2
OS X : 10.12.6

please give me steps to fix this issue?

![screen shot 2018-03-30 at 10 35 29 am](https://user-images.githubusercontent.com/502236/38125390-b7e13544-3406-11e8-99cf-c30ada7df008.png)

**Comment by migro1982** [comment]
I have the same problem. you found solution?

**Comment by jberkel** [comment]
Looks like a Swift issue, not SQLite.swift
