### ISSUE TITLE
Version 9.3 (9E145) generates warnings

### ISSUE THREAD

**Issue by appsird** [stephencelis/SQLite.swift#788]
I downloaded and installed latest Xcode Version 9.3 (9E145) and iOS 11.3 today.

Now, a number of warnings are generated due to deprecations. would appreciate if you could clean  these and generate a new release.

![untitled](https://user-images.githubusercontent.com/8471833/38155390-5bbb7b6e-342c-11e8-9eab-0e3fbf101740.png)

![untitled 2](https://user-images.githubusercontent.com/8471833/38155427-9020e484-342c-11e8-93ed-3afb8a1b0c2e.png)

**Comment by jberkel** [comment]
Fixed in master

**Comment by appsird** [comment]
Tried to update my pod, though still brings down version 0.11.4 using

  pod 'SQLite.swift'


The following fails:


 pod 'SQLite.swift' '~> 0.11.5'


[!] Unable to find a specification for `SQLite.swift~> 0.11.5`


Please make me aware how to bring down the new version.


Brian

**Comment by jberkel** [comment]
I'll do a release soon. In the meantime,  can you try:

```
pod  'SQLite.swift' , git: 'https://github.com/stephencelis/SQLite.swift.git'
```

**Comment by jberkel** [comment]
Released.

**Comment by appsird** [comment]
Thank's so much for your contribution. 

Latest now compiles without warning in Xcode Version 9.3 (9E145)
