### ISSUE TITLE
How to delete database file

### ISSUE THREAD

**Issue by AnilTodkar** [stephencelis/SQLite.swift#789]
How to delete a whole database file?

**Comment by saormart** [comment]
If you want to delete the database file (mydatabase.sqlite), you must do it on your programing code...
In Swift 4:

> let fm = FileManager.default
do {
	let vFileURL = NSURL(fileURLWithPath: "Your DB file URL path")
	try fm.removeItem(at: vFileURL as URL)
	print("Database Deleted!") 
} catch {
	print("Error on Delete Database!!!")
}

**Comment by anilsutariya** [comment]
[logging] BUG IN CLIENT OF libsqlite3.dylib: database integrity compromised by API violation: vnode unlinked while in use: /private/var/mobile/Containers/Data/Application/9BA85548-C334-4119-B583-69FFBD88FBF9/Documents/inspectionDB.sqlite3

**Comment by anilsutariya** [comment]
Below code causing error.

func deleteDatabase(filePath : String)
{
        let filemManager = FileManager.default
        do {
            let fileURL = NSURL(fileURLWithPath: filePath)
            try filemManager.removeItem(at: fileURL as URL)
            print("Database Deleted!")
        } catch {
            print("Error on Delete Database!!!")
        }
}

**Comment by saormart** [comment]
The code looks fine, but that error seems that your app may doing some DB transaction after you delete it !
So, that error also depends of your app behavior after you delete it! In my case, when I really need to force it to be deleted, I send an alert to the user asking to restart the app, and force it to close by adding the code: "exit(0)" after "OK" of the alert message is tapped! So this way when the app is reopened, the new Database is created!

**Comment by anilsutariya** [comment]
Thanks !
