### ISSUE TITLE
Could not build project for iOS

### ISSUE THREAD

**Issue by mediarium** [stephencelis/SQLite.swift#79]
Could not build project for iOS after COMMIT 5380d5b: “Preserve 64-bit integers on 32-bit platforms”.

Get an errors in Schema.swift:
“Same-type constraint type 'Int64' does not conform to required protocol 'Bindable'” for “public func column< V: Value where V.Datatype == Int64 >(...) {...}”

and:
“Same-type constraint type 'String' does not conform to required protocol 'Bindable'” for “public func column< V: Value where V.Datatype == String >(...) {...}”

**Comment by stephencelis** [comment]
Thanks for the report! Would you please post the failing lines in question and the associated expression objects/types?

**Comment by mediarium** [comment]
Can't build my “Cocoa Touch Framework” for iOS with SQLite.swift from “swift-1-2” branch (with Xcode 6.3 beta 2).

I was upload simple project to test here:
https://github.com/mediarium/cocoa-deps-with-sqlite

**Comment by stephencelis** [comment]
This looks like it's a Swift 1.2 bug in incremental builds (though an incremental build of the SQLite.swift framework itself works for me). `Int64` definitely conforms to `Bindable` (via the `Number` protocol) in another file. I'd advise you to file a radar with Apple: https://bugreport.apple.com

Workarounds: if you enable "Whole Module Optimization" (in the build settings), it builds just fine for me (albeit much slower). You could also try concatenating all the SQLite.swift source files into one.

(I'm also a bit confused by your example: the project you link to _is_ a framework, so it won't work with iOS 7, either.)

**Comment by mediarium** [comment]
Ok, I will try that. Thanks for your help.

“the project you link to is a framework” — yes, you right. I use this module as framework for development for iOS 8+ only, but later will convert it to the static library for iOS 7/8.

**Comment by stephencelis** [comment]
> “the project you link to is a framework” — yes, you right. I use this module as framework for development for iOS 8+ only, but later will convert it to the static library for iOS 7/8.

You might want to test that. I'm not sure it's possible to compile static Swift libraries.

**Comment by mediarium** [comment]
It's not a problem. I already do that before.

For example you can see this project:
https://github.com/AlexDenisov/ToySwiftModule

**Comment by garker** [comment]
I could not get any part of SQLite to build on IOS and have given up.

**Comment by stephencelis** [comment]
@garker Sorry to hear that! Would love to help but you'll need to provide more information if you're interested in getting things working.
