### ISSUE TITLE
Putting column values into an array

### ISSUE THREAD

**Issue by Chullainn** [stephencelis/SQLite.swift#790]
Hi! How would I pluck the values of a tables column and place them into a normal swift array?? This is what I have so far but I don't know where to go from here:

    `do {
            let fetchUsers = db.table.filter(Title == "Bob")
            let emails = fetchUsers(email)
            let emailArray = Array(try db.prepare(emails))
            
        } catch {
            print(error)
        }`

**Comment by jberkel** [comment]
please use stackoverflow
