### ISSUE TITLE
Insert Example 

### ISSUE THREAD

**Issue by ramy814** [stephencelis/SQLite.swift#793]
need example to insert 
      let stmt = try db.prepare("INSERT INTO Login (id , name, email , agreement_id) VALUES (?,?,?,?)")

**Comment by damikon8** [comment]
```
try db.run(login.insert(email <- "alice@mac.com", name <- "Alice"))
// INSERT INTO "login" ("email", "name") VALUES ('alice@mac.com', 'Alice')

try db.run(login.insert(or: .replace, email <- "alice@mac.com", name <- "Alice B."))
// INSERT OR REPLACE INTO "login" ("email", "name") VALUES ('alice@mac.com', 'Alice B.')
```
The insert function, when run successfully, returns an Int64 representing the inserted row’s ROWID.

```
do {
    let rowid = try db.run(login.insert(email <- "alice@mac.com"))
    print("inserted id: \(rowid)")
} catch {
    print("insertion failed: \(error)")
}
```

**Comment by ramy814** [comment]
i need to insert without login Object  i need another way

============================
 Eng. Rami Eid Gayadah
 Computer Engineer at Municipality of Gaza
 E-mail  ramy.814@gmail.com
 Phone  (0599) 316286
============================
