### ISSUE TITLE
More convenient transaction support

### ISSUE THREAD

**Issue by alecthomas** [stephencelis/SQLite.swift#8]
Hi,

The transaction support is not that convenient IMO. It forces pre-generation of statements with no opportunity for logic inside the transaction.

That is, AFAICT, you can not perform a select inside the transaction then conditionally issue other statements based on the result. Or in fact, issue any kind of conditional statements.

It also makes decomposition of many statements into separate functions more difficult, forcing all functions to return Statements.

eg. I can not do this:

```swift
db.transaction({
   if let user: In = users.filter(age >= 18).first {
    if user.location == location {
      // update some other table
    }
  } else {
    // do some other update
  }
})
```

Is there any reason a more convenient form of transaction couldn't be supported?

**Comment by stephencelis** [comment]
Closed by https://github.com/stephencelis/SQLite.swift/commit/c5881a8a67df214a2518963e7ca8eba23496d1ca
