### ISSUE TITLE
Expose error for public func execute(SQL: String)

### ISSUE THREAD

**Issue by donshin** [stephencelis/SQLite.swift#80]
I'm using the execute method for SQL obtained from an outside source; I'd like to capture the error message if at all possible when things go wrong. Would you consider exposing the error value somehow (either an NSError or simply the error string)?

**Comment by stephencelis** [comment]
How would your app recover if it fails? Is there a query the app could make to test success?

`db.execute` will throw an assertion if it fails. In production, you should be able to try `db.lastError` to check for failures—although `db.lastError` is always populated at the moment, so maybe we can return `nil` there if the status is `SQLITE_{OK,STEP,DONE}`.

**Comment by donshin** [comment]
Hi there, thanks for the reply! For the particular app I'm working on, I would need to report to a server if there was an error in processing the sql given to the app - hence, my need to grab the error message. I'm open to any mechanism for retrieving the error- reading db.lastError would work as long as there was confidence that it reflected the most recent execution attempt (and not something previous), and it was nil if the most recent execution attempt was successful. I suppose another way to go about it would be to have the execute func itself return indication of success or failure- or pass in a closure to handle success or failure, though that might be overkill. I'd be excited for anything as long as it reliably reflected the success or failure of the most recent execution attempt. :)

**Comment by stephencelis** [comment]
You could also split the string by ";" and execute each individually.

``` swift
for SQL in split(";", allSQL) {
    let stmt = db.run(SQL)
    if stmt.failed {
        println(stmt.reason) // or send to server
        break
    }
}
```

I'll keep this ticket open to explore returning `nil` from `lastError` when there is no error, though.

**Comment by donshin** [comment]
Sounds good- thanks for your consideration, and for the tip.

**Comment by stephencelis** [comment]
Done! https://github.com/stephencelis/SQLite.swift/commit/7749e3ee7923e79177b1c94b54d3439c2a32aed5
