### ISSUE TITLE
building failed,version0.11.5

### ISSUE THREAD

**Issue by lyimin** [stephencelis/SQLite.swift#803]
![1524554290055](https://user-images.githubusercontent.com/7721713/39171909-bc964220-47d2-11e8-9d5e-09fbf68dfd45.jpg)

**Comment by xuxueing** [comment]
are you fixed it?
i have the some question  but version0.11.5 not workin in swift 4.1

**Comment by lyimin** [comment]
@xuxueing 我的xcode版本是9.2的，我的解决方案是吧sqlte.swift的库降到0.11.4
