### ISSUE TITLE
I can't use the carthage build, carthage version 0.29.0

### ISSUE THREAD

**Issue by codepgq** [stephencelis/SQLite.swift#807]
>/Carthage/Checkouts/SQLite.swift/Sources/SQLite/Typed/CoreFunctions.swift:654:57: error: cannot convert value of type 'Self.IndexDistance' to expected argument type 'Int'
        let templates = [String](repeating: "?", count: count).joined(separator: ", ")
                                                        ^~~~~
                                                        Int( )

>Carthage/Checkouts/SQLite.swift/Sources/SQLite/Typed/Schema.swift:50:25: error: value of type '[Expressible?]' has no member 'compactMap'
        return " ".join(clauses.compactMap { $0 }).asSQL()

>Carthage/Checkouts/SQLite.swift/Sources/SQLite/Typed/Query.swift:693:69: error: missing argument for parameter #2 in call
        return Update(" ".join(clauses.compactMap { $0 }).expression)
                                                                    ^
                                                                    , <#[Binding?]#>

>Carthage/Checkouts/SQLite.swift/Sources/SQLite/Typed/Query.swift:880:12: note: 'init' declared here
    public init(_ template: String, _ bindings: [Binding?]) {

>** ARCHIVE FAILED **

The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal arm64
(2 failures)

**Comment by jberkel** [comment]
You need Xcode 9.3 to compile
