### ISSUE TITLE
SQLCipher 0.11.5 - not an error (code: 21)

### ISSUE THREAD

**Issue by lucascorrea** [stephencelis/SQLite.swift#809]
When I use the version 0.11.5 with Cocoapods I received the error `not an error (code: 21)`

```
pod 'SQLite.swift', '~> 0.11.5'
pod 'SQLite.swift/SQLCipher', '~> 0.11.5'
```

But If I use `pod 'SQLite.swift/SQLCipher', :git => 'https://github.com/stephencelis/SQLite.swift.git'` It works.

```
do {
            db = try Connection("database.db")
            try db!.key("password") // error with the version 0.11.5
            return db
        } catch {
            print(error)
        }
```

I would like to know why it happens. 
To who have this problem using `pod 'SQLite.swift/SQLCipher', :git => 'https://github.com/stephencelis/SQLite.swift.git'`

**Comment by KevinZhouRafael** [comment]
I meat the same problem. 
Also I used pod 'SQLite.swift/SQLCipher', :git => 'https://github.com/stephencelis/SQLite.swift.git', It not worked.

**Comment by hansrajgavali** [comment]
I am also getting the same error, even when I used pod 'SQLite.swift/SQLCipher', :git => 'https://github.com/stephencelis/SQLite.swift.git', the issue is not resolved, anyone of you have found any solution on this?

**Comment by tungdx** [comment]
I am getting the same as you guys. Have you solved it? If yes please share your solution. Thank you so much!

**Comment by SolorzanoJose** [comment]
Still happening in 2019

**Comment by tungdx** [comment]
now It works if I use

target 'YourAppTargetName' do
  pod 'SQLite.swift/SQLCipher', '~> 0.12.0'
end
