### ISSUE TITLE
Segfault 11 in Expression.swift on Xcode 6.2 optimized builds

### ISSUE THREAD

**Issue by kklobe** [stephencelis/SQLite.swift#81]
Building my project on Xcode 6.2 (6C131e) with optimizations causes a segfault:

    1.	While emitting IR SIL function @_TFE6SQLiteSig10expressionGVS_10ExpressionT__ for 'anonname=0x7fb4a589e540' at /Users/kklobe/src/HabitAware-iOS/SQLite.swift/SQLite/Expression.swift:176:43

Disabling optimizations works just fine.

**Comment by vvasanth86** [comment]
+1

**Comment by stephencelis** [comment]
Sorry about that! I've been in a mostly-Swift 1.2 world. Fixed here: https://github.com/stephencelis/SQLite.swift/commit/83bbd896fa336c763288590e777d0090bfe37d98
