### ISSUE TITLE
How do I make the equivalent of "SELECT username FROM usertable WHERE userID == 1"?

### ISSUE THREAD

**Issue by sdlcheng** [stephencelis/SQLite.swift#814]
I have been trying and trying again, and can't seem to understand how to do this. 

I keep trying the following:
Building Complex Queries
Queries have a number of chainable functions that can be used (with expressions) to add and modify a number of clauses to the underlying statement.

let query = users.select(email)           // SELECT "email" FROM "users"
                 .filter(name != nil)     // WHERE "name" IS NOT NULL
                 .order(email.desc, name) // ORDER BY "email" DESC, "name"
                 .limit(5, offset: 1)     // LIMIT 5 OFFSET 1

but can't seem to get it to get the value out of the "query"

Any help would be appreciated.

**Comment by saormart** [comment]
Hi @sdlcheng, I was in the same situation and as a "SQL" person I was more used to the "old school sql syntax" so I decide to move to GRDB.swift.
The GRDB is a toolkit for SQLite, and it allows you to use the native SQLite syntax or use the "old school sql syntax" let's say in that way.
Their repository is pretty good maintained, so if you're like me, it's a good choice to go with them!
This is the link: [GRDB.swift](https://github.com/groue/GRDB.swift)
Hope it help you!

**Comment by sdlcheng** [comment]
Hi @saormart 

Will try it out later! Thanks though! 👍

**Comment by jberkel** [comment]
please use stackoverflow for general questions
