### ISSUE TITLE
new column in existing databse

### ISSUE THREAD

**Issue by jzafar** [stephencelis/SQLite.swift#815]
Hi,
I have already created database and tables. Now i need to add new column in existing table. it is not creating new column.
Here is my code
func createTasksDetailTable () {
        print("CREATE TASKS_DETAIL TABLE")
        let createTable = self.tasksTable.create { (table) in
            table.column(self.taskId, primaryKey: true)
            table.column(self.projectId)
            table.column(self.taskTitle)
            table.column(self.taskDescription)
            table.column(self.creatorId)
            table.column(self.assignedId)
            table.column(self.createdDate)
            table.column(self.dueDate)
            table.column(self.taskStatus)
            table.column(self.isDelete, defaultValue: SQLValidationView.FALSE.rawValue)
            table.column(self.repeatIntervals)
            
        }
        do {
            try Globals.DATABASE_CONNECTION_TASKS.run(createTable)
            
            print("CREATED TASKS_DETAIL TABLE")
        } catch {
            print(error)
        }
    }

I need to create new column self.repeatIntervals

/* DataBase Table */
    let tasksTable = Table("tasks_detail")
    
    /* DataBase Properties */
    let taskId          = Expression<String>("TASK_ID")
    let projectId       = Expression<String>("PROJECT_ID")
    let taskTitle       = Expression<String>("TASK_TITLE")
    let taskDescription = Expression<String>("TASK_DESCRIPTION")
    let creatorId       = Expression<String>("CREATOR_ID")
    let assignedId      = Expression<String>("ASSIGNED_ID")
    let createdDate     = Expression<String>("CREATED_DATE")
    let dueDate         = Expression<String>("DUE_DATE")
    let taskStatus      = Expression<String>("TASK_STATUS")
    let repeatIntervals = Expression<String>("REPEAT_INTERVALS")
    let isDelete        = Expression<Int>("IS_DELETE")

**Comment by ammar-wizsoft** [comment]
Just call addColumn on your Table and pass the new column Expression to it.
 ```
do {
        try Globals.DATABASE_CONNECTION_TASKS.run(self.tasksTable.addColumn(self.repeatIntervals))
        print("Added repeatIntervals")
    } catch {
        print(error)
    }
```
do {
        try Globals.DATABASE_CONNECTION_TASKS.run(self.tasksTable.addColumn(self.repeatIntervals))
        print("Added repeatIntervals")
    } catch {
        print(error)
    }
```
