### ISSUE TITLE
Basic problem

### ISSUE THREAD

**Issue by mbolder** [stephencelis/SQLite.swift#816]
Hello, I am trying to get a basic app started and create/connect a database on startup. 
After adapting the example code given to the new throw syntax. I cannot understand why 
it would not create the database file. Compiles fine. 

## Build Information

- Latest SQLite.swift version
- Xcode 9.4, Mac OS 10.13.5
- Integrated via CocoaPods

```
import Cocoa
import SQLite

@NSApplicationMain
class AppDelegate: NSObject, NSApplicationDelegate
{
    @IBOutlet weak var window: NSWindow!

    func applicationDidFinishLaunching(_ aNotification: Notification)
    {
        // Insert code here to initialize your application
        do
        {
            let db = try Connection("/Users/mbolder/Desktop/db.sqlite3")
        }
        catch
        {
            print ("error")
        }
    }
    func applicationWillTerminate(_ aNotification: Notification)
    {
        // Insert code here to tear down your application
    }
}

```

**Comment by EmyXOR** [comment]
You should do something like 
do {
if let sqlPath = Bundle.main.path(forResource: "db.sqlite3", ofType: nil) {
            let db = try Connection(sqlPath)
            let queryView = Table("Your_Table_Name")
....
}
catch let error {
        print("Error loading SQL Database: db.sqlite3 \(error)")
}

Make sure your database is copied > Project > Build Phases > Copy bundled resources

**Comment by mbolder** [comment]
![bildschirmfoto 2018-06-14 um 09 57 21](https://user-images.githubusercontent.com/1629706/41399175-e80e1658-6fb9-11e8-94b7-76fdc49ac6ad.png)

That is is not working either, now the Errors are handled and catch let errors is also not accepted by Xcode.

**Comment by khacdat1994** [comment]
> You should do something like
> do {
> if let sqlPath = Bundle.main.path(forResource: "db.sqlite3", ofType: nil) {
> let db = try Connection(sqlPath)
> let queryView = Table("Your_Table_Name")
> ....
> }
> catch let error {
> print("Error loading SQL Database: db.sqlite3 (error)")
> }
> 
> Make sure your database is copied > click Project > Build Phases > check Copy bundled resources
> 
> @mbolder - You should load the db data async in the GCD so that your UI does not wait for the db data load.

thanks
