### ISSUE TITLE
Is it able to convert field type in filter function?

### ISSUE THREAD

**Issue by zhouhao27** [stephencelis/SQLite.swift#822]
I have a field like this:

```
let x = Expression<String>("X")
```

Which actually is a double but I can't change the database for some reason. Is it possible to change it when I do the filtering?

```
let query = table.filter(x > 100.0 && x < 200.0)
```

Any suggestion? Thanks.

**Comment by jberkel** [comment]
`let x = Expression<Double>("X")`
