### ISSUE TITLE
Same-type constraint type 'Int64' does not conform to required protocol 'Bindable'

### ISSUE THREAD

**Issue by Bouke** [stephencelis/SQLite.swift#83]
I'm trying to get this package working with Xcode 6.3 beta 3. However it produces build errors when using `swift-1-2` branch. In `Expression.swift`, I get ~48 errors similar to this one:

> /Users/X/Developer/X/Libs/SQLite/SQLite/Expression.swift:272:43: Same-type constraint type 'Int64' does not conform to required protocol 'Bindable'

I'm using the "Frameworkless instructions", as I'm including it in a command line tool;

![screen shot 2015-03-15 at 13 46 49](https://cloud.githubusercontent.com/assets/235882/6656022/c2ae583e-cb19-11e4-9ad5-081f7871513d.png)

**Comment by stephencelis** [comment]
Same report as #79.

I've gotten rid of the commit that adds the `Bindable` protocol, so this should hopefully work now on non-whole-module-optimized builds.
