### ISSUE TITLE
Upgrade to SQLite 3.24.0

### ISSUE THREAD

**Issue by jaredrada** [stephencelis/SQLite.swift#833]
Are there any plans to upgrade to SQLite 3.24.0? I'm aware this version was very recently released however there is a feature I'm keen to use: Support for additional *custom* columns in R*tree tables. This makes it significantly easier to deal with R*trees for geospatial applications.

https://sqlite.org/rtree.html

**Comment by jberkel** [comment]
With cocoapods you can easily use any recent version of SQLite3 together with SQLite.swift. Or do you specifically mean Swift support/wrapping of these new features?

**Comment by jaredrada** [comment]
Is there a way to specify this version of SQLite w/o Cocoapods? I imported the project manually. I dont expect thered be any changes on the SQLite.swift front to support this (and if there were I'd simply make sure of its ability to execute raw SQL- at least in the mean time). The changes simply allow you to insert more columns when creating the table. Cheers and thanks for a great lib!

**Comment by jberkel** [comment]
If you integrate SQLite directly you can specify the version yourself, however there are currently no instructions for that.

**Comment by ChrisChares** [comment]
I'm having some issues trying to directly integrate sqlite3 (and spatialite) with SQLite.swift.  @jberkel do you know of any resources anywhere that document this process?

Side note:  looks like iOS 12 ships with sqlite3 v3.24.0.

**Comment by jberkel** [comment]
fixed, closing
