### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by jibransiddiqui** [stephencelis/SQLite.swift#835]
Fatal error: 'try!' expression unexpectedly raised an error: database is locked (code: 5)
File Location : 
 Project ->Sqlite > Core > Statement.swift.

## Build Information

- Include the SQLite.swift version, commit or branch experiencing the issue.
- Mention Xcode and OS X versions affected.
    Xcode 9.4.1 , OS X high Sierra 10.13.6
- How do do you integrate SQLite.swift in your project?
    - manual

## General guidelines

<img width="1059" alt="screen shot 2018-08-17 at 12 12 25 pm" src="https://user-images.githubusercontent.com/23705554/44252987-825ed280-a217-11e8-84a8-fdb0eb54631c.png">

**Comment by vandadnp** [comment]
Is there going to be any fix on this?

We are quite heavily affected by this issue as well where our app crashes on this exact same line upon startup.

**Comment by dqueralto** [comment]
Does anyone know anything about this error?

**Comment by touee** [comment]
> I have the same issue. This occurs with multiple connexion, even if I put the Thread-Safety code :
> 
> ```
> db.busyTimeout = 5
> 
> db.busyHandler({ tries in
>     if tries >= 3 {
>         return false
>     }
>     return true
> })
> ```

Not sure if this is a good idea, but you can try:
```swift
db.busyHandler({ (_) in true })
```
This way I can execute expensive query in applications like DB Browser, while running my program, without causing the program complain about database being locked (of course, the thread writing the database would be blocked until the external application's query has been done)

**Comment by juanjoseluisgarcia** [comment]
@touee I do not know if it is a good idea. I just know that it works. Thanks

**Comment by juanjoseluisgarcia** [comment]
This is happening a lot. The app crashes. I am going to try to use a sync thread and if not I will have to use [GRDB](https://github.com/groue/GRDB.swift) with WAL mode.

**Comment by jberkel** [comment]
https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#thread-safety
