### ISSUE TITLE
Geospatial Support

### ISSUE THREAD

**Issue by Knights22** [stephencelis/SQLite.swift#84]
Is there any plans to add geospatial support in the future? Thanks.

**Comment by stephencelis** [comment]
If you mean R*Tree module support, it got added earlier today :smile:

https://github.com/stephencelis/SQLite.swift/commit/6f3eef7619ddbf1e97726dc87008bf322db86e29

**Comment by Knights22** [comment]
ahhhh.... Thanks I just took a look at the tests now, didn't see anything in the Wiki. Thanks excellent lib!
