### ISSUE TITLE
Strings empty when contains acute accent

### ISSUE THREAD

**Issue by javizarza** [stephencelis/SQLite.swift#85]
Hi there.

I've found a problem with your awesome framework.

Imagine you have a table... two fields, id=int, nombre=string filled with data like:

1,"árbol"
2,"arbol"

I'm searching for a substring like:

        let entidades = db["Entidades"];
        let id = Expression<Int64>("ID");
        let nombre = Expression<String>("Nombre");
        let query = entidades.select(id,nombre).filter(like("%rbo%",nombre)).order(nombre);
        let items = Array(query);

items.count is 2, as it should, but if I print the values I got this

ID: 1, Nombre: ""
ID: 2, Nombre: "arbol"

I suppose there is a problem in the Expression<string>, so I try to avoid that writing a pure SQL query:

        for row in db.prepare("SELECT id,nombre FROM entidades WHERE nombre like (?)", "%rbo%") {
            println("ID: \(row[0]), Nombre:'\(row[1])'");
        }

And I got this:

ID: Optional(1), Nombre:'Optional("")'
ID: Optional(2), Nombre:'Optional("arbol")'

So, I'm stuck there... I don't know what else can I do, but I need to be able to retrieve accented strings. Any ideas?

**Comment by stephencelis** [comment]
Looks like a potential UTF-8 issue. I won't be able to take a look today but should have some time tomorrow. If you can attach a sample project with the problem I should be able to hit the ground running.

**Comment by javizarza** [comment]
Hi Stephen.

It seems it was my fault. I was preparing a sample code to send you, and whoops... it worked.

I created a new .sqlite for the test, having the accents, and it worked like a charm... so I try exporting to SQLite again with another tool, and this time it worked perfect.

It seems encoding of SQLiteConverter wasn't properly UTF8 or I didn't set up properly any option. I was looking the data with Liya and it showed all the accents, so I was sure the file was right.

Converting with RazorSQL saved the day :)

Anyway, thanks for your help!

**Comment by stephencelis** [comment]
Thanks for looking into this and glad you could rectify the problem!
