### ISSUE TITLE
Crazy Syntax Errors

### ISSUE THREAD

**Issue by isa3bel** [stephencelis/SQLite.swift#851]
Hi,

I downloaded the SQLite.swift file and tried creating my own db. For some reason all these errors occur. When I change the icon next to the simulator button these errors don't occur, but then I can't run my app in the simulator. I want my app to run in simulator so I can trigger the function that prints the row ids that inserted in the database

All help is appreciated.
<img width="1272" alt="screen shot 2018-10-10 at 8 46 42 pm" src="https://user-images.githubusercontent.com/18249360/46773981-2623a680-ccce-11e8-85fa-11ab4287a959.png">
No errors when this selected but can't run in simulator
<img width="193" alt="screen shot 2018-10-10 at 8 23 23 pm" src="https://user-images.githubusercontent.com/18249360/46773989-3176d200-ccce-11e8-8979-0336a078a480.png">

**Comment by NTruchaud** [comment]
I have the same error If someone can help us out.

Did you find any workaround for your problem ?
