### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by vladplacintescu** [stephencelis/SQLite.swift#852]
<img width="859" alt="screenshot 2018-10-13 at 12 31 37" src="https://user-images.githubusercontent.com/35224579/46903860-3614d380-cee4-11e8-9f39-480c18826567.png">
 
After I did the manual installing, I wanted to see if it has any errors
I also installaded carthage and cocoapods
Can someone tell me what can I do? thanks in advance

**Comment by vladplacintescu** [comment]
Same issues appear even if i install it throught pods...

**Comment by jberkel** [comment]
this should be fixed
