### ISSUE TITLE
how can we add SQLite.swift inside the cocoa touch framework ?

### ISSUE THREAD

**Issue by ravikanthatstoryboard** [stephencelis/SQLite.swift#854]
how can we add SQLite.swift inside the cocoa touch framework ? can any one help me out [
<img width="865" alt="screenshot 2018-10-19 at 3 35 08 pm" src="https://user-images.githubusercontent.com/19217975/47212026-b63fab00-d3b4-11e8-83d6-cfffd33f84ed.png">
<img width="267" alt="screenshot 2018-10-19 at 3 36 43 pm" src="https://user-images.githubusercontent.com/19217975/47212110-ea1ad080-d3b4-11e8-8804-96332fe97769.png">

](url)

**Comment by mbain** [comment]
It looks like you've run `pod install` already. Are you making sure to open your project via the .xcworkspace file, rather than the Xcode project file?
