### ISSUE TITLE
Can’t Build `swift-1-2` Branch With Xcode 6.3 Beta 4

### ISSUE THREAD

**Issue by maarf** [stephencelis/SQLite.swift#86]
When creating a new OS X project in Xcode 6.3 beta 4 and adding SQLite.swift (`swift-1-2` branch) as described in Installation section in documentation, building project fails with `Swift Compiler Error`s.

`Database.swift`:
```
Missing return in a closure expected to return 'Binding?'
```

`Statement.swift`:
```
Missing return in a function expected to return 'Binding?'
```

**Comment by stephencelis** [comment]
How are you going about building the project? I haven't run into this one but know it has to do with the `assertionFailure` in both files, so maybe with the **Release** scheme it fails? (Though I can build in **Release** mode just fine.) I've thought about switching both of those failures to `fatalError`. Can you try to make that change locally and see if it fixes things for you? If so, I'll make the commit to `swift-1-2` soon.

**Comment by fredwaltman** [comment]
I did that on the release version of Xcode 6.3/OSX 10.10.3 and that got rid of the error.
I had to change "Xcode-beta.app" to "Xcode.beta" in a couple of places.

**Comment by stephencelis** [comment]
This should hopefully be fixed now. Can you verify on the `master` branch? (I've merged the `swift-1-2` branch in with the GM release today.)

**Comment by fredwaltman** [comment]
Seems to work fine -- I had some issues with Int vs Int64 but I think that was me not you :)

Thanks for a great tool.

**Comment by maarf** [comment]
Hey, just wanted to mention that everything is working great on Xcode 6.3. Thanks for your effort @stephencelis!
