### ISSUE TITLE
Getting error when using SQLCipher

### ISSUE THREAD

**Issue by hansrajgavali** [stephencelis/SQLite.swift#861]
I added SQLCipher by following the steps given in the documentation, after adding this pod **'SQLite.swift/SQLCipher', '~> 0.11.5'** , I followed the steps added key to db 

let db = try Connection("path/to/db.sqlite3")
try db.key("secret")

and I compiled the project but I am getting error **(error code:21)**

**[logging] misuse at line 213459 of [2b0954060f]**

need guidance to solve the issue

**Comment by tungdx** [comment]
Hi @hansrajgavali Just wonder if you manage to solve this issue? I have been encountering the same issue.

**Comment by altagir** [comment]
you should NOT include the commit to indeed have the latest from git 
just use :  

`  pod 'SQLite.swift/SQLCipher', :git => 'https://github.com/stephencelis/SQLite.swift.git'
`

it does fix the problem temporary, but using dev version is not ideal

**Comment by cognophile** [comment]
@swlkr I've tried your suggestion, but the problem remains when attempting to build `allyourpasswords` using `SQLCipher`. 

`Podfile`:
```
platform :macos, '10.14'
use_frameworks!

target 'allyourpasswords' do
    pod 'SQLite.swift/SQLCipher', :git => 'https://github.com/stephencelis/SQLite.swift.git'
    pod 'FavIcon', '~> 3.0.0'
end
```
Still doesn't seem able to locate `SQLCipher` despite `pod install` completing and claiming to have installed all pods. 

<img width="269" alt="Screenshot 2019-04-13 at 02 31 51" src="https://user-images.githubusercontent.com/14915130/56072947-a1a50400-5d94-11e9-899f-3419e700dcf5.png">

I'm also referencing the frameworks in the target build phases. 

<img width="534" alt="Screenshot 2019-04-13 at 02 35 58" src="https://user-images.githubusercontent.com/14915130/56072966-ecbf1700-5d94-11e9-9bc6-1ad8e9d1ae0c.png">

Not sure what I'm missing.
