### ISSUE TITLE
how to import sql or sqlite file in it

### ISSUE THREAD

**Issue by nadia-am** [stephencelis/SQLite.swift#869]
I have a sql file which create a table and add over 1000 row in that table i want to run it in swift, is it possible?

**Comment by zunjae** [comment]
You can find it in the docs

**Comment by SudheerArava** [comment]
Can we have a sample code? I searched in the doc. But not found.

**Comment by nadia-am** [comment]
the file format is txt , i didn't find in the document! can you give me a clue?

**Comment by jberkel** [comment]
sorry, please use stackoverflow for support, github is for bugs only.
