### ISSUE TITLE
IFNULL supported?

### ISSUE THREAD

**Issue by devSC** [stephencelis/SQLite.swift#874]
How to select value like below?

```
SELECT firstname,
       lastname,
       IFNULL(fax, 'Call:' || phone) fax
  FROM customers
 ORDER BY firstname;
```

Thanks.

**Comment by yacir** [comment]
Any update about this request ?

**Comment by jberkel** [comment]
https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#core-sqlite-functions
