### ISSUE TITLE
Create table from Codable

### ISSUE THREAD

**Issue by kwstasna** [stephencelis/SQLite.swift#879]
Is there any way to create a table from a model which conforms to codable?
For example

class User: Codable {
  let pk: Int?
  etc.. 
}

**Comment by anilsutariya** [comment]
Below Like that.
struct Person:Codable {
    
    let personID:Int
    let personName:String?
    let type:String?
   
    
    init(personID:Int:Int,personName:String,type:String) {
        
        self. personID = personID
        self. personName = personName
        self.type = type
  
    }
    
    enum CodingKeys:String,CodingKey {
        
        case personName
        case personID
   
    }
}

**Comment by codingspark** [comment]
You have to create the table manually:
https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#creating-a-table

Check previous issue
#748

**Comment by NathanFallet** [comment]
Duplicate of #748
