### ISSUE TITLE
ld: framework not found SQLite

### ISSUE THREAD

**Issue by ty2610** [stephencelis/SQLite.swift#884]
## Build Information

```
ld: warning: directory not found for option '-F/Users/tyler.green/Library/Developer/Xcode/DerivedData/Festival_Time_Manager-aivrmzjawpbvmbclrsmfwabrbfsv/Build/Products/Debug-iphonesimulator/SQLite.swift'
ld: framework not found SQLite
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

- SQLite.swift version: 0.11.5
- This is with Xcode 10.01 and swift 4.2
- How do do you integrate SQLite.swift in your project?
    - CocoaPods

I run into this problem every time I try to build and open my app locally. I have already tried cleaning my project as well.

**Comment by NathanFallet** [comment]
Try to update to 0.13.0. If it still don't work, please reopen this issue.
