### ISSUE TITLE
I used cocoapods to report an error

### ISSUE THREAD

**Issue by songyuyang0918** [stephencelis/SQLite.swift#887]
Hello, I use Xcode10 for cocoapods inheritance
I have checked a lot of relevant documents, but I still can't solve it. I hope you can help me. Thank you!
<img width="1755" alt="屏幕快照 2019-03-19 下午5 20 47" src="https://user-images.githubusercontent.com/15685672/54594340-69e3be80-4a6b-11e9-88d2-b815d410576c.png">

**Comment by jberkel** [comment]
please retry with the latest version and reopen if needed
