### ISSUE TITLE
Invalid SQL statements with Xcode 10.2

### ISSUE THREAD

**Issue by tanzolone** [stephencelis/SQLite.swift#888]
## Build Information

- SQLite iOS Version 0.11.4 (however it's likely to impact all the targets)
- Xcode 10.2 beta 4
- manual integration in our project

## General guidelines

In Xcode 10.2 beta 4 the macro` #function `shows a different behaviour. As SQLite.swift relies on `#function` in different subroutines for the composition of SQLite queries, several bugs linked to invalid SQLite statements seem to be introduced. 

I have just run the SQLite.swift tests with Xcode 10.2 beta 4 and **there are several failures linked to this issue**.

An example as follows:

In the following helper function (Helpers.swift line 107):

```
func wrap<T>(_ expression: Expressible, function: String = #function) -> Expression<T> {
    return function.wrap(expression)
}
```

when called from

`static func count(_ star: Star) -> Expression<UnderlyingType>`

the value of `function` when running in Xcode 10.2 beta 4 is `count(_:)` instead of `count`. This leads to invalid SQLite statements of the type `SELECT count(_:)(*) myTable`.

**Comment by christopheblin** [comment]
I have the exact same problem with Xcode 10.2 (not the beta) !

Do you have a workaround or a fix ?

**Comment by tanzolone** [comment]
The best option in my opinion is to get rid altogether of the `#function` default parameter and explicitly passing the name of the SQL function (maybe an enum with string raw value). The `#function` macro seems to be intended for debug purposes (this explains this sort of change in a minor update of Xcode) and I would avoid relying on it for such a critical part of the SQL statement composition.

**Comment by christopheblin** [comment]
Note that this also silently breaks SqlLiteMigrationManager 

https://github.com/garriguv/SQLiteMigrationManager.swift/blob/a716a877eca2e25fd8f0201605feaebfc0db27fc/Sources/SQLiteMigrationManager.swift#L68

=> Will always fall into the catch and report that no migration exists ...

**Comment by christopheblin** [comment]
Here is a patch to apply if you have a pod install

[mystuff.patch.zip](https://github.com/stephencelis/SQLite.swift/files/3008304/mystuff.patch.zip)

**Comment by chess92** [comment]
the simplest fix would be to just ignore any string after the first `(` of `#function`

**Comment by arjavlad** [comment]
> Here is a patch to apply if you have a pod install
> 
> [mystuff.patch.zip](https://github.com/stephencelis/SQLite.swift/files/3008304/mystuff.patch.zip)

I tried your patch but now it started giving 148 errors similar to /Pods/SQLite.swift/Sources/SQLite/Typed/Operators.swift:471:12: Use of unresolved identifier 'infix'
/Pods/SQLite.swift/Sources/SQLite/Typed/CoreFunctions.swift:73:16: Use of unresolved identifier 'wrap'.

@christopheblin  Could you please explain how you used the patch?

**Comment by wbustraan** [comment]
In folder where you cloned repo:
```patch -p3 < mystuff.patch```

All tests pass after patch applied

**Comment by arjavlad** [comment]
Thanks,
But for now, I forked the original repo and manually made changes.

**Comment by itruf** [comment]
@stephencelis hello! Can you check this issue and linked pr? Any project with SQLite.swift will not work on new Xcode 10.2 without this fix.

**Comment by timshadel** [comment]
The symptom which lead me down this rabbit hole was first seeing was that it could not prepare a statement so: `The operation couldn’t be completed. (SQLite.Result error 0.)`. Turning on the [trace logging](https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#logging) helped see which statements were successful. Finally spitting out `query.asSQL()` in the `catch` of the error showed that `count` and `!=` had now been rendered as `count(_:)` and `!=(_:_:)`.

I agree with @chess92. My simple workaround for now this change in `Helpers.swift`. It fixes all the problems I had, but obviously I'll toss it out and use a formal fix as soon as it's ready.

```swift
private func trimName(_ function: String) -> String {
    return function.components(separatedBy: "(").first ?? function
}

func infix<T>(_ lhs: Expressible, _ rhs: Expressible, wrap: Bool = true, function: String = #function) -> Expression<T> {
    return trimName(function).infix(lhs, rhs, wrap: wrap)
}

func wrap<T>(_ expression: Expressible, function: String = #function) -> Expression<T> {
    return trimName(function).wrap(expression)
}

func wrap<T>(_ expressions: [Expressible], function: String = #function) -> Expression<T> {
    return trimName(function).wrap(", ".join(expressions))
}
```

**Comment by tanzolone** [comment]
@timshadel `return function.components(separatedBy: "(").first ?? function` yucky :)

**Comment by karishmapujara** [comment]
Hello
Any solution for this problem?

**Comment by ypopovych** [comment]
@karishmapujara  We have PR with the fix. Waiting for @stephencelis to review and merge

**Comment by timshadel** [comment]
> @timshadel `return function.components(separatedBy: "(").first ?? function` yucky :)

Right??!! Exactly why I was waiting for a real fix. 😃 It looks like #891 handles this nicely with several enums and removes the `#function` magic.
