### ISSUE TITLE
Iterator produced by a prepared statement fails on repeated `next` calls after exhaustion

### ISSUE THREAD

**Issue by kasei** [stephencelis/SQLite.swift#889]
SQLite.swift version: 0.11.5
Xcode: 10.1 and 10.2 beta 4 (10P107d)
macOS version: 10.14.3
Swift Package manager

Preparing a statement returns an `AnySequence<Row>`. In turn, this sequence's `makeIterator` returns an `AnyIterator<Row>`. However, this iterator does not seem to conform to the semantics of `IteratorProtocol`. The [documentation for `IteratorProtocol`](https://developer.apple.com/documentation/swift/iteratorprotocol/1641682-next#discussion) says this of the `next` method:

> As soon as the sequence has run out of elements, all subsequent calls return nil.

However, calling `next` on the iterator after it has been exhausted will raise an error due to the `try! failableNext()` call in [SQLite/Core/Statement.swift:211](https://github.com/stephencelis/SQLite.swift/blob/0.11.5/Sources/SQLite/Core/Statement.swift#L211).

[Sample code demonstrating this issue](https://gist.github.com/kasei/f8c0ab9904061fb07642eff59666b116).

**Comment by NathanFallet** [comment]
Fixed in 0.13.0. (try! was replaced by try?)
