### ISSUE TITLE
Xcode 6.3: could not compile SQLite (both alone or part of a project) - Code signing error

### ISSUE THREAD

**Issue by abraccini77** [stephencelis/SQLite.swift#89]
Hi,
I have a project including SQLite that was compiling without errors with Xcode 6.2. After the upgrade it won't compile and I get the following error:

Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.3'

When I compile my project I get "Command /usr/bin/codesign failed with exit code 1" with lots of other details stating that the issue is in the subcomponent SQLite.

**Comment by stephencelis** [comment]
Any chance you can paste in the full error output (from the **Report** navigator)?

**Comment by abraccini77** [comment]
Here is the complete error output. I get this when I try to compile one project that includes SQLite as a swift framework. It was working fine till yesterday (prior the upgrade to Xcode 6.3). I hope this is of help.
Thanks a lot for your time.

CodeSign /Users/alex/Library/Developer/Xcode/DerivedData/cvManager-axwtehmmfoxxbxaxdxadunirkvvt/Build/Products/Debug/cvManager.app/Contents/Frameworks/SQLite.framework/Versions/A
    cd /Users/alex/Documents/OneDrive/Personale/Sviluppo/OSX/cvManager
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --preserve-metadata=identifier,entitlements,resource-rules /Users/alex/Library/Developer/Xcode/DerivedData/cvManager-axwtehmmfoxxbxaxdxadunirkvvt/Build/Products/Debug/cvManager.app/Contents/Frameworks/SQLite.framework/Versions/A

Warning: usage of --preserve-metadata with option "resource-rules" (deprecated in Mac OS X >= 10.10)!
/Users/alex/Library/Developer/Xcode/DerivedData/cvManager-axwtehmmfoxxbxaxdxadunirkvvt/Build/Products/Debug/cvManager.app/Contents/Frameworks/SQLite.framework/Versions/A: code object is not signed at all
In subcomponent: /Users/alex/Library/Developer/Xcode/DerivedData/cvManager-axwtehmmfoxxbxaxdxadunirkvvt/Build/Products/Debug/cvManager.app/Contents/Frameworks/SQLite.framework/Versions/A/Frameworks/sqlite3.framework
Command /usr/bin/codesign failed with exit code 1

**Comment by JamesSeo** [comment]
I have experienced the same error.
------------------------

Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.3'

**Comment by jklarfeld** [comment]
Go check the Target and Project for the SQLite lib in your project, the code signing was left in iOS mode.  I changed it to match the code signing rules I was using (Just the `Mac Developer` preset actually) and it code signed just fine.

![screen shot 2015-04-11 at 4 46 33 pm](https://cloud.githubusercontent.com/assets/1403387/7103209/80bbc6da-e06a-11e4-98e9-737236429ac8.png)

That said, you should the able to turn code sign off (`Don't Code Sign` preset) and have it code sign during the wrapper phase over in Copy Frameworks, like this:

![screen shot 2015-04-11 at 4 49 10 pm](https://cloud.githubusercontent.com/assets/1403387/7103213/b8216ada-e06a-11e4-978c-c975b0825dd6.png)

However, I did not test this.

**Comment by stephencelis** [comment]
Can you update to the latest commit on master and try again? The sub-framework should no longer be embedded and that should hopefully fix the build for you (I tested it locally and couldn't reproduce—code signing worked just fine).

**Comment by stephencelis** [comment]
@abraccini77 (and @jklarfeld) any update? Were you able to avoid this issue with the latest pushed version?

**Comment by jklarfeld** [comment]
I apologize for the delay, I am testing tonight, and I'll update you on the status.

**Comment by abraccini77** [comment]
Hi, sorry for the delay but I have been sick and away from the keyboard for some days. A brand new project with the new version compiles without any problems (while it did not before).
My original project with the new SQLite version compiles only after having followed jklarfeld's helpful (thanks a lot btw) instructions. 

I did not fully understand if Xcode 6.3 created some troubles in migrating my project from v. 6.2 to 6.3 since with the same settings and the same new SQLite build the old one still had the problem and the new one never showed it. I am quite sure this is not on SQLite side.

In any case the issue is fixed for me. Thanks a lot.

**Comment by stephencelis** [comment]
Great to hear!
