### ISSUE TITLE
App crash in Xcode 10.2 after migrating project swift 3 -> swift 4.2

### ISSUE THREAD

**Issue by albertchubakov** [stephencelis/SQLite.swift#895]
App crash for this line: try connection.check(sqlite3_prepare_v2(connection.handle, SQL, -1, &handle, nil))

log: "2019-03-28 10:28:40.364847+0300 Router[3268:416103] [logging] near ":_": syntax error"

device: iPhone XS 12.2
Xcode 10.2

## Build Information
CocoaPods

**Comment by tanzolone** [comment]
Duplicate of #888

**Comment by albertchubakov** [comment]
> Duplicate of #888

it still does't work

**Comment by ypopovych** [comment]
Should be fixed in the new version
