### ISSUE TITLE
update to Xcode 6.3: could not compile and show: SQLite-Bridging.h' file not found

### ISSUE THREAD

**Issue by Bronts** [stephencelis/SQLite.swift#90]
'SQLite-Bridging.h' file not found
#import "SQLite-Bridging.h"
<img src="http://i2.tietuku.com/69b25a637e9d35ce.jpg">
<img src="http://i2.tietuku.com/d7b5d2da4837c8af.jpg">

**Comment by stephencelis** [comment]
How are you installing SQLite.swift? Are you using the framework as instructed or did you drag the source files into your project? Are you building for OS X or iOS (device or simulator)?

**Comment by Bronts** [comment]
hello，I use SQLite.swift with supporting iOS7, before I update to Xcode6.3, it works well in Xcode 6.2. I created a new project and drag the sourece files in to it. And it also show the error above when compiling.

**Comment by Bronts** [comment]
Sorry,I checked agin and found something wrong I made.
I read Frameworkless Targets section

In your target’s Build Phases, add libsqlite3.dylib to the Link Binary With Libraries build phase.

Copy the SQLite.swift source files (from its SQLite directory) into your Xcode project.

Remove import sqlite3 (and @import sqlite3;) from the SQLite.swift source files that call it.

Add the following lines to your project’s bridging header (a file usually in the form of $(TARGET_NAME)-Bridging-Header.h.

#import <sqlite3.h>
#import "SQLite-Bridging.h"


I remove improt sqlite3 but now there is another error

![qq 20150410103128](https://cloud.githubusercontent.com/assets/3986255/7080936/c42f9b34-df6c-11e4-8e95-62ef130cc959.jpg)

**Comment by Bronts** [comment]
Hi.I solved the miss error.
I drag fts3_tokenizer.h file into my project. it complied success.

**Comment by stephencelis** [comment]
Glad you got it working :+1:
