### ISSUE TITLE
Version 0.11.6

### ISSUE THREAD

**Issue by christopheblin** [stephencelis/SQLite.swift#901]
After #888 and nearly a year since 0.11.5, I think it is time for 0.11.6 to get out ...

What do you think @stephencelis (or other contributors) ?

**Comment by ypopovych** [comment]
Yep. Because we need to push 10.2 changes. I think we will need even 0.12 soon, with Swift 5 support.

**Comment by crudolf** [comment]
Is there anything we can do to make this module swift 5 compatible? Like take current master version? 
We are using carthage.

**Comment by ypopovych** [comment]
I think we should start from 0.11.6 version. We need PR for this. Update README, versions everywhere. Swift 5 - next step

**Comment by stephencelis** [comment]
@ypopovych I've added you as a collaborator after your recent contribution. Would you be willing to shepherd the release? I handed contributor duties off awhile ago but it looks like those contributors have also mostly stepped away from the project.

**Comment by ypopovych** [comment]
@stephencelis I will work on this. Will try to get help from other active contributors too. Because right now I'm working on the publishing of 6 our own libraries + PRs to 3 libs :) Will do what I can.

I hope someone can start with PR. If not - will do this tomorrow by myself

**Comment by karishmapujara** [comment]
Yes please

**Comment by ypopovych** [comment]
@christopheblin do you want to start PR with fixes for the new version?

**Comment by christopheblin** [comment]
@ypopovych I'm in france and this is nearly the end of the workday for me so I can not start this until tomorrow (at best). Plus, I've never contributed to an iOS Pod so you'll need to explain me what I need to do (I've catched that I must change documentation but I have no clue what else should be done)

**Comment by ypopovych** [comment]
@christopheblin in general - version update everywhere (podspec, docs, etc.). Also, we should check Package.swift file (and all files with . in the beginning). Then I will publish a new release (and tag).  We will need @stephencelis only for the push of the new podspec.

**Comment by asuhasoft** [comment]
@ypopovych  Looking forward. Thanks.

**Comment by sburlewapg** [comment]
@ypopovych I've created #902 which updates the project to swift 5, and bumps the version to 0.11.6. Please let me know if I missed anything in here!

**Comment by juanjoseluisgarcia** [comment]
I will need to move to CoreData and abandon the library. Swift 5 it is a big milestone because for first time is ABI stable.

**Comment by sburlewapg** [comment]
#902 was merged last week and updated to version 0.11.6. #913 is awaiting review, and will introduce Swift 5 with version 0.12.

**Comment by stephencelis** [comment]
Sorry for the delay! I've pushed 0.11.6 to CocoaPods. @ypopovych please shoot me an email with your CocoaPods email address if you'd like access to unblock things in the future.

**Comment by ypopovych** [comment]
@christopheblin I pushed 0.12.0 too. With Swift 5.
