### ISSUE TITLE
Error  after migrating project to swift 5

### ISSUE THREAD

**Issue by antileks** [stephencelis/SQLite.swift#905]
After upgrading to Swift 5, a lot of non-critical errors appeared. For example:
`'withUnsafeBytes' is deprecated: use 'withUnsafeBytes <R> (_: (UnsafeRawBufferPointer) throws -> R) rethrows -> R' instead`

Code:
```
public var datatypeValue: Blob {
     return withUnsafeBytes {(pointer: UnsafePointer <UInt8>) -> Blob in
         return blob (bytes: pointer, length: count)
     }
}
```

**Comment by hermosillo8** [comment]
we also get the warning 

>'init(bytes:)' is deprecated: use `init(_:)` instead

Code: 
`
public static func fromDatatypeValue(_ dataValue: Blob) -> Data { return Data(bytes: dataValue.bytes)}
`

**Comment by mag911** [comment]
Additionally, this fixes the other warning about ```init(_:)```
```
public static func fromDatatypeValue(_ dataValue: Blob) -> Data 
    {
        return Data(_: dataValue.bytes)
    }
```

**Comment by sburlewapg** [comment]
#902 fixed these build warnings & errors. #913 will update the project to Swift 5.

**Comment by akiratoya13** [comment]
> #902 fixed these build warnings & errors. #913 will update the project to Swift 5.

Hi!! How to use this fixes? Thank you :).

**Comment by sburlewapg** [comment]
@akiratoya13 The latest version in master is 0.11.6, which contains these fixes. If you use that version (also available in CocoaPods), then the warnings & errors should disappear. Stay tuned for version 0.12 which should also be coming soon :)

**Comment by akiratoya13** [comment]
> @akiratoya13 The latest version in master is 0.11.6, which contains these fixes. If you use that version (also available in CocoaPods), then the warnings & errors should disappear. Stay tuned for version 0.12 which should also be coming soon :)

Hi @sburlewapg , I'm using that version. Apparently, it's not fixed. Still giving error.. Should I post the error here? It's similar error, but not exactly the same.

**Comment by sburlewapg** [comment]
Yeah, can you post the error?

**Comment by akiratoya13** [comment]
![image](https://user-images.githubusercontent.com/11811584/56598555-e47d9c00-661e-11e9-9c6a-d55d080eb7fd.png)
This is the screenshot

**Comment by sburlewapg** [comment]
Which version of Xcode are you using?

**Comment by akiratoya13** [comment]
> Which version of Xcode are you using?

Version 10.1 (10B61). I can't update beyond that.

**Comment by sburlewapg** [comment]
Gotcha, I think that's the issue. Version 0.11.6 requires Xcode 10.2 or later.

**Comment by akiratoya13** [comment]
> Gotcha, I think that's the issue. Version 0.11.6 requires Xcode 10.2 or later.

I see. So, how do I resolve this issue? ><..

**Comment by sburlewapg** [comment]
For now, I'd probably suggest forking 0.11.6 and changing the code back to the old version until you're able to update to Xcode 10.2, at which point you could just switch back to the master release.

**Comment by akiratoya13** [comment]
> For now, I'd probably suggest forking 0.11.6 and changing the code back to the old version until you're able to update to Xcode 10.2, at which point you could just switch back to the master release.

Thanks @sburlewapg , will try that after trying upgrade the Xcode again... :)

**Comment by ypopovych** [comment]
You can use 0.11.5 with Xcode 10.1, or 0.12.0 with Xcode 10.2 (or 0.11.6 if you need Swift 4.2)
