### ISSUE TITLE
Cannot invoke update after Swift 1.2 update

### ISSUE THREAD

**Issue by mikewalkerjr** [stephencelis/SQLite.swift#91]
I have updated Xcode to 6.3, swift to 1.2, and SQLIte. Since then I have not been able to get the update call, or any calls to the DB to work. I get a compile error. I have the following lines

    let version = Expression<Double>("version")
    let db = Database(dbFilePath)
    db["app"].updated(version <- 1.0)

With that I'm getting an error "Cannot invoke 'update' with an argument list of type '(Setter)'"

I am also getting a similar error with the insert call.

**Comment by violabg** [comment]
I'm getting the same for insert method.

**Comment by kklobe** [comment]
I had the same thing happen and had to add a !:

    let version = Expression<Double>("version")
    let db = Database(dbFilePath)
    db["app"].update(version <- 1.0)!

**Comment by stephencelis** [comment]
Swift 1.2 no longer lets you disambiguate inserts and updates with `?`. Use `!` instead, for now, or use `if`–`let`.

I'll likely remove the overloaded functions soon to avoid confusion.
