### ISSUE TITLE
Limit not working on query

### ISSUE THREAD

**Issue by Alexof** [stephencelis/SQLite.swift#92]
Hi there, 

It seems there is an issue with the .limit() method, the query count always returns the total records for the table. 

Code:
```
        // Select the table
        let messages = db["messages"]
        
        // Construct the query
        let query = messages.select(_message)
            .filter(_category == 1 && _language == "EN"  )
            .limit(1)
        
        println(query.count) // --> This line here prints a total of 3 records instead of 1
```
Is this expected?

Thanks

**Comment by stephencelis** [comment]
Could you try calling `db.trace(println)` beforehand to log your queries? This may just be how SQLite runs `SELECT count(*)` (ignoring LIMITs). I'll verify soon but am traveling at the moment.

**Comment by Alexof** [comment]
Here you go
```
SELECT count(*) FROM "messages" WHERE ((("category" = 1) AND ("language" = 'EN')) ) LIMIT 1
Total count: 2
SELECT count(*) FROM "messages" WHERE ((("category" = 1) AND ("language" = 'EN'))) LIMIT 1
SELECT "message" FROM "messages" WHERE ((("category" = 1) AND ("language" = 'EN'))) LIMIT 1
```
Cheers

**Comment by stephencelis** [comment]
Yup. Looks like this is just how SQLite works. Check out the discussion here: http://sqlite.1065341.n5.nabble.com/Limit-COUNT-td35980.html

**Comment by Alexof** [comment]
I see, ok i think there's no much we can do here. 

Thanks!

**Comment by stephencelis** [comment]
You could count the results in memory if need be. Or use a subquery. I don't know your use case, though.

**Comment by Alexof** [comment]
Thanks Stephen,

I will try what you are proposing, i changed the approach now and i am using a db.prepare instead and works as expected. I am struggling now is trying to assign the value in the row to a string variable. Not sure what am i missing but i am almost there. 

Cheers,
Alex

**Comment by stephencelis** [comment]
You can do direct cursor access for speed:

``` swift
stmt.step()
let stringCount: String = stmt.row[0]
```

SQLite.swift is still young so I may offer better support for this in the `scalar` function in the future.
