### ISSUE TITLE
'UnsafeRawBufferPointer' is not convertible to 'UnsafePointer<_>'

### ISSUE THREAD

**Issue by Viswanth92** [stephencelis/SQLite.swift#920]
I used this integration to report this error.

use xcode 10.1 ,swift 4.2

I tried pod version 0.11.6 and the issue still exists. I do not want to update my Xcode yet due to other SDKs that I am using my project.

**Comment by aniiskywalker** [comment]
Any solutions?

**Comment by bdorfman** [comment]
Having the same issue, it seems that  0.11.6+ should be marked as "Swift 5 Required" and not "Swift 5 Supported"

It seems like possibly replacing the implementation of `datatypeValue` in `Foundation.swift` with the following could be a possible solution to continue supporting both versions but I am unclear how safe this change actually is.

```    public var datatypeValue: Blob {
        #if swift(>=5.0)
        return withUnsafeBytes { (pointer: UnsafeRawBufferPointer) -> Blob in
            return Blob(bytes: pointer.baseAddress!, length: count)
        }
        #else
        return withUnsafeBytes { (pointer: UnsafePointer<UInt8>) -> Blob in
            return Blob(bytes: pointer, length: count)
        }
        #endif
    }```

If you make this change and also change SWIFT_VERSION to 4.2, all the tests seem to pass on Xcode 10.1 at least

**Comment by JasonLiu1989** [comment]
try this
add these code into your podfile
`post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.2'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end`
and set pod 'SQLite.swift', '0.11.5'
