### ISSUE TITLE
Cannot insert unrecognized token: ":" in Xcode Version 10.2.1 (10E1001)

### ISSUE THREAD

**Issue by ravinleague** [stephencelis/SQLite.swift#923]
Suddenly I am experiencing this issue Cannot insert unrecognized token: ":"
Everything was working fine until I updated to Xcode Version 10.2.1 (10E1001) - May 07th 2019

Any help greatly appreciated

**Comment by vinodcbre** [comment]
I am also facing the same issue

**Comment by tuchangwei** [comment]
Me too.
```
created_at > timeInterval
```
convert to sql will be
```
("created_at" >(_:_:) 0.0)
```
`timeInterval ` is a double value.
