### ISSUE TITLE
database disk image is malformed (code: 11)

### ISSUE THREAD

**Issue by chichaykin** [stephencelis/SQLite.swift#928]
Hi,

My app has crashes in Crashlytics:
Fatal error: 'try!' expression unexpectedly raised an error: database disk image is malformed (code: 11): file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang_Fall2018/swiftlang_Fall2018-1000.11.42/src/swift/stdlib/public/core/ErrorType.swift, line 184

Crashed: com.xx.some-queue
0  libswiftCore.dylib             0x56c6594 $Ss15EmptyCollectionVyxGSTsWa + 2101
1  libswiftCore.dylib             0x56fc4a1 swift_unexpectedError + 278
2  (Missing)                      0x6f52646c (Missing)

## Build Information

- SQLite.swift version: 0.11.4
- Mention Xcode:Version 10.1 (10B61)
- How do you integrate SQLite.swift in your project?
    - CocoaPods
- iOS: 10.3.3 (14G60)

## General guidelines
I cannot reproduce it.

Is there a way somehow to handle the database disk image malformed error?

**Comment by georgbachmann** [comment]
Hey... did you ever figure out the reason for your diskimage to be malformed? I see the same problem in my logs, but can't reproduce it either... :(

**Comment by georgbachmann** [comment]
Sorry to ping you again @chichaykin . Can you tell me if you figured out the root cause of the problem? And how did you fix it?
Also... any idea how our database disk image turned malformed? I can also not reproduce it :(

**Comment by Ankit-Aggarwal** [comment]
Hey,
Any update on the issue.
This issue has increased for us on latest silicon mac.

**Comment by georgbachmann** [comment]
For me the issue was that I did replace the database but only the .db file but did not remove the -shm and -wal files...
Maybe that help for you?

**Comment by NathanFallet** [comment]
Please ask on StackOverflow for this kind of questions (we are tracking bugs on GitHub)
