### ISSUE TITLE
Build fails after upgrading to Xcode 6.3 (6D570)

### ISSUE THREAD

**Issue by Alexof** [stephencelis/SQLite.swift#93]
Hi @stephencelis 

I upgraded my Xcode to 6.3 (6D570) and now i get a lot of errors when trying to build the app. 

- Lots of: 'autoclosure' attribute is now an attribute of the parameter declaration, not its type
- SQLite.swift-master/SQLite/Value.swift:42:11: Class properties are only allowed within classes; use 'static' to declare a static property
- SQLite.swift-master/SQLite/Statement.swift:39:68: Cannot assign to immutable value of type 'COpaquePointer'
- SQLite.swift-master/SQLite/Statement.swift:39:18: Cannot invoke 'try' with an argument list of type '(Int32)'
- SQLite.swift-master/SQLite/Statement.swift:192:27: Closure use of @noescape parameter 'block' may allow it to escape

**Comment by stephencelis** [comment]
Xcode 6.3 introduced Swift 1.2 and a lot of changes. You'll need to update to the latest version of SQLite.swift.

**Comment by Alexof** [comment]
Sorry @stephencelis,

I thought I had the latest version, is not the be in the master branch? That's the one I have. 

Cheers
Alex

**Comment by stephencelis** [comment]
@Alexof Please verify against GitHub. The issues you list above were corrected on a `swift-1-2` branch awhile ago, which was merged into `master` the day the GM was released.
