### ISSUE TITLE
After update to 0.12 misuse error 21.

### ISSUE THREAD

**Issue by lucascorrea** [stephencelis/SQLite.swift#934]
Guys, after I've updated to version 0.12 SQLite.swift and Cypher. Now it's happening it every time. I can't get a connection. Did anyone get the same error?

`Installing SQLCipher 4.1.0 (was 4.0.1)`
`Installing SQLite.swift 0.12.0 (was 0.11.5)`

[logging] misuse at line 222151 of [95fbac39ba]
not an error (code: 21)

**Comment by SolorzanoJose** [comment]
Yes, I'm getting the same error

**Comment by CC-iOS-feifei** [comment]
Have you solved it?

**Comment by lucascorrea** [comment]
Hey, It was a long time ago that I don't use SQLite.swift, I saw that has so many updates, maybe it has been solved.

**Comment by NathanFallet** [comment]
Try with 0.13.0. Please reopen this issue if it still don't work.
