### ISSUE TITLE
App Crashing at Connection's Prepare Method - AssertionFailure

### ISSUE THREAD

**Issue by Jeba-Moses-Official** [stephencelis/SQLite.swift#938]
> Crash happening at **try connection.prepare(query)** statement.

> Maximum occurrence in background

OS : 100%  iOS 12 

## Build Information

Carthage:
"stephencelis/SQLite.swift" == 0.11.6

Xcode 10.2.1 
Swift 4.2

Logs:

0  libswiftCore.dylib             0x109e921a4 specialized _assertionFailure(_:_:file:line:flags:) + 42360
1  libswiftCore.dylib             0x109ee7c48 swift_unexpectedError + 280
2  SQLite                         0x108eccb5c $S6SQLite10ConnectionC7prepareys11AnySequenceVyAA3RowVGAA9QueryType_pKFs0D8IteratorVyAHGycfU_AHSgycfU_ + 204
3  SQLite                         0x108ed7cd0 $S6SQLite3RowVSgIego_ADIegr_TRTA + 24
4  libswiftCore.dylib             0x109e76320 _ClosureBasedIterator.next() + 93472
5  libswiftCore.dylib             0x109e764ac _IteratorBox.next() + 93868
6  libswiftCore.dylib             0x109d38050 AnyIterator.next() + 237412
7  libswiftCore.dylib             0x109e764ac _IteratorBox.next() + 93868
8  CrewForce_Release              0x100fcf0f0 specialized static SyncHelper.query(_:tableName:limit:contextId:) (<compiler-generated>)

**Comment by Jeba-Moses-Official** [comment]
![SQLITE CRASH](https://user-images.githubusercontent.com/51657893/60013165-662f8b80-969b-11e9-88f3-2619429d9524.png)

**Comment by adramani90** [comment]
Did you get any solution for the above issue? Because i get the same error but still not got the solution. Please help me to get out of this. Thanks.

**Comment by dbanik** [comment]
I am seeing the same issue. Would be helpful to have a solution.

**Comment by mickael-menu** [comment]
You need to disable the file protection on the folder containing your database, because it gets encrypted when the device is locked.

```swift
try FileManager.default.setAttributes([.protectionKey: FileProtectionType.none], ofItemAtPath: folderPath)
```

More info here: https://github.com/groue/GRDB.swift/blob/master/README.md#data-protection
