### ISSUE TITLE
.Group/.max operator question

### ISSUE THREAD

**Issue by THEJOKER88** [stephencelis/SQLite.swift#94]
Hey,

I do have an SQL Statement that looks something like this:

SELECT * FROM table
WHERE age IN (SELECT max(age) FROM table
GROUP BY id)
ORDER BY id

My statement, build with your Framework looks something like this

table.filter(contains[table.max(age)!
.group by id], age)
.order by id

so i want to use the group by function to the knew query with the max age values. 
The Problem I have is, that .max returns a simple value and no query. 

Is there any way I can solve this Problem?

**Comment by stephencelis** [comment]
Have you tried the following?

``` swift
table.filter(contains(table.select(max(age)).group(id), age)).order(id)
```

The `contains` function may not support a subquery yet but it should be trivial to add support for the above if it doesn't work.

**Comment by THEJOKER88** [comment]
Thanks for the response.
Yes I tried it and the error I get is "could not find member 'group' ".
What can I do to add the support? Or can you do this? Please :)
