### ISSUE TITLE
Cannot fetching SQLite.swift 

### ISSUE THREAD

**Issue by codepgq** [stephencelis/SQLite.swift#942]
A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/stephencelis/SQLite.swift.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /Users/mark/Library/Caches/org.carthage.CarthageKit/dependencies/SQLite.swift)) failed with exit code 1

i can fetching other lib

**Comment by NathanFallet** [comment]
Please ask on StackOverflow for this kind of questions (we are tracking bugs on GitHub)
