### ISSUE TITLE
Why users.insert(Expression<String?>("name") <- "NAME")  is error?

### ISSUE THREAD

**Issue by SunshineDays** [stephencelis/SQLite.swift#943]
let path = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0]
        let db = try? Connection("\(path)/db.sqlite3")
        let users = Table("users")
        let id = Expression<Int64>("id")
        let name = Expression<String?>("name")
        let email = Expression<String>("email")
        
        try! db?.run(users.create(ifNotExists: true, block: { (table) in
            table.column(id, primaryKey: true)
            table.column(name)
            table.column(email, unique: true)
        }))

let insert = users.insert(Expression<String?>("name") <- "NAME")
"<-" is failed
Operator is not a known binary operator

I hope some kind-hearted people help me solve it！Thanks！

**Comment by sunhuaiwu** [comment]
Are you using ObjectMapper Or overloaded the ‘<-’ operator?

**Comment by NathanFallet** [comment]
Please ask on StackOverflow for this kind of questions (we are tracking bugs on GitHub)
