### ISSUE TITLE
Swift 5 compiler warning - umbrella header for sqlite

### ISSUE THREAD

**Issue by mgundy** [stephencelis/SQLite.swift#944]
Hello!  Newb here. I just migrated to Xcode 10.2.1 and Swift 5 using SQLite.swift 0.12.2 (using CocoaPods).  

I get the following Swift compiler warning:

Umbrella header for module 'SQLite' does not include header 'SQLite-Bridging.h' <module-includes>

I searched existing issues, but didn't see anything.

**Comment by chunxige** [comment]
me too

**Comment by mafiaIOS** [comment]
hello, have you handle this problem? bro.

**Comment by NathanFallet** [comment]
Try again with 0.13.0, it should be fixed (else, please reopen this issue)
