### ISSUE TITLE
force unwrap cause crash

### ISSUE THREAD

**Issue by huahuahu** [stephencelis/SQLite.swift#956]
## Build Information

- SQLite.swift: d2b4642190917051ce6bd1d49aab565fe794eea3
- XCode Version 11.0 (11A420a)
- Mac OS 10.14.6 (18G87)
- How do do you integrate SQLite.swift in your project?
    - CocoaPods

## 
I found it crashed when reading from a corrupted db file.
Is there a way to handle this ?

Here is the message
>  Fatal error: 'try!' expression unexpectedly raised an error: database disk image is malformed (code: 11): file /Users/larkios/Jenkins/workspace/lark/ios/appcenter/ios-beta-pack/Pods/SQLite.swift/Sources/SQLite/Core/Statement.swift, line 211
--

![image](https://user-images.githubusercontent.com/5757671/65512645-36975600-df0c-11e9-82bc-c43b76bd185c.png)

**Comment by pandapancake** [comment]
I changed it to optional ` return try? failableNext()`.  So far it haven't crush yet.

**Comment by NathanFallet** [comment]
Fixed by a PR in 0.13.0

**Comment by arthursalgado** [comment]
@nathanfallet  The adjustment has been reversed here:
https://github.com/stephencelis/SQLite.swift/commit/7e6d8b98d47c3cf7cfcb60d63fff17868eefd8c0

Why?
