### ISSUE TITLE
When do you support Swift 5.1?

### ISSUE THREAD

**Issue by codepgq** [stephencelis/SQLite.swift#957]
Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler:

**Comment by rust-rave** [comment]
Why are you specifically using Swift 5.1 instead of 5.0 ?

**Comment by codepgq** [comment]
I accidentally upgraded Xcode.🤷‍♀️

**Comment by misteral** [comment]
Fix it by `carthage update --platform iOS --no-use-binaries`

**Comment by FraggedResources** [comment]
I also fixed it now, using CocoaPods. Deleted the frameworks (just reference) and updated the pods again with `pod install --repo-update`. After reopening the workspace I did not convert to swift 5, which let me run my app on iPhone with newest iOS update.

**Comment by chillamcharlakavya** [comment]
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.3 compiler

**Comment by NathanFallet** [comment]
Swift 5.x is supported.
