### ISSUE TITLE
Ambiguous reference to member '<-'

### ISSUE THREAD

**Issue by Sannaraek** [stephencelis/SQLite.swift#958]
I am getting the error "Ambiguous reference to member '<-' " when i try to add a data to a row in my databse

 try db.run(scheduleDetail.insert(shour <- Int64(hourData), sday <- Int64(dayData)))

**Comment by ShaharHD** [comment]
Have the exact same issue...

**Comment by Sannaraek** [comment]
solved by declaring the DB connection locally rather then globally wrapped.
