### ISSUE TITLE
IPhone 4s Compatability: SQLiteCreateFunction: Extra Argument in Call

### ISSUE THREAD

**Issue by schan93** [stephencelis/SQLite.swift#96]
Hi,

I am using your application library and it works fine for all simulator devices and on an actual iPhone 6 I tested it on. However, I wanted to run my application on an iPhone 4s but I keep getting two errors in Database.swift saying that:

    `SQLiteCreateFunction(handle, function, Int32(argc), deterministic ? 1 : 0) { context, argc, argv`

has an `Extra argument in call` and on the line that has

`SQLiteCreateCollation(handle, collation) { lhs, rhs in`

there is the `Use of resolved identifier 'SQLiteCreateCollision'` error. I have no idea why this would break on the iPhone 4s but works on the iPhone 6. Any ways to fix this? Thanks!

**Comment by stephencelis** [comment]
I'm building for iPhone 4s just fine. Are you on the latest build and version of Xcode? Have you cleaned your build folder (deleted Derived Data)?

**Comment by schan93** [comment]
Ah, I have no idea why there were errors but after I just repulled my project from bitbucket everything seemed to work. Thank you for offering to help!
