### ISSUE TITLE
Crashing at ‘Connection.prepare(_:)’

### ISSUE THREAD

**Issue by zyflovelam** [stephencelis/SQLite.swift#960]
## Build Information

- SQLite.swift: 0.11.5
- Xcode: 10.1 (10B61)
- OS X: 10.13.6 (17G65)

## General guidelines

![image](https://user-images.githubusercontent.com/19360803/66619280-fd026280-ec0e-11e9-88c6-b4c54fe3db4e.png)

![image](https://user-images.githubusercontent.com/19360803/66619291-0ab7e800-ec0f-11e9-84f9-3fefb590ca0f.png)

**Comment by zyflovelam** [comment]
How do I resolve it? Could anyone give me help, please

**Comment by Swasidhant** [comment]
Any update on this? I seem to be facing the same issue

**Comment by NathanFallet** [comment]
This should be fixed in 0.13.0. If not, please reopen this issue.
