### ISSUE TITLE
Use of unresolved identifier 'SQLITE_CONSTRAINT'

### ISSUE THREAD

**Issue by chee1986** [stephencelis/SQLite.swift#961]
SQLite.swift0.12.2
Xcode11 MacOS Catalina
Swift Package manager(use the xcode11's build-in gui tool)

**Comment by fewlinesofcode** [comment]
You should also `import SQLite3`

**Comment by akda5id** [comment]
Thanks fewlinesofcode. This should be added to the documentation https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#handling-sqlite-errors

**Comment by NathanFallet** [comment]
@fewlinesofcode @akda5id Feel free to open a PR if you want to help to improve the documentation.
