### ISSUE TITLE
No such module 'SQLite' in Xcode 6.3 Swift 1.2 and Target iOS 7.0

### ISSUE THREAD

**Issue by confile** [stephencelis/SQLite.swift#97]
I followed the description [Frameworkless Targets](https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#frameworkless-targets) Step 1 to Step 4 I did not do any thing else.

I use Xcode 6.3beta4 and Swift 1.2. My target is iOS 7.0. I could compile my project after Step 1 to Step 4. When I use ``import SQLite`` in my ViewController I get the following error:

```
/Test111/Test111/ViewController.swift:10:8: No such module 'SQLite'
```

**Comment by confile** [comment]
@stephencelis I created a demo project here: https://github.com/confile/Test-SwiftSQLite

**Comment by ronnycsharp** [comment]
your demo project doesn't work with Xcode 6.3 GM

**Comment by stephencelis** [comment]
The framework is what creates the SQLite module. If you're going framework-less, no need to call `import`. Just start using the SQLite classes as if they're part of your app.

**Comment by ronnycsharp** [comment]
I can't build my App.
Xcode shows an issue.

1.	While deserializing decl #23 (XREF)
2.	Cross-reference to module 'WareApp'
	... _
3.	While reading from /Users/ronny/Library/Developer/Xcode/DerivedData/WareApp-famaieoaerhbeadunzmnnkzjgico/Build/Intermediates/WareApp.build/Debug-iphonesimulator/WareApp.build/Objects-normal/x86_64/Query~partial.swiftmodule

:(

**Comment by confile** [comment]
@stephencelis thank you. This should be added to the documentation as a note.

**Comment by stephencelis** [comment]
@confile I'll think about it, but to be honest I'm leaning more toward not supporting iOS 7 at all and letting dedicated people figuring it out on their own. There's a burden in providing support for an aging OS.

**Comment by confile** [comment]
@stephencelis There are still 20% on iOS7. So you might need to support it for a while.

**Comment by stephencelis** [comment]
@confile While I provide basic instructions to help people, I don't really support iOS 7 or putting effort into ensuring support. The projects in which I'm using this library are iOS 8-only. I'm always happy to accept PRs maintaining iOS 7 support if anything breaks, though.

**Comment by confile** [comment]
@stephencelis Do you mean that your lib does not work with iOS7?

**Comment by stephencelis** [comment]
@confile It should work and people do use it, but I don't put time into assuring support. This is a completely free open source project and my personal use case is iOS 8-centric using a framework. iOS 7 support shouldn't be too difficult for most developers to figure out, though.

**Comment by confile** [comment]
@stephencelis I really like you lib but you should not try to exclude iOS7 because it will be around for quite a while.

**Comment by stephencelis** [comment]
@confile I'm not excluding it. If anything breaks I will accept pull requests. If you would like to be an active contributor to ensure that, that would be great!

**Comment by confile** [comment]
@stephencelis I would love to but I am still at the beginning of Swift. If I can I will do a pull.
