### ISSUE TITLE
How do I tell if a table exists

### ISSUE THREAD

**Issue by Gaozn** [stephencelis/SQLite.swift#975]
rt

**Comment by manan6166** [comment]
try! DBConnection.Constant.db.run(tblVehicles.create(ifNotExists: true) { t in
            t.column(id, primaryKey: true)
            t.column(name)
            t.column(company, unique: true)
        })

**Comment by NathanFallet** [comment]
As @icodeuridevice showed, you can create a table if it doesn't exist yet.
