### ISSUE TITLE
Can't build with Xcode 6.3, Swift 1.2

### ISSUE THREAD

**Issue by ronnycsharp** [stephencelis/SQLite.swift#98]
I can't compile the project if I add an extension.like this NSDate.
I added the library without framework, only the SQLite.swift-folder.

 extension NSDate: Value {}...

I hope you can help.
Regards

**Comment by stephencelis** [comment]
You'll need to provide a lot more specific information to your issue and/or a link to a downloadable project with the error to troubleshoot.

In general I do not recommend using SQLite.swift in any capacity other than a framework. If you are building a new application, supporting iOS 7 is not going to give you a much wider reach than supporting iOS 8-only.

**Comment by ronnycsharp** [comment]
it works now. I've added the library as Framework. =) thx

**Comment by stephencelis** [comment]
Glad you got it working!

**Comment by stephencelis** [comment]
This is duplicated by https://github.com/stephencelis/SQLite.swift/issues/115 if you want an alternate solution.
