### ISSUE TITLE
'View' is ambiguous for type lookup in this contex

### ISSUE THREAD

**Issue by digitxo** [stephencelis/SQLite.swift#980]
When I import SQLite to my SwiftUI controller I get this msg:

![image](https://user-images.githubusercontent.com/39468483/72645340-40641f80-3928-11ea-8807-6183f341ef1a.png)

**Comment by pwightman** [comment]
Both SwiftUI and SQLite have a `View` type, so the compiler is confused about which one to use. You either need to not import SQLite and SwiftUI in the same file, or be explicitly put `SwiftUI.View` anywhere it’s supposed to be a View from SwiftUI. I would personally recommend not putting your SQLite code in the same file as your SwiftUI code.

**Comment by adam0x01** [comment]
My workaround is to put the SQLite related codes to a new separated swift file, then invoke `func` directly in your main SwiftUI file.
