### ISSUE TITLE
[QUESTION] Storing data as [String] in column

### ISSUE THREAD

**Issue by benmckillop** [stephencelis/SQLite.swift#987]
```
private let mixer = Expression<[String]>("mixer")

   func createTable() {
        do {
            try db!.run(trays.create(ifNotExists: true) { table in
                table.column(mixer) <- Error here
            })
        }
        catch {
            print("Unable to create table")
        }
    }
```

I'm trying to store items in an array of strings but at the line table.column(mixer) I get:

> Instance method 'column(_:unique:check:defaultValue:)' requires that '[String]' conform to 'Value'

Any advice on how I can store values in an array? I can't see anything in the docs

**Comment by xgjyjy** [comment]
me too

**Comment by NathanFallet** [comment]
Try to encode your String array to json and store the json output (best solution to store an array)

```swift
import Foundation

// ENCODING
print("ENCODING")

// Assume this is our array of strings
let array = ["one", "two", "three"]

// Convert your array to JSON
if let jsonData = try? JSONEncoder().encode(array), let json = String(bytes: jsonData, encoding: .utf8) {
    // Here you have your array as a json string
    // So you can save it into a string column
    
    print(json) // ["one","two","three"]
}

// DECODING
print("DECODING")

// Assume this is the string retrieved from database
let json = "[\"one\",\"two\",\"three\"]"

// Convert JSON to array
if let jsonData = json.data(using: .utf8), let array = try? JSONDecoder().decode([String].self, from: jsonData) {
    // Here you have your array back
    
    for e in array {
        print(e)
    }
}
```

![Screen Shot 2020-07-10 at 6 59 27 PM](https://user-images.githubusercontent.com/30439790/87179730-7e426f00-c2df-11ea-98c5-0f62092e511f.png)

**Comment by pujiaxin33** [comment]
I also encountered the same problem before, adding extension to Array conform `Value`
Protocol, you can directly store [String] type data.

I encapsulated the code into the `SQLiteValueExtension` library, you can introduce it through Cocoapods, you can directly store the data of the [String] type.

Specific details can be found in the `SQLiteValueExtension` Github homepage:[SQLiteValueExtension](https://github.com/pujiaxin33/SQLiteValueExtension)

**Comment by NathanFallet** [comment]
@pujiaxin33 Feel free to open a PR to add this feature to SQLite.switt
