### ISSUE TITLE
Example doesn't work ...

### ISSUE THREAD

**Issue by AgosrinhoScz** [stephencelis/SQLite.swift#988]
Hi,

Error in example ... how correct ?
<img width="869" alt="Captura de Tela 2020-02-07 às 23 25 39" src="https://user-images.githubusercontent.com/60299985/74077763-6e0d2780-4a01-11ea-8eeb-674fb0fce320.png">

**Comment by NathanFallet** [comment]
Because your `db` object is defined in the `do` structure, you need to wrap everything in it (`db` is created in it so stays in it)

```swift
do {
    let db = try Connection("financeiro.db")

    // Move your code here
    let users = Table("users")
    // ...
} catch {
    print (error)
}
```
