### ISSUE TITLE
Prefix Request for Expression, Database, Query,...

### ISSUE THREAD

**Issue by confile** [stephencelis/SQLite.swift#99]
I have some type collisions in my projects with types like: 
```
Expression, Database, Query,...
```

It would be awesome if you could creaate a Prefix like SC (Stephan Celis):

```
SCExpression, SCDatabase, SCQuery,...
```

**Comment by stephencelis** [comment]
Swift uses namespaces to disambiguate, wherever there is a conflict you can do the following:

``` swift
SQLite.Expression // refers to the SQLite module's Expression structure
YourApp.Expression // refers to your app module's Expression
```

**Comment by confile** [comment]
@stephencelis Well this is true is you import your code as Framework bit wenn you do it Frameworkless I have the same namespace. Do you have a solution for that?

**Comment by stephencelis** [comment]
@confile The solution would be to prefix them manually, or prefix your own classes.

**Comment by confile** [comment]
okay thank you
